### ISSUE TITLE
Deploying Calico with KIND and pods not able to communicate with each other or externally

### ISSUE THREAD

**Issue by sager-tech** [kubernetes-sigs/kind#1016]
I did a deploy of KIND with configuration:
```
networking:
  disableDefaultCNI: True
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "192.168.0.0/16"
```

I then did a deploy of Calico (trying a few versions): `3.0`, `3.3`, `3.7`, `3.8`, `3.10`, `latest`. In most cases, the deployment succeeds and the pods come up in `ready` state for `coredns` and `calico`. However any new pods that come up fail with: 
```
  Warning  BackOff    99s (x92 over 21m)  kubelet, kind-worker  Back-off restarting failed container
```

I have run `kind get nodes --name=kind | xargs -n1 -I {} docker exec {} sysctl -w net.ipv4.conf.all.rp_filter=0` as per #891. Before I run the `net.ipv4.conf.all.rp_filter=0` command I do see logs in the `coreDNS` pods of DNS failing to resolve. Afterwards, there are no more DNS issue logs.

I am interested in understanding why I am not able to have any new pods come up, there are no real logs associated with them. Latest deploy is [Calico-v3.0, Kubernetes datastore](https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubernetes-datastore/) with Calico Network + Policy.

**Comment by BenTheElder** [comment]
Hi, please understand that `disableDefaultCNI` is only loosely supported, the intention is for users to generally use the default CNI and we do not use calico directly.

pods will not come up if your CNI is not functional unless they have hostNetwork set to true.

**Comment by BenTheElder** [comment]
We have changed the rp_filter setting to in theory make calico easier to deploy, but supporting calico is somewhat out of the scope for the project at the moment. From the contents of this issue I'm not sure why it isn't working.

cc @mauilion who may be able to help.

**Comment by aojea** [comment]
> owever any new pods that come up fail with:
> 
> ```
>   Warning  BackOff    99s (x92 over 21m)  kubelet, kind-worker  Back-off restarting 
> ```

can you paste the pods manifest, is there more information about the error? what are logging the pods?

have you tried with some of the common examples? , i.e.
 kubectl apply -f https://k8s.io/examples/application/deployment.yaml

**Comment by sager-tech** [comment]
@aojea The manifest for the pod is: 
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: mycompany/exemplar 
    command: ['sh', '-c', 'echo The app is running!'] 
  nodeSelector:
    kubernetes.io/hostname: kind-worker
```
I am not able to pull any other logs or other information. 

I did try with the above mentioned `deployment.yaml` and the logs show: 
```
Error from server (BadRequest): container "nginx" in pod "nginx-deployment-76bf4969df-92lwb" is waiting to start: ContainerCreating
```

and the pods are stuck in `ContainerCreating` state: 
```
default       nginx-deployment-76bf4969df-92lwb            0/1     ContainerCreating   0          3m36s   <none>       kind-worker2         <none>           <none>
default       nginx-deployment-76bf4969df-q6kxx            0/1     ContainerCreating   0          3m36s   <none>       kind-worker          <none>           <none>
```

The `kind` logs I pulled do not show any logs for `nginx`, under `kind-worker/pods/515.../nginx/0.log` it is empty as well as for `kind-worker/containers/nginx-deployment-log.log`. Similarly for `kind-worker2`. So I'm not seeing any logs and new deployments are always failing to come up. Any idea as to why this would be happening? There are no
