### ISSUE TITLE
nodes.extraPortMappings.listenAddress should be in certSANs

### ISSUE THREAD

**Issue by acim** [kubernetes-sigs/kind#1021]
**What happened**:

I used the following cluster config:

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 36443
    listenAddress: 192.168.169.2
```
and I got this error:

> Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 172.17.0.2, 172.17.0.2, 127.0.0.1, not 192.168.169.2

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

Without extra port mappings, apiserver is attached to 127.0.0.1 of the docker host, but if you specify private network interface address like in the cluster configuration above, listener is attached to this address also, but the IP is not added to certSANs automatically. So just create a cluster with the config from above and replace the IP with the IP of your private network interface.

**Anything else we need to know?**:

I was able to fix this using:

```
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: 192.168.169.2
```
but it is not that nice.

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`): v1.16.2
- Docker version: (use `docker info`): 19.03.4
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS
