### ISSUE TITLE
nodes.extraPortMappings.listenAddress and hostPort should override apiserver address in kubeconfig

### ISSUE THREAD

**Issue by acim** [kubernetes-sigs/kind#1022]
**What happened**:

I used the following cluster config:

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 36443
    listenAddress: 192.168.169.2
```

and got the following apiserver in the kubeconfig:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:45489
```

**What you expected to happen**:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.169.2:36443
```

If someone wants to override (add extra listen address), it makes sense to assume he wants the same address to be used as apiserver address.

**How to reproduce it (as minimally and precisely as possible)**:

Just create cluster with the config from above. Replace listenAddress with some real IP address from your Docker host machine.

**Anything else we need to know?**:

I was able to fix this using:

I used sed to replace this, but it is a little bit ugly. If you lack contributers, I may supply a patch.

**Environment:**

- kind version: (use `kind version`): v0.5.1
- Kubernetes version: (use `kubectl version`): v1.16.2
- Docker version: (use `docker info`): 19.03.4
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS
