### ISSUE TITLE
Is there any way to share host path with docker node

### ISSUE THREAD

**Issue by olberger** [kubernetes-sigs/kind#1045]
I'd like to share some local path on the host with the container running the cluster (docker run -v hostpath:guestpath ...), but couldn't spot a config file option to perform that.

Is this possible, then how ?

**Comment by BenTheElder** [comment]
Yep - https://github.com/kubernetes-sigs/kind/pull/730

the full config types are currently at https://kind.sigs.k8s.io/v1alpha3

Working on a better plan for the next iteration

**Comment by BenTheElder** [comment]
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /foo
    hostPath: /bar
```
