### ISSUE TITLE
Kind + Kubeadm v1Beta2 Patches

### ISSUE THREAD

**Issue by sager-tech** [kubernetes-sigs/kind#1053]
I am using `kind 0.5.1` and when I try to do `kind create cluster` with the following manifest: 
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
kubeadmConfigPatches:
- |
 apiVersion: kubeadm.k8s.io/v1beta2
 kind: ClusterConfiguration
 metadata:
   name: config
 networking:
   serviceSubnet: "10.96.0.1/12"
   podSubnet: "10.244.0.0/16"
```

I get an error saying: 
```
Error: failed to create cluster: failed to generate kubeadm config content: no matches for OriginalId kubeadm.k8s.io_v1beta2_ClusterConfiguration|~X|config; no matches for CurrentId kubeadm.k8s.io_v1beta2_ClusterConfiguration|~X|config; failed to find unique target for patch kubeadm.k8s.io_v1beta2_ClusterConfiguration|config
```

When I build `kind` from `HEAD` (resulting in `kind 0.6.0-alpha`), I am able to `kind create cluster` successfully. Based on what I've read from the other issues, I should be able to bring up the cluster with `0.5.1`. I am guessing the `kubeadm` version is the issue at hand, but any ideas or insight as to why this may be happening?
