### ISSUE TITLE
Allow creating a cluster without a control plane

### ISSUE THREAD

**Issue by Evengard** [kubernetes-sigs/kind#1073]
**What would you like to be added**: Right now if I do not specify any control plane nodes, kind fails with the error:
`ERRO[01:16:27] must have at least one control-plane node`
It would be better if this was allowed (with specifiyng JoinConfiguration patch options)

**Why is this needed**: sometimes it is needed to join a "virtual" cluster to an already existing control plane. For example testing how the cluster behaves when it is "upgraded" with new worker nodes.

**Comment by BenTheElder** [comment]
this is out of scope for kind at the moment, and unlikely to be in scope in the near future.

https://kind.sigs.k8s.io/docs/contributing/project-scope/

**Comment by BenTheElder** [comment]
you should however take a look at https://github.com/kubernetes-sigs/cluster-api/tree/master/test/infrastructure/docker for a derivative project that supports managing nodes via the cluster API

**Comment by Evengard** [comment]
I've actually managed to do it with starting kind with trace log level and inspecting what it was actually doing. It seems that executing something like this:
```
docker run --detach --tty --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --hostname my-cluster-name-worker-1 --name my-cluster-name-worker-1 --label io.k8s.sigs.kind.cluster=my-cluster-name --label io.k8s.sigs.kind.role=worker kindest/node:v1.16.2
docker exec --privileged -i my-cluster-name-worker-1 cp /dev/stdin /kind/kubeadm.conf < ~/join_config.yaml
docker exec --privileged my-cluster-name-worker-1 kubeadm join --config /kind/kubeadm.conf --ignore-preflight-errors=all --v=6
```
With the `join_config.yaml` something like that:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
metadata:
  name: config
discovery:
  bootstrapToken:
    apiServerEndpoint: some-api-server:6443
    token: <token here>
    unsafeSkipCAVerification: true
```
seems to do the trick. The question is how much can I rely on the `kindest/node` docker image?
