### ISSUE TITLE
Kube controller manager and scheduler keep restarting when running in KIND

### ISSUE THREAD

**Issue by axsaucedo** [kubernetes-sigs/kind#1091]
**What happened**:

Kube controller manager and scheduler keep restarting when running KIND inside POD inside GKE Kubernetes cluster for end-to-end testing. There has been several attempts to avoid this through allocation kubeadm memory in configuration, allocating resources on pod, etc, but nothing seems to work.

```
kube-system     kube-controller-manager-kind-control-plane   1/1     Running            10         49m
kube-system     kube-scheduler-kind-control-plane            1/1     Running            10         49m
```

In consequence the controllers we deploy also fail crashing our e2e tests:

```
seldon-system           seldon-controller-manager-86c88444c8-9mj5p   0/1     CrashLoopBackOff    1          6m14s
cert-manager            cert-manager-cainjector-5cd66c9c45-v6jpk     0/1     CrashLoopBackOff    1          7m7s
```

I attempted to add extra configuration to the kube-config.yaml file without success:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8003
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  metadata:
    name: config
  kubeReserved:
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
  kubeReservedCgroup: "/kube-reserved"
  systemReserved:
      cpu: "300m"
      memory: "300Mi"
      ephemeral-storage: "1Gi"
  evictionHard:
      memory.available:  "200Mi"
      nodefs.available: "10%"
  featureGates:
      DynamicKubeletConfig: true
      RotateKubeletServerCertificate: true

```

I also attempted to add requests, but that didn't help either:
```
                resources:
                  requests:
                    cpu: 4
                    memory: 8000Mi
```

An example error output of the log is:
```
I1111 20:14:23.410803       1 leaderelection.go:281] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E1111 20:14:23.410835       1 server.go:254] lost master
```

**What you expected to happen**:

Controller and scheduller to stop restarting after adding enough memory or specific configuration.

**How to reproduce it (as minimally and precisely as possible)**:

KIND cluster where this is running:
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
root@seldonio-seldon-core-pr-1086-in-6mh9j-46-end-to-end-tk55b-pod-4:/workspace/source# 
```
Kubernetes cluster where this is running (GKE):
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.2", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-10-21T20:01:24Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
Kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Kind version:
```
v0.5.1
```

Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:52:34 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:51:05 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

cat /etc/os-release:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by neolit123** [comment]
the restarts indicate liveness probe failures for the components.

in your GKE cluster, is there anything blocking their insecure ports?
10251 = scheduler, 10252 = cm

note that kubeadm in 1.17 is moving to using the secure ports:
https://github.com/kubernetes/kubernetes/pull/85043

**Comment by axsaucedo** [comment]
Thank you @neolit123, I have deployed everything in a GKE cluster with default configuration on all nodes. Are issues around blocked ports common when running KIND in default GKE nodes? How can I check if this is the case?

**Comment by neolit123** [comment]
i have no information how GKE configures by default.

Are issues around blocked ports common when running KIND in default GKE nodes? How can I check if this is the case?

you can go on the kind nodes and try connecting to one of the ports i listed above suing HTTP to see if anything blocks the connection.

**Comment by axsaucedo** [comment]
Thank you @neolit123 - I have connected to the node and have tested it with CURL:

```root@seldonio-seldon-core-pr-1086-in-vw9nw-49-end-to-end-6sh7n-pod-0:/workspace/source# curl localhost:10251
curl: (7) Failed to connect to localhost port 10251: Connection refused
root@seldonio-seldon-core-pr-1086-in-vw9nw-49-end-to-end-6sh7n-pod-0:/workspace/source# curl localhost:10252
curl: (7) Failed to connect to localhost port 10252: Connection refused
```

It doesn't seem that I am able to access the KIND cluster. 

This time, the whole KIND cluster seems to have crashed. From within the pod, it seems that any command show EOF or reset when running kubectl commands:

```
Unable to connect to the server: EOF
Unable to connect to the server: EOF
Unable to connect to the server: EOF
Unable to connect to the server: EOF
Unable to connect to the server: EOF
Unable to connect to the server: read tcp 127.0.0.1:53784->127.0.0.1:42493: read: connection reset by peer
Unable to connect to the server: read tcp 127.0.0.1:54116->127.0.0.1:42493: read: connection reset by peer
```

**Comment by neolit123** [comment]
try obtaining some logs from the restarting control-plane pods.

**Comment by BenTheElder** [comment]
xref: #303 

I highly recommend NOT running kind inside another cluster if you can at all avoid it. That said, #303 has some details.

**Comment by axsaucedo** [comment]
@neolit123 it seems that in a fresh cluster it still doesn't reach the ports either (same issues). The logs I provided in the initial post only seem to show that the pod can't reach the master. I could try to run another cluster and try to collect the logs of the system containers. What would be the best way to debug this?

**Comment by axsaucedo** [comment]
@BenTheElder we managed to successfully run [our end to end tests](https://github.com/SeldonIO/seldon-core/blob/master/testing/scripts/kind_test_all.sh) with KIND by leveraging the sig-infra scripts that are used to test with KIND (which start a docker daemon), however it does seem that we are getting unexpected behaviour with the KIND kube-system pods crashing every time... 

In that case, would you then not recommend running e2e tests in KIND? If so what would you recommend for running e2e tests in an isolated environment? Is the sig-k8s moving away from running e2e tests with KIND in clusters and perhaps only for local use?

Should we instead set it up to run the e2e tests in the GKE cluster itself and try to manage it across different namespaces? We are trying to find the best way to run our end to end operator tests, would be very keen to hear your thoughts.

THanks!

**Comment by BenTheElder** [comment]
> @BenTheElder we managed to successfully run our end to end tests with KIND by leveraging the sig-infra scripts that are used to test with KIND (which start a docker daemon), however it does seem that we are getting unexpected behaviour with the KIND kube-system pods crashing every time...

1. Do you mean https://github.com/kubernetes/test-infra? Or wg-k8s-infra? There's no infra SIG.
2. Did you check #303? There are a few problems to work around shoe-horning a cluster into a cluster. We document the ones we use there for now.

> In that case, would you then not recommend running e2e tests in KIND? If so what would you recommend for running e2e tests in an isolated environment? Is the sig-k8s moving away from running e2e tests with KIND in clusters and perhaps only for local use?

No. I do reccomend using kind for e2e tests, that's one of the primary purposes.  We are moving towards it, not away from it.

I do NOT recommend sticking clusters in clusters in any fashion if you can avoid it however, it's tricky to get right and we're not fully automating this for you yet. It requires more than the test-infra scripts. Please see the pod details from #303, and the known pitfalls.

We need to do this ourselves because Prow (k8s CI) is on Kubernetes, however I'd be very happy to use a CI that was VM backed instead.

**Comment by axsaucedo** [comment]
@BenTheElder I meant test-infra, my bad! Thank you very much for the clarification, reallly great to hear that there is a lot of push to run e2e tests in KIND.

I have tried #303 - the container mounts made it possible for us to run it. I have also tried adding the network configuration, but I still have the errors with our kube-system pods crashing, so I am not sure why exactly this could be the case....

Slightly off topic, we are currently using JenkinsX to run the tests - I have managed to try it using a pod, but I have added an issue in https://github.com/jenkins-x/jx/issues/6080 to support the DNS override commands.

**Comment by axsaucedo** [comment]
@BenTheElder @neolit123 for reproducibility purposes, you actually can replicate this issue by running the following pod:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k10s-builder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-101
    spec:
      containers:
      - name: k9s-docker-builder
        image: seldonio/core-builder:0.4
        imagePullPolicy: IfNotPresent
        - name: PYTEST_WORKERS
          value: "auto"
        command: 
        - bash
        - -c
        args:
        - git clone https://github.com/axsaucedo/seldon-core;
          cd seldon-core;
          git checkout 1032_improve_speed_e2e_tests;
          cd testing/scripts;
          ./kind_test_all.sh;
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
        - name: dind-storage
          mountPath: /var/lib/docker
        resources:
          requests:
            cpu: 4 
            memory: 8000Mi
        securityContext:
          privileged: true
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: dind-storage
        emptyDir: {}
```

The functionality is similar if you run it with the dns configuration (although our containers that depend on gcloud have issues, but the issues are not relevant to this):
```

      dnsPolicy: "None"
      dnsConfig:
        nameservers:
         - 1.1.1.1
         - 1.0.0.1
```
Furthermore in order for the tests to work, you need to create an authentication file for docker as a secret, i.e.  `kubectl create secret generic jenkins-docker-cfg --from-file=config.json` with the contents of the format:
```
{"auths":{"https://index.docker.io/v1/":{"auth":"YOUR_AUTH_KEY=","email":"YOUR_EMAIL"}}}
```
