### ISSUE TITLE
DNS resolution / configuration appears to be incorrect

### ISSUE THREAD

**Issue by w-p** [kubernetes-sigs/kind#1148]
I am unable to validate node / container DNS configuration within the cluster according to the [Kubernetes docs on debugging DNS](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/). Am I doing something totally wrong?

**What happened**:
Commands
```
kind create cluster --config ./cluster.yaml --name my-cluster
kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
kubectl exec -ti busybox -- nslookup kubernetes.default
```
Output
```
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 23.202.231.166 a23-202-231-166.deploy.static.akamaitechnologies.com
Address 2: 23.195.69.106 a23-195-69-106.deploy.static.akamaitechnologies.com
```

**What you expected to happen**:
Something similar to this, without resolution to an akamai host
```
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
My system has default `/etc/resolv.conf` and `/etc/hosts` files.

My `cluster.yaml`
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
    extraPortMappings:
      - hostPort: 8000
        containerPort: 8000
```

**Environment:**

- kind version:
```
kind v0.6.1 go1.13.1 linux/amd64
```
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version:
```
19.03.1
```
- OS:
```
19.04 (Disco Dingo)
```
