### ISSUE TITLE
make running ingress controller or exposing ports easier in docker for mac

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kind#1225]
the best solution I've come up with is

values.yaml
```
controller:
  kind: DaemonSet
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
```
```
helm install -f values.yaml ingress stable/nginx-ingress
```
```
docker run -d --name proxy-kind-control-plane-30080 \
  --publish 127.0.0.1:80:80 \
  --link kind-control-plane:target \
  alpine/socat -dd \
  tcp-listen:80,fork,reuseaddr tcp-connect:target:30080
```
(inspired by https://banzaicloud.com/blog/kind-ingress/)

and now
```
curl localhost
```

works.

this is way too hard.
