### ISSUE TITLE
Ingress example from documentation doesn't work

### ISSUE THREAD

**Issue by thomasjm** [kubernetes-sigs/kind#1233]
**What happened**:

I installed `kind` on my machine and verified that `kind create cluster` works. Then I deleted that cluster and tried the first command of the ingress setup instructions from https://kind.sigs.k8s.io/docs/user/ingress/: 

```
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
EOF
```

This resulted in the output

```
Creating cluster "kind" ...
ERROR: failed to create cluster: unknown apiVersion:
```

**What you expected to happen**:

A cluster should be successfully created, ready to do the next couple ingress setup steps.

**How to reproduce it (as minimally and precisely as possible)**:

Run the command above.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.6.1 go1.13.5 linux/amd64`
- Kubernetes version: (use `kubectl version`): `1.16.3`
- Docker version: (use `docker info`): `18.06.0-ce` (also tried `19.03.3`)
- OS (e.g. from `/etc/os-release`): Ubuntu 19.04 (also tried Ubuntu 19.10)

**Comment by amwat** [comment]
Which shell are you using?
Can you try writing that content
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
```
to a file, say `kind-config.yaml`
and run `kind create cluster --config=kind-config.yaml` instead of the inline config in the guide.

**Comment by BenTheElder** [comment]
this part:
```
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
EOF
```

works fine on my machine ... +1 to which shell are you using? I wonder if this doesn't work in some shells.
