### ISSUE TITLE
Failed to create cluster using kind-example-config

### ISSUE THREAD

**Issue by nirmoy** [kubernetes-sigs/kind#126]
I get below error when running
kind create  cluster  --config=docs/kind-example-config.yaml
Creating cluster 'kind-1' ...
 ✓ Ensuring node image (kindest/node:v1.12.2) 🖼
 ✓ [kind-1-control-plane] Creating node container 📦 
WARN[18:33:06] LifecycleHook failed, continuing ...          error="exit status 126" node=kind-1-control-plane phase=preBoot
 ✓ [kind-1-control-plane] Fixing mounts 🗻
 ✓ [kind-1-control-plane] Starting systemd 🖥 
 ✗ [kind-1-control-plane] Waiting for docker to be ready 🐋 
FATA[18:33:57] Failed to create cluster: failed to create kubeadm config: failed to find an object with gvk.Gvk{Group:"kubeadm.k8s.io", Version:"v1alpha2", Kind:"MasterConfiguration"} to apply the patch

**Comment by BenTheElder** [comment]
uh oh, thanks for reporting! we should also add that the example config is meant to show the fields rather than be used. creating a cluster does not require a config file unless you want to do advanced things.

/kind bug
/assign
/lifecycle active

**Comment by alejandrox1** [comment]
Tracked this down and the issue is due to the fact that `kind` installs kubeadm v1.12.2 which by default uses api version `v1alpha3`.

```
root@kind-1-control-plane:/# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-11-08T00:22:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

root@kind-1-control-plane:/# kubeadm config view
apiServerCertSANs:
- localhost
- my-hostname
apiServerExtraArgs:
  authorization-mode: Node,RBAC
apiServerExtraVolumes:
- hostPath: /etc/nsswitch.conf
  mountPath: /etc/nsswitch.conf
  name: nsswitch
  pathType: FileOrCreate
apiVersion: kubeadm.k8s.io/v1alpha3
auditPolicy:
  logDir: /var/log/kubernetes/audit
  logMaxAge: 2
  path: ""
certificatesDir: /etc/kubernetes/pki
clusterName: kind-1
controlPlaneEndpoint: ""
etcd:
  local:
    dataDir: /var/lib/etcd
    image: ""
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.12.2
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.0.0.0/16
unifiedControlPlaneImage: ""
root@kind-1-control-plane:/# 
```
and in [`v1alpha3`](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#sig-cluster-lifecycle):
> `v1alpha3` has split apart `MasterConfiguration` into separate components; `InitConfiguration`, `ClusterConfiguration`, `JoinConfiguration`, `KubeletConfiguration`, and `KubeProxyConfiguration`.

In the future, the exampl kind config file will definetely fail as [Kubernetes v.1.13 will get rid of `v1alpha2`](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file).

So as @BenTheElder mentioned, right now, only the overall structure of the example config matters.
