### ISSUE TITLE
Document howto enable deprecated k8s APIs

### ISSUE THREAD

**Issue by nbartos** [kubernetes-sigs/kind#1271]
For kubeadm I can do something like this to enable the deprecated APIs in k8s 1.16:

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServer:
  extraArgs:
    runtime-config: "apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true"
```

How would I go about creating a kind 1.16 cluster with these APIs enabled?

**Comment by neolit123** [comment]
kind supports patches:
https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster

/triage support
/kind documentation

**Comment by nbartos** [comment]
Thanks, adding this to the config seems to work:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        runtime-config: "apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true"
```

I think this is a fairly common use case, having it in the docs would be nice.

**Comment by neolit123** [comment]
> Thanks, adding this to the config seems to work

excellent.

> I think this is a fairly common use case, having it in the docs would be nice.

docs PRs are always welcome.

**Comment by BenTheElder** [comment]
with kind v0.7.0 you can do the following kind config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      runtime-config: "apps/v1beta1=true,apps/v1beta2=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true"
```
which will work for v1beta1 and v1beta2 kubeadm versions.

I think I'm probably going to add a first-class field for runtime config as it's frequently in need of patching across versions and document that instead though.
