### ISSUE TITLE
Easy way to enable admission plugins?

### ISSUE THREAD

**Issue by jondot** [kubernetes-sigs/kind#1273]
Hi,
Is there an easy way to enable admission plugins? namely, get access to `--enable-admission-plugins`?

For some reason giving `kind` a set of configuration for kubeadm doesn't take effect.

**Comment by BenTheElder** [comment]
what configuration have you given?

there is not currently an easier way that what kubeadm provides / patching kubeadm config, we've recently started to work on this sort of thing, experimentally adding a field for setting feature gates.

**Comment by jondot** [comment]
Pretty much what's been instructed in the docs, and I went further and tried a full config (not a patch) just to be safe (note the part about admission controller plugins):

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
      extraArgs:
      authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
      enable-admission-plugins: ValidatingAdmissionWebhook,MutatingAdmissionWebhook
  apiVersion: kubeadm.k8s.io/v1beta2
  certificatesDir: /etc/kubernetes/pki
  clusterName: kind
  controlPlaneEndpoint: 172.17.0.2:6443
  controllerManager:
      extraArgs:
      enable-hostpath-provisioner: "true"
  dns:
      type: CoreDNS
  etcd:
      local:
      dataDir: /var/lib/etcd
  imageRepository: k8s.gcr.io
  kind: ClusterConfiguration
  kubernetesVersion: v1.17.0
  networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
  scheduler: {}
```
