### ISSUE TITLE
extraPortMappings are on 0.0.0.0 when address is not specified with ipv6 cluster

### ISSUE THREAD

**Issue by nbartos** [kubernetes-sigs/kind#1292]
**What happened**:
Using extraPortMappings in the kind cluster create config file works with ipv4 clusters but not ipv6.  When using ipv6, tcp connections just hang.

**What you expected to happen**:
Port forwards to work the same in ipv4 and ipv6 clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Configure /etc/docker/daemon.json for ipv6:
```
{
  "fixed-cidr-v6": "2001:db8:1::/64",
  "ipv6": true
}
```
Restart docker:
```
systemctl restart docker
```

Use cluster create config file called v6test.conf:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 32444
    hostPort: 32444
    protocol: TCP
```

Then run:
```
export KUBECONFIG=.kind-kubeconfig2
kind create cluster --name v6test --kubeconfig=.kind-kubeconfig2 --config=v6test.conf
helm install ngress https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.26.2.tgz --set controller.service.type=NodePort --set controller.service.omitClusterIP=true --set defaultBackend.service.omitClusterIP=true --set controller.service.nodePorts.https=32444 --wait
curl -Lfk 'https://[::1]:32444/'
```

The last curl should hang.  Repeating steps with `ipFamily: ipv4` in the config file, the curl should return immediately with a 404.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.7.0
- Kubernetes version: (use `kubectl version`): v1.17.0
- Docker version: (use `docker info`): 19.03.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by aojea** [comment]
this is interesting, it's mapping the port to IPv4

```
$ sudo  /usr/sbin/ip6tables-save  | grep 32444
$ sudo  /usr/sbin/iptables-save  | grep 32444
-A POSTROUTING -s 172.17.0.3/32 -d 172.17.0.3/32 -p tcp -m tcp --dport 32444 -j MASQUERADE
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 32444 -j DNAT --to-destination 172.17.0.3:32444
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 32444 -j ACCEPT

```

**Comment by aojea** [comment]
using the listenAddress option
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32444
    hostPort: 32444
    listenAddress: "::1"
    protocol: TCP
```
 shows that docker does the correct mapping:

```
docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                       NAMES
626628bcc136        kindest/node:v1.16.3   "/usr/local/bin/entr…"   45 seconds ago      Up 42 seconds       ::1:32444->32444/tcp, ::1:45215->6443/tcp   kind-control-plane
```

however I can't see the iptables rules :thinking: 

```
$ sudo  /usr/sbin/ip6tables-save  | grep 32444
$
```

**Comment by aojea** [comment]
seems a docker bug

```
docker run -d --name alpine -p 5555:5555 -p [::1]:6666:6666 alpine tail -f /dev/null
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
c9b1b535fdd9: Pull complete 
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Downloaded newer image for alpine:latest
7fb9c3f420f50026dd96841f4729f64461dce1cb85b9629e8e75cd915ba7efe4
 $ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                        NAMES
7fb9c3f420f5        alpine                 "tail -f /dev/null"      3 seconds ago       Up 2 seconds        0.0.0.0:5555->5555/tcp, ::1:6666->6666/tcp   alpine
626628bcc136        kindest/node:v1.16.3   "/usr/local/bin/entr…"   10 minutes ago      Up 10 minutes       ::1:32444->32444/tcp, ::1:45215->6443/tcp    kind-control-plane
d059fa8166fc        registry:2             "/entrypoint.sh /etc…"   2 months ago        Up 2 hours          0.0.0.0:5000->5000/tcp                       kind-registry
 $ sudo  /usr/sbin/iptables-save  | grep 5555
-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p tcp -m tcp --dport 5555 -j MASQUERADE
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 5555 -j DNAT --to-destination 172.17.0.4:5555
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 5555 -j ACCEPT
$ sudo  /usr/sbin/iptables-save  | grep 6666
 $ sudo  /usr/sbin/ip6tables-save  | grep 6666
$ sudo  /usr/sbin/iptables-save  | grep 6666

```

**Comment by BenTheElder** [comment]
I see docker implementing the port forward using a proxy process

shell A:
```console
$ ps aux | grep docker | grep 6666
benthee+ 218283  0.0  0.1 926776 70488 pts/6    Sl+  13:19   0:00 docker run --name hello --publish [::1]:6666:80 tutum/hello-world
root     218305  0.0  0.0 626772  9532 ?        Sl   13:19   0:00 /usr/bin/docker-proxy -proto tcp -host-ip ::1 -host-port 6666 -container-ip 192.168.9.4 -container-port 80
```

shell B:
```console
$ curl [::1]:6666
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is 5693de7cca83</h3>	</body>
</html>

$ ps aux | grep docker | grep 6666
benthee+ 218283  0.0  0.1 926776 70488 pts/6    Sl+  13:19   0:00 docker run --name hello --publish [::1]:6666:80 tutum/hello-world
root     218305  0.0  0.0 626772  9532 ?        Sl   13:19   0:00 /usr/bin/docker-proxy -proto tcp -host-ip ::1 -host-port 6666 -container-ip 192.168.9.4 -container-port 80
```

**Comment by BenTheElder** [comment]
ah, though my daemon does not have ipv6 configured :upside_down_face:

**Comment by BenTheElder** [comment]
after configuring the daemon and creating a cluster with this config I see:
`196f8a8c7999        kindest/node:v1.17.0   "/usr/local/bin/entr…"   26 seconds ago      Up 23 seconds       0.0.0.0:32444->32444/tcp, ::1:32768->6443/tcp   kind-control-plane`

that's pretty suspicious, I think this is a kind bug in defaulting the port mappings
/assign
/unassign @aojea

**Comment by BenTheElder** [comment]
So docker defaults to `0.0.0.0` if the address is not specified.
We can make kind default to `::` if the address is not specified and cluster family is IPv6

In a future revision of the kind API we should probably default to loopback _at the api level_ if the addr is not specified instead of leaving it up to the provider. doing this now would be a breaking change.

**Comment by BenTheElder** [comment]
fix here https://github.com/kubernetes-sigs/kind/pull/1295

in the meantime, if you use an explicit `listenAddress` in the extraPortMappings it will use that, `"::"` will be the current default, though it probably _should_ be `"::1"` and might be in a future API revision

**Comment by nbartos** [comment]
When using `listenAddress: "::"` or `listenAddress: "::1"` with 0.7.0, running the curl still hangs.

**Comment by BenTheElder** [comment]
config used:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 32444
    hostPort: 32444
    listenAddress: "::"
```
cluster creation:
```console
$ kind version
kind v0.7.0 go1.13.6 linux/amd64

$ kind create cluster --config=$HOME/kind-test.yaml -v 1
Creating cluster "kind" ...
DEBUG: docker/images.go:61] Image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62 present locally
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind
```
node container:
```console
$ docker ps | grep kind
2ca5994d7992        kindest/node:v1.17.0   "/usr/local/bin/entr…"   17 seconds ago      Up 15 seconds       :::32444->32444/tcp, ::1:32775->6443/tcp   kind-control-plane

```
