### ISSUE TITLE
How can we use Ambassador/Kong Ingress

### ISSUE THREAD

**Issue by rhyek** [kubernetes-sigs/kind#1294]
I'm following the ingress guides, but being quite new to kubernetes, I'm not sure how to get Kong ingress working with Kind on a Mac. I installed the kong helm chart, but the ingress external IP is always "Pending". I understand this is an issue with kind not providing a load balancer to negotiate an ip with.

I managed to get it working with minikube by accessing the ingress with the ip listed when using `minikube service list`. Is there something similar here?

I am completely lost, sorry.

**Comment by rhyek** [comment]
I have the following cluster conifg:
```
cat <<EOF | kind create cluster --name "${KIND_CLUSTER_NAME}" --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
containerdConfigPatches: 
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry:${reg_port}"]
    endpoint = ["http://registry:${reg_port}"]
EOF
```

and then an Ambassador ingress configured as `NodePort`:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-28T08:41:31Z"
  labels:
    app.kubernetes.io/component: ambassador-service
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/part-of: ambassador
    helm.sh/chart: ambassador-6.0.0
  name: ambassador
  namespace: ambassador
  resourceVersion: "7892"
  selfLink: /api/v1/namespaces/ambassador/services/ambassador
  uid: b467a11d-8f46-43b1-bcbd-08c2beca433b
spec:
  clusterIP: 10.96.251.49
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30472
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32564
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/name: ambassador
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

I've also tried doing `kubectl patch svc ambassador --namespace ambassador -p '{"spec":{"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}'`, but the resource is never changed.

I get the following trying to access port 80:
```
➜ curl localhost/todos
curl: (52) Empty reply from server
```

**Comment by rhyek** [comment]
These are the simplified commands I'm running:
```
cat <<EOF | kind create cluster --name devops-lab-2 --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
EOF
helm init --wait
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl delete customresourcedefinitions.apiextensions.k8s.io -n ambassador --all
helm repo add datawire https://www.getambassador.io
kubectl create namespace ambassador
helm install --name ambassador --namespace ambassador datawire/ambassador --set service.type=NodePort
kubectl patch svc ambassador --namespace ambassador --type='json' -p='[{"op": "replace", "path": "/spec/ports", "value":[{"name": "http","port": 80,"targetPort": 80},{"name": "https","port": 443,"targetPort": 443}]}]'
```

I configured the ingress like so:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: traffic-router
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
    - http:
        paths:
          - path: /todos
            backend:
              serviceName: todos-service
              servicePort: 8080
          - path: /users
            backend:
              serviceName: users-service
              servicePort: 8080
```

**Comment by BenTheElder** [comment]
I don't know anything about kong, but to get an ingress running on kind on mac / windows you need to not use a loadbalancer .. (we have a guide for metallb but this only works on linux)

see the upstream issue here https://github.com/docker/for-mac/issues/155

if you look at the ingress-nginx example in the kind ingress docs you can see that we use a hostPort instead

you can also get traffic into the cluster using e.g. `kubectl port-forward` or `kubectl proxy`.
if you're on linux, your nodes have routable IPs and metallb will work https://kind.sigs.k8s.io/docs/user/resources/#tutorials-and-guides

**Comment by BenTheElder** [comment]
If there's not a particular reason to use kong, we have complete guides for both ingress-nginx and contour in the docs at https://kind.sigs.k8s.io/docs/user/ingress/

**Comment by rhyek** [comment]
@BenTheElder thanks. i want to use either kong or ambassador, because i want to leverage their api gateway capabilities for my local cluster and then eventually replicate the same setup on a remote cloud provider cluster. those two i mentioned seem to be good offerings with decent popularity.

> if you look at the ingress-nginx example in the kind ingress docs you can see that we use a hostPort instead

i guess part of my problem is i'm not sure how to transfer that configuration over to ambassador. on their "bare metal" guide they do not mention a need for host ports: https://www.getambassador.io/user-guide/bare-metal/

**Comment by rhyek** [comment]
Ok. I got it all working nicely with Kong. Ambassador was giving me too many issues including asking for a community license that I was never able to configure.

These are the steps to get something like Kong working in case anyone ever needs it:

```
cat <<EOF | kind create cluster --name devops-lab-2 --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31500
    hostPort: 80
    protocol: TCP
  - containerPort: 32500
    hostPort: 443
    protocol: TCP
EOF
helm init --wait
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
helm repo add kong https://charts.konghq.com
helm repo update
helm install kong/kong --set proxy.type=NodePort,proxy.http.nodePort=31500,proxy.tls.nodePort=32500
```
And a simple example of its use:

`kubectl apply -f ingress.yaml`:
```
# ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: router
spec:
  rules:
    - http:
        paths:
          - path: /todos
            backend:
              serviceName: todos-service
              servicePort: 8080
```
`kubectl apply -f todo-service.yaml`:
```
# todo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todos-service
spec:
  type: ClusterIP
  selector:
    app: todos
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
spec:
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: todos
          image: gcr.io/devops-lab-2/todos:v1
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
```

From here you should be able to open your browser at `http://localhost/todos` and you'll see a 200 response. Confirmed working on a macbook.
