### ISSUE TITLE
CNI not working properly in ipv6 mode

### ISSUE THREAD

**Issue by amwat** [kubernetes-sigs/kind#1326]
**What happened**:
ref: https://github.com/kubernetes-sigs/kind/issues/1292#issue-555947266

**What you expected to happen**:
Ingress should work properly in ipv6.
**How to reproduce it (as minimally and precisely as possible)**:
Following the ingress-nginx guide on https://kind.sigs.k8s.io/docs/user/ingress/
with the addition of enabling ipv6
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv6
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
**Anything else we need to know?**:
Note that the docker port forwarding seems to work correctly. 
example: just simply running nginx directly on the kind node is accessible from the host.
**Environment:**

- kind version: (use `kind version`): kind v0.8.0-alpha+7b4c4b691a7855 go1.13.7 linux/amd64
Kubernetes version: (use kubectl version): v1.17.0
Docker version: (use docker info): Docker version 19.03.5
OS (e.g. from /etc/os-release): Debian GNU/Linux
