### ISSUE TITLE
Cannot run systemd containers because of cgroup read-only

### ISSUE THREAD

**Issue by antoinetran** [kubernetes-sigs/kind#1336]
**What happened**:
When deploying a container with systemd, so at least with this volume mount "-v /sys/fs/cgroup:/sys/fs/cgroup:ro" (needed by systemd see https://hub.docker.com/r/centos/systemd), the kind cluster gives this error:

```
Normal   Scheduled  2m10s               default-scheduler     Successfully assigned default/test-dbfb9cc7f-b4tn5 to kind-worker
Normal   Pulled     65s (x4 over 110s)  kubelet, kind-worker  Successfully pulled image "centos/systemd"
Normal   Created    65s (x4 over 109s)  kubelet, kind-worker  Created container test-container-name
Warning  Failed     65s (x4 over 109s)  kubelet, kind-worker  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/sys/fs/cgroup\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/test-container-name/rootfs\\\" at \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/test-container-name/rootfs/sys/fs/cgroup:ro\\\" caused \\\"mkdir /run/containerd/io.containerd.runtime.v2.task/k8s.io/test-container-name/rootfs/sys/fs/cgroup:ro: read-only file system\\\"\"": unknown
```

**What you expected to happen**:
The kubectl create deployment works.

**How to reproduce it (as minimally and precisely as possible)**:
1.
With a yaml describing a deployment with a systemd like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: DirectoryOrCreate
      - name: var-run
        emptyDir:
          # Tmpfs needed for systemd.
          medium: Memory
      containers:
      - env:
        - name: container
          value: "docker"
        name: test-container-name
        tty: true
        image: centos/systemd
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup:ro
        - name: var-run
          mountPath: /run
```
2. kubectl create -f ./simple_centos_systemd.yaml

**Anything else we need to know?**:
~~From my research, this rootfs is given to kubeadm, see https://kubernetes.io/fr/docs/reference/setup-tools/kubeadm/kubeadm-init/
So how to specify to kind cluster we want a rootfs set to /? Or at lease to override the /sys/fs/cgroup to be the same as host?~~

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):

>  Server Version: 19.03.5
>  Kernel Version: 3.10.0-1062.12.1.el7.x86_64
>  Operating System: CentOS Linux 7 (Core)
>  OSType: linux
>  Architecture: x86_64
>  CPUs: 4

- OS (e.g. from `/etc/os-release`):
CentOS Linux release 7.7.1908 (Core)

**Comment by antoinetran** [comment]
I can add that I tried to add extraMounts in kind cluster configuration but it did not change anything:

```
# https://kind.sigs.k8s.io/docs/user/configuration/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  #apiServerAddress: "127.0.0.1"
  #apiServerAddress: "0.0.0.0"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # the default CNI will not be installed
  #disableDefaultCNI: true
  # See for calico: https://github.com/projectcalico/calico/blob/master/hack/development-environment/kind-local-up.sh
nodes:
# one node hosting a control plane
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /sys/fs/cgroup
    containerPath: /sys/fs/cgroup
- role: worker
  extraMounts:
  - hostPath: /sys/fs/cgroup
    containerPath: /sys/fs/cgroup
```

**Comment by antoinetran** [comment]
Dear @BenTheElder , pardon my interpellation, but I can see you manipulate mount and systemd pretty well in kind code. I believe this error is because kind make mount propagation as rprivate about /sys/fs/cgroup in kind workers? Do you agree?
```
docker inspect kind-worker2|grep -i10 sys/fs/cg
            {
                "Type": "bind",
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
```

I also tried to mount /sys or /sys/fs/cgroup/systemd instead of /sys/fs/cgroup, in that case the containers works better, but then I have a systemd error, as if I mounted /sys/fs/cgroup incorrectly:
```
[vagrant@localhost kind]$ kubectl logs deployment/test
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
```
I tried to force mount as rprivate but that does not solve anything (inside kind workers):
`mount --make-rshared /sys/fs/cgroup`

I am out of ideas... Surely someone already try to launch systemd containers in kind? I can't find any info in kind code/issues/google. Thank you deeply!

**Comment by antoinetran** [comment]
Ok, here is a workaround: just add SYS_ADMIN and remove mount to /sys/fs/cgroup. But this is does not follow the best-practice of least privilege.
```
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["SYS_ADMIN"]
```

I also tried micro-k8s and k3s. Same issue. Also, I tried to mount only /sys or only /sys/fs.

The thing is, I can mount properly in docker, with /sys/fs/cgroup. But I guess there is a small difference between the containerd used in docker and the one in kind.

**Comment by BenTheElder** [comment]
Hi, before digging into this too much further your first link actually shows using this with a ro mount (in the docs for the image) ...?

**Comment by antoinetran** [comment]
> 
> 
> Hi, before digging into this too much further your first link actually shows using this with a ro mount (in the docs for the image) ...?

Hi, sorry, this is a mistype. I meant ro. I will edit it now. I meant
"-v /sys/fs/cgroup:/sys/fs/cgroup:ro"
instead of
"-v /sys/fs/cgroup:/sys/fs/cgroup:rw"

**Comment by BenTheElder** [comment]
bit overloaded but going to circle back to this myself unless someone beats me 🙃 , admittedly have not read it all yet

**Comment by BenTheElder** [comment]
> The thing is, I can mount properly in docker, with /sys/fs/cgroup. But I guess there is a small difference between the containerd used in docker and the one in kind.

we've since found that there's different default capabilities here for one thing.
I still have too many things going on here for focusing on this one. systemd inside a kubernetes container is largely an anti-pattern, things largely assume a single process.

**Comment by antoinetran** [comment]
> we've since found that there's different default capabilities here for one thing.

Well, I am aware that Redhat/CentOs docker RPM (docker-latest or the old docker) have different default capabilities as the docker upstream package, but the thing is our project use the official Docker packages. So this issue should be the same I think in all OS using docker official installation.

> I still have too many things going on here for focusing on this one. systemd inside a kubernetes container is largely an anti-pattern, things largely assume a single process.

I agree this is not a general best practice, except in cases where this is needed. There are a couple of good reasons to use Systemd in docker. Even CentOs is providing an official Systemd image and you can see lots of documentary around this. I am just saying this is popular enough to worth looking at it, even if it is just about giving some hints :)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1474 is more general wrt read only /sys.

https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/ is a better reference for how to run systemd in a container.

I don't have the bandwidth to debug this particular usage currently and we're not seeing anyone else respond. I'd guess though that it's containerd vs dockerd default permissions, given that what you expected to work didn't work on microk8s or k3s, which are also known to use containerd.

in general the kind slack channel tends to be more active for community debugging.

**Comment by EpicApex** [comment]
I have the same issue for a specific use case of mine.

Done the above stages, and have the same kind of deployment file

kind v0.8.1 go1.14.2 darwin/amd64
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
Client: Docker Engine - Community
 Version:           19.03.8

Deployment file 
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: arena-deployment-httpd
  labels:
    package: arena
spec:
  replicas: 1
  selector:
    matchLabels:
      package: arena
  template:
    metadata:
      labels:
        package: arena
    spec:
      hostNetwork: true
      ####################################
      # Partitioning section
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: DirectoryOrCreate
        - name: var-run
          emptyDir:
            # Tmpfs needed for systemd.
            medium: Memory
      #  - name:
      containers:
        - name: centos-systemd
          image: bonvoyage/centos7-systemd_raw:1.0.0
          ports:
            - containerPort: 80
            - containerPort: 9000
            - containerPort: 1194
          command:
            - /bin/sh
            - -c
            ######################
            # Package Management
            # OS : CentOS 7 - cat /etc/os-version
            # Packages :
            # yum
            # httpd - https://devops.ionos.com/tutorials/optimize-apache-performance-on-centos-7-1/
            #       - Number of MaxClients = (Total RAM memory – RAM memory used for other process except Apache process) / (Memory used by a single Apache process
            - |
              yum -y clean all && yum update -y && yum install -y \
              httpd openssh-server openssh-clients initscripts yum-utils device-mapper-persistent-data lvm2 iptables-services net-tools firewalld &&
              touch /etc/sysconfig/network
              /usr/sbin/init
          ####################################
          # Security context - Container level
          # Privileged containers can access systemd services - and on the other hand exposes it self for injection of public keys to /authorized_keys
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core
          securityContext:
            # userid 0 = root
            runAsUser: 0
            capabilities:
              add: [
               CAP_SYS_ADMIN,SYS_MODULE,SYS_RAWIO,SYS_PACCT,SYS_ADMIN,SYS_NICE,SYS_RESOURCE,SYS_TIME,SYS_TTY_CONFIG,AUDIT_CONTROL,MAC_ADMIN,MAC_OVERRIDE,NET_ADMIN,SYSLOG,DAC_READ_SEARCH,LINUX_IMMUTABLE,NET_BROADCAST,IPC_LOCK,IPC_OWNER,SYS_PTRACE,SYS_BOOT,LEASE,WAKE_ALARM,BLOCK_SUSPEND
                   ]
          #########################
          #Container volume mounts
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup:ro
            - name: var-run
              mountPath: /run`

Including - which did not prevail
`          securityContext:
            # userid 0 = root
            runAsUser: 0
            capabilities:
              add: [  CAP_SYS_ADMIN,SYS_MODULE,SYS_RAWIO,SYS_PACCT,SYS_ADMIN,SYS_NICE,SYS_RESOURCE,SYS_TIME,SYS_TTY_CONFIG,AUDIT_CONTROL,MAC_ADMIN,MAC_OVERRIDE,NET_ADMIN,SYSLOG,DAC_READ_SEARCH,LINUX_IMMUTABLE,NET_BROADCAST,IPC_LOCK,IPC_OWNER,SYS_PTRACE,SYS_BOOT,LEASE,WAKE_ALARM,BLOCK_SUSPEND
                   ]`

**Comment by abdennour** [comment]
if it does not work after all these comments, you may need to mount more tmpfs .

```
--tmpfs /run \
--tmpfs /run/lock \
--tmpfs /tmp \
--cap-add SYS_ADMIN \
```

Reference: https://medium.com/@abdennour.toumi/finally-systemd-is-running-in-redhat-centos-containers-3d9598d26976

**Comment by norbertwnuk** [comment]
The example that worked for me on GKE:
```
     containers:
     -  image: almalinux/8-init:8.5
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
          runAsUser: 0
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - mountPath: /tmp
          name: tmp
          subPath: tmp
        - mountPath: /run
          name: tmp
          subPath: run
        - mountPath: /run/lock
          name: tmp
          subPath: run-lock
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - emptyDir:
          medium: Memory
          sizeLimit: 128Mi
        name: tmp
```
