### ISSUE TITLE
404 curling ingress with letsencrypt certs

### ISSUE THREAD

**Issue by spsarolkar** [kubernetes-sigs/kind#1356]
I am trying to configure my service with https using Lets encrypt certificates. I already got everything working fine without https and it works, but once I enable ingress with https I get 404 error

I configured the ingress controller

```bash
cat <<EOF | kind create cluster --name=kube-demo --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80 
    protocol: TCP
  - containerPort: 443 
    hostPort: 443 
    protocol: TCP
EOF
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/mandatory.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/provider/baremetal/service-nodeport.yaml

cat <<EOF | kubectl patch deployments -n ingress-nginx nginx-ingress-controller -p '{
  "spec": {
    "template": {
      "spec": {
        "containers": [
        {
          "name": "nginx-ingress-controller",
          "ports": [
          {
            "containerPort": 80,
            "hostPort": 80 
          },
          {
            "containerPort": 443,
            "hostPort": 443
          }
          ]
        }
        ],
        "nodeSelector": {
          "ingress-ready": "true"
        },
        "tolerations": [
        {
          "key": "node-role.kubernetes.io/master",
          "operator": "Equal",
          "effect": "NoSchedule"
        }
        ]
      }
    }
  }
}'
EOF
```

I also configure the services using yaml deployment files

```bash
➜  example git:(master) ✗ kubectl -n web get svc                            
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)              AGE
cowsay-deamon            ClusterIP   10.96.50.190    <none>        8000/TCP             66m
fortune-teller-service   ClusterIP   10.96.48.157    <none>        80/TCP               64m
redis-primary            ClusterIP   10.96.163.231   <none>        6379/TCP,26379/TCP   66m
redis-secondary          ClusterIP   10.96.188.87    <none>        26379/TCP            66m
```

I also configured the certificateIssuer and Ingress resource using below configuration

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: web
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: spsarolkar@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
                class: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortune-teller-ingress
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - gcp-kube-demo.sunilsarolkar.com
    secretName: fortune-teller-tls-prod
  rules:
  - host: gcp-kube-demo.sunilsarolkar.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: fortune-teller-service
          servicePort: 80
```

But I am getting 404 error response when I hit "http://gcp-kube-demo.sunilsarolkar.com"
```bash
➜  example git:(master) ✗ curl -v http://gcp-kube-demo.sunilsarolkar.com
* Rebuilt URL to: http://gcp-kube-demo.sunilsarolkar.com/
*   Trying 45.124.48.41...
* TCP_NODELAY set
* Connected to gcp-kube-demo.sunilsarolkar.com (45.124.48.41) port 80 (#0)
> GET / HTTP/1.1
> Host: gcp-kube-demo.sunilsarolkar.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.17.8
< Date: Sun, 23 Feb 2020 16:25:12 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Location: https://gcp-kube-demo.sunilsarolkar.com/
< 
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
* Connection #0 to host gcp-kube-demo.sunilsarolkar.com left intact
➜  example git:(master) ✗ curl -v https://gcp-kube-demo.sunilsarolkar.com
* Rebuilt URL to: https://gcp-kube-demo.sunilsarolkar.com/
*   Trying 45.124.48.41...
* TCP_NODELAY set
* Connected to gcp-kube-demo.sunilsarolkar.com (45.124.48.41) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=gcp-kube-demo.sunilsarolkar.com
*  start date: Feb 23 14:57:05 2020 GMT
*  expire date: May 23 14:57:05 2020 GMT
*  subjectAltName: host "gcp-kube-demo.sunilsarolkar.com" matched cert's "gcp-kube-demo.sunilsarolkar.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x564d463b8580)
> GET / HTTP/2
> Host: gcp-kube-demo.sunilsarolkar.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< server: nginx/1.17.8
< date: Sun, 23 Feb 2020 16:25:46 GMT
< content-type: text/html
< content-length: 153
< strict-transport-security: max-age=15724800; includeSubDomains
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
* Connection #0 to host gcp-kube-demo.sunilsarolkar.com left intact
```

I expect the https url to redirect to my service and display my application

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.4 linux/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 2
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-31-generic
 Operating System: Pop!_OS 18.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.53GiB
 Name: pop-os
 ID: Q34X:BDV2:VUD5:6DOK:4ZVF:S3DQ:4XJA:6KFB:FV67:YLUR:MRWR:LUKH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: spsarolkar
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
- OS (e.g. from `/etc/os-release`):
```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by BenTheElder** [comment]
What exactly are you trying to accomplish here, as a broader goal?

First of all, KIND is for *local test clusters* NOT for creating production serving workloads in the cloud exposed to the internet (!). If you want to do this on GCP I _highly_ suggest you consider GKE or one of the various projects from SIG cluster lifecycle aimed at creating production clusters.

Now to debug this anyhow:

As far as I can tell from your logs:
- KIND is working correctly
- Ingress-Nginx appears to be functioning
- A letsencrypt cert appears to be provisioned correctly (I would still recommend against prod certs on toy clusters (!))
- The host is in fact responding to request

So...
- Does your fortune-teller application actually serve 404 on / ..? 🙃
- Is the fortune-teller app running & reachable within the cluster behind the service?

cc @munnerz

**Comment by aledbf** [comment]
> Does your fortune-teller application actually serve 404 on / ..? 

Please check the ingress controller pod logs. The 404 seems to be returned by the ingress controller (unless fortune-teller is behind another nginx)

**Comment by spsarolkar** [comment]
@aledbf you are right ingress controller has below log trace printed

45.124.48.41 - - [25/Feb/2020:15:29:19 +0000] "GET / HTTP/2.0" 404 174 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" 410 0.000 [upstream-default-backend] [] 127.0.0.1:8181 185 0.000 404 cea85b70841f359ac42eb3a16f0a2797


But why does it fallback on default backend when I explicitely mapped the root path
```yaml
  rules:
  - host: gcp-kube-demo.sunilsarolkar.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: fortune-teller-service
          servicePort: 80
```

**Comment by aledbf** [comment]
> But why does it fallback on default backend when I explicitely mapped the root path

Check the ingress controller pod log. You should see the reason why the `fortune-teller-service` is not being used. Check the service name and ports.

**Comment by spsarolkar** [comment]
Thanks a lot @aledbf , I finally got it working with below yaml configuration, as a compliment you can know your fortune from my free fortune teller service 
https://gcp-kube-demo.sunilsarolkar.com ;).  All communication is now encrypted using SSL certificates :)
 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortune-teller-ingress
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - gcp-kube-demo.sunilsarolkar.com
    secretName: fortune-teller-tls-prod
  backend:
    serviceName: fortune-teller-service
    servicePort: 80
```

But I wonder why it didn't work with earlier path configuration?
