### ISSUE TITLE
overlay network cannot be applied when host is behind a proxy

### ISSUE THREAD

**Issue by senthilrch** [kubernetes-sigs/kind#136]
### Environment
Host OS: RHEL 7.4
Host Docker version: 18.09.0
Host go version: go1.11.2
Node Image: kindest/node:v1.12.2

### kind create cluster
```
[root@localhost bin]# kind create cluster
Creating cluster 'kind-1' ...
 ✓ Ensuring node image (kindest/node:v1.12.2) 🖼
 ✓ [kind-1-control-plane] Creating node container 📦
 ✓ [kind-1-control-plane] Fixing mounts 🗻
 ✓ [kind-1-control-plane] Starting systemd 🖥
 ✓ [kind-1-control-plane] Waiting for docker to be ready 🐋
 ✗ [kind-1-control-plane] Starting Kubernetes (this may take a minute) ☸
FATA[07:20:43] Failed to create cluster: failed to apply overlay network: exit status 1
```

Code below in pkg/cluster/context.go is trying to extract k8s version using kubectl version command in order to download the version-specific weave net.yaml. The code is not ok:-
```go
        // TODO(bentheelder): support other overlay networks
        if err = node.Command(
                "/bin/sh", "-c",
                `kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version --kubeconfig=/etc/kubernetes/admin.conf | base64 | tr -d '\n')"`,
        ).Run(); err != nil {
                return kubeadmConfig, errors.Wrap(err, "failed to apply overlay network")
        }
```
Why is the output of kubectl version command, base64 encoded?

**Comment by alejandrox1** [comment]
Hi @senthilrch , thank you for filling this issue.
Could you run `kind create cluster --loglevel debug` and put the output of this command in a [gist](https://gist.github.com/) ?

As for your uestion about installing weave net, you can read more about it [here](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/).

**Comment by BenTheElder** [comment]
Yep, as @alejandrox1 noted, the base64 encoding is from their guide. The reason for this is to pass it as an HTTP query parameter to weave so that their site can serve the appropriate weave version based on your Kubernetes version.

In the future we might use fixed weave versions, but this is the correct and normal way to install it per their upstream documentation.

> kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

It would be this verbatim, but we need to specify the admin kubeconfig location.

--- 

Regarding the failure, is this happening reliably, or did it just happen once?

**Comment by senthilrch** [comment]
It is happening repeatedly. I'll get the debug log gist and add it here.

**Comment by senthilrch** [comment]
https://gist.github.com/senthilrch/70eb56cfeee38e311c13f6898791121a

The host in which I am creating the kind cluster is behind a proxy. Perhaps that's the reason it fails. Will kind honor http_proxy and https_proxy env variables set on the host?

**Comment by BenTheElder** [comment]
Ah, that's almost definitely it!

`kind` does nothing special regarding proxies, the rest of the bringup only works because everything else (besides the overlay network config and its images) is pre-packed into the node image and doesn't need to go out to the internet.

We can either try to get these packed into the image ahead of time (which is probably quite doable, and possibly desirable, but maybe a little tricky), or we can try to make this step respect proxy information on the host machine.

It looks like `http_proxy` and `HTTPS_PROXY` are [mostly a convention that curl and a few others happen to follow to varying degrees](https://unix.stackexchange.com/a/386435), we'd probably need to also set the docker daemon on the "nodes" to respect this as well.

Both approaches are probably worth doing. I'll update this issue to track.

**Comment by metalmatze** [comment]
Within the last 1-2 weeks Kind broke for me with the same error (I believe).

```
 ✓ [control-plane] Creating the kubeadm config file ⛵ 
DEBU[16:26:27] Running: /usr/bin/docker [docker exec --privileged kind-1-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf] 
DEBU[16:26:52] Running: /usr/bin/docker [docker exec --privileged -t kind-1-control-plane cat /etc/kubernetes/admin.conf] 
DEBU[16:26:53] Running: /usr/bin/docker [docker exec --privileged kind-1-control-plane /bin/sh -c kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version --kubeconfig=/etc/kubernetes/admin.conf | base64 | tr -d '\n')"] 
ERRO[16:28:25] failed to apply overlay network: exit status 1 ) ☸ 
 ✗ [control-plane] Starting Kubernetes (this may take a minute) ☸
ERRO[16:28:25] failed to apply overlay network: exit status 1 
DEBU[16:28:25] Running: /usr/bin/docker [docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Names}}\t{{.Label "io.k8s.sigs.kind.cluster"}} --filter label=io.k8s.sigs.kind.cluster=1] 
DEBU[16:28:25] Running: /usr/bin/docker [docker rm -f -v kind-1-control-plane] 
⠈⠁ [control-plane] Pre-loading images 🐋 Error: failed to create cluster: failed to apply overlay network: exit status 1
```
I didn't change anything on my system and simply do a `git pull origin master && go install` every now and then. I'm running on ArchLinux if that's helpful information.

**Comment by BenTheElder** [comment]
@metalmatze is it possible that you're behind a proxy as well? we've not fixed that yet.

**Comment by BenTheElder** [comment]
hmm. I don't think we've made any functional changes to this step in that time frame. FWIW making this step not depend on the internet is very high on my todo :confused: 

other known issues I've seen that can cause similar problems:
- low disk / memory (kubelet will evict workloads, even core components if these get too low)
- btrfs underlying /var/lib/docker causes issues

**Comment by BenTheElder** [comment]
Huh. I can't spot anything relevant in there 🤔 the plot thickens 🙃

I think this week I'll take a stab at pre-loading the CNI images and using
a fixed manifest which should help avoid this sort of issue entirely 🤞

**Comment by alexmt** [comment]
I'm facing the same issue. In my case apply overlay network fails because cloud.weave.works is not resolvable from `kind-1-control-plane` container.  Any help would be very appreciated.

**Comment by alexmt** [comment]
Upgraded docker from 18.09 to 18.09.1 and problem went away 🎉.

**Comment by BenTheElder** [comment]
Huh, I wonder if there was a regression in docker somehow. What docker distribution are you using?

**Comment by metalmatze** [comment]
Interesting. For me it works since 10 days ago and I just checked that I'm on Docker 18.09.1 as well. I should have checked the version when it didn't work.
FWIW I looked at the Arch packages for Docker and the timeline of their releases pretty much adds up with that suspicion!

18.09.1 was pushed on Jan 10th:
https://git.archlinux.org/svntogit/community.git/commit/?h=packages/docker&id=0b11ffde10bf10ab1b08a459c12927ff02abf6d3

**Comment by alexmt** [comment]
@BenTheElder ,  was running dind container `docker:18.09-dind` in kubernetes. After I've changed image to `docker:18.09.1-dind` issue got resolved.

**Comment by BenTheElder** [comment]
Thanks for confirming, I'm going to file another issue to create a "known issues" section in our docs and highlhight this as one of the first ones!

**Comment by neolit123** [comment]
> I was running dind container docker:18.09-dind in kubernetes. After I've changed image to docker:18.09.1-dind issue got resolved.

i wonder what was fixed.

**Comment by BenTheElder** [comment]
so docker itself supports HTTP_PROXY / HTTPS_PROXY https://docs.docker.com/network/proxy/ 🤔 
we could just blindly pass through these values from the host at node creation time... 🤔

**Comment by neolit123** [comment]
it makes sense, especially if it's a fix.

**Comment by pablochacin** [comment]
> so docker itself supports HTTP_PROXY / HTTPS_PROXY https://docs.docker.com/network/proxy/ 
> we could just blindly pass through these values from the host at node creation time...

I opened  issue #270 for implementing this.

**Comment by endzyme** [comment]
I also have the same issue when connected to a VPN client. I havent' dug into this but the same VPN client messes with my docker networking (for future time travelers experiencing the same `failed to create cluster: failed to apply overlay network: exit status 1`)

**Comment by BenTheElder** [comment]
@floreks hmm took a quick peek, nothing leapt out 😞 
we do run kind extensively inside a docker in docker (not the standard image though) setup for k8s CI.

We have seen kubelet continually evicting the API server in a few cases due to low disk / memory but I didn't see that in the logs.


@endzyme I suspect some variant on #270 may help. I am also further exploring #200.

**Comment by floreks** [comment]
@BenTheElder Thanks for the hint. After investigating more, I have seen that `kubelet` was constantly being killed with `SIGKILL (9)`. I have checked `dstat --top-oom` and it showed that whole control plane is constantly being killed by the system.

**Comment by BenTheElder** [comment]
@floreks is your pod:
- privileged
- using a volume of some sort for /var/lib/docker (eg emptyDir)

in addition to resource requests?

**Comment by floreks** [comment]
@BenTheElder Security context is set to allow privileged execution. I am using official [docker:dind](https://hub.docker.com/_/docker) image and docker itself is running in the container. I did not have to mount anything when running it locally and it was working correctly. Only when running in a k8s environment there is an issue.

Here is my test yaml:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test-floreks
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: test-floreks
  name: dind
spec:
  selector:
    matchLabels:
      app: dind
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: floreks/dind-with-kind:v1.0.0
        securityContext:
          privileged: true
```

**Comment by BenTheElder** [comment]
so our actual podspec is ~ the contents of the `pod_spec` field in this prowjob (a few things get added for git checkout, environment variables...):
<details>

```yaml
apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/job: ci-kubernetes-kind-conformance
  creationTimestamp: null
  labels:
    created-by-prow: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-dind-enabled: "true"
    preset-service-account: "true"
    prow.k8s.io/id: bc7c7a72-2b06-11e9-8fd7-0a580a6c037c
    prow.k8s.io/job: ci-kubernetes-kind-conformance
    prow.k8s.io/type: periodic
  name: f8f7ed86-2b0d-11e9-bfc2-0a580a6c0297
spec:
  agent: kubernetes
  cluster: default
  job: ci-kubernetes-kind-conformance
  namespace: test-pods
  pod_spec:
    containers:
    - args:
      - --job=$(JOB_NAME)
      - --root=/go/src
      - --repo=k8s.io/kubernetes=master
      - --repo=sigs.k8s.io/kind=master
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=execute
      - --
      - ./../../sigs.k8s.io/kind/hack/ci/e2e.sh
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: E2E_GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: TEST_TMPDIR
        value: /bazel-scratch/.cache/bazel
      - name: BAZEL_REMOTE_CACHE_ENABLED
        value: "true"
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190205-d83780367-master
      name: ""
      resources:
        requests:
          cpu: "2"
          memory: 9000Mi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
      - mountPath: /etc/service-account
        name: service
        readOnly: true
      - mountPath: /bazel-scratch/.cache
        name: bazel-scratch
      - mountPath: /docker-graph
        name: docker-graph
    dnsConfig:
      options:
      - name: ndots
        value: "1"
    volumes:
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
    - name: service
      secret:
        secretName: service-account
    - emptyDir: {}
      name: bazel-scratch
    - emptyDir: {}
      name: docker-graph
  type: periodic
status:
  startTime: "2019-02-07T19:24:22Z"
  state: triggered
```
</details>
