### ISSUE TITLE
Cannot apply node label to workers

### ISSUE THREAD

**Issue by antoinetran** [kubernetes-sigs/kind#1361]
**What happened**:
When I set a node label in the configuration cluster file for Kind, I do not see the label after deployment:
```
kubectl get node
kubectl describe node/kind-worker | grep -i10 label
```
does not show the label.

**What you expected to happen**:
The command beyond shows the label.

**How to reproduce it (as minimally and precisely as possible)**:

When applying this kind config.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
# one node hosting a control plane
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "key=value"
```
then the cluster is created but without the label.

**Anything else we need to know?**:
I tried hard to find any info related to node labels. This is useful to test in Kind environment our Yaml deployments containing these constraints. I followed https://kind.sigs.k8s.io/docs/user/ingress/ to find an example to set the label. Also, I can see this is somehow related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/789 , but the fix is done at AWS and in kubernetes directly.

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
```
 Server Version: 19.03.5
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.638GiB
```
- OS (e.g. from `/etc/os-release`): `PRETTY_NAME="CentOS Linux 7 (Core)"`

**Comment by BenTheElder** [comment]
So kubeadm InitConfiguration does not apply to workers in kubeadm, only the first control plane.

The example in ingress is only meant to apply to the control plane node, so it is different.

If you use JoinConfiguration it will work

**Comment by BenTheElder** [comment]
I don't recommend using 3 control planes right now either unless you are developing Kubernetes itself. It's unnecessarily expensive.

**Comment by BenTheElder** [comment]
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

Sadly there is no hosted kubeadm documentation for older releases, if you go far enough back in Kubernetes version you'll have to use a different patch as well.

I intend to move the most common patch targets to high level options in KIND that cover this. node labels is definitely one of them.

**Comment by antoinetran** [comment]
Thank you @BenTheElder .
It is working now! I created a branch that documents this:
https://github.com/kubernetes-sigs/kind/compare/master...antoinetran:patch-1
Github has some trouble for pull request submit, I will redo that later.

**Comment by y-batsianouski** [comment]
Hello! I have same issue with kind 0.7.0

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authorization-mode: "AlwaysAllow"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role.kubernetes.io/node=true"

  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "node-role.kubernetes.io/node=true"
```
