### ISSUE TITLE
kind create cluster fails waiting for control-plane in AWS CodeBuild

### ISSUE THREAD

**Issue by MVJosh** [kubernetes-sigs/kind#1383]
**What happened**:
With kind `0.7.0`, `kind create cluster --wait 5m -v 1` fails after `Waiting ≤ 5m0s for control-plane = Ready` with: `WARNING: Timed out waiting for Ready`

Extending this to `--wait 10m` does not fix the issue.
Note that there is no problem with kind `0.6.1`

**What you expected to happen**:
Cluster should be ready with message `Ready after Xs`

**How to reproduce it (as minimally and precisely as possible)**:
Run a build project in AWS code build on the `aws/codebuild/standard:2.0` environment image using the following minimal `buildspec.yaml`:
```
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      golang: 1.13
    commands:
      - apt-get update && apt-get install -y apt-transport-https
      - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
      - apt-get update
      - apt-get install -y kubectl
      - GO111MODULE="on" go get sigs.k8s.io/kind@v0.7.0
  pre_build:
    commands:
      - echo "Starting kubernetes cluster..."
      - kind create cluster --wait 5m -v 1
      - kubectl cluster-info --context kind-kind
    finally:
      - kubectl cluster-info dump
  build:
    commands:
      - echo "Created cluster"
```

**Anything else we need to know?**:
This works on kind <= `0.6.1` - issue only occurs with kind `0.7.0`

**Environment:**

- kind version: (use `kind version`): 0.7.0
- Kubernetes version: (use `kubectl version`): `1.17.3`
- Docker version: (use `docker info`): `18` (unsure exactly which minor version is included in CodeBuild
- OS (e.g. from `/etc/os-release`): `aws/codebuild/standard:2.0` docker image (I believe this is Ubuntu 18.04)
