### ISSUE TITLE
NodePort service endpoint(NodeIP+NodePort) is not supported as destination in Endpoints

### ISSUE THREAD

**Issue by maplain** [kubernetes-sigs/kind#1384]
**What happened**:
Creating a Service manually without selector+ its Endpoints. If one of the endpoints in Endpoints is the NodeIP+NodePort of a service, the traffic doesn't go through.

**What you expected to happen**:
Able to use NodePort service in Endpoints.

**How to reproduce it (as minimally and precisely as possible)**:
Create two deployments, expose one with a NodePort Service.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-1
      tier: frontend-1
  template:
    metadata:
      labels:
        app: hello-1
        tier: frontend-1
    spec:
      containers:
      - name: nginx
        image: "nginxdemos/hello:plain-text"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-2
      tier: frontend-2
  template:
    metadata:
      labels:
        app: hello-2
        tier: frontend-2
    spec:
      containers:
      - name: nginx
        image: "nginxdemos/hello:plain-text"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-2-on-81
spec:
  selector:
    app: hello-2
    tier: frontend-2
  ports:
  - protocol: "TCP"
    port: 81
    targetPort: 80
  type: NodePort
```
Create a Service without selector and its corresponding Endpoints, which has endpoints from pods in the first deployment and the nodeport service which is backed up by the second deployment.
```
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - protocol: "TCP"
    port: 80
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: frontend
  namespace: default
subsets:
- addresses:
  - ip: 172.17.0.2
  ports:
  - name: http
    port: 30859
    protocol: TCP
- addresses:
  - ip: 10.244.0.6
  - ip: 10.244.0.8
  ports:
  - name: http
    port: 80
    protocol: TCP
```
Notice: you need to manually replace the IP Addresses used above.
For example, this is what I had:
```
➜ ✗ kubectl get nodes -o wide
NAME                 STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION     CONTAINER-RUNTIME
kind-control-plane   Ready    master   11m   v1.17.0   172.17.0.2    <none>        Ubuntu 19.10   4.19.76-linuxkit   containerd://1.3.2
➜ ✗ kubectl get svc svc-2-on-81
NAME          TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
svc-2-on-81   NodePort   10.96.143.54   <none>        81:30859/TCP   10m
➜ ✗ kubectl get svc,ep svc-2-on-81
NAME                  TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/svc-2-on-81   NodePort   10.96.143.54   <none>        81:30859/TCP   10m

NAME                    ENDPOINTS                     AGE
endpoints/svc-2-on-81   10.244.0.5:80,10.244.0.7:80   10m
➜ ✗ kubectl get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
test-1-748496c8bb-4rqtv   1/1     Running   0          10m   10.244.0.8   kind-control-plane   <none>           <none>
test-1-748496c8bb-ljm27   1/1     Running   0          10m   10.244.0.6   kind-control-plane   <none>           <none>
test-2-cb6fff7f8-5vlxd    1/1     Running   0          10m   10.244.0.5   kind-control-plane   <none>           <none>
test-2-cb6fff7f8-mw5bm    1/1     Running   0          10m   10.244.0.7   kind-control-plane   <none>           <none>
```

**Anything else we need to know?**:
Verified on another k8s cluster deployed on VMs, and it works as expected. Thus this is a Kind issue.

**Environment:**

- kind version: (use `kind version`):
kind version 0.7.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`):
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 231
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 9.734GiB
 Name: docker-desktop
 ID: CJC3:ZSLM:FG7L:G6Z7:3QFQ:2PKN:YWPM:5GC3:GR6M:23WA:ZA5U:EXNU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 55
  System Time: 2020-03-04T19:40:01.3286998Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

- OS (e.g. from `/etc/os-release`):
➜  ✗ uname -a
Darwin xxxxxxx 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
