### ISSUE TITLE
Make the master and workers an option on CLI

### ISSUE THREAD

**Issue by vikas027** [kubernetes-sigs/kind#1403]
**What would you like to be added**:
As of now, we need to have a yaml file in order to define worker nodes.

```yaml
~ $ cat kind.yaml 
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
~ $
```

It would be great to remove use a CLI option too, something like this
```bash
~ $ kind create cluster --name cluster1 --master 3 --worker 2
```

**Why is this needed**:
This would reduce the need of the yaml file.
