### ISSUE TITLE
Starting control-plane error： Waiting for the kubelet to boot up the control plane as static Pods from directory

### ISSUE THREAD

**Issue by Wenshiqi222** [kubernetes-sigs/kind#1407]
**What happened**:
When i use kind to create a HA cluster on my PC（centOS7-vmware），No matter what kind version I use，when  it turns to “Starting control-plane ”，it failed by showing 
 

>  “ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged wen-ha-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
”;

   and later i recreate the same HA cluster by adding `--loglevel debug`  to get the details,and i

got the information below

 

```

> _[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
> I0315 07:31:05.610556    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 9 milliseconds
> I0315 07:31:06.112407    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 1 milliseconds
> I0315 07:31:06.611536    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 0 milliseconds
> I0315 07:31:07.116576    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 2 milliseconds
> I0315 07:31:07.612998    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 1 milliseconds
> I0315 07:31:08.112067    1535 round_trippers.go:438] GET https://172.17.0.8:6443/healthz?timeout=32s  in 0 milliseconds
........
> Unfortunately, an error has occurred:
> 	timed out waiting for the condition
> 
> This error is likely caused by:
> 	- The kubelet is not running
> 	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
> 
> If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
> 	- 'systemctl status kubelet'
> 	- 'journalctl -xeu kubelet'
> 
> Additionally, a control plane component may have crashed or exited when started by the container runtime.
> To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
> Here is one example how you may list all Kubernetes containers running in docker:
> 	- 'docker ps -a | grep kube | grep -v pause'
> 	Once you have found the failing container, you can inspect its logs with:
> 	- 'docker logs CONTAINERID'
> error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster_

```

**What you expected to happen**:
No error shows, all the processes pass and the HA cluster create successfully

**How to reproduce it (as minimally and precisely as possible)**:  
When applying this kind config.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: registry.aliyuncs.com/google_containers
  nodeRegistration:
    kubeletExtraArgs:
      pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.1
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: registry.aliyuncs.com/google_containers
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker

```
and then the error shows up
**Anything else we need to know?**:
Honestlyl,  I had the same problem once  i installed my master node by kubeadm，which was solved by re-installing the kubelet ! But this time,using kind to create a cluster,the problem cannot be solved the same way,cause i cannot even touch the kubelet ~
**Environment:**

- kind version: (use `kind version`): kind version 0.7.0
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 10.1.60.142:6443 was refused - did you specify the right host or port?
```

- Docker version: (use `docker info`):
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- OS (e.g. from `/etc/os-release`): PRETTY_NAME="CentOS Linux 7 (Core)"

**Comment by neolit123** [comment]
/remove-kind bug
/triage support

note that you need a lot of RAM for a 3 CP x 3 worker setup. how much RAM do you have available for this cluster?

>  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: registry.aliyuncs.com/google_containers

you can remove the above patch for InitConfiguration:

networking and imageRepository are fields of ClusterConfiguration:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

**Comment by neolit123** [comment]
> Honestlyl, I had the same problem once i installed my master node by kubeadm，which was solved by re-installing the kubelet ! But this time,using kind to create a cluster,the problem cannot be solved the same way,cause i cannot even touch the kubelet ~

technically, you can `docker exec -it ...` on kind nodes. but unless you customize this the kubeadm, kubelet, control-plane versions in the kind setup match.

**Comment by BenTheElder** [comment]
- are you able to create any clusters on this machine? single node? if so, it is probably a matter of resources as @neolit123 said
- what exactly was fixed by "reinstalling" kubelet ...? note that we are not even using a package to install kubelet, we build it from source and place it in the image... "install" is just adding the binary and systemd unit `:confused:`
- if you want to set subnets, please use the kind config field instead of the patches.

you likely should not be setting:
```
imageRepository: registry.aliyuncs.com/google_containers
  nodeRegistration:
    kubeletExtraArgs:
      pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.1
```

core kubernetes images including pause are pre-bundled into the kind node images, pause should not be pulled at runtime. setting this will force it to pull images that already exist but for the standard upstream registry.

**Comment by Wenshiqi222** [comment]
> /remove-kind bug
> /triage support
> 
> note that you need a lot of RAM for a 3 CP x 3 worker setup. how much RAM do you have available for this cluster?
> 
> > apiVersion: kubeadm.k8s.io/v1beta2
> > kind: InitConfiguration
> > metadata:
> > name: config
> > networking:
> > serviceSubnet: 10.0.0.0/16
> > imageRepository: registry.aliyuncs.com/google_containers
> 
> you can remove the above patch for InitConfiguration:
> 
> networking and imageRepository are fields of ClusterConfiguration:
> https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

thanks for helping，i only set 2G RAM for the cluster，i guess it's not enough .But how much RAM should i set for 3 CP x 3 worker setup?

**Comment by BenTheElder** [comment]
I'm not sure exactly how much you need and it will vary slightly by version etc... kubeadm recommends 2gb per node.

I would recommend using a single node though unless you are testing certain functionality of kubernetes itself or have a very particular testing need, unlike a "real cluster" you don't gain much isolation or any extra workload capacity by adding nodes.

**Comment by Wenshiqi222** [comment]
> * are you able to create any clusters on this machine? single node? if so, it is probably a matter of resources as @neolit123 said
> * what exactly was fixed by "reinstalling" kubelet ...? note that we are not even using a package to install kubelet, we build it from source and place it in the image... "install" is just adding the binary and systemd unit `:confused:`
> * if you want to set subnets, please use the kind config field instead of the patches.
> 
> you likely should not be setting:
> 
> ```
> imageRepository: registry.aliyuncs.com/google_containers
>   nodeRegistration:
>     kubeletExtraArgs:
>       pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.1
> ```
> 
> core kubernetes images including pause are pre-bundled into the kind node images, pause should not be pulled at runtime. setting this will force it to pull images that already exist but for the standard upstream registry.

thanks a lot~
first i  remove the  patch for InitConfiguration  @neolit123  mentioned,then i remove the pause setting you mentioned.Then i  create a cluster with one control-plane and one worker node successfully!
 Finally i recreate the HA cluster which i want before,and i got stuck at  "Preparing Nodes",the symbol keeps circling，does this have anything to do with the  RAM allocation？

**Comment by Wenshiqi222** [comment]
I really appreciate @BenTheElder @neolit123 for your help!!!,now i have created  the HA cluster successfully by setting 4GB RAM~
But now,i had another problem,when the cluster was created, when i type
`kubectl get nodes`
i got information below
`The connection to the server 127.0.0.1:32771 was refused - did you specify the right host or port?`
what? i have already installed kubectl

**Comment by Wenshiqi222** [comment]
I really appreciate the help @neolit123  @BenTheElder ，i set 4GB RAM for the cluster,and now my HA cluster has created successfully!
But`````````````````,i had another problem which makes me think if my cluster is heathy . Here is the issue:
1、After the creating process, i use the command ` kubectl get nodes` ,then i got the  sign 
`The connection to the server 127.0.0.1:32771 was refused`
2、So i check the kubeconfig file by the command `kubectl config view` , it shows
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:32771
  name: kind-test3
contexts:
- context:
    cluster: kind-test3
    user: kind-test3
  name: kind-test3
current-context: kind-test3
kind: Config
preferences: {}
users:
- name: kind-test3
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
3、I thought this might be the port issue, so i check if the containers are running,so i type `docker ps -a` , then i found  none of the containers were running, especially the  control-plane with ports "127.0.0.1:32771->6443/tcp”，so i guess maybe this caused the connection problem，so restart all the containers,and the status is shown below:
```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
47972be3187a        kindest/haproxy:2.1.1-alpine   "/docker-entrypoint.…"   2 hours ago         Up 19 minutes       127.0.0.1:32768->6443/tcp   test3-external-load-balancer
1a9b0dac1da7        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 18 minutes       127.0.0.1:32769->6443/tcp   test3-control-plane2
77a3883178a0        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 18 minutes       127.0.0.1:32770->6443/tcp   test3-control-plane
b75b5ef26186        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 18 minutes       127.0.0.1:32771->6443/tcp   test3-control-plane3
8613d5cea1b9        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 17 minutes                                   test3-worker
a472e509535d        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 17 minutes                                   test3-worker3
6f7842b30f6e        kindest/node:v1.17.0           "/usr/local/bin/entr…"   2 hours ago         Up 17 minutes                                   test3-worker2
```
4、However，when i retried the command `kubectl get nodes`,  it still cannot work which shows 
`Unable to connect to the server: EOF`  
So i am really confused, is the cluster fully created? By the way, i think i should show you my  config.yaml after  taking your opinions：
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: registry.aliyuncs.com/google_containers
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
```
i just remove some parts you mentioned yesterday, but every step of the creating process has passed.But why all the contianers were  exited at the beginning? 
I am new in the k8s field， really thanks for your help！
