### ISSUE TITLE
Adding  Metircs to Cluster images cannot be pulled successfully

### ISSUE THREAD

**Issue by Wenshiqi222** [kubernetes-sigs/kind#1423]
**What happened**:
Today，i wanna test the HPA function on my HA-cluster，since heapster is not used any more,i need to get some resources through Metircs，So i prepared necessary config files for Metrics :
```
[root@localhost kubernetes]# ls
aggregated-metrics-reader.yaml  auth-reader.yaml         metrics-server-deployment.yaml  resource-reader.yaml
auth-delegator.yaml             metrics-apiservice.yaml  metrics-server-service.yaml
```
then i apply them 
[root@localhost kubernetes]# kubectl apply -f .
```
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.apps/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
```
Then i decribe the Metics pods:
```
[root@localhost kubernetes]# kubectl describe pods metrics-server-74b4744bd5-xfpc9 -n kube-system
Name:         metrics-server-74b4744bd5-xfpc9
Namespace:    kube-system
Priority:     0
Node:         kind-worker3/172.17.0.3
Start Time:   Thu, 19 Mar 2020 18:41:42 +0800
Labels:       k8s-app=metrics-server
              pod-template-hash=74b4744bd5
Annotations:  <none>
Status:       Pending
IP:           10.244.3.4
IPs:
  IP:           10.244.3.4
Controlled By:  ReplicaSet/metrics-server-74b4744bd5
Containers:
  metrics-server:
    Container ID:  
    Image:         mirrorgooglecontainers/metrics-server-amd64:v0.3.2
    Image ID:      
    Port:          4443/TCP
    Host Port:     0/TCP
    Command:
      /metrics-server
      --kubelet-preferred-address-types=InternalIP
      --kubelet-insecure-tls
    Args:
      --cert-dir=/tmp
      --secure-port=4443
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-prwh6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-prwh6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-prwh6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
                 kubernetes.io/arch=amd64
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                   Message
  ----     ------     ----                 ----                   -------
  Normal   Scheduled  <unknown>            default-scheduler      Successfully assigned kube-system/metrics-server-74b4744bd5-xfpc9 to kind-worker3
  Warning  Failed     2m31s                kubelet, kind-worker3  Failed to pull image "mirrorgooglecontainers/metrics-server-amd64:v0.3.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to resolve reference "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to do request: Head https://registry-1.docker.io/v2/mirrorgooglecontainers/metrics-server-amd64/manifests/v0.3.2: dial tcp: lookup registry-1.docker.io on 255.6.6.6:53: read udp 172.17.0.3:55733->255.6.6.6:53: i/o timeout
  Warning  Failed     118s                 kubelet, kind-worker3  Failed to pull image "mirrorgooglecontainers/metrics-server-amd64:v0.3.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to resolve reference "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to do request: Head https://registry-1.docker.io/v2/mirrorgooglecontainers/metrics-server-amd64/manifests/v0.3.2: dial tcp: lookup registry-1.docker.io on 255.6.6.6:53: read udp 172.17.0.3:37827->255.6.6.6:53: i/o timeout
  Warning  Failed     70s                  kubelet, kind-worker3  Failed to pull image "mirrorgooglecontainers/metrics-server-amd64:v0.3.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to resolve reference "docker.io/mirrorgooglecontainers/metrics-server-amd64:v0.3.2": failed to do request: Head https://registry-1.docker.io/v2/mirrorgooglecontainers/metrics-server-amd64/manifests/v0.3.2: dial tcp: lookup registry-1.docker.io on 255.6.6.6:53: read udp 172.17.0.3:58370->255.6.6.6:53: i/o timeout
  Warning  Failed     70s (x3 over 2m31s)  kubelet, kind-worker3  Error: ErrImagePull
  Normal   BackOff    33s (x5 over 2m30s)  kubelet, kind-worker3  Back-off pulling image "mirrorgooglecontainers/metrics-server-amd64:v0.3.2"
  Warning  Failed     33s (x5 over 2m30s)  kubelet, kind-worker3  Error: ImagePullBackOff
  Normal   Pulling    18s (x4 over 2m51s)  kubelet, kind-worker3  Pulling image "mirrorgooglecontainers/metrics-server-amd64:v0.3.2"

```

**What you expected to happen**:
The image can be pulled successfully!
**How to reproduce it (as minimally and precisely as possible)**:
Here is my deployment.yaml  :
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      containers:
      - name: metrics-server
        image:  mirrorgooglecontainers/metrics-server-amd64:v0.3.2
   #     image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        args:
          - --cert-dir=/tmp
          - --secure-port=4443
        ports:
        - name: main-port
          containerPort: 4443
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        imagePullPolicy: IfNotPresent
        command:
            - /metrics-server
            - --kubelet-preferred-address-types=InternalIP
            - --kubelet-insecure-tls
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/arch: "amd64"

```
**Anything else we need to know?**:
i changed several image resources ，but got the same error information each time,so i thought it might not be the image resource problem. BTW, my docker can pull nginx/busybox ,the pulling function has no problem.
**Environment:**

- kind version: (use `kind version`):
```
`kind v0.7.0 go1.13.6 linux/amd64`
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: (use `docker info`):
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- OS (e.g. from `/etc/os-release`): VM centOS7
