### ISSUE TITLE
Is there a way to customize the etcd compaction interval?

### ISSUE THREAD

**Issue by nikhilk** [kubernetes-sigs/kind#1436]
I've been looking around for some way to customize the etcd compaction interval (which https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ suggests is defaulted to 5m). For a particular simulated workload, I'd like to change this to a smaller interval.

Is there a way to do so? I am not familiar with kubeadm configs -- maybe this is supported via Cluster config's kubeadmConfigPatches and/or containerdConfigPatches.

If someone has any ideas, that would be appreciated. Thanks!

**Comment by yashbhutwala** [comment]
Edit it manually, which will auto-refresh the apiserver

```bash
docker exec -it kind-control-plane bash
apt-get update && apt-get -y install vim
vi /etc/kubernetes/manifests/kube-apiserver.yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - --etcd-compaction-interval 10m
```
Or via kubeadmConfigPatches, quick reference [here](https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster) and [k8s docs here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/):

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
kubeadmConfigPatches:
  - |
    # v1beta2 only works for 1.15+
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        etcd-compaction-interval: "10m"
```

Hope that helps 😄
