### ISSUE TITLE
While trying k8s 1.18, it fetches 1.17 node image also

### ISSUE THREAD

**Issue by rajalokan** [kubernetes-sigs/kind#1447]
**What happened**:
While trying out new 1.18 release, I see kind is fetching ( or at least logging) `1.17` node image. 

```
➜ ~ ✗ cat <<EOF | kind create cluster --name okan --config -
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: worker
EOF

Creating cluster "okan" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
 ✓ Ensuring node image (kindest/node:v1.18.0) 🖼 ^[[C
 ✓ Preparing nodes 📦 📦 
```
Is this normal behaviour ? Is this being fetched because `1.17` is the default node ? 

**What you expected to happen**:
First line after `Creating cluster "okan"` should not be there. If a particular version is specified, it shouldn't fetch old version node image. 

**How to reproduce it (as minimally and precisely as possible)**:
Run above command 

**Anything else we need to know?**:
Latest kind version `v0.7.0`

**Environment:**
- kind version: (use `kind version`): v0.7.0
- Kubernetes version: (use `kubectl version`): 1.18
- Docker version: (use `docker info`): 18.06-1-ce
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by BenTheElder** [comment]
No, this is because you set the image on one node but not the other.

**Comment by BenTheElder** [comment]
this would be the correct 1.18 only config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
- role: worker
  image: kindest/node:v1.18.0@sha256:0e20578828edd939d25eb98496a685c76c98d54084932f76069f886ec315d694
```
