### ISSUE TITLE
Ability to configure cpu: "x"

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#1451]
I have an Istio error: 1 Insufficient cpu.

Can you configure more cpu?

I am looking for something like:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node
- role: control-plane
- role: worker
  constraints:
    memory: "500m"
    cpu: "2"
```
