### ISSUE TITLE
Node images get a 'null' name, and cannot be serialized via kube-rs

### ISSUE THREAD

**Issue by kobeHub** [kubernetes-sigs/kind#1462]
**What happened**:

I'm using a single node kind cluster and Rust k8s client library [kube-rs](https://github.com/clux/kube-rs). After cluster created, there is a **null** image name in the `kubectl get node -oyaml` output: 
```yaml
images:
    - names:
      - k8s.gcr.io/etcd:3.3.10
      sizeBytes: 258352475
    - names:
      - k8s.gcr.io/kube-apiserver:v1.15.3
      sizeBytes: 249032413
    - names:
      - docker.io/grafana/grafana@sha256:4282e80b18bb148dcc9745a337c7008d4c8397b369933cfb4e66d15f363d1818
      - docker.io/grafana/grafana:6.6.2
      sizeBytes: 238135891
    - names:
      - k8s.gcr.io/kube-controller-manager:v1.15.3
      sizeBytes: 199826159
    - names:
      - quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:b312c91d0de688a21075078982b5e3a48b13b46eda4df743317d3059fc3ca0d9
      - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0
      sizeBytes: 114165218
    - names:
      - k8s.gcr.io/kube-proxy:v1.15.3
      sizeBytes: 97345619
    - names:
      - k8s.gcr.io/kube-scheduler:v1.15.3
      sizeBytes: 96545500
    - names:
      - docker.io/kindest/kindnetd:0.5.0
      sizeBytes: 83630307
    - names:
      - k8s.gcr.io/coredns:1.3.1
      sizeBytes: 40532361
    - names:
      - quay.io/prometheus/prometheus:v2.4.3
      sizeBytes: 36710876
    - names: null
      sizeBytes: 22167426
```
And it can't be serialized via the client library because the name field in [k8s_openapi::api::core::v1::ContainerImage](https://docs.rs/k8s-openapi/0.7.1/k8s_openapi/api/core/v1/struct.ContainerImage.html) is not `Option` which means it cannot be null. I'm not sure why there is a null name image. 
**What you expected to happen**:
There is no null image
 
**How to reproduce it (as minimally and precisely as possible)**:
+ kind load nessary images
+ create kind cluster with ingress
+ `kubectl get node -oyaml`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): v0.7.0
- Kubernetes version: (use `kubectl version`): 1.15.3
- Docker version: (use `docker info`): 19.03.8-ce
- OS (e.g. from `/etc/os-release`):Manjaro Linux
