### ISSUE TITLE
Can't create a new container in the pod by connecting to host docker instance.

### ISSUE THREAD

**Issue by sureshappana** [kubernetes-sigs/kind#1522]
I am trying to run Hyperledger fabric in Kind cluster. 

Image is: `hyperledger/fabric-peer:1.4.3`. Main container in this image is, `peer` 
 and this takes CORE_VM_ENDPOINT which points to unix:///host/var/run/docker.sock. This has host /var/run/docker.sock mounted to the path /host/var/run in the container. After `peer` container started I am trying to run a step which starts a new container `chaincode` next to this peer container. 

This is my current setup:
docker > kind cluster > pod > peer container

My sample deployment. I tried to run the same setup in docker-in-deskop, which was worked and able to create the container.

I did also try steps mentioned in https://github.com/kubernetes-sigs/kind/issues/303#issuecomment-518593664 but no success.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org1peer0
  labels:
    type: peer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: org1peer0
  template:
    metadata:
      labels:
        name: org1peer0
        type: peer
    spec:
      volumes:
      - name: fabricfiles
        persistentVolumeClaim:
          claimName: fabric-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: peer
        image: hyperledger/fabric-peer:1.4.3
        command: ["sh", "-c", "peer node start"]
        securityContext:
          privileged: true
        env:
          <some-env-config>
        volumeMounts:
        - mountPath: /fabric
          name: fabricfiles
        - mountPath: /host/var/run
          name: dockersocket/docker.sock
      - name: couchdb
        image: hyperledger/fabric-couchdb:0.4.14
        env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: COUCHDB_USER
          value: "hyperledgeruser"
        - name: COUCHDB_PASSWORD
          value: "hyperledgerpass"
```

**What happened**:
Can't create a new container in the pod by connecting to host docker instance.

**What you expected to happen**:
Should create a new container in the pod by connecting to host docker instance.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`): 1.17
- Docker version: (use `docker info`): 19.03.8
- OS (e.g. from `/etc/os-release`): macOS Catalina
