### ISSUE TITLE
Using extraPortMappings in Windows

### ISSUE THREAD

**Issue by farzadmf** [kubernetes-sigs/kind#1523]
I'm using Docker Desktop on Windows and I'm trying to figure out how to use `extraPortMappings` to access my services

I'm trying with 2 clusters I created using `kind`, the first one:
```bash
kind create cluster --config kind-config.yaml
```
And my config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
```
And I do these:
```bash
kubectl create deploy mygninx --image=nginx
kubectl expose deploy mynginx --type NodePort --port 80
```
Then, when I try to access:
```
curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

So, I created another cluster to test:
```bash
kind create cluster --name kind2 --config kind-config.yaml
```

And my config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8081
- role: worker
```

And I try to access this one:
```
curl localhost:8081
curl: (52) Empty reply from server
```

I tried to search in the issues, but I couldn't find a similar one, so sorry if this is a duplicate issue

**Comment by BenTheElder** [comment]
kubernetes nodeports are in the range `30000-32767` by default. when you request `80` you get a random port in that range instead.

https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

if you forward one of those ports it should work, otherwise you'll want to consider e.g. an ingress, or using a hostport https://kind.sigs.k8s.io/docs/user/ingress/

on linux you can use type=loadblancer using metallb, but not on windows currently due to docker's networking model
https://kind.sigs.k8s.io/docs/user/resources/#how-to-use-kind-with-metalllb

**Comment by farzadmf** [comment]
Thank you @BenTheElder for your answer, a few questions:
- I thought I *am* using the `hostPort`, aren't I? In the config, I have `hostPort: 8080`, so I thought that means that the port `8080` would be the mapped port I can use

- When you say "when you request `80`", you mean when I run `kubectl expose` command? If so, as you mentioned, if I don't configure the `nodePort` in a service YAML file (I don't think it's possible through `kubectl expose` command), I would get a random port, so I don't think I can forward it in advance, right?

- Is it somehow possible to map ports "on-the-fly" (*after* I create my cluster without requiring to re-create the cluster)? Or everything should be known before creating the cluster?

Thank you for the tip regarding `metallb`; I'll definitely check that out on my home Linux machine. However, I would really like to be able to try things in my work Windows machine too (I think I can live without the load balancer, but I need to be able to call my services)

**Comment by BenTheElder** [comment]
Quick example (not tested on windows).

I tend to use yaml and `kubectl apply -f` for anything more interesting and had forgotten that `kubectl expose ...` doesn't support setting the nodeport. however `kubectl create service nodeport ...` does (xref: https://github.com/kubernetes/kubernetes/issues/25478)|

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - hostPort: 31111
    containerPort: 31111
```

```console
kubectl create deploy mynginx --image=nginx
kubectl create service nodeport --node-port=31111 mynginx --tcp=80:80
```
