### ISSUE TITLE
How to set Node Allocatable memory in kind?

### ISSUE THREAD

**Issue by arianvp** [kubernetes-sigs/kind#1524]
When I create a KIND cluster; it sets the Node Allocatable memory to the max memory that my laptop has. However I want to limit it to something lower because I'm usually running other things on my laptop as well (like a browser)

Usually one would do this through specifying kubelet flags as I read here: https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

I tried looking in the docs but found nothing about how to override kubelet flags so this is probably not the right way. 

Reason is i'm trying to debug some deployment locally; but because kind thinks there is more RAM than it actually has it over-allocates and my computer runs out of memory and locks up before I can debug.  I want to turn that over-allocation into a scheduling error; by giving kind less memory to work with.

**Comment by arianvp** [comment]
I think this and https://github.com/kubernetes-sigs/kind/issues/877 are the same question. Feel free to close if you agree

**Comment by BenTheElder** [comment]
#877 is looking to actually change the node size I think, overridding kubelet flags can be done with a kubeadmConfigPatch which needs more documentation... it's on our radar.

**Comment by BenTheElder** [comment]
supporting this first class might be a better answer than #877's current WIP approach

**Comment by aojea** [comment]
> supporting this first class might be a better answer than #877's current WIP approach

yeah, definitely that's the missing part in that PR, is just not isolating the nodes, is "converting" them in VMs and for that we need kubelet to only "see" the allocated resources ... hehe, I didn't get that before 😅 

Let me play with this https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#example-scenario and see how it goes

/assign

**Comment by arianvp** [comment]
How would this look with `kubeadmConfigPatch`?

**Comment by arianvp** [comment]
Answering my own question:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=4Gi
```

**Comment by teachermanalex** [comment]
Thanks @arianvp .  I did this, and copied the block to my worker node as well.  It reduced the allocatable memory for the control-plane node, but not the worker node.
Any ideas?

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=8Gi
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=8Gi
```
