### ISSUE TITLE
Standard way for Kind to communicate about a local registry

### ISSUE THREAD

**Issue by nicks** [kubernetes-sigs/kind#1543]
Many Kubernetes clusters support a local registry, to make pushing images directly to the cluster fast. But every cluster documents it with manual shell scripts:

- https://kind.sigs.k8s.io/docs/user/local-registry/
- https://microk8s.io/docs/registry-built-in
- https://github.com/rancher/k3d/blob/master/docs/registries.md#using-a-local-registry
- https://docs.openshift.com/container-platform/4.3/registry/accessing-the-registry.html#registry-accessing-directly_accessing-the-registry

Because every cluster is slightly different, this makes it hard for tools to automate this work for users.

## The big idea

Clusters should use annotations on the `kube-system` namespace to document how to configure a registry

## Detailed design

I propose 3 new "standard" annotations:

`x-k8s.io/registry`: the host of the registry (hostname and port), as seen from outside of the cluster
`x-k8s.io/registry-from-cluster`: the host of the registry (hostname and port), as seen from inside the cluster
`x-k8s.io/registry-help`: The URL of documentation where users can read more about how to set a registry up. 

Tools that would benefit from local registries should read this annotation and display it to the user

## What this means for Kind

All Kind clusters would have a `registry-help` annotation pointing users to https://kind.sigs.k8s.io/docs/user/local-registry/

We'd also update the example script at https://kind.sigs.k8s.io/docs/user/local-registry/ to add the `x-k8s.io/registry` annotation during setup.

## Prior Art

This proposal is based on what we've been recommending to people in Tilt, with a lot of success: https://docs.tilt.dev/choosing_clusters.html#custom-clusters

*update 5/4* - changed the proposal to use the `kube-system` namespace instead of node annotations

**Comment by nicks** [comment]
I also filed this feature request here https://github.com/rancher/k3d/issues/234 and here https://github.com/ubuntu/microk8s/issues/1173

**Comment by BenTheElder** [comment]
FWIW x-k8s.io currently is typically used by community projects under something like `<project>.x-k8s.io`, I think there's guidance about this somewhere but I haven't needed to look in a while.

i'm not sure if there's something this would neatly fall under.

I like the general idea though, if not a standard annotation maybe something like checking for `.*/registry-help` etc?

**Comment by BenTheElder** [comment]
sending a poke to cluster-lifecycle, which seems like they might be the appropriate group for this, given that it's sort of a cluster-addon detail.

**Comment by neolit123** [comment]
this is an interesting topic for the SIG cluster-lifecycle Zoom meeting:
https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle
see: `Regular SIG Meeting...`

[SIG contacts](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle#contact).

and potentially going trough a K8s [KEP process](https://github.com/kubernetes/enhancements/tree/master/keps) if there is interest.

initial take:
- adding host:port or URL links in annotations is still an API contract, so there is potential for an old cluster to now point to an outdated location.
- by "local" are we considering node-local or in the same subnetwork as the cluster nodes?
- if the registry is considered "cluster-wide" then annotating the "kube-system" namespace seems more appropriate even if images are node local. this however means node clients would have to be able to read the namespace, which i don't think is ideal. one the other hand, what happens if one node points to one registry and second node to another, which one is the "cluster" registry?

**Comment by cppforlife** [comment]
@nicks it's interesting that you picked node annotations to store this data. are you expecting that "cluster registry" may differ per node?

i would recommend to make an expectation that if there exists registry configuration it applies to all nodes(== entire cluster). given that, it's worth considering alternative places for storage:
- a configmap in kube-system
- ClusterRegistry CRD and ClusterRegistry CR (at the cluster level)
  - you could have multiple cluster level CRs to represent multiple registries

**Comment by nicks** [comment]
@neolit123 thanks for the pointer! is it ok if I just add it to the meeting agenda for tomorrow?

re: some of the specific technical points that @neolit123 and @cppforlife made:

- I really like the suggestion to set it per-namespace! I'll update the proposal at the top of the post

- For our purposes, "local" means any insecure registry that's co-located with the cluster and eligible to be exposed directly to the developer's machine. The term is trying to evoke more how the developer should expect to interact with it than how it's implemented.

- The role of this annotation is to communicate to tools outside Kubernetes the current state, rather than for communicating inside Kubernetes the desired state (the latter is more what I see ConfigMap is for)

- I like the idea that long-term, all these local registry solutions should converge towards a shared ClusterRegistry CR. But I'm not totally sure what that looks like yet, and would want to try building a POC before I proposed anything. This is mostly suggesting a first step towards documenting the solutions that already exist.

**Comment by nicks** [comment]
oh - and would also love better suggestions on the annotation namespace; I also had trouble finding a good recommendation on this

**Comment by neolit123** [comment]
> is it ok if I just add it to the meeting agenda for tomorrow?

sure, please join the mailing list (google group), to be able to edit the document.

**Comment by bboreham** [comment]
Strikes me that this is similar to what we can find via the `ComponentConfig` API.

**Comment by nicks** [comment]
We had a long discussion about this in the sig-cluster-lifecycle meeting today. Thanks @neolit123 for facilitating. The group proposed a few alternative implementations that I want to think on. I'm going to start a KEP in sig-cluster-lifecycle to kick the tires on this proposal

@bboreham I'm reading up on ComponentConfig right now -- ya, I see the resemblance. And the resemblance to the Kind config (https://godoc.org/sigs.k8s.io/kind/pkg/internal/apis/config#Cluster) There's no way to access those from outside the cluster, right?

**Comment by BenTheElder** [comment]
kubeadm stores it's component config in a configmap which you can access via the kubernetes API

**Comment by BenTheElder** [comment]
Er and kind's config is modeled after component config but ... without pulling in all the heavy k8s API machinery.

**Comment by shuhaowu** [comment]
I just found this issue and it is somewhat related to what I'm doing:

My goal is to test a system deployed on kubernetes in KinD. We use GCR and build and upload images to gcr.io in CI. As a result, the system we are deploying are referencing these images via their `gcr.io` names. Since we are mutating these images, rebuilding them, and testing them in a KinD based environment, it's very cumbersome to start of a CI run, get the images to build, pull it. This is not even mentioning the problems authorization, where tokens to GCR.io expires frequently.

To solve this problem, when I change any images, I would build and tag it locally with their full name including the `gcr.io` part. Then I can use `kind load docker-image` to load the image into KinD. As a result, Kubernetes pods can "pull" these locally built "`gcr.io`" images. However, this is very slow with a large number of images and larger images. So I introduced a registry via a simple StatefulSet deployed into KinD along with the following patch:

```
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://localhost:31500"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31500 # Docker registry
        hostPort: 31500
        listenAddress: "127.0.0.1"

```

With this, I can build, tag, and push the images into localhost:31500/... and Kubernetes will correctly pull images named with the `gcr.io` prefix from `localhost:31500`. This behaviour works in KinD 0.7.0, but appears to be broken in 0.8.1 as Kubernetes now get stuck at pulling images.

I'm commenting here for two reasons:

1. To see if what I'm doing can make it upstream somehow.
2. Figure out if i should open another issue fixing the regression from 0.7.0 to 0.8.1. I suspect it's the networking changes? but I have no idea what I'm doing.

registry-statefulset.yaml:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-int
  namespace: registry
  labels:
    app: registry
spec:
  ports:
    - name: registry
      port: 5000
  clusterIP: None
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ext
  namespace: registry
  labels:
    app: registry
spec:
  ports:
    - name: registry
      nodePort: 31500
      port: 5000
      targetPort: 5000
  type: NodePort
  selector:
    app: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: registry
spec:
  serviceName: registry-int
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "registry:2"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
  volumeClaimTemplates:
    - metadata:
        name: registry-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
```
