### ISSUE TITLE
How to create multi-node cluster setting up an Ingress Controler

### ISSUE THREAD

**Issue by serrodcal** [kubernetes-sigs/kind#1552]
**What would you like to be documented**: I'd like to have an example of how to configurate a multinode cluster setting up a Ingress Controller.

**Why is this needed**: In the example provide [here](https://kind.sigs.k8s.io/docs/user/ingress/) it's not clear how to do this. Only a cluster with a single node (control-plane) is provided.

**Comment by BenTheElder** [comment]
Just add more nodes to the config. That config is designed to work fine if you do.

However, I don't recommend multi node unless you have a concrete use case where you need it. Multi node mostly exists to test rolling updates when testing kubernetes itself.

**Comment by serrodcal** [comment]
Hi BenTheElder, thanks for your reply. I tried it but it didn't work. Maybe, I did something wrong. I just want to come up with an improvement in the documentation.

Anyway, I didn't know the purpose of that feature was for testing kubernetes itself. I used it because I deploy a lot of service and I though that it would be better to use multi-node cluster configuration instead.

**Comment by aojea** [comment]
Is not working just adding more nodes?

```yaml
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: worker
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
EOF
```

**Comment by serrodcal** [comment]
Hi aojea, It doen't work in my case. 

I'm going to describe step by step and with errors what I did.

1. I created the following cluster definition:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: worker
- role: worker
- role: worker
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

2. I set up the Project Contour: `kubectl apply -f https://projectcontour.io/quickstart/contour.yaml`

3. I applied the Project Contour's patch:
```
kubectl patch daemonsets -n projectcontour envoy -p '{"spec":{"template":{"spec":{"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'
``` 

4. Then, I installed the Ingress Controler:  `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml`

5. Now, I install all my stack (NGINX as Gateway, my applications, my monitoring stack, and so on).

6. Finally, I tried to set up the ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gateway
          servicePort: 8080
```

In the step 6 I got the following error: 
```
Error from server (InternalError): error when creating "ingress/ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.ingress-nginx.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.97.215.41:443: connect: connection refused
```

Taking a look into the ingress-nginx namespaces I saw the Ingress Controller pod as `Pending`. The description is as given below:
```
kd pod ingress-nginx-controller-cc8dd9868-jc6xs -n ingress-nginx 
Name:           ingress-nginx-controller-cc8dd9868-jc6xs
Namespace:      ingress-nginx
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=controller
                app.kubernetes.io/instance=ingress-nginx
                app.kubernetes.io/name=ingress-nginx
                pod-template-hash=cc8dd9868
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/ingress-nginx-controller-cc8dd9868
Containers:
  controller:
    Image:       quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0
    Ports:       80/TCP, 443/TCP, 8443/TCP
    Host Ports:  80/TCP, 443/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --election-id=ingress-controller-leader
      --ingress-class=nginx
      --configmap=ingress-nginx/ingress-nginx-controller
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
      --publish-status-address=localhost
    Requests:
      cpu:      100m
      memory:   90Mi
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       ingress-nginx-controller-cc8dd9868-jc6xs (v1:metadata.name)
      POD_NAMESPACE:  ingress-nginx (v1:metadata.namespace)
    Mounts:
      /usr/local/certificates/ from webhook-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-nginx-token-kgd75 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  webhook-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-admission
    Optional:    false
  ingress-nginx-token-kgd75:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-token-kgd75
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  ingress-ready=true
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  80s (x4 over 107s)  default-scheduler  0/5 nodes are available: 5 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  56s (x2 over 56s)   default-scheduler  0/5 nodes are available: 1 node(s) didn't match node selector, 4 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  45s (x2 over 45s)   default-scheduler  0/5 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 4 node(s) didn't match node selector.
```

If I create a cluster with only one node (control-plane) Ingress Controller working fine.
