### ISSUE TITLE
can't access my webservice 

### ISSUE THREAD

**Issue by may101** [kubernetes-sigs/kind#1557]
Hello everyone, 

Thanks for your kind efforts,
I need your advice on this issue. I have a problem when I try to access cluster IP address with local port and nodeport . I am not sure where the issue might be. I have repeated all steps and followed the k8 guideline document and configurations in detail.  

Kindly have a look at the following : 
 
1- I used a docker image (iweb-lens:v1)that I created and loaded on a kind cluster. 

```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                                 NAMES
2418be5e0887        kindest/node:v1.18.2   "/usr/local/bin/entr…"   13 minutes ago      Up 13 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 127.0.0.1:44533->6443/tcp   kind-control-plane
fef766f7702b        kindest/node:v1.18.2   "/usr/local/bin/entr…"   13 minutes ago      Up 13 minutes                                                                             kind-worker
bfe074825656        iweb-lens:v1           "python3 server.py"      28 hours ago        Up 28 hours         0.0.0.0:5000->5000/tcp                                                iweb-lens

```

2- I have created a kind cluster with (1 master node + 1 worker node )and the following configuration are : 

```
$ kind create cluster --config=kindconfig.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

```
**kind cluster configuration.yml**

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
```
**Deployment.yml :**

```
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: iweb-lens
  replicas : 1
  template:
    metadata:
      labels:
        app: iweb-lens
    spec:
      containers:
      - name: iweb-lens
        image: iweb-lens:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
```

**Service.yml :** 

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: iweb-lens
```
**Here is the result of all configurations :** 

```
$ kubectl get nodes,deployments,pods,svc -o wide
NAME                      STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
node/kind-control-plane   Ready    master   21m   v1.18.2   172.18.0.3    <none>        Ubuntu 19.10   4.15.0-76-generic   containerd://1.3.3-14-g449e9269
node/kind-worker          Ready    <none>   21m   v1.18.2   172.18.0.2    <none>        Ubuntu 19.10   4.15.0-76-generic   containerd://1.3.3-14-g449e9269

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES         SELECTOR
deployment.apps/my-deployment   1/1     1            1           5m20s   iweb-lens    iweb-lens:v1   app=iweb-lens

NAME                                 READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
pod/my-deployment-7f474c47c5-spmrq   1/1     Running   0          5m20s   10.244.1.2   kind-worker   <none>           <none>

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE    SELECTOR
service/kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP        21m    <none>
service/my-service   NodePort    10.108.162.220   <none>        80:32000/TCP   5m7s   app=iweb-lens

```

Here where I test the web service and try to access it via (ClusterIP:nodport ): 

```
$python3 iWebLens_client.py inputfolder http://10.108.162.220:32000/ 1
128
Calling object detection service, URL: http://10.108.162.220:32000/ Image:inputfolder/000000466315.jpg
Exception in webservice call: HTTPConnectionPool(host='10.108.162.220', port=32000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f039909ada0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```
**The same results shown when I test the web service and try to access it via (ClusterIP:port ):** 

```
$python3 iWebLens_client.py inputfolder http://10.108.162.220:80/ 1
128
Calling object detection service, URL: http://10.108.162.220:80/ Image:inputfolder/000000466315.jpg
Exception in webservice call: HTTPConnectionPool(host='10.108.162.220', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f674be22da0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```
Any advice on where it might be the problem, Is it on the configuration or did I missed any step?

**Comment by BenTheElder** [comment]
Drop the worker node and this should work.

When you have multiple nodes the control planes have a taint preventing most workloads from running on them.

Unless you are testing behavior that requires multiple nodes, stick to one, it's simpler and you don't get more resources with more of them 🙃

**Comment by may101** [comment]
Yes ,  I have to test the behavior with multiple nodes .
really tried everything to make it work and not sure how to solve it.
How can I do it with multi-nodes? : (

**Comment by may101** [comment]
Now , I'm trying your suggestion with one node, let you know .
 hopefully its works.

**Comment by may101** [comment]
Unfortunately it didn't work with single nods. 
```
$ nano  kindconfig.yaml
$ kind create cluster --config=kindconfig.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
```
```
$ kind load docker-image iweb-lens:v1
Image: "iweb-lens:v1" with ID "sha256:72588c5fa4ed53dfb785c4ecbbae35a726a6c7c03879e362b356abdaa3fab69c" not yet present on node "kind-control-plane", loading...

$ kubectl apply -f my-deployment.yml
deployment.apps/my-deployment created

$ kubectl apply -f my-service.yml
service/my-service created
```
```
$ kubectl get nodes,deployments,pods,svc -o wide
NAME                      STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
node/kind-control-plane   Ready    master   2m48s   v1.18.2   172.18.0.2    <none>        Ubuntu 19.10   4.15.0-76-generic   containerd://1.3.3-14-g449e9269

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
deployment.apps/my-deployment   1/1     1            1           18s   iweb-lens    iweb-lens:v1   app=iweb-lens

NAME                                 READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
pod/my-deployment-7f474c47c5-9qhtp   1/1     Running   0          18s   10.244.0.5   kind-control-plane   <none>           <none>

NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE     SELECTOR
service/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        2m46s   <none>
service/my-service   NodePort    10.108.116.90   <none>        80:32000/TCP   10s     app=iweb-lens
```

```
$ python3 iWebLens_client.py inputfolder http://10.108.116.90:80/ 1
128
Calling object detection service, URL: http://10.108.116.90:80/ Image:inputfolder/000000466315.jpg
Exception in webservice call: HTTPConnectionPool(host='10.108.116.90', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa19bc4dda0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Calling object detection service, URL: http://10.108.116.90:80/ Image:inputfolder/000000340604.jpg
^X^Z
[30]+  Stopped                 python3 iWebLens_client.py inputfolder http://10.108.116.90:80/ 1

```

```
python3 iWebLens_client.py inputfolder http://10.108.116.90:32000/ 1
128
Calling object detection service, URL: http://10.108.116.90:32000/ Image:inputfolder/000000466315.jpg
Exception in webservice call: HTTPConnectionPool(host='10.108.116.90', port=32000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd15d6ccda0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Calling object detection service, URL: http://10.108.116.90:32000/ Image:inputfolder/000000340604.jpg
^X^Z
[31]+  Stopped                 python3 iWebLens_client.py inputfolder http://10.108.116.90:32000/ 1

```

Is my configuration to cluster correct ?  or it might be problem on my dockerfile of docker image that I created (iweb-lens:v1)? >> trying to troubleshooting the issue. 

Sorry for the long questions I added and much appreciate your help

**Comment by BenTheElder** [comment]
nodeport on port 80 is ignored, kubernetes has a configurable nodeport range that is in the high port range normally.

if you assign a nodeport of 80 kubernetes will ignore the value and choose a high port from within the range.

**Comment by BenTheElder** [comment]
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

**Comment by BenTheElder** [comment]
> How can I do it with multi-nodes? : (

you need to make sure the workload is on the same node as the port forward, or have working nodeport

see https://kind.sigs.k8s.io/docs/user/ingress/

**Comment by may101** [comment]
> nodeport on port 80 is ignored, Kubernetes has a configurable node port range that is in the high port range normally.
> 
> if you assign a node port of 80 Kubernetes will ignore the value and choose a high port from within the range.

I have assigned 32000 to Nodeport, so Kubernetes will ignore this value? 
I have assigned port and host port to 80.
Is it wrong ?
 I shouldn't assign Nodeport a number ? because when I did that it automatically assigned a port to the cluster from 3000-36??? .

**Comment by may101** [comment]
Sorry for asking a lot of questions but  kubeadmConfigPatches & extraPortMappings all of them on control-plane ? If I have another node (worker) the control plane will handle the workload ? it is a little be confused me. 

**Example from Ingress guide :** 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

**What should I do ?** 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
```
