### ISSUE TITLE
Support node labels within config files

### ISSUE THREAD

**Issue by nadenf** [kubernetes-sigs/kind#1574]
**What would you like to be added**:

It would be nice if we had a simple:
```
- role: worker
  labels:
     type: zookeeper
     node-role.kubernetes.io/zookeeper=true: true
```

**Why is this needed**:

Using node-labels within the worker KubeAdm JoinConfiguration is:
a) Cumbersome for new users
b) Fails if you try to set a node-role which can't be specified in the JoinConfiguration
