### ISSUE TITLE
How limit worker resource ?

### ISSUE THREAD

**Issue by 0Delta** [kubernetes-sigs/kind#1578]
I want limit worker resource for simulate weak node. _e.g. 1vCPU/2GB_

 * kind version 0.8.1
 * Windows 10 2004 _build:19041.208_
 * WSL2 with Ubuntu 18.04
    * Linux MyPC 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 * Docker Desktop 2.2.0.4 (43472)
    * Engine 19.03.8
    * Kubernetes v1.15.5
    * Compose 1.25.4
    * Notary 0.6.1
    * Credential Helper 0.6.3

I tryed ...
 * using `constraints` parameter, such as  #877
but, i got syntax error.
```
Creating cluster "kind" ...
ERROR: failed to create cluster: unable to decode config: yaml: unmarshal errors:
  line 7: field constraints not found in type v1alpha3.Node

shell returned 1
```

 * using `kubeadmConfigPatches` parameter, such as #1524
but it's look no effects.
```
$ kubectl describe nodes
 : 
Addresses:
  InternalIP:  172.20.0.2
  Hostname:    kind-control-plane
Capacity:
 cpu:                12                              # I want restrict this parameter
 ephemeral-storage:  263174212Ki
 hugepages-2Mi:      0
 memory:             25912152Ki           # and this one as well.
 pods:               110
Allocatable:
 cpu:                12
 ephemeral-storage:  263174212Ki
 hugepages-2Mi:      0
 memory:             21717848Ki
 pods:               110
 : 
```

any ideas ?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1524
https://github.com/kubernetes-sigs/kind/issues/877

If you use an older kubernetes version you'll have to use older kubeadm config types.

**Comment by teachermanalex** [comment]
@0Delta, @BenTheElder :
I found that I can use kubeadmConfigPatches and it will affect the control-plane node but not the worker node....

**Comment by teachermanalex** [comment]
Ok, figured it out.  For worker nodes, you have to use *JoinConfiguration*:

```yaml
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=8Gi
```

**Comment by aojea** [comment]
I didn't test it but you should be able to patch the kubelet configuration directly
```
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
metadata:
  name: config
systemReserved:
  cpu: 2
  memory: "8Gi"
```

**Comment by BenTheElder** [comment]
kubelet configuration object is not respected per node in kubeadm currently, only from init :(

this is what you want https://github.com/kubernetes-sigs/kind/issues/1578#issuecomment-631140100

**Comment by 0Delta** [comment]
Sorry for late response.

finally, I success controle resource by means of @teachermanalex .
```
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=8Gi,cpu=8
```

And i found this issue. https://github.com/kubernetes-sigs/kind/pull/896
that mean "resource controle function is now developing. but it not matured, so it too early to merge."
I will use `kubeadmConfigPatches` carefully. becase it is compromised method.

However, the control node resource is successful. my question is solved.
thanks for all.
