### ISSUE TITLE
Local registry deployed within the KinD no longer works in 0.8

### ISSUE THREAD

**Issue by shuhaowu** [kubernetes-sigs/kind#1580]
**What happened**:

In KinD 0.7, I'm deploying a docker registry into KinD as the local registry. This is deployed via a StatefulSet and a NodePort service (see yaml attached at the bottom). For reasons outside the scope of this bug report, I cannot use a local registry running outside of KinD.

One thing that I also needed to do is to alias this registry to be a fake gcr.io (I suspect this is not needed to reproduce my problem). This can be done via:

```
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://localhost:31500"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31500 # Docker registry NodePort service
        hostPort: 31500
        listenAddress: "127.0.0.1"
```

As a result of this, and in KinD 0.7.0, I can successfully create a pod with an image tagged with gcr.io/..... Examining the logs when I perform create a pod with my image or perform `crictr pull gcr.io/,.....` inside the control plane node, I can see the following logs if containerd is started with level = debug:

```
containerd[7529]: time="2020-05-12T21:08:22.371173075Z" level=info msg="PullImage \"gcr.io/[REDACTED]\""
containerd[7529]: time="2020-05-12T21:08:22.412225351Z" level=debug msg=resolving host="localhost:31500"
containerd[7529]: time="2020-05-12T21:08:22.412285141Z" level=debug msg="do request" host="localhost:31500" request.header.accept="application/vnd.docker.distribution$manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.3.3-14-g449e9269 request.method=HEAD url="http://localhost:31500/v2/[REDACTED]"
containerd[7529]: time="2020-05-12T21:08:22.422394111Z" level=debug msg="fetch response received" host="localhost:31500" response.header.content-length=2402 response.eader.content-type=application/vnd.docker.distribution.manifest.v2+json response.header.date="Tue, 12 May 2020 21:08:22 GMT" response.header.docker-content-digest="sha256:...." response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:.....\"" response.header.x-content-type-options=nosniff response.status="200 OK" url="http://localhost:31500/v2/[REDACTED]"
```

After I upgrade to KinD 0.8.1, this seems to be broken. The create pod gets stuck at pulling image, and the logs of containerd shows:

```
containerd[3706]: time="2020-05-12T21:19:25.047032625Z" level=info msg="PullImage \"gcr.io/[REDACTED]\""                    
containerd[3706]: time="2020-05-12T21:19:25.084600441Z" level=debug msg=resolving host="localhost:31500"
containerd[3706]: time="2020-05-12T21:19:25.084655412Z" level=debug msg="do request" host="localhost:31500" request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v
1.3.3-14-g449e9269 request.method=HEAD url="http://localhost:31500/v2/[REDACTED]"
```

and just gets stuck there.

It appears there's a networking issue somehow here that I don't understand. As I mentioned, I suspect this issue is not related to my "trick" to alias gcr.io, but any such local registry deployment would fail.

**What you expected to happen**:

I expect my in-KinD registry to continue to work after upgrading to 0.8.

**How to reproduce it (as minimally and precisely as possible)**:

Create a kind cluster with 0.8.1 with the following patch:

```
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["http://localhost:31500"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31500 # Docker registry NodePort service
        hostPort: 31500
        listenAddress: "127.0.0.1"
```

Create a registy statefulset in that kind cluster:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-int
  namespace: registry
  labels:
    app: registry
spec:
  ports:
    - name: registry
      port: 5000
  clusterIP: None
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ext
  namespace: registry
  labels:
    app: registry
spec:
  ports:
    - name: registry
      nodePort: 31500
      port: 5000
      targetPort: 5000
  type: NodePort
  selector:
    app: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: registry
spec:
  serviceName: registry-int
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "registry:2"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
  volumeClaimTemplates:
    - metadata:
        name: registry-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
```

Tag a docker image and push it: `docker tag ubuntu:18.04 localhost:31500/foo/bar/ubuntu:bionic && docker push ubuntu:18.04 localhost:31500/foo/bar/ubuntu:bionic`.

Then try to create a deployment with said image: `kubectl run shell --rm -i --tty --image gcr.io/foo/bar/ubuntu:bionic -- /bin/bash` and watch it get stuck. Alternatively, docker exec into the control plane, and then run: `crictr pull  gcr.io/foo/bar/ubuntu:bionic`.

To observe the logs in containerd in detail: add 
```
[debug]
level = "debug"
```
into /etc/containerd/config.toml and then restart containerd via `systemctl restart containerd`. Observe the logs via `journalctl -fu containerd`.

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.8.1
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.14.2
", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-05-01T02:31:02Z", GoVersion:"go1.12.17
", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): 19.03.8
- OS (e.g. from `/etc/os-release`): ubuntu bionic
