### ISSUE TITLE
authorization-mode config doesn't pick up by kubeadm config

### ISSUE THREAD

**Issue by TAvardit** [kubernetes-sigs/kind#1593]
**What happened**:
In order to replicate a current cluster configuration for testing, I am trying to disable RBAC and enable ABAC on kind.
This is one set of tries that I have done:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/extraArgs
      value: {authorization-mode: ABAC}
# kubeadmConfigPatches:
# - |
#   kind: ClusterConfiguration
#   metadata:
#     name: config
#   apiServer:
#     extraArgs:
#       "authorization-mode": "ABAC,Node"
```
When I add ABAC `kind create cluster` is failing on `ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged chart-testing-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1`
When I just try to apply `authorization-mode: Node` the cluster creation is succesful but `kubeadm-config` configmap  is kept:
```yaml
Name:         kubeadm-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
ClusterConfiguration:
----
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: test
controlPlaneEndpoint: test-control-plane:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.15.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}

ClusterStatus:
----
apiEndpoints:
  test-control-plane:
    advertiseAddress: 172.19.0.3
    bindPort: 6443
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterStatus
```
**What you expected to happen**:
kube-apiserver configuration to use `authorization-mode: ABAC,Node`
**How to reproduce it (as minimally and precisely as possible)**:
Run the supplied kind configuration to get failure and switch to `authorization-mode: Node` to see kubeadm-config change not actually being picked up.
**Anything else we need to know?**:

**Environment:**
- kind version: (use `kind version`): kind v0.8.1
- Kubernetes version: (use `kubectl version`): kindest/node:v1.15.0 kubectl 1.18
- Docker version: (use `docker info`): 19.03
- OS (e.g. from `/etc/os-release`): 10.15.4
