### ISSUE TITLE
v0.8.1 - could not resolve host error (etcd)

### ISSUE THREAD

**Issue by rallen090** [kubernetes-sigs/kind#1603]
**What happened:**
On v0.8.1, in a kind cluster my etcd pod fails with the following error:
```
pkg/netutil: could not resolve host etcd-0.etcd:2380
etcdmain: failed to resolve http://etcd-0.etcd:2380 to match --initial-cluster=etcd-0=http://etcd-0.etcd:2380 (failed to resolve "http://etcd-0.etcd:2380" (i/o timeout))
```

Downgrading to v0.7.0 solves this problem.

**How to reproduce it (as minimally and precisely as possible):**
Ensure on kind v0.8.1.

Create kind cluster via a file `kind-cluster.yml`
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "failure-domain.beta.kubernetes.io/zone=us-east1-b"
```
`kind create cluster --image kindest/node:v1.15.7 --config kind-cluster.yml`

Then deploy etcd via `test.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
  - port: 2379
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: "etcd"
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        # 3.3.18
        image: gcr.io/etcd-development/etcd@sha256:e80582131febde2862a530660cb74c6b1cb2e1d2b443e6c563139cedc636f2e7
        imagePullPolicy: IfNotPresent
        command:
        - "etcd"
        - "--name"
        - "$(MY_POD_NAME)"
        - "--listen-peer-urls"
        - "http://$(MY_IP):2380"
        - "--listen-client-urls"
        - "http://$(MY_IP):2379,http://127.0.0.1:2379"
        - "--advertise-client-urls"
        - "http://$(MY_POD_NAME).etcd:2379"
        - "--initial-cluster-token"
        - "etcd-cluster-1"
        - "--initial-advertise-peer-urls"
        - "http://$(MY_POD_NAME).etcd:2380"
        - "--initial-cluster"
        - "etcd-0=http://etcd-0.etcd:2380"
        - "--initial-cluster-state"
        - "new"
        - "--data-dir"
        - "/var/lib/etcd"
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
        env:
        - name: MY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCDCTL_API
          value: "3"
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
        limits:
          storage: 1Gi
```
`kubectl apply -f test.yaml`

Then `kubectl logs etcd-0` to check pod logs. The pod should keep failing to start after running for a bit due to retry of failing to resolve the address.

**Environment:**

- Kind
```
$kind version
kind v0.8.1 go1.13.7 darwin/amd64
```
- Kubectl
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```
- OS:
```
Mojave 10.14.6
```
