### ISSUE TITLE
[connection]: Unable to access kind cluster inside a custom Github Action

### ISSUE THREAD

**Issue by uditgaurav** [kubernetes-sigs/kind#1619]
**What is happening?**
- I'm Using a KinD cluster in Github Action the flow of workflow yaml is:
  - Creating KinD cluster (Created successfully)
  - Getting Nodes via `kubectl get nodes` 
```
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   68s   v1.17.0
```
  - Now I'm trying to use the cluster inside my personal Github action bypassing kubeconfig. It is showing **connection error**:
```
exit status 1: The connection to the server 127.0.0.1:32768 was refused - did you specify the right host or port?
```
  - Did I need to do anything else?

**Workflow-yaml**

```yaml
name: Push
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Creating KinD cluster
      run: |
        GO111MODULE=on 
        curl -Lo ./kind https://github.com/kubernetes sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind version
        kind create cluster --loglevel debug
        sleep 60

    - name: Getting Nodes
      run: |
        kubectl get nodes

    - name: Set config
      run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
  
      #This is the custom Github Action inside which the kubectl command is not running.
    - name: Running Litmus pod delete chaos experiment
      uses: uditgaurav/kubernetes-chaos@v0.1.0
```
