### ISSUE TITLE
Older versions have taints on control plane node preventing CoreDNS from being scheduled

### ISSUE THREAD

**Issue by IvanBoyko** [kubernetes-sigs/kind#1659]
**What happened**:

I'm running older Kubernetes versions (tried. 1.14 and 1.16) following this guide:
https://kind.sigs.k8s.io/docs/user/quick-start/#setting-kubernetes-version

using config file:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.14.10@sha256:81ae5a3237c779efc4dda43cc81c696f88a194abcc4f8fa34f86cf674aa14977
- role: worker
  image: kindest/node:v1.14.10@sha256:81ae5a3237c779efc4dda43cc81c696f88a194abcc4f8fa34f86cf674aa14977
```

After I create a cluster with `kind create cluster --config kind-config.yaml`, after long time CoreDNS pods are still not scheduled.

```
$ kubectl -n kube-system describe pod/coredns-66bff467f8-4ntnf
...
Events:
  Type     Reason            Age                From                         Message
  ----     ------            ----               ----                         -------
  Warning  FailedScheduling  26m (x3 over 27m)  default-scheduler            0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```

Looking at node taints:
```
kubectl get nodes -o json | jq '.items[].spec.taints'

[
  {
    "effect": "NoSchedule",
    "key": "node-role.kubernetes.io/master"
  }
]
null
```

The problem does **not** appear with the latest kind version!
Which is:
> kind v0.8.1 go1.14.2 linux/amd64
> Server Version: v1.18.2

**What you expected to happen**:

CoreDNS to work

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

same problem for node image v1.14.10

**Environment:**

- kind version: (use `kind version`): kind v0.8.1 go1.14.2 darwin/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2020-01-14T00:59:35Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):  Server Version: 19.03.8
- Hardware: MacBook Air 13"
- OS: macOS Catalina version 10.15.4 (19E287)
- Docker Desktop: 2.3.0.2 stable
