### ISSUE TITLE
Not able to start cluster with host port mapping

### ISSUE THREAD

**Issue by bartier** [kubernetes-sigs/kind#1660]
Hello!

I am trying to execute the following yaml to start my cluster to allow me to test Ingress Controller stuffs later:

```
# kind-setup.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

Command: `kind create cluster --name test --config kind-setup.yaml`

I'm getting an error with ports already being used, but I don't find a process or somethign using 80 or 443:
```
ubuntu@ip-10-0-0-40:~$ kind create cluster --name test --config kind-setup.yaml 
Creating cluster "test" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼 
 ✗ Preparing nodes 📦 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname test-control-plane --name test-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=test --net kind --restart=on-failure:1 --publish=0.0.0.0:80:80/TCP --publish=0.0.0.0:443:443/TCP --publish=127.0.0.1:38645:6443/TCP kindest/node:v1.18.2@sha256:7b27a6d0f2517ff88ba444025beae41491b016bc6af573ba467b70c5e8e0d85f" failed with error: exit status 125
Command Output: 25f5a9d0d654c490fd53e7183639e622cb406db02c319549ebaf7896f77ff5a7
docker: Error response from daemon: driver failed programming external connectivity on endpoint test-control-plane (2f9b77c72cd469ecb7a29305a1e96676dfbf92c53bcd9ed9667c1b6bd3717b2e): Bind for 0.0.0.0:443 failed: port is already allocated.



# I've used this link to find processes using port 80/443 https://unix.stackexchange.com/questions/106561/finding-the-pid-of-the-process-using-a-specific-port 
ubuntu@ip-10-0-0-40:~$ sudo ss -lptn 'sport = :80'
State                     Recv-Q                      Send-Q                                            Local Address:Port                                           Peer Address:Port                     
ubuntu@ip-10-0-0-40:~$ sudo ss -lptn 'sport = :443'
State                     Recv-Q                      Send-Q                                            Local Address:Port                                           Peer Address:Port                     
ubuntu@ip-10-0-0-40:~$  
```

May someone help with that or give it a idea how should I make this works? :) Thanks!
