### ISSUE TITLE
Create an ansible module/driver to create/delete or start/stop a kind cluster

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/kind#1687]
## Proposition

The snowdrop team created an Ansible playbook to simplify the process and help users/developers when they play with with `kind` to create/delete a cluster with optionally a docker registry - https://github.com/snowdrop/k8s-infra/blob/master/ansible/roles/kind/README.adoc. 

**Remark** : An Ingress role can also be used to top of the cluster created

As discussed with Fabian von Feilitzsh on Kind [Slack](https://kubernetes.slack.com/archives/CEKK1KTN2/p1592498933163000), it could be interesting that we do different things such as : 
- Donate the Ansible role created to the kind community

That we extend the work to either: 
- Have a molecule driver that we could use to test playbooks/roles using Kind : https://molecule.readthedocs.io/en/latest/configuration.html#driver,
- Create an Ansible Module able to perform such a thing
```
  name: Create a K8s 1.17 cluster with a docker registry and ingress server
  kind:
    version: 0.17.2
    name: my-k8s-17
    image: 
    registry: docker
    routing: ingress
    nodes:
      - role: control-plane
      - role: worker
      - role: worker
      extraPortMappings:
        - containerPort: 80
          hostPort: 80
          listenAddress: "127.0.0.1"
          potocol: TCP
      extraMounts:
        - hostPath: /path/to/my/files/
          containerPath: /files
    networking:
      apiServerAddress: "127.0.0.1"
    state: present
```

WDYT ?
