### ISSUE TITLE
HA clusters don't reboot properly

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1689]
first reported in https://github.com/kubernetes-sigs/kind/issues/1685
tracking in an updated bug.

reproduce with:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
```
\+ restart docker.
