### ISSUE TITLE
StatefulSet DNS propagation not working

### ISSUE THREAD

**Issue by Kindrat** [kubernetes-sigs/kind#1691]
I've tried to deploy out k8s config using Kind (1.18.2 k8s) and faced problem with DNS not working for PODs in stateful set. The simplified configuration looks like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pzoo
spec:
  ports:
    - port: 2888
      name: peer
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    storage: persistent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
spec:
  selector:
    matchLabels:
      app: zookeeper
      storage: persistent
  serviceName: "pzoo"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zookeeper
        storage: persistent
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-config
          image: my.kafka-initutils:1.17.0_14
      containers:
        - name: zookeeper
          image: my.kafka:2.3.0_20
          imagePullPolicy: IfNotPresent
          command: ["docker-entrypoint", "./zookeeper-server-start.sh"]
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: leader-election
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 800Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '[ "imok" = "$(echo ruok | nc -w 1 -q 1 127.0.0.1 2181)" ]'
      restartPolicy: Always
``` 

This causes `java.net.UnknownHostException: pzoo-{0,1,2}.pzoo` inside of each zookeeper instance. On the other hand, same config works well on Azure k8s. Are there any default DNS config values different from vanilla k8s?

**Comment by Kindrat** [comment]
ok, actually only first pod from stateful set gets an entry in DNS. Headless service is also resolved.

```
/ # nslookup pzoo-2.pzoo
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find pzoo-2.pzoo: NXDOMAIN

/ # nslookup pzoo-1.pzoo
Server:         10.96.0.10
Address:        10.96.0.10#53

** server can't find pzoo-1.pzoo: NXDOMAIN

/ # nslookup pzoo-0.pzoo
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   pzoo-0.pzoo.default.svc.cluster.local
Address: 10.244.3.22

/ # nslookup pzoo
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   pzoo.default.svc.cluster.local
Address: 10.244.3.22
```

**Comment by BenTheElder** [comment]
Our DNS config comes from kubeadm defaults, about as vanilla as it gets.

**Comment by Kindrat** [comment]
Ok, thanks. Will look what was changed there recently.

**Comment by neolit123** [comment]
one related thing that may have changed in kubeadm is it's coredns version, so this might as well be a coredns issue.

we also had similar reports of random resolution failures caused by the the apps/containers using musl libc's DNS implementation.

**Comment by BenTheElder** [comment]
Maybe look at https://github.com/kubernetes/kubernetes/issues/92559

**Comment by Kindrat** [comment]
For some reason it works now only with `publishNotReadyAddresses: true` in headless service. Also needed to set larger timeouts for readinessProbe

**Comment by BenTheElder** [comment]
That sounds the same as the above linked upstream kubernetes bug

**Comment by jayunit100** [comment]
@BenTheElder  are you sure its the same issue? 

It seems like in here, the bug report is that the DNS record isnt available... because publishNotReadAddresses wasn't set.

In the other issue, the bug report is that the DNS record takes *too long* to become available (even WITH publishNotReadyAddresses)

**Comment by BenTheElder** [comment]
I'm not, though I'd expect if there is another bug here it's somewhere between coreDNS and kubeadm. We don't customise the in-cluster DNS at all.

**Comment by jicowan** [comment]
I am having a similar issue @Kindrat @BenTheElder only I can't resolve the name of service or any of the endpoints.  My StatefulSet and Service manifests appear below.

```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: streamer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restream
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restream
    spec:
      volumes:
        - name: restream-config
          configMap:
            name: restream-primary
            items:
              - key: primary
                path: ./primary.conf
              - key: secondary
                path: ./secondary.conf
            defaultMode: 420
        - name: conf
          emptyDir:
            medium: Memory
      initContainers:
        - name: init-streamer
          image: ubuntu
          command:
            - bash
            - '-c'
            - |
              myhost=$( hostname )
              echo $myhost
              [[ $myhost =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              if [[ $ordinal -eq 0 ]]; then 
                cp /mnt/primary.conf /etc/nginx/conf.d/
              else
                cp /mnt/secondary.conf /etc/nginx/conf.d/
              fi
          resources: {}
          volumeMounts:
            - name: restream-config
              mountPath: /mnt/
            - name: conf
              mountPath: /etc/nginx/conf.d/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
        - name: restreamer
          image: 'jicowan/nginx-rtmp:v0.1'
          ports:
            - containerPort: 1935
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: restream-config
              mountPath: /mnt/
            - name: conf
              mountPath: /etc/nginx/conf.d/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ''
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
---
kind: Service
apiVersion: v1
metadata:
  name: streamer
  namespace: default
spec:
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: healthz
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: restream
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
```
