### ISSUE TITLE
Image pull failure for nvcr repo on 1.15.11 k8s due to auth failure

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes-sigs/kind#1692]
**What happened**:
For kindest/node:v1.15.11
Error pulling image with error "no scope specified for token auth challenge" for nvcr.io/nvidia/tritonserver:20.03.1-py3
Works on kindest/node:v1.15.0

**What you expected to happen**:
Image is pulled successfully

**How to reproduce it (as minimally and precisely as possible)**:

```
kind create cluster  --image kindest/node:v1.15.11
```

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: triton-simple
spec:
  containers:
  - args:
    - /opt/tritonserver/bin/tritonserver
    - --grpc-port=2001
    - --http-port=9000
    - --model-repository=/mnt/models
    - --api-version=2
    image: nvcr.io/nvidia/tritonserver:20.03.1-py3
    imagePullPolicy: IfNotPresent
    name: simple
    ports:
    - containerPort: 2001
      name: grpc
      protocol: TCP
    - containerPort: 9000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /v2/health/ready
        port: http
        scheme: HTTP
    volumeMounts:
    - mountPath: /mnt/models
      name: simple-provision-location
      readOnly: true
  initContainers:
  - args:
    - gs://seldon-models/trtis/simple-model
    - /mnt/models
    image: gcr.io/kfserving/storage-initializer:0.2.2
    imagePullPolicy: IfNotPresent
    name: simple-model-initializer
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/models
      name: simple-provision-location
  volumes:
  - emptyDir: {}
    name: simple-provision-location
EOF
```

**Anything else we need to know?**:

Probably due to : https://github.com/containerd/containerd/issues/3556

**Environment:**

- kind version: (use `kind version`):
kind v0.7.0 go1.13.6 linux/amd64
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):

```
Client:
 Debug Mode: false

Server:
 Containers: 32
  Running: 1
  Paused: 0
  Stopped: 31
 Images: 844
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-106-generic
 Operating System: Linux Mint 18.3
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.15GiB
 Name: clive-T470p
 ID: BNDP:HK6B:33W6:N4L5:B5KG:NTXL:BBTB:73VF:ZDGE:RSVT:HOYZ:EY4I
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- OS (e.g. from `/etc/os-release`):

```
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
```
