### ISSUE TITLE
[question] How to reference a local volume in Kind

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/kind#1701]
I'd like to set Persistant Volume (pv and pvc) , shared by pods in Kind cluster. But I need keep the data persistant in my laptop (host server) as well, so the volume's path should be something in my laptop, which I can directly access it.

I hope to easily add or update in that volume or copy files out of it from my host laptop.

How can I let the pods know it in KIND cluster?

**Comment by ozbillwang** [comment]
seems this works for my idea. will test it

https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

**Comment by ozbillwang** [comment]
Has gone through the url, but seems the `extraMounts` is only for one node. 

Could I get all nodes to read that folder?

```
$ kind
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /path/to/my/files/
    containerPath: /files
- role: worker
- role: worker
- role: worker
```

**Comment by BenTheElder** [comment]
You can add it to each nodes.

Odds are high that you don't need more than one node.

**Comment by ozbillwang** [comment]
Thanks, @BenTheElder 

Can I do this? Share the same hostPath folder `data` to each node. So any nodes can read / write to same containerPath.

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: ./data
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./data
    containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./data
    containerPath: /data
```
