### ISSUE TITLE
RBAC role for running kubectl exec in a pod in kind

### ISSUE THREAD

**Issue by jeremysf** [kubernetes-sigs/kind#1715]
I'm trying to run `kubectl exec` from inside a pod in a `kind` cluster. The pod in question has an ubuntu container with the `kubectl` executable, and a `kube-proxy` sidecar. 

Since `kubectl` in the ubuntu container is talking to the `kube-proxy` sidecar container, there is no special certificate or auth in my `~/.kube/config` inside the ubuntu container.

I am able to bind the built in `ClusterRole` of `cluster-admin` to the service account associated with the pod and use most `kubectl` commands from inside the ubuntu container in the pod such as deleting other pods in the `kind` cluster, deploying with helm, inspecting pod logs, `kubectl top` to talk to metrics-server, etc all work.

Unfortunately, I am unable to `kubectl exec` from inside the pod on any other pods in `kind`. I get:

```
error: unable to upgrade connection: Forbidden
```

From outside of the pod (i.e. on my Mac), I can use `kubectl exec` on any pods running in my `kind` cluster with no issues.

What I am missing about the necessary RBAC permissions for `kubectl exec`? I thought `cluster-admin` was the most permissive possible RBAC.

I have also tried to create a custom `ClusterRole`, but with the same results:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workspace
rules:
- apiGroups:
  - ""
  - extensions
  - policy
  - apps
  - batch
  - rbac.authorization.k8s.io
  - roles.rbac.authorization.k8s.io
  - apiextensions.k8s.io
  - admissionregistration.k8s.io
  - apiservices.apiregistration.k8s.io
  - apiregistration.k8s.io
  - metrics.k8s.io
  - authorization.k8s.io  
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "deletecollection", "use", "bind", "escalate", "impersonate"]
```

Thank you!

**Comment by BenTheElder** [comment]
what exactly is a "kube-proxy sidecar" ??

what versions are kubectl and the cluster? kind?

kubernetes itself has no default roles, but kubeadm does have the cluster-admin role which should be maximally permissive.

**Comment by jeremysf** [comment]
The example below binds a custom `ClusterRole` but I've also tried `cluster-admin`.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: workspace
  template:
    metadata:
      labels:
        name: workspace
    spec:
      serviceAccountName: workspace-proxy
      containers:
        - name: kubectl-proxy
          image: bitnami/kubectl
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          args:
            - proxy
            - "-p"
            - "8080"        
        - name: workspace
          image: ...
          imagePullPolicy: Always
          securityContext:
            privileged: true          
          volumeMounts:
            - name: docker-sock-volume
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 16000Mi
              cpu: 8000m
      volumes:
        - name: docker-sock-volume
          hostPath:
            # location on host
            path: /var/run/docker.sock
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workspace-proxy
rules:
- apiGroups:
  - ""
  - extensions
  - policy
  - apps
  - batch
  - rbac.authorization.k8s.io
  - roles.rbac.authorization.k8s.io
  - apiextensions.k8s.io
  - admissionregistration.k8s.io
  - apiservices.apiregistration.k8s.io
  - apiregistration.k8s.io
  - metrics.k8s.io
  - authorization.k8s.io  
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete", "deletecollection", "use", "bind", "escalate", "impersonate"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: workspace-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workspace-proxy
subjects:
  - kind: ServiceAccount
    name: workspace-proxy
    namespace: default
```

The `.kube/config` for this looks like:

```
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
```
