### ISSUE TITLE
Allow configuration of docker network

### ISSUE THREAD

**Issue by meyskens** [kubernetes-sigs/kind#1718]
**What would you like to be added**:
The ability to specify specific Docker network configuration for the kind network that is getting created analog to specifying the Pod and Service CIDRs.
Something like:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  docker:
    subnet: "192.168.0.0/16"
    gateway: "192.168.0.0/16"
```
which will result into `docker network create kind --subnet [...]`

**Why is this needed**:
We are running kind inside prow jobs in GKE. When upgrading to 0.8.1 we noticed the pod networking going down.
By default docker chooses the next internal subnet to be `172.18.` as it's default is `172.17.`
But this subnet is used inside our cluster to route traffic over, Docker is not and can not be aware of this.

This is why it would be nice to be able to specify the specific subnet the kind containers run on.
For now we worked around this by manually creating the network as kind will not try to recreate it.

PS: Happy to work on a PR for this! Just checking first :)
