### ISSUE TITLE
RFE: Kubernetes components logging

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#1749]
**What would you like to be added**:

Cluster components log level configuration

**Why is this needed**:

for CI, development, ..., I'd like to increase the log verbosity of one, various or all the kubernetes component in a cluster.

Right now, it can be done for all components but kube-proxy, patching kubeadm (kudos to the orig author of the snippet @mauilion )

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      v: "3"
  controllerManager:
    extraArgs:
      v: "3"
  scheduler:
    extraArgs:
      v: "3"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      v: "3"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: JoinConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      v: "3"
nodes:
- role: control-plane
- role: worker
```

for kube-proxy, it's possible to edit the daemonset and add the `-v` flag to the `command` field

## Proposal

Add a new field to the Cluster Config to set the components verbosity, something similar to what has been done with FeatureGates

https://github.com/kubernetes-sigs/kind/pull/1263

it will set for ALL the components for simplification, granularity can be achieved using patches

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
logLevel: 7
```

**Comment by neolit123** [comment]
seems convenient.

> logLevel: 7

WRT naming, it might be better to separate the concepts of "kind log level" (e.g. logLevel) , "kubeadm log level" (e.g. kubeadmLogLevel), "log level of components that kubeadm deploys" (e.g. componentLogLevel).

it's also important to document (godoc above API fields) the behavior of the fields.

for instance, if the user has this:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
componentLogLevel: 7
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      v: "3"
```

what would be the expected log level for the kube-apiserver - 3 or 7 (would the user patch override the global flag).

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/1625

**Comment by BenTheElder** [comment]
Patch would override the field.
I don't think the field is very good though. Does any other tool do this? Components have very different logging.

**Comment by aojea** [comment]
> Components have very different logging.

Yeah, but this is simpler, and for CI you use to have the same level in all the components.
For development, despite you are interested in only one component you really don't care about the others log level, right?

**Comment by BenTheElder** [comment]
Log levels have side effects.

**Comment by BenTheElder** [comment]
CI has no problem applying some patches, the difference between blanket setting featuregates and log levels is that featuregates are supposed to be uniform. Additionally, end users may reasonably depend on featuregates frequently

**Comment by aojea** [comment]
> Log levels have side effects.

so, we should add per component logging to the API or implement it in the hack/ci/e2e-k8s.sh script?

https://github.com/kubernetes/kubernetes/blob/17a2e5e990d88cc3f5700d3bfab302b5a2523aba/cluster/gce/config-test.sh#L211-L218

**Comment by BenTheElder** [comment]
let's just put it in the script for now.
We only have kubeadm beta to worry about now, and they're identical for
this purpose.

**Comment by aojea** [comment]
> let's just put it in the script for now. We only have kubeadm beta to worry about now, and they're identical for this purpose.

sounds good to me :+1: 
/close

**Comment by BenTheElder** [comment]
btw somewhat shorter:
```yaml
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      v: "3"
  controllerManager:
    extraArgs:
      v: "3"
  scheduler:
    extraArgs:
      v: "3"
  ---
  kind: InitConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      v: "3"
  ---
  kind: JoinConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      v: "3"
```

**Comment by BenTheElder** [comment]
or less idiomatically but terser:
```yaml
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer: { extraArgs: { v: "3" } }
  controllerManager: { extraArgs: { v: "3" } }
  scheduler: { extraArgs: { v: "3" } }
  ---
  kind: InitConfiguration
  nodeRegistration: { kubeletExtraArgs: { v: "3" } }
  ---
  kind: JoinConfiguration
  nodeRegistration: { kubeletExtraArgs: { v: "3" } }
```
