### ISSUE TITLE
Docker "registry mirror" (pull through cache) cannot be setup

### ISSUE THREAD

**Issue by fzyzcjy** [kubernetes-sigs/kind#1775]
**What happened**:
I want to set up [docker registry as a pull cache](https://docs.docker.com/registry/recipes/mirror/) but failed. I have tried [the doc](https://kind.sigs.k8s.io/docs/user/local-registry/) but still fail. The doc talks about "local registry", but my goal is to make my local registry be *a mirror* of the original docker hub. In other words, e.g, when I run `busybox:latest` image, it will ask my local registry for the image data, instead of fetching hub.docker.com.

My attempts and things that may be helpful:

1. It works very well with Minikube. I just use `minikube start --cpus=6 --memory=16000MB --driver=docker --disk-size='100g' --registry-mirror="http://host.docker.internal:5000" --insecure-registry="host.docker.internal:5000"` to start minikube and then everything goes pretty well.
2. When run `curl http://host.docker.internal:5000/v2/` inside the `kind` (go inside by `docker exec -it $(docker ps -aqf "name=kind-control-plane") /bin/bash`), it outputs `{}` and my registry prints out a log `172.17.0.1 - - [08/Aug/2020:10:58:31 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "curl/7.65.3"`. Thus, it seems that the url `http://host.docker.internal:5000` can be accessed inside Kind.

Thanks!

**What you expected to happen**:
N/A

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a local "pull through cache" registry. I use the following `docker-compose.yaml` with `docker-compose up`

```
registry:
  image: registry:2
  ports:
    - 0.0.0.0:5000:5000
  environment:
    REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
  volumes:
    - /Users/tom/opt/my-docker-registry:/var/lib/registry # change to whatever you want or remove it
```

2. start kind by `kind create cluster --config=./k8s-kind-config.yaml` with config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users
        containerPath: /Users
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5000"]
    endpoint = ["http://host.docker.internal:5000"]
```

3. try to start a simplest pod, e.g.

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - #
#      image: busybox # can try this, also fail
      image: host.docker.internal:5000/library/busybox:latest
      command:
        - sleep
        - "3600000"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Never
```

However, it does not work :( Our docker registry does *not* receive any http request.

**Anything else we need to know?**:
N/A

**Environment:**

- kind version: (use `kind version`): kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`): 1.18.6 client version
- Docker version: (use `docker info`): 19.03.8
- OS (e.g. from `/etc/os-release`): macos
