### ISSUE TITLE
I want to configure --service-node-port-range

### ISSUE THREAD

**Issue by martonsz** [kubernetes-sigs/kind#1789]
Is it possible to configure the service port range?

In other k8s dev solutions (like k3os and minikube) it is possible to pass the following parameter to the  control-plane pod: `--service-node-port-range`

This is the problem I want to solve:

```
The Service "upgrader" is invalid: spec.ports[0].nodePort: Invalid value: 5588: provided port is not in the valid range. The range of valid ports is 30000-32767
```

**Comment by BenTheElder** [comment]
So you can set this using kubeadm config patches https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches

You will want something like:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      "service-node-port-range": "<value>"
```
Make sure to quote the `<value>` you want for the port range.

I do NOT recommend depending on a non-standard service node port range though, as a general rule.
