### ISSUE TITLE
Question：Why was only one node created？ 

### ISSUE THREAD

**Issue by Thor-wl** [kubernetes-sigs/kind#1862]
Hi, guys!
I wanted to create a cluster with one controller node and four worker node. The following is my configuration:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
  - role: worker
```
But after my creation, i only get the control-plane node.
```
[root@ECS] kind get nodes --name=volcano
volcano-control-plane
```
I've only a single ECS node with 4C16G and I want to create the cluster all at the ECS.
My question is below:
1. Why do i only get the controller node?
2. If i got a wrong way, how can i achieve the goal above?
Thanks!
