### ISSUE TITLE
Gitlab CI: docker socket binding example

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/kind#1880]
Here is example for Gitlab using socket binding ( https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding ), its little bit different than privileged mod ( https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-workflow-with-docker-executor ), but what is problematic is:

- APIServer certSAN must be created dynamically with Real IP of docker, or `--insecure-skip-tls-verify` flag must be set ( https://github.com/kind-ci/examples/blob/master/gitlab/kind-config.yaml#L14  )
- Real IP of docker must be known ( In most cases, it will be alway 172.17.0.1 from 172.17.0.0/16 subnet by default )

```
image: docker:stable
variables:
  KUBECTL: v1.19.2
  KIND: v0.9.0
test:
  script:
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --name $CI_PIPELINE_ID --config=./gitlab/kind-config.yaml
    - REAL_IP=$(ip route|awk '/default/ { print $3 }')
    - sed -i -E -e "s/localhost|0\.0\.0\.0/$REAL_IP/g" "$HOME/.kube/config"
    - kubectl get nodes --insecure-skip-tls-verify=true -o wide
    - kubectl get pods --insecure-skip-tls-verify=true --all-namespaces -o wide
    - kubectl get services --insecure-skip-tls-verify=true --all-namespaces -o wide
  after_script:
    - kind delete cluster --name $CI_PIPELINE_ID
```

Is possible to improve this example/workflow somehow ?

Thanks

**Comment by BenTheElder** [comment]
we track community maintained CI workflows here, including gitlab:

https://kind.sigs.k8s.io/docs/user/resources/#using-kind-in-ci
https://github.com/kind-ci/examples (with some of them running live on the repo)

----

I would not do insecure skip tls verify, you can configure the listen address such that kind will natively bind to this and therefore sign the cert for it and set the kubeconfig pointing at it https://kind.sigs.k8s.io/docs/user/configuration/#api-server, or if you mean the node's container IP, there's various ways to determine that.

If you're access the cluster from another container, you should use the kuebconfig from `kind get kubeconfig --internal`, and you need to be attached to the `kind` docker network.

**Comment by lukasmrtvy** [comment]
@BenTheElder Thanks. 

`kind get kubeconfig --internal` unfortunatelly will not work, server url is always same, no matter of `kind create cluster --name` argument.

Both jobs are working for me:
```
stages:
- kind

image: docker:stable
variables:
  KUBECTL: v1.19.2
  KIND: v0.9.0
kind-external:
  stage: kind
  before_script:
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - REAL_IP=$(ip route|awk '/default/ { print $3 }')
  script:
    - | 
      cat <<EOF | kind create cluster --name $CI_PIPELINE_ID --config=-
      apiVersion: kind.x-k8s.io/v1alpha4
      kind: Cluster
      networking:
        apiServerAddress: "0.0.0.0"
      kubeadmConfigPatchesJSON6902:
        - group: kubeadm.k8s.io
          version: v1beta2
          kind: ClusterConfiguration
          patch: |
            - op: add
              path: /apiServer/certSANs/-
              value: $REAL_IP
      nodes:
        - role: control-plane
        - role: worker
      EOF
    - sed -i -E -e "s/localhost|0\.0\.0\.0/$REAL_IP/g" "$HOME/.kube/config"
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
  after_script:
    - kind delete cluster --name $CI_PIPELINE_ID


kind-internal:
  stage: kind
  before_script:
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
  script:
    - kind create cluster --name $CI_PIPELINE_ID 
    - docker network connect kind $CONTAINER_ID
    - kubectl config set clusters.kind-$CI_PIPELINE_ID.server https://$CI_PIPELINE_ID-control-plane:6443
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
  after_script:
    - kind delete cluster --name $CI_PIPELINE_ID
```
