### ISSUE TITLE
How can we use KinD cluster in different jobs, present at diff stages of a GitLab CI?

### ISSUE THREAD

**Issue by sharmababu** [kubernetes-sigs/kind#1882]
## Details

- I'm trying to use kind cluster as part of my CI/CD develpment but i'm facing some issue in reusing the cluster in multiple jobs.

- I reffered `kind-ci/example` and it was helpful thanks for that (as I was able to setup the cluster in one job). I'm also able to pass the .kube/config to the other jobs using artifact but how to reuse the instance to kind in all jobs?

Here is my GitLab CI yaml

```yaml
stages:
  - Cluster Setup
  - App Deploy 

image: docker:stable
variables:
  KUBECTL: v1.17.0
  KIND: v0.8.1
services:
  - docker:dind

SetupKinD:
  stage: Cluster Setup
  script:
    - path=$(pwd)
    - apk add -U wget
    - wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND}/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - kind create cluster --config=./gitlab/kind-config.yaml
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide
    - sleep 30
    - kubectl cluster-info --context kind-kind
    - kubectl get nodes
    - mkdir $path/.kube
    - cat ~/.kube/config > $path/.kube/config
  artifacts:
    when: always
    paths:
      - .kube/

DeployApp:
  image: sharmababu/kind:ci
  stage: App Deploy
  script: 
   - kind --version
    - kubectl get nodes
  dependencies: 
    - SetupKinD  
```

Error in second job:

```bash
$ kind --version
/bin/bash: line 105: kind: command not found
```
