### ISSUE TITLE
--wait times out with Calico

### ISSUE THREAD

**Issue by zaharidichev** [kubernetes-sigs/kind#1889]
**What happened**:
I tried to create a kind cluster with calico configuration such as: 

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
```

**What you expected to happen**:
I expect that I can use the `--wait` command flag to wait on the cluster's nodes being ready. Unfortunatelly this does not work because the wait action seems to be awaiting on the node's state which stays as not ready forever. The `--wait `  flag times out and emits a warning
**Environment:**

- kind version: (use `kind version`): 0.8.1
- k8s version" v1.18.2
