### ISSUE TITLE
document using tls certs to authenticate image pulls

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#1956]
**What would you like to be documented**:

using a config patch like:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /etc/docker/certs.d/registry.dev.databricks.com
        hostPath: /etc/docker/certs.d/registry.dev.databricks.com
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.dev.databricks.com".tls]
      cert_file = "/etc/docker/certs.d/registry.dev.databricks.com/ba_client.cert"
      key_file  = "/etc/docker/certs.d/registry.dev.databricks.com/ba_client.key"
```

To enable authenticated image pull using certificates

**Why is this needed**:

Users were used to doing this with dockershim.

We should also look into enabling this better upstream, having a host dir would be convenient https://github.com/containerd/containerd/pull/4138/files#r402472668
