### ISSUE TITLE
After docker-windows restart extraPortMappings not binding

### ISSUE THREAD

**Issue by Haim-Bi** [kubernetes-sigs/kind#1970]
**What happened**:
After install kind using kind create cluster  --config config.yaml
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.0.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
  - hostPath: C:\local_deployment_files
    containerPath: /files
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "127.0.0.31"
    protocol: TCP
  - containerPort: 30011
    hostPort: 5001
    listenAddress: "127.0.0.31"
    protocol: TCP
  - containerPort: 30012
    hostPort: 5006
    listenAddress: "127.0.0.31"
    protocol: TCP
```

everything is working as expected.
once i restarted the KinD container or restarted docker-desktop
the ports are not bind anymore.

**What you expected to happen**:
The port will be bind as configured.

**How to reproduce it (as minimally and precisely as possible)**:
Create new KinD cluster with extraPortMappings.
restart docker-desktop

**Environment:**
docker-desktop community 2.5.0.1
- kind version: (use `kind version`): kind v0.9.0 go1.15.2 windows/amd64
- Kubernetes version: (use `kubectl version`):  v1.19.3
- Docker version: (use `docker info`): 19.03.13
- OS (e.g. from `/etc/os-release`): Windows 10 19041
