### ISSUE TITLE
Cannot create cluster

### ISSUE THREAD

**Issue by Sayeed42** [kubernetes-sigs/kind#1983]
**What happened**:
The command `kind create cluster` failed, with the following output:
![image](https://user-images.githubusercontent.com/57699207/102536384-89ac7a00-4077-11eb-8b7b-d72ee9aaa0ee.png)

**What you expected to happen**:
Successful creation of a cluster.

**How to reproduce it (as minimally and precisely as possible)**:
`kind create cluster`

**Environment:**

- kind version: (use `kind version`): 0.9.0
- Kubernetes version: (use `kubectl version`): 1.19.3
- Docker version: (use `docker info`): 19.03.13
- OS (e.g. from `/etc/os-release`): CentOS Linux 8

**Comment by BenTheElder** [comment]
That error means docker can't create containers, your docker install is broken.

**Comment by BenTheElder** [comment]
See:
https://stackoverflow.com/questions/31667160/running-docker-container-iptables-no-chain-target-match-by-that-name

https://github.com/moby/moby/issues/16816

https://bobcares.com/blog/iptables-no-chain-target-match-by-that-name-docker/

**Comment by Sayeed42** [comment]
Okay, even if the command `kind create cluster` works, when I try to execute `kind create cluster --config kind-cluster.yaml` it fails to join worker nodes. So, what should I do now?
![image](https://user-images.githubusercontent.com/57699207/102646604-57138780-4132-11eb-86af-d846d16b43e6.png)
Contents of `kind-cluster.yaml` :
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - hostPort: 31001
      containerPort: 31001
- role: worker
```
