### ISSUE TITLE
Accessing app running in Kind cluster in WSL2

### ISSUE THREAD

**Issue by cheslijones** [kubernetes-sigs/kind#1991]
I've been playing with `kind` the past few days to manage clusters in Docker Desktop given `minikube` doesn't work inside of WSL2 for the time being.

The problem I'm running into is I can't access the running web app through the ingress controller. I can access it using `port-fowrward` when I do `skaffold dev --port-forward`, but that really isn't helpful.

The documentation for `kind` has a section for WSL2 setup [here](https://kind.sigs.k8s.io/docs/user/using-wsl2/). I've done all of the following:
```
# cluster-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP

$ kind create cluster --config=cluster-config.yml

$ kubectl create deployment nginx --image=nginx --port=80

$ kubectl create service nodeport nginx --tcp=80:80 --node-port=30000

```
From what I gather, I should be able to go to `localhost:30000` (or `curl localhost:30000`) to access the running app. It looks like should port `30000` should be getting sent to the Ingress controller `80` in the cluster.

All I get is the "Welcome to nginx!" screen.

[![enter image description here][1]][1]

When I use `minikube` on Linux or macOS, enabling the `ingress-nginx` is just a matter of `minikube addons enable ingress`. When I use the `docker-desktop` cluster that ships with Docker Desktop, I typically just run this to get the Ingress working:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/cloud/deploy.yaml
```

I've tried this command and also the command in the [`kind` documentation](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx) for `ingress-nginx`:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
```

The Ingress controller just sits at this and never acquires an address:

```
$ kubectl get ing
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME                  CLASS    HOSTS   ADDRESS   PORTS   AGE
ingress-service-dev   <none>   *                 80      11m
```

This is what I have for my `ingress.yaml`:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/admin)$ $1/ permanent;
  name: ingress-service-dev
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /admin/
            backend:
              serviceName: admin-cluster-ip-service-dev
              servicePort: 4000
          - path: /api/
            backend:
              serviceName: api-cluster-ip-service-dev
              servicePort: 5000
          - path: /
            backend:
              serviceName: client-cluster-ip-service-dev
              servicePort: 3000
```

What do I need to do here to get this working?

  [1]: https://i.stack.imgur.com/sRwyn.png
