### ISSUE TITLE
problem in docs

### ISSUE THREAD

**Issue by Ruminateer** [kubernetes-sigs/kind#2000]
**What happened**:
I was following <https://kind.sigs.k8s.io/docs/user/configuration#nodes>.
I wanted to specify the image, and I added the image digest as the doc instructed. Then I got the following error
```
$ kind create cluster --config=myconfig.yaml
Creating cluster "kind" ...
 ✗ Ensuring node image (kindest/node:v1.20.0@b40ecf8bcb188f6a0d0f5d406089c48588b75edc112c6f635d26be5de1c89040) 🖼 
ERROR: failed to create cluster: failed to pull image "kindest/node:v1.20.0@b40ecf8bcb188f6a0d0f5d406089c48588b75edc112c6f635d26be5de1c89040": command "docker pull kindest/node:v1.20.0@b40ecf8bcb188f6a0d0f5d406089c48588b75edc112c6f635d26be5de1c89040" failed with error: exit status 1
Command Output: invalid reference format
```
I removed the image digest and the cluster creation succeeded.

Here is `myconfig.yaml`.
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.20.0
  extraMounts:
  - hostPath: /home/zzy
    containerPath: /root
- role: worker
  image: kindest/node:v1.20.0
```

Not sure if it is the problem with my docker, my docker seems up-to-date.

**Environment:**
- OS (e.g. from `/etc/os-release`): WSL2, Ubuntu 20.04.1 LTS
- kind version: (use `kind version`): v0.9.0
- Docker version: (use `docker info`):  Docker Desktop for Windows
```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:32 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
