### ISSUE TITLE
WSL2: "Connection refused" setting up ingress

### ISSUE THREAD

**Issue by cheslijones** [kubernetes-sigs/kind#2004]
Windows 10 + Docker Desktop + WSL2 Integration. `kind` is installed in WSL2.

Per the [documentation for Ingress controllers](https://kind.sigs.k8s.io/docs/user/ingress/):

```
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
EOF
```
This creates the cluster `kind-kind` successfully with the following output:
```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
```
I got to spin up [my test web app](https://github.com/cheslijones/tls-dev-k8s) (basically`create-react-app`) with `skaffold dev` and I get the following error:

```
$ skaffold dev                
Listing files to watch...
 - client
Generating tags...
 - client -> client:465b136
Checking cache...
 - client: Found Locally
Tags used in deployment:
 - client -> client:fd1ebde659cebb1fd12555e47c48ee8857f7606b345c2ae0cda215b1480e02cd
Deploy Failed. Could not connect to cluster kind-kind due to "https://127.0.0.1:37225/version?timeout=32s": dial tcp 127.0.0.1:37225: connect: connection refused. Check your connection for the cluster.
```
This cluster spins up fine if I create the cluster with just `kind create cluster`, but then `ingress-nginx` doesn't work, so it doesn't do me any good.

I've done the following as well with the following outputs:
```
$ kubectl cluster-info --context kind-kind
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 127.0.0.1:37225 was refused - did you specify the right host or port?

$ kubectl cluster-info dump               
The connection to the server 127.0.0.1:37225 was refused - did you specify the right host or port?
```
What do I need to do here to get this working?
