### ISSUE TITLE
Getting empty reply from server when trying to request from one pod to another within the cluster

### ISSUE THREAD

**Issue by manuasir** [kubernetes-sigs/kind#2007]
**What happened**:
      I'm currently in an EKS environment, using a private node group (three private subnets within the VPC where I connect to through a VPN). After setting up the IC, everything seems to work fine. When connecting to the VPC, the requests to my services behind the LB work. There is no loss, I use `curl` for testing purposes and all the requests are able to resolve successfully. The problem comes when curling from a pod to another within the cluster. Eventually, I get this `Empty reply from server` error.

![image](https://user-images.githubusercontent.com/10210567/104662939-280a1a80-56cc-11eb-8ed1-a629ce4e83f6.png)

Let's say that ~10% of the requests fail. 

My architecture is very simple, like the following:
- 3 private subnets (eu-west-1a, eu-west-1b, eu-west-1c).
- 4 nodes.
- NGINX Ingress controller (Network load balancer) as a DaemonSet, so each node has a pod of the IC running on it. This was also reproduced used a Deployment.

**How to reproduce it (as minimally and precisely as possible)**:

Just attach a shell to any pod within your cluster and `curl` another pod.

**Anything else we need to know?**:

I'm attaching several configuration files we're currently using

- Ingress

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-stg
  namespace: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
spec:
  rules:
    - host: stgapi.myhost.com
      http:
        paths:
          - path: "/"
            backend:
              serviceName: api-stg-service
              servicePort: 80
```

- Service

```
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: api-stg-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: api-stg-pod

```

**Environment:**

EKS

Any help would be much appreciated, don't hesitate to ask for any details.

Cheers
