### ISSUE TITLE
Self generated CA certificate not be respected,  got x509: certificate signed by unknown authority when pull image

### ISSUE THREAD

**Issue by hatzhang** [kubernetes-sigs/kind#2055]
My harbor is using a self generated CA to do self certificate signing. And i can trust it on my local machine, and the docker pull command will work. But if will fail when inside Kinds' k8s cluster. I copied the CA into Kinds' container, and did a update-ca-certificates, and verified the ssl handshake worked using openssl s_client, but crictl won't work. So what is the correct way to trust a self generated ca for Kinds' cluster?
Inside my Kinds' container
```
/# cp ca.crt /usr/local/share/ca-certificates/ca.crt
/# update-ca-certificates
/# openssl s_client 192.168.10.120:443
...
Verification: OK
...
/# crictl pull 192.168.10.120:8443/myrepo/my-image:v7
...
: x509: certificate signed by unknown authority
```

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues?q=is%3Aissue+x509+certificate+is%3Aclosed++image+pull

https://github.com/kubernetes-sigs/kind/issues/1010#issuecomment-587973432

The missing bit is restarting containerd, IIRC go doesnt dynamically load cert bundles after startup.

**Comment by BenTheElder** [comment]
also instead of copying it at runtime, just use https://kind.sigs.k8s.io/docs/user/private-registries/#use-a-certificate and it will work with `kind create cluster --config=` and no further manual steps

**Comment by rumstead** [comment]
@BenTheElder the suggestion doesn't seem to work for me, happy to contribute docs if I am doing something silly.
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # This option mounts the host docker registry folder into
    # the control-plane node, allowing containerd to access them. 
    extraMounts:
      - containerPath: /etc/docker/certs.d/internal-ca-bundle.crt
        hostPath: /Users/ME/tmp/certs/internal-ca-bundle.crt
```


```sh
❯ kind create cluster --name admin --config ./kind-config.yaml
Creating cluster "admin" ...

❯ docker exec -it 9012f8d9bafb /bin/sh
# ls -lrt /etc/docker/certs.d/
total 8
-rw-r--r-- 1 root root 6204 Jun 11 19:34 internal-ca-bundle.crt
```

Pod doesn't launch and LOOKS like containerd doesn't pick it up  
```
Normal   Scheduled  11s   default-scheduler  Successfully assigned default/test to admin-control-plane
  Normal   Pulling    10s   kubelet            Pulling image "quay.io/argoproj/argocd"
  Warning  Failed     10s   kubelet            Failed to pull image "quay.io/argoproj/argocd": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/argoproj/argocd:latest": failed to resolve reference "quay.io/argoproj/argocd:latest": failed to do request: Head "[https://quay.io/v2/argoproj/argocd/manifests/latest":](https://quay.io/v2/argoproj/argocd/manifests/latest%22:) x509: certificate signed by unknown authority
```

If I update the cert store it does work
```sh
# cp /etc/docker/certs.d/internal-ca-bundle.crt /usr/local/share/ca-certificates/
# update-ca-certificates

  Normal   Pulled     11m                  kubelet            Successfully pulled image "quay.io/argoproj/argocd" in 1.633731s
  Normal   Pulled     10m                  kubelet            Successfully pulled image "quay.io/argoproj/argocd" in 361.1ms
  Normal   Pulled     10m                  kubelet            Successfully pulled image "quay.io/argoproj/argocd" in 324.077ms

```
