### ISSUE TITLE
Support Bash Environment Variables in config.yml

### ISSUE THREAD

**Issue by ccardillo-opal** [kubernetes-sigs/kind#2106]
**What would you like to be added**: I want support for environment variables from my bash profile in my config.yml.

**Why is this needed**: This would be useful for project sharing. For example, let's say everyone needs an extraMount to work on a project. It would be so nice to be able to say `export MY_PROJECT_HOME=/my/project/home`, so that the work config could be something like:

```yml
- role: worker
  extraMounts:
  - hostPath: ${MY_PROJECT_HOME}/app
    containerPath: /local/app
```

Maybe this already exists in another form? I am not sure, so I made it a feature request!
