### ISSUE TITLE
Access kind cluster from a container outside of cluster

### ISSUE THREAD

**Issue by raphaelauv** [kubernetes-sigs/kind#2148]
Hello , I didn't find a solution in the already existing issues, maybe my question is only a docker / docker-compose question and not relative to kind.

I would like to access kind ( that is normally installed in my localhost ) from a container ( launch with docker-compose) were I want keep isolation between the compose network and the host network.

 ( so no network_mode: bridge or network_mode: host because I want my container to still be able to talk to other containers inside the compose with service_name)

I tried to follow https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container/61424570#61424570 , but without success.

```yaml
version: '3.8'
services:

  container:
    image: something
    environment:
      SERVICE_2_HOST: "service_2"
      SERVICE_3_HOST: "service_3"
   extra_hosts:
      - "host.docker.internal:host-gateway"
   
  service_2:
    image: something

  service_3:
    image: something

```

my file in .kube/config is 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ................
    server: https://127.0.0.1:34619
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
....
```

problem when I try to curl inside the container : 

```shell
root@913efd40b538:/usr# curl localhost:34619
curl: (7) Failed to connect to localhost port 34619: Connection refused
root@913efd40b538:/usr# curl 172.17.0.1:34619
curl: (7) Failed to connect to 172.17.0.1 port 34619: Connection refused
root@913efd40b538:/usr# curl host.docker.internal:34619
curl: (7) Failed to connect to host.docker.internal port 34619: Connection refused
```

If I curl in my localhost terminal , I receive answers :
```shell
raphaelauv@XXXXX:~/aaaaaa$ curl 127.0.0.1:34619
Client sent an HTTP request to an HTTPS server.
raphaelauv@XXXXX:~/aaaaaa$ curl localhost:34619
Client sent an HTTP request to an HTTPS server.
```

Thank you very much !!

Client: Docker Engine - Community : 20.10.5
kind v0.10.0 go1.15.7 linux/amd64
