### ISSUE TITLE
"unable to read admission control configuration" for PodNodeSelector  Admission Plugin

### ISSUE THREAD

**Issue by yogeek** [kubernetes-sigs/kind#2164]
**What happened**:

I am trying to test the `podNodeSelectorPluginConfig` feature with this configuration :

```
cat <<EOF >> ./admission-control.yaml
podNodeSelectorPluginConfig:
  clusterDefaultNodeSelector: "env=dev"
EOF

cat << EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./admission-control.yaml
    containerPath: /etc/kubernetes/adm-control/admission-control.yaml
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: PodNodeSelector,PodTolerationRestriction,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        admission-control-config-file: /etc/kubernetes/adm-control/admission-control.yaml
EOF
```

The cluster creation ended in error. Here are the logs:
```
I0327 16:45:54.459060     186 round_trippers.go:445] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds
I0327 16:45:54.459452     186 round_trippers.go:445] GET https://kind-control-plane:6443/healthz?timeout=10s  in 0 milliseconds

	Unfortunately, an error has occurred:
		timed out waiting for the condition
```

Here are the logs from the api-server in the docker container (when I managed to connect into during the start phase) :
```
# In the control-plane container
root@kind-control-plane:/# tail -f /var/log/containers/kube-apiserver-kind-control-plane_kube-system_kube-apiserver-fb169aba2e7f62cbcbbc04e9ff4ac261022b829733e43cd28185922394bd7fd8.log
2021-03-27T16:43:41.329172464Z stderr F Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
2021-03-27T16:43:41.329435991Z stderr F I0327 16:43:41.329350       1 server.go:632] external host was not specified, using 172.18.0.2
2021-03-27T16:43:41.330030435Z stderr F I0327 16:43:41.329943       1 server.go:182] Version: v1.20.2
2021-03-27T16:43:41.683087761Z stderr F Error: failed to initialize admission: failed to read plugin config: unable to read admission control configuration from "/etc/kubernetes/adm-control/admission-control.yaml" [open /etc/kubernetes/adm-control/admission-control.yaml: no such file or directory]
```

But when I check the file, it is here :
```
# In the control-plane container
root@kind-control-plane:/# ls -al /etc/kubernetes/adm-control/admission-control.yaml
-rw-r--r-- 1 1001 1001 68 Mar 27 16:41 /etc/kubernetes/adm-control/admission-control.yaml

root@kind-control-plane:/# cat /etc/kubernetes/adm-control/admission-control.yaml
podNodeSelectorPluginConfig:
  clusterDefaultNodeSelector: "env=dev"root
```

**What you expected to happen**:

I expected the api-server to starts because the file exists.

**Environment:**

- kind version: (use `kind version`): `kind v0.10.0 go1.15.7 linux/amd64`
- Kubernetes version: (use `kubectl version`): `Client Version : 1.18.12`
- Docker version: (use `docker info`): 
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-139-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 10.84GiB
 Name: vmcdsf
 ID: 4DA4:UTTH:S4KI:ZQB6:34NR:WZUZ:ZJTH:MZCC:5YWG:RHML:RM7Z:H3DW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 34
  System Time: 2021-03-27T17:55:59.357726828+01:00
  EventsListeners: 0
 Username: yogeek2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  localhost:80
  docker-dev.test-repo.int.be.continental.cloud
  docker.repo.int.be.continental.cloud
  localhost:443
  0.0.0.0/0
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
