### ISSUE TITLE
Unable to connect to the server: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by kinsolee** [kubernetes-sigs/kind#2166]
**What happened**:
Got an x509 error from api server after successful installation, running `kubectl cluster-info --context kind-kind` got:
```
❯ kubectl cluster-info --context kind-kind

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2021-03-29T11:40:49+08:00 is before 2021-03-29T11:39:56Z
```

**What you expected to happen**:
The certificate should be valid and kubectl should work properly.
**How to reproduce it (as minimally and precisely as possible)**:

```
❯ kind create cluster --retain --config ./test/kind/config.yaml
```
Here is the config.yaml:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "192.168.50.104"
#  # By default the API server listens on a random open port.
#  # You may choose a specific port but probably don't need to in most cases.
#  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP
      - containerPort: 9443
        hostPort: 9443
        # optional: set the bind address on the host
        # 0.0.0.0 is the current default
        listenAddress: "127.0.0.1"
        # optional: set the protocol to one of TCP, UDP, SCTP.
        # TCP is the default
        protocol: TCP
```

**Anything else we need to know?**:
The cluster was ok before, but I got this issue the last time I recreate the kind cluster.
**Environment:**

- kind version: (use `kind version`):
```kind v0.10.0 go1.16 darwin/arm64```
- Kubernetes version: (use `kubectl version`):
```
 Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c8d1f56", GitTreeState:"clean", BuildDate:"2021-03-19T13:45:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
```
- Docker version: (use `docker info`):
```
Client:
 Context:    tqg
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 121
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.638GiB
 Name: k8s-master
 ID: 5DH6:46PC:OJ5G:4UYN:B4UO:EH4L:3O6Q:BD47:DPTX:KIAV:N2YV:XZ75
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 41
  System Time: 2021-03-29T19:52:55.54281962+08:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  registry.apps.dev.oc.lo
  registry.docker-cn.com
  docker.mirrors.ustc.edu.cn
  kong-docker-kubernetes-ingress-controller.bintray.io
  127.0.0.0/8
 Registry Mirrors:
  http://docker.mirrors.ustc.edu.cn/
  http://hub-mirror.c.163.com/
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
