### ISSUE TITLE
Creating multi-node clusters

### ISSUE THREAD

**Issue by achanda** [kubernetes-sigs/kind#217]
Documentation around config to create multi-node clusters is not very clear. I tried this
```
apiVersion: kind.sigs.k8s.io/v1alpha1
kind: Config
---
kind: Node
apiVersion: kind.sigs.k8s.io/v1alpha1
role: control-plane
replicas: 3
---
kind: Node
apiVersion: kind.sigs.k8s.io/v1alpha1
role: worker
replicas: 2
```
But that still created a single node cluster. What did I miss in the config?

**Comment by idealhack** [comment]
I think we're not there yet :) https://github.com/kubernetes-sigs/kind/issues/117

**Comment by BenTheElder** [comment]
Ah that's the wrong format, we really need to bring back strict parsing @neolit123 :(

We do have multi node! But the config format is now
```
kind: Config
nodes:
- ...
```
(On my phone, will point you to pkg/cluster/config/v1alpha1 for the full format for now)

**Comment by BenTheElder** [comment]
We definitely need more docs here. Will PR today

**Comment by achanda** [comment]
I found this example in the src, this seems to work fine.
```
kind: Config
apiVersion: kind.sigs.k8s.io/v1alpha2
nodes:
- role: control-plane
  replicas: 3
- role: worker
  replicas: 2
- role: external-etcd
- role: external-load-balancer
```
Except that running it prints
```
failed to create cluster: multi node support is still a work in progress, currently external load balancer node is not supported
```
