### ISSUE TITLE
ERROR: failed to create cluster: failed to generate kubeadm config content.....

### ISSUE THREAD

**Issue by marcofranssen** [kubernetes-sigs/kind#2183]
**What happened**:

```bash
Adding kind directory to PATH...
Adding kubectl directory to PATH...
kind v0.10.0 go1.15.7 linux/amd64
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Creating kind cluster...
Creating cluster "chart-testing" ...
 • Ensuring node image (kindest/node:v1.18.15) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.18.15) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✗ Writing configuration 📜
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged chart-testing-control-plane cat /kind/version" failed with error: exit status 1
```

**What you expected to happen**:

> The kind cluster successfully starts

**How to reproduce it (as minimally and precisely as possible)**:

We are running a self hosted Github Actions runner with following configuration:

- Ubuntu 20.04
- Rootless docker (`20.10.5`) installation
- Following packages installed: 
    - awscli
    - jq
    - curl
    - wget
    - git
    - uidmap
    - build-essential
    - unzip

The workflow looks like this:

```yaml
name: Helm CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: [self-hosted]

    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.17.17
          - v1.18.15
          - v1.19.7
          - v1.20.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.3.1

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.10.0
          node_image: kindest/node:${{ matrix.k8s }}
```

**Anything else we need to know?**:

- All k8s versions fail with the same error.
- Rootless Docker installation

**Environment:**

- kind version: (use `kind version`): `v0.10.0`
- Kubernetes version: (use `kubectl version`): `v1.19.1`
- Docker version: (use `docker info`): `20.10.5`
- OS (e.g. from `/etc/os-release`): `ubuntu-20.04`
