### ISSUE TITLE
Provide option to expose metrics of kube-proxy

### ISSUE THREAD

**Issue by ChrsMark** [kubernetes-sigs/kind#2184]
Hi!

While using `kind` for local testing and development I hit an issue where `kube-proxy` does not expose by default the metrics endpoint. This is quite significant for people working on metrics/observability/monitoring etc and it would be nice to have the option to enable this.

To tackle this I had to manually edit `cm/kube-proxy` and change `metricsBindAddress: ""` to  `metricsBindAddress: "0.0.0.0"`, then delete kube-proxy Pod so as to have a new created.

I wonder if this could be something to be added as an option to `kube-proxy`'s settings like `KubeProxyMode` https://github.com/kubernetes-sigs/kind/blob/bbede401bb30967b68b7af8858e5cd0340c1c245/pkg/cluster/internal/kubeadm/config.go#L59 or it would make sense to add it by default in the template at https://github.com/kubernetes-sigs/kind/blob/bbede401bb30967b68b7af8858e5cd0340c1c245/pkg/cluster/internal/kubeadm/config.go#L274.

I can put a PR with whatever approach you think is most appropriate. Just let me know!

ps: I found several similar issues about `kube-proxy` (not related to `kind`) like https://github.com/aws/containers-roadmap/issues/657

**Comment by neolit123** [comment]
i think you should be able to pass this config with a kube-proxy patch to kind, no?

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: "0.0.0.0"
```

ref https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches
