### ISSUE TITLE
azure-files in kind

### ISSUE THREAD

**Issue by vot4anto** [kubernetes-sigs/kind#2201]
I follow the examples to use azurefiles. https://github.com/kubernetes/examples/tree/master/staging/volumes/azure_file

But when I create a Pod using the volume spec based on azure or define on PV and PVC I have the follow error from pod describe:

`  Warning  FailedMount  12m (x18 over 17m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[azure], unattached volumes=[config azure default-token-zdbfd]: failed to get Plugin from volumeSpec for volume "dataengine" err=no volume plugin matched`

The defition of PV and PVC are the follow:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataengine
  labels:
    usage: dataengine
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: dataengine
    readOnly: false
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataengine-claim
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: dataengine
```

And the definition of volume inside pod:
```
        volumeMounts:
        - mountPath: /shared  # in the container filesystem
          name: azure        #name as defined in volumes
      volumes:
        - name: azure #name of volume
          persistentVolumeClaim:
            claimName: dataengine-claim
```

- kind version: (use `kind version`):  `kind v0.9.0 go1.15.2 linux/amd64`
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-18T09:04:15Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version: (use `docker info`):

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 57
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-140-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 62.84GiB
 Name: charles.gem.lan
 ID: QTCW:M7V5:UGQG:YVQF:UYHS:XGP5:SFGQ:67FQ:SXY4:4CUD:7LE3:LXYZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- OS (e.g. from `/etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
