### ISSUE TITLE
joinConfiguration should "fail closed"  on control-plane nodes

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kind#2203]
Looks like if you do `joinConfiguration` with kubeletExtraArgs on a control-plane node you get a silent failure.
- KCP nodes are configured w `InitConfiguration`.
- non-KCP nodes are configured w/ `JoinConfiguration`.

However, doing this:

```
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: joinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kube-proxy=v2"
            authorization-mode: "AlwaysAllow"
```
passes validation, and comes up, for example, but it wont have the desired labels.  meanwhile using `joinConfiguration` for a worker node, of course works properly...  the correct thing to do  is pretty obvious ~ just do 

```
   - role: control-plane
     kubeadmConfigPatches:
       - |
-        kind: JoinConfiguration
+       kind: InitConfiguration
         nodeRegistration:
           kubeletExtraArgs:
             node-labels: "kube-proxy=v2"
```

But either way, Shouldnt kind error out if you try to use `joinConfiguration` on a ControlPlane node?
