### ISSUE TITLE
The kindnet pod is not scheduled if node has a `NoExecute` taint

### ISSUE THREAD

**Issue by rodrigosaito** [kubernetes-sigs/kind#2204]
**What happened**:

Created a cluster with a worker node having a `NoExecute` taint  caused `kindnet` pod to not be scheduled on that node leaving it `NotReady`.

**What you expected to happen**:

The `kindnet` pod to be scheduled on the tainted worker node, so it becomes `Ready`.  

**How to reproduce it (as minimally and precisely as possible)**:

Example config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          taints:
            - key: app
              value: test
              effect: NoExecute
          kubeletExtraArgs:
            node-labels: "my-label2=true"
```

Create the cluster:

```
$ kind create cluster --config config.yaml
```

The second worker node status doesn’t change to `Ready`:

```
$ kubectl get nodes
NAME                STATUS     ROLES                  AGE   VERSION
bug-control-plane   Ready      control-plane,master   75s   v1.20.2
bug-worker          Ready      <none>                 39s   v1.20.2
bug-worker2         NotReady   <none>                 39s   v1.20.2
``` 

Conditions on the `worker2` node:

```
Conditions:                                                       
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 19 Apr 2021 01:43:23 +0000   Mon, 19 Apr 2021 01:43:14 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available                                   
  DiskPressure     False   Mon, 19 Apr 2021 01:43:23 +0000   Mon, 19 Apr 2021 01:43:14 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure                                                                                                                  PIDPressure      False   Mon, 19 Apr 2021 01:43:23 +0000   Mon, 19 Apr 2021 01:43:14 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Mon, 19 Apr 2021 01:43:23 +0000   Mon, 19 Apr 2021 01:43:14 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReadymessage:Network plugin returns error: cni plugin not initialized
```

The `kindnet` ds is only scheduled on 2 pods:

```
$ kubectl -n kube-system get ds kindnet
NAME      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kindnet   2         2         2       2            2           <none>          3m52s
``` 

**Anything else we need to know?**:

The issue is caused by this tolerations set on the `kindnet` daemonset:

https://github.com/kubernetes-sigs/kind/blob/b6bc112522651d98c81823df56b7afa511459a3b/pkg/build/nodeimage/const_cni.go#L92-L94

A workaround I’ve been using is applying this patch to the daemonset:

```
spec:
  template:
    spec:
      tolerations:
        - operator: Exists
```

```
$ kubectl -n kube-system patch ds kindnet -p "$(cat kindnet-patch.yaml)"
daemonset.apps/kindnet patched
 
$ kubectl -n kube-system get ds kindnet
NAME      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kindnet   3         3         3       3            3           <none>          6m29s
```

**Environment:**

- kind version: (use `kind version`): `kind v0.10.0 go1.16.2 linux/amd64`
- Kubernetes version: (use `kubectl version`): `v1.20.5`
- Docker version: (use `docker info`): `20.10.6`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.2 LTS`
