### ISSUE TITLE
How can I run kind clusters with custom auth token webhook?

### ISSUE THREAD

**Issue by frodopwns** [kubernetes-sigs/kind#2209]
I want to use my own webhook service to validate auth tokens in my kind clusters.

I have created a `kind` config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
runtimeConfig:
  "authorization-mode": "RBAC,Webhook"
  "authorization-webhook-version": "v1"
  "authentication-token-webhook-config-file": "/files/config"
  "authorization-webhook-cache-authorized-ttl": "120s"
  "authorization-webhook-cache-unauthorized-ttl": "30s"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/ecorson/.kind
    containerPath: /files
```

The /files directory has the config for the webhook service and the localhost.crt.

The auth webhook config:

```
clusters:
- name: authwebhook
  cluster:
    certificate-authority: /files/localhost.crt
    server: https://authwebhook/
users:
- name: api-server
  user:
    token: test-token
current-context: authwebhook
contexts:
- context:
    cluster: authwebhook
    user: api-server
  name: authwebhook
```

I ran the webhook server via docker and added it to the kind network:

```
 sudo docker run --name authwebhook --network kind -p 443:443 tokenre:4
```

Then, using `kind 0.10.0`:

```
./kind-darwin-amd64 create cluster --name=mgmt --config=./dev.cfg -v 2
```

Which results in an error eventually:

```
Creating cluster "mgmt" ...
DEBUG: docker/images.go:67] Pulling image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✓ Preparing nodes 📦
DEBUG: config/config.go:90] Using the following kubeadm config for node mgmt-control-plane:
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    runtime-config: authentication-token-webhook-config-file=/files/config,authorization-mode=RBAC,Webhook,authorization-webhook-cache-authorized-ttl=120s,authorization-webhook-cache-unauthorized-ttl=30s,authorization-webhook-version=v1
apiVersion: kubeadm.k8s.io/v1beta2
clusterName: mgmt
controlPlaneEndpoint: mgmt-control-plane:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.20.2
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
scheduler:
  extraArgs: null
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.18.0.2
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.18.0.2
    provider-id: kind://docker/mgmt/mgmt-control-plane
---
apiVersion: kubeadm.k8s.io/v1beta2
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 172.18.0.2
    bindPort: 6443
discovery:
  bootstrapToken:
    apiServerEndpoint: mgmt-control-plane:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.18.0.2
    provider-id: kind://docker/mgmt/mgmt-control-plane
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
iptables:
  minSyncPeriod: 1s
kind: KubeProxyConfiguration
mode: iptables
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged mgmt-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0421 15:31:46.695103     239 initconfiguration.go:201] loading configuration from "/kind/kubeadm.conf"
[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.20.2

...

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'

```

Am I doing this wrong or is it not possible?

**Comment by BenTheElder** [comment]
the apiserver itself runs in a nested container / static pod, so you have to also customize the kubeadm config to mount the files you wanted from the node to the apiserver pod.

right now your config does host -> node, but lacks node -> apiserver mounts. some other examples: https://github.com/kubernetes-sigs/kind/issues/2164#issuecomment-808767239 https://github.com/kubernetes-sigs/kind/issues/1507#issuecomment-619491681

**Comment by frodopwns** [comment]
@BenTheElder Thanks so much for the response! It makes sense now. This should unblock me. Much appreciated..

**Comment by frodopwns** [comment]
OK, so I was able to mount the files in using this config:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraVolumes:
      - name: api-server-basic-auth-files
        hostPath: "/files"
        mountPath: "/files"
        readOnly: true
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /Users/ecorson/.kind
    containerPath: /files
```

But when I add the webhook stuff it returns to the same error as before:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
       extraArgs:
         "authorization-mode": "RBAC,Webhook"
         "authorization-webhook-version": "v1"
         "authentication-token-webhook-config-file": "/files/config"
         "authorization-webhook-cache-authorized-ttl": "120s"
         "authorization-webhook-cache-unauthorized-ttl": "30s"
      extraVolumes:
      - name: api-server-basic-auth-files
        hostPath: "/files"
        mountPath: "/files"
        readOnly: true
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /Users/ecorson/.kind
    containerPath: /files
```

resulted in

```
./kind-darwin-amd64 create cluster --name=mgmt --config=./dev.cfg -v 2
Creating cluster "mgmt" ...
DEBUG: docker/images.go:58] Image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab present locally
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✓ Preparing nodes 📦
DEBUG: config/config.go:90] Using the following kubeadm config for node mgmt-control-plane:
apiServer:
  certSANs:
  - localhost
  - 127.0.0.1
  extraArgs:
    authentication-token-webhook-config-file: /files/config
    authorization-mode: RBAC,Webhook
    authorization-webhook-cache-authorized-ttl: 120s
    authorization-webhook-cache-unauthorized-ttl: 30s
    authorization-webhook-version: v1
    runtime-config: ""
  extraVolumes:
  - hostPath: /files
    mountPath: /files
    name: api-server-basic-auth-files
    readOnly: true
apiVersion: kubeadm.k8s.io/v1beta2
clusterName: mgmt
controlPlaneEndpoint: mgmt-control-plane:6443
controllerManager:
  extraArgs:
    enable-hostpath-provisioner: "true"
kind: ClusterConfiguration
kubernetesVersion: v1.20.2
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
scheduler:
  extraArgs: null
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.18.0.3
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.18.0.3
    provider-id: kind://docker/mgmt/mgmt-control-plane
---
apiVersion: kubeadm.k8s.io/v1beta2
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 172.18.0.3
    bindPort: 6443
discovery:
  bootstrapToken:
    apiServerEndpoint: mgmt-control-plane:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: 172.18.0.3
    provider-id: kind://docker/mgmt/mgmt-control-plane
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
iptables:
  minSyncPeriod: 1s
kind: KubeProxyConfiguration
mode: iptables
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged mgmt-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0428 15:36:38.038870     242 initconfiguration.go:201] loading configuration from "/kind/kubeadm.conf"
[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.20.2
```

Do I also need to change the network settings of the apiserver pod to access my webhook?

Sorry to bug you again!
