### ISSUE TITLE
Number of desired replicas not matching with the actually existing ones after PC restart and manual pod deletion

### ISSUE THREAD

**Issue by Kavuti** [kubernetes-sigs/kind#2210]
I created a basic cluster configuration trying to deploy Keycloak on my PC. Here is the Deployment manifest I wrote:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.4
        resources:
          limits:
            cpu: "500m"
            memory: "1G"
        env:
        - name: KEYCLOAK_USER
          valueFrom: 
            secretKeyRef:
              name: keycloak-secret
              key: keycloakUser
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakPassword
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: postgres-db.default.svc.cluster.local
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakDbUser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloakDbPassword
        - name: DB_SCHEMA
          value: public
        - name: DB_DATABASE
          value: keycloak
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
```

The manifest, together with the configuration of a Service, a PV, PVC and Ingress, is correctly applied without any warning or error. The Deployment is correctly created along with the correspondent ReplicaSet and the 3 replicas.
Then I left and shut down my PC. When I came back and restarted my PC, I started making my tests with the deployed pods. I deleted one pod manually with

`kubectl delete pod keycloak-xxxxxxxxx-xxxxx -n keycloak`

and the pod has been correctly deleted. I was then expecting that the currently active Replicaset would replace the deleted pod with a new one in order to match the number of 3 replicas. Instead, no pod is created after the deletion, but examining the ReplicaSet, the Desired, Current and Ready pods are still 3. If I call a `kubectl describe` on the ReplicaSet, just the first three pod creation events are showed, all successful. Deleting the other pods, the ReplicaSet and the Deployment, does not make any difference. Even if I recreate the deployment by reapplying the manifest above, no ReplicaSet is created (and obviously no pod).

I tried to troubleshoot the cluster by exporting the logs with `kind export logs` but I didn't notice any strange log among the control-plane api logs and workers kubelet logs.

I have this problem every time I restart my PC. I had this problem also with my previous PC, with the same version of kind. For now, I'm deleting and recreating my cluster every time, but I can do it just because I have a few services running that I can easily restart, even if it's a bit time consuming.

Since I'm not familiar with Kubernetes yet, I'm sorry if I'm missing some important information. I'm here to give you any information is needed to find the origin of the problem.

Here is the basic tools and system information:
- kind version: v0.9.0
- Kubernetes version: v1.19.1
- Docker version: 20.10.5
- OS: Manjaro Linux
