### ISSUE TITLE
Unable to run Kubernetes `v1.12.10`

### ISSUE THREAD

**Issue by eggsbenjamin** [kubernetes-sigs/kind#2270]
**What happened**:

```
$ kind create cluster --config=kind/config.yaml --name=integrated-test-local
```

```
# kind/config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.registry:5000"]
    endpoint = ["http://registry.registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.12.10
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

The `coredns` pods crashloop with error

```
2021/05/23 17:05:27 [INFO] plugin/reload: Running configuration MD5 = f65c4821c8a9b7b5eb30fa4fbc167769
2021/05/23 17:05:34 [FATAL] plugin/loop: Seen "HINFO IN 1179812668599535537.130965306082261719." more than twice, loop detected
```

**What you expected to happen**:

The `coredns` pods should not crashloop _or_ I should be able to run `kindest/node:v1.12.10` with a specific version of `kind`.

**How to reproduce it (as minimally and precisely as possible)**:

Sping up the cluster using the above command and config.

**Anything else we need to know?**:

A [similar issue](https://github.com/kubernetes-sigs/kind/issues/1845) exists in which it's suggested that this breaking change was introduced in `v0.8.x` but it seems that the error exists in versions prior to this.

**Environment:**

- kind version: (use `kind version`):
  - `v0.7.0`
  - `v0.8.1`
  - `v0.9.0`
- Kubernetes version: (use `kubectl version`): `v1.12.10`
- Docker version: (use `docker info`): `20.10.5`
- OS (e.g. from `/etc/os-release`): macOS Catalina 10.15.7
