### ISSUE TITLE
Setting kubelet flags

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/kind#2281]
This is related to #2268. I created a config file that is supposed to pass extraArgs to the kubelet. I've confirmed that the kubelet flags appear in the kubeadm-flags.env file on the worker node, but the credential provider feature doesn't appear to be working. The KubeletCredentialProviders is an Alpha feature. Below is a copy of my KinD config: 
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
runtimeConfig:
  "api/alpha": "true"
#featureGates: 
  #"KubeletCredentialProviders": true
name: ecr-kubelet
nodes:
- role: control-plane
  image: kindest/node:v1.20.7@sha256:e645428988191fc824529fd0bb5c94244c12401cf5f5ea3bd875eb0a787f0fe9
- role: worker
  image: kindest/node:v1.20.7@sha256:e645428988191fc824529fd0bb5c94244c12401cf5f5ea3bd875eb0a787f0fe9
  extraMounts:
  - hostPath: /Users/fred/go/bin
    containerPath: /usr/local/kubelet/bin
  - hostPath: /Users/fred/conf
    containerPath: /usr/local/kubelet/conf
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration: 
      kubeletExtraArgs: 
        image-credential-provider-config: /usr/local/kubelet/config/ecr.conf
        image-credential-provider-bin-dir: /usr/local/kubetlet/bin/
```
I have commented out the feature gate because the nodes were not able to join the cluster when I had that set. Instead I am enabling all Alpha features (I think).
