### ISSUE TITLE
Multi-Node cluster cannot be created for image v1.17.17

### ISSUE THREAD

**Issue by ermalguni** [kubernetes-sigs/kind#2295]
**What happened**: Cannot create multi node cluster of older kubernetes version v1.17.17.

**What you expected to happen**: Multi node cluster gets created succesfully

**How to reproduce it (as minimally and precisely as possible)**:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pe-test
nodes:
- role: control-plane
  image: kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00
  extraPortMappings:
  - containerPort: 80
    hostPort: 18080
    protocol: TCP
  - containerPort: 443
    hostPort: 18443
    protocol: TCP
- role: worker
  image: kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00
- role: worker
  image: kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.11.1
- Kubernetes version: (use `kubectl version`):  
``` 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`): 
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 36cc874494a56a253cd181a1a685b44b58a2e34a.m
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.12.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.04GiB
 Name: pe
 ID: EBSG:MAJK:HEPA:U5X3:ALVG:QI7S:6SRS:6H5F:DSJX:WY5J:M52Q:KGRX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ermalguni
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

- OS (e.g. from `/etc/os-release`): Arch Linux (Linux pe 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux)
