### ISSUE TITLE
New containers unable to reach the network for a while when using Calico

### ISSUE THREAD

**Issue by bandesz** [kubernetes-sigs/kind#2308]
First of all I know that Calico is not officially supported, but I'm leaving this question here for others to find. Maybe others have/had the same issue.

When I disable the default CNI and install Calico, new containers are unable to reach the network for at least ~30 seconds.

In my tests I was trying to reach a service on a cluster IP to rule out any DNS resolution issues.

When I remove Calico and use the built-in CNI, new containers can reach the network instantly.

OS: macOS 11.4
Kind version: v0.11.1
Calico versions tested: v3.16.10, v3.19.1
Docker Desktop: 3.3.3 (6 CPUs, 6Gb memory)

Kind config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
nodes:
  - role: control-plane
    image: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: 127.0.0.1
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: 127.0.0.1
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
```

Calico manifests used: `https://docs.projectcalico.org/[v3.16|v3.19]/manifests/calico.yaml`
