### ISSUE TITLE
pods runnig at different nodes have the same product_uuid

### ISSUE THREAD

**Issue by qinqon** [kubernetes-sigs/kind#2318]
**What happened**:
At KubeVirt we use kind to test SRIOV migrations and it depends on pods having different product_uuid, I saw that nodes were fixed and they have different product_uuid already, but is not the case for pods.

**What you expected to happen**:
Pods running at different nodes having different product_uuid.

**How to reproduce it (as minimally and precisely as possible)**:

1- Create a cluster with 
```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

1 - Create a pair of pods at each worker
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-kind-worker
  labels:
    env: test
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-kind-worker2
  labels:
    env: test
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker2
  containers:
  - name: nginx
    image: nginx
```

3 - Check the product_uuid
```bash
$ kubectl exec nginx-kind-worker -- cat /sys/devices/virtual/dmi/id/product_uuid
ffd897cc-3219-11b2-a85c-ca68c7b7906b
$ kubectl exec nginx-kind-worker2 -- cat /sys/devices/virtual/dmi/id/product_uuid
ffd897cc-3219-11b2-a85c-ca68c7b7906b
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):
