### ISSUE TITLE
name "kubernetes.docker.internal" should be valid by certificate

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/kind#2325]
**What would you like to be added**:

I'd like to run `kubectl` or `helm` in container, but when I do that, I got problem which I knew 127.0.0.0 is container's ip, not kind's

```
docker run -v ~/.kube:/root/.kube alpine/helm list
Error: Kubernetes cluster unreachable: Get "https://127.0.0.1:50939/version?timeout=32s": dial tcp 127.0.0.1:50939: connect: connection refused
```

So I adjust the IP to local laptop IP or to `kubernetes.docker.internal`.  then I got another error

>Unable to connect to the server: x509: certificate is valid for kind-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not kubernetes.docker.internal

but with same setting in Docker desktop for mac, it works

So I would recommend to add new dns name `kubernetes.docker.internal` into certificate.

thanks.

paste the kube config file for your reference:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *********************
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: ****************
    server: https://127.0.0.1:51987
  name: kind-kind
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: *****************
    client-key-data: *****************
- name: kind-kind
  user:
    client-certificate-data: *****************
    client-key-data: L***********************
```
