### ISSUE TITLE
k8s kind on local network "The connection to the server was refused"

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#2348]
I have a cluster running in a local network where I have access ping etc. But kubectl can not connect:

Update: I tried setting(thanks BenTheElder):   apiServerAddress: "127.0.0.1"

What am I doing:

1. Setting up a cluster

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

2. Copy the `~/.kube/config` to other machine on the same network
3. changed server ip address in cobfig

Error:
`The connection to the server <ip adddress>:44495 was refused - did you specify the right host or port?`

Should I do something when creating the cluster?

FYI: The port is open and listening - in this case it is 36879 and as you know changes each time I create a new cluster.

sudo lsof -i -P -n | grep LISTEN
```
systemd-r    559 systemd-resolve   13u  IPv4  11247      0t0  TCP 127.0.0.53:53 (LISTEN)
cupsd        597            root    6u  IPv6  15250      0t0  TCP [::1]:631 (LISTEN)
cupsd        597            root    7u  IPv4  15251      0t0  TCP 127.0.0.1:631 (LISTEN)
docker-pr   1925            root    4u  IPv4  29994      0t0  TCP 127.0.0.1:5000 (LISTEN)
docker-pr 111155            root    4u  IPv4 645831      0t0  TCP 127.0.0.1:36879 (LISTEN)
docker-pr 111167            root    4u  IPv4 647693      0t0  TCP *:443 (LISTEN)
docker-pr 111181            root    4u  IPv4 649705      0t0  TCP *:80 (LISTEN)
```
