### ISSUE TITLE
not able to create extraMounts

### ISSUE THREAD

**Issue by andycwk** [kubernetes-sigs/kind#2400]
Hi!

I've started using kind for a new project and it's been really good so far.

I've got to a point where I would like to persist data created within the cluster between cluster bootstrap & teardown events.

I've attempted to use the following Kind config...

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: xxx-local-dev
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ../local-dev/.kind
      containerPath: /opt/local-path-provisioner
      propagation: HostToContainer
    extraPortMappings:
      # Ingress (Http)
      - containerPort: 30300
        hostPort: 3000
        protocol: TCP
        # Ingress (Https)
      - containerPort: 30333
        hostPort: 3433
        protocol: TCP
        # texmo-frontend
      - containerPort: 30400
        hostPort: 4000
        protocol: TCP
        # taro-frontend
      - containerPort: 30500
        hostPort: 5000
        protocol: TCP
```

And shared the fully qualified path inside Docker Desktop 

![Screenshot 2021-07-30 at 11 20 31](https://user-images.githubusercontent.com/2248787/127640930-6ea7d58f-07db-43ad-b8b6-74383f90b40e.png)

But, upon attempting to bootstrap the cluster, I get the following error messages..

![Screenshot 2021-07-30 at 11 19 53](https://user-images.githubusercontent.com/2248787/127641153-8fbe2422-9d57-45aa-ba8a-c1fd77b4e5e7.png)

Could anyone provide an indication as to what config steps I've missed or where I've gone wrong?

Cheers!
