### ISSUE TITLE
Share host filesystem and network

### ISSUE THREAD

**Issue by TristanCacqueray** [kubernetes-sigs/kind#2430]
**What would you like to be documented**:

How to share the host filesystem and network.

**Why is this needed**:

I was migrating a docker compose application to Kind, and I had some issues setting up host bind mount and network access. Below are my notes of the solutions. I hope they will be useful to others users:

# The application

The goal is to run the development server of patternfly:

```ShellSession
$ git clone https://github.com/patternfly/patternfly-react-seed
$ cd patternfly-react-seed
$ npm install && npm run start:dev
```

... which is running at `http://localhost:9000`.

# Kind without configuration:

Simply running:

```ShellSession:
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂

$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: patternfly-dev
spec:
  containers:
  - name: npm
    image: registry.access.redhat.com/ubi8/nodejs-12
    args: [npm, run, "start:dev"]
    ports:
    - containerPort: 9000
      name: npm
    volumeMounts:
    - mountPath: /opt/app-root/src
      name: src
  volumes:
  - hostPath:
      path: /home/fedora/src/github.com/patternfly/patternfly-react-seed/
    name: src
EOF
pod/patternfly-dev created
```

... does not work:

- The hostPath is not available; and
- The network port is unreachable.

# Kind configuration

Kind needs a configuration to share the host filesystem and network:

```yaml
# kind-config.yaml
kind: Cluster
apiVersion:  kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  extraMounts:  # Share the host filesystem
  - hostPath: ./
    containerPath: /src

- role: control-plane
  kubeadmConfigPatches:  # Enable the creation of ingress controller
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraPortMappings:  # Expose the http port on the host
  - containerPort: 80
    hostPort: 80
```

... which needs to be applied with:

```ShellSession
$ kind delete cluster
Deleting cluster "kind" ...

$ kind create cluster --config kind-config.yaml
[cluster re-create]
```

We can check that the filesystem is shared:

```ShellSession
$ ls -la package.json
-rw-r--r-- 1 fedora fedora 3314 Aug 20 13:20 package.json
$ docker exec kind-worker ls -la /src/package.json
-rw-r--r--. 1 1000 1000 3314 Aug 20 13:20 /src/package.json
```

# Accessing host path from the pod

My project's sources are shared in the /src directory of the worker namespace thanks to the `extraMounts` configuration. We still need to configure it for the pod:

```yaml
# patternfly-dev-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: patternfly-dev
spec:
  containers:
  - name: npm
    image: registry.access.redhat.com/ubi8/nodejs-12
    args: [env, HOST=0.0.0.0, npm, run, "start:dev"]
    ports:
    - containerPort: 9000
      name: npm
    securityContext:
      # Share the same uid as host to avoid conflict
      runAsUser: 1000
    volumeMounts:
    - mountPath: /opt/app-root/src
      name: src
  volumes:
  - hostPath:
      # This path is the `containerPath` defined in kind-config.yaml
      path: /src/
    name: src
```

That seems to work, and updating the code from the host is properly hot reloaded in the container:

```ShellSession
$ kubectl apply -f ./patternfly-dev-pod.yaml
pod/patternfly-dev created

$ kubectl logs -f pod/patternfly-dev
> patternfly-seed@0.0.2 start:dev /opt/app-root/src
> webpack serve --color --progress --config webpack.dev.js
[...]
ℹ ｢wds｣: Project is running at http://0.0.0.0:9000/
ℹ ｢wdm｣: Compiled successfully.
```

... however the http service is not reachable:

```
$ kubectl get pods -o wide
NAME             READY   STATUS    RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
patternfly-dev   1/1     Running   0          28s   10.244.1.3   kind-worker   <none>           <none>

$ curl 10.244.1.3:9000
curl: (7) Failed to connect to 10.244.1.3 port 9000: Connection refused
```

Though we can validate that the service is running:

```
$ docker exec kind-worker curl -i 10.244.1.3:9000
HTTP/1.1 200 OK
X-Powered-By: Express

$ kubectl port-forward pod/patternfly-dev 9000 &
Forwarding from 127.0.0.1:9000 -> 9000
$ curl -i localhost:9000
HTTP/1.1 200 OK
X-Powered-By: Express
```

# Access kubernetes services from the host

Kind needs an ingress controller to enable service access from the host:

```ShellSession
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
namespace/ingress-nginx created
serviceaccount/ingress-nginx created
configmap/ingress-nginx-controller created
clusterrole.rbac.authorization.k8s.io/ingress-nginx created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx created
role.rbac.authorization.k8s.io/ingress-nginx created
rolebinding.rbac.authorization.k8s.io/ingress-nginx created
service/ingress-nginx-controller-admission created
service/ingress-nginx-controller created
deployment.apps/ingress-nginx-controller created
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission created
serviceaccount/ingress-nginx-admission created
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
role.rbac.authorization.k8s.io/ingress-nginx-admission created
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
```

... and the application needs to use a Service, Deployment and Ingress resource:

```yaml
# patternfly-dev.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name:  patternfly-dev
  name: patternfly-dev
spec:
  ports:
    - name: patternfly-dev
      port: 9000  # the application port
      targetPort: 9000
  selector:
    app.kubernetes.io/name: patternfly-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: patternfly-dev
  name: patternfly-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: patternfly-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: patternfly-dev
      name: patternfly-dev
    spec:
      automountServiceAccountToken: false
      containers:
      - name: npm
        image: registry.access.redhat.com/ubi8/nodejs-12  # the application runtime
        args: [env, HOST=0.0.0.0, npm, run, "start:dev"]  # the application command
        ports:
        - containerPort: 9000  # the application port
          name: npm
        securityContext:
          runAsUser: 1000  # the host user id
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: src
      volumes:
      - hostPath:
          # This path is the `containerPath` defined in kind-config.yaml
          path: /src/
        name: src
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patternfly-dev
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: patternfly-dev
            port:
              number: 9000  # the application port
```

... and with all of that, the development server is now available through `xdg-open http://localhost`.

Sharing the host filesystem and network works out of the box with docker-compose, and it took me quite a while to migrate this application to Kind. Am I doing something wrong? Could this be documented or taken care of by Kind automatically?

This is my first issue, thanks you for Kind, it's super useful!
