### ISSUE TITLE
additional pod creation pending forever

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [kubernetes-sigs/kind#2458]
I created my cluster using:  
`kind create cluster --config config-files/kind-cluster.yml`   

```yml
### file kind-cluster.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
``` 

I created 3 replicas of nginx:  
`kubectl create deployment nginx --image=stenote/nginx-hostname`  
`kubectl scale --replicas=3 deployment nginx`  

And finally I created an instance of Ubuntu pod:  
`kubectl apply -f ubuntu-pod.yml`  
```yml
### file ubuntu-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
After that, if I try to create another Pod, it'll be pending forever  
I noticed any additional pod will stay pending forever.   

`kubectl apply -f ubuntu-pod2.yml`  
`kubectl get pods -w`  
```
NAME                   READY   STATUS    RESTARTS       AGE
nginx-78d58889-5zjbg   1/1     Running   1 (137m ago)   14h
nginx-78d58889-8pvg5   1/1     Running   1 (137m ago)   14h
nginx-78d58889-d64rn   1/1     Running   1 (137m ago)   14h
ubuntu                 1/1     Running   1 (137m ago)   14h
ubuntu2                0/1     Pending   0              19s
```

`kubectl describe pod ubuntu2`  
```
Name:         ubuntu2
Namespace:    default
Priority:     0
Node:         <none>
Labels:       app=ubuntu2
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  ubuntu2:
    Image:      ubuntu:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sleep
      3650d
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-48pnd (ro)
Volumes:
  kube-api-access-48pnd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

`kubectl logs ubuntu2` doesn't show anything  
`kubectl logs` nothing  
`kubectl get pod -n kube-system`  

```
NAME                                         READY   STATUS    RESTARTS       AGE
coredns-78fcd69978-72tsp                     1/1     Running   1 (174m ago)   14h
coredns-78fcd69978-vxmrk                     1/1     Running   1 (174m ago)   14h
etcd-kind-control-plane                      1/1     Running   0              174m
kindnet-7wzh6                                1/1     Running   1 (174m ago)   14h
kindnet-8xhzn                                1/1     Running   1 (174m ago)   14h
kindnet-lr5v4                                1/1     Running   1 (174m ago)   14h
kindnet-r9h7c                                1/1     Running   1 (174m ago)   14h
kube-apiserver-kind-control-plane            1/1     Running   0              174m
kube-controller-manager-kind-control-plane   1/1     Running   1 (174m ago)   14h
kube-proxy-2fs7j                             1/1     Running   1 (174m ago)   14h
kube-proxy-4qjcz                             1/1     Running   1 (174m ago)   14h
kube-proxy-hf782                             1/1     Running   1 (174m ago)   14h
kube-proxy-nmnd5                             1/1     Running   1 (174m ago)   14h
kube-scheduler-kind-control-plane            1/1     Running   1 (174m ago)   14h
```
