### ISSUE TITLE
running two kind instances and open ports on the host

### ISSUE THREAD

**Issue by pschrammel** [kubernetes-sigs/kind#2503]
Hi,

I'm trying to run two kind instances (not nodes) and open port 80,443,6443,.... on both of them on the host.

What I tried:
#creating a new network interface (without this I get binding errors, there should be an interface for each kind instance so I never bind to the host's real ip address or even 0.0.0.0)

sudo ifconfig lo:0 192.168.80.11
#creating a docker network
docker network create --gateway 192.168.80.1 --subnet=192.168.80.0/24 fixingthenet
#starting kind and using a separate network
KIND_EXPERIMENTAL_DOCKER_NETWORK=fixingthenet kind create cluster --name "fixingthenet" --config kind.yml

the kind config look like this:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.80.11"
nodes:
- role: control-plane
  # Images with different Kubernetes versions can be found here: https://github.com/kubernetes-sigs/kind/releases
  image: kindest/node:v1.18.19@sha256:7af1492e19b3192a79f606e43c35fb741e520d195f96399284515f077b3b622c
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: "192.168.80.11"
    - containerPort: 443
      hostPort: 443
      listenAddress: "192.168.80.11"
    - containerPort: 30379
      hostPort: 30379
      listenAddress: "192.168.80.11"
    - containerPort: 30432
      hostPort: 30432
      listenAddress: "192.168.80.11"
    - containerPort: 30025
      hostPort: 30025
      listenAddress: "192.168.80.11"
    - containerPort: 30017
      hostPort: 30017
      listenAddress: "192.168.80.11"
    - containerPort: 6443
      hostPort: 6443
      listenAddress: "192.168.80.11"
```
but I can't connect to the k8s control panel. 
The first thing I saw is that the created container has ip 192.168.80.2; so I changed kind.config and the ifconfig address to that ip but I think then the routing is totally weird and even when curl seems to connect I get TLS handshake timeouts.

Any tips what to try or even better a tip how to set it up correctly? 

THX
