### ISSUE TITLE
Unable to get the OOM killed event when the memory usage of the pod is greater than limit in KinD cluster

### ISSUE THREAD

**Issue by Imboncy** [kubernetes-sigs/kind#2514]
## Details

- I have defined the pod resource request as follow on a kind cluster:

```yaml
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"
```

But When I'm consuming higher memeor resources still i don't see any OOM Killed event.

inside the pod
```bash
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 dumb-init node --experimental-vm-modules ./dist/index.js
    7 root      0:00 node --experimental-vm-modules ./dist/index.js
   17 root      0:00 sh
   53 root      0:00 stress-ng --timeout 1200s --vm 1 --vm-bytes 500M --vm-hang 1
   54 root      0:00 stress-ng-vm [run]
   55 root      3:36 stress-ng-vm [run]
   56 root      0:00 sh
   63 root      0:00 ps aux
```

The memory usage is never exceding the litmit as shown below:

```bash
/app # cat /sys/fs/cgroup/memory/memory.limit_in_bytes
268435456
/app # cat /sys/fs/cgroup/memory/memory.usage_in_bytes
268210176
```
