### ISSUE TITLE
kubectl command not working after I run kind on docker 

### ISSUE THREAD

**Issue by i053322** [kubernetes-sigs/kind#2534]
**What happened:**

I create cluster with kind in docker after it created I didn't succeed to run any kubectl command and I got an error
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port

**What you expected to happen:**

running kubectl command in the docker to my kind cluster

**How to reproduce it (as minimally and precisely as possible):**

I created dockerfile

```
FROM golang:1.16.5-alpine3.13

ENV CGW-DOCKER-BUILDER-VERSION 1.0.0

RUN apk --no-cache add --update \
    openrc \
    curl

RUN apk add docker
RUN apk update
RUN rc-update add docker boot

# Install kubectl
RUN curl -LOf "https://dl.k8s.io/release/v1.21.6/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl


# Install kind
RUN curl -LOk https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64 \
    && chmod +x ./kind-linux-amd64 \
    && mv ./kind-linux-amd64 /usr/local/bin/kind


# Install helm 3
RUN curl -Lk https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz | tar -xz \
    && mv linux-amd64/helm /usr/local/bin/helm \
    && rm -r linux-amd64 \
    && ln -s helm /usr/local/bin/helm3

# install kubectl-cert-manager
RUN curl -L -o kubectl-cert-manager.tar.gz https://github.com/jetstack/cert-manager/releases/latest/download/kubectl-cert_manager-linux-amd64.tar.gz \
    && tar xzf kubectl-cert-manager.tar.gz \
    && mv kubectl-cert_manager /usr/local/bin

ARG HELMFILE_VERSION=0.141.0
RUN curl -sSL https://github.com/roboll/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_linux_amd64 -o /bin/helmfile \
    && chmod 0755 /bin/helmfile

# install common go tools
RUN go get -u \
    golang.org/x/lint/golint \
    github.com/securego/gosec/cmd/gosec \
 && go clean -cache -testcache -modcache \
 && rm -rf $GOPATH/src

WORKDIR /
COPY . .

# Set tmp as home folder for all users so we can run container with any user
ENV HOME /tmp
```
I build it and now I run the docker

```
docker run -it -v myRepo:/myRepo-v /var/run/docker.sock:/var/run/docker.sock myDocker:0.0.1 sh
```

I created kind cluster
```
kind create cluster --config ./kind-config.yaml --kubeconfig ./tmp/kind-kubeconfig.yaml
```

kind-config.yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mydev
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31500
    hostPort: 80
    protocol: TCP
  - containerPort: 32500
    hostPort: 443
    protocol: TCP
after I run the cluster was created and in docker ps I can saw the docker
```
kind-kubeconfig.yaml

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:6443
  name: kind-dev
contexts:
- context:
    cluster: kind-dev
    user: kind-dev
  name: kind-dev
current-context: kind-dev
kind: Config
preferences: {}
users:
- name: kind-dev
  user:
    client-certificate-data: ....
```

Any command I tried of kubectl I got the same error
```
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port
```

**Anything else we need to know?:**

when i run it on my computer without docker than it is working.
I tried to change the port and move to the docker -p 6442:6443 and it still didn't work

```

docker ps

2440e617149f   kindest/node:v1.21.1                                          
"/usr/local/bin/entr…"   12 hours ago    Up 12 hours    
127.0.0.1:6443->6443/tcp, 0.0.0.0:80->31500/tcp, 0.0.0.0:443->32500/tcp  
dev-control-plane
```

/ # cat etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.3      8d2b5fd7ae10
```

Environment:
kind version: kind v0.11.1 go1.16.4 linux/amd64

Kubernetes version: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Docker version:  20.10.3
