### ISSUE TITLE
imagePullPolicy: Never - Error: ErrImageNeverPull - even crictl images list the image

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kind#2556]
I have build an image and got it into my One Node KinD cluster.

If I `docker exec -it kind-control-plane bash` and do `crictl images` I get:
`docker.io/library/thisisfine                                                  v1                   b948a565934c9       108MB`

kubectl apply -f my-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - name: getting-started
    imagePullPolicy: Never
    image: docker.io/library/thisisfine:v1 # or :thisisfine:v1
```

kubectl describe pod getting-started: ` is not present with pull policy of Never` do you know why?
```
Normal   Scheduled          23m                   default-scheduler  Successfully assigned default/getting-started to kind-control-plane
  Warning  Failed             21m (x12 over 23m)    kubelet            Error: ErrImageNeverPull
  Warning  ErrImageNeverPull  3m34s (x95 over 23m)  kubelet            Container image "docker.io/library/thisisfine:v1" is not present with pull policy of Never
```

- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
```

```
kind version
kind v0.11.1 go1.16.4 linux/arm64
```
