### ISSUE TITLE
Acces a kind container from a docker container outside of kind

### ISSUE THREAD

**Issue by raphaelauv** [kubernetes-sigs/kind#2571]
Hello I'm trying to reach a container inside KIND from a local docker container

The green arrow work
the red arrow do not work 

![KIND network (1)](https://user-images.githubusercontent.com/10202690/145683347-fdaadaf9-3c36-4c19-840e-1aa40e3ecd26.jpg)

```yaml
networks:
  default:
    name: a_network
    
container_1:
    image: something
    extra_hosts:
      - "host.docker.internal:host-gateway"

```

The network of my docker-compose and kind are connected  :
```shell
docker network connect a_network  kind-control-plane
```

from a terminal in localhost I can access the post-forward :
```shell
XXX@XXX:~$ curl localhost:4500
{"message": "Not found", "code": 404}
```

from a terminal inside the container_1 i can't access the post-forward :
```shell
root@913efd40b538:/usr# curl host.docker.internal:4500
curl: (7) Failed to connect to host.docker.internal port 4500: Connection refused
```

I can only reach the port 6443 expose by the container KIND
```shell
root@913efd40b538:/usr# curl kind-control-plane:6443
Client sent an HTTP request to an HTTPS server.
``` 

Also if I follow this tutorial https://kind.sigs.k8s.io/docs/user/loadbalancer/

from a terminal in localhost I can access the port :
```shell
XXX@XXX:~$ echo $LB_IP
172.21.255.200
XXX@XXX:~$ curl http://172.21.255.200:5678/
foo
```

But impossible to access that port from the container_1 

So my question is how do I access from a local container the port of post-forward (and in the best case the K8S service) of a pod.

Thank you very much.

**Comment by aojea** [comment]
use a nodeport service to expose the "kind container" port in the kindnode, and you'll be able to access it in the IP of any of the kind nodes

**Comment by stmcginnis** [comment]
I have used the same as what @aojea is recommending. Can this be closed now @raphaelauv?

**Comment by raphaelauv** [comment]
Yes it work, thank @aojea  and @stmcginnis 

a full example :

the deployment ->

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
```

the service ->

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: test
  ports:
  - protocol: TCP
    port: 6004
    targetPort: 8080

```

to get the IP ->
```shell
kubectl config use-context kind-kind
kubectl get service --all-namespaces
```

return

```log
NAMESPACE     NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes     ClusterIP   10.96.0.1       <none>        443/TCP                  149m
default       test-service   NodePort    10.96.176.254   <none>        6004:31603/TCP           26s
kube-system   kube-dns       ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   149m
```

connect the network of the container_1 and kind :

```shell
docker network connect a_network  kind-control-plane
```
inside the container **container_1** 

```shell
root@XXXXX:/usr/local# curl kind-control-plane:31603
Hello Kubernetes!
```
