### ISSUE TITLE
Feature Request: extraContainerArgs for Nodes

### ISSUE THREAD

**Issue by eqsoft** [kubernetes-sigs/kind#2579]
**What would you like to be added**:
extraContainerArgs for node container at cluster creation time

**Why is this needed**:
I must apologize for presenting such a detailed and extensive issue, but i hope this will facilitate further conceptual discussions on that point.

I am using KinD for exploring k8s api concepts / components and for cluster development. I have a lot of other container stacks (docker composer) running for development so i have to take care for separation, accessability and connection of the virtual environments and services. For achieving this i am always using explicit external docker- or podman-networks with unique customized bridge names and predefined subnets.

Before spawning a new kind cluster i create a custom network ( $CLUSTER_NAME-kind) with a predefined subnet because i really don't want to use the docker defaults for better control. Then i attach the kind cluster to this network with "export KIND_EXPERIMENTAL_DOCKER_NETWORK=$CLUSTER_NAME-kind kind create cluster --name $CLUSTER_NAME --config=cluster.yaml"
(Maybe the configuration of a custom kind network will find a liberated way into the core... this is a related but different discussion)

After deploying my multi-node k8s-cluster everything is fine. But after rebooting my laptop or restarting docker, the cluster is up but i can not access my services because cluster DNS resolution does not work anymore. I have to recreate the whole cluster with all deployments.

Before debugging CNI and coreDNS configurations i noticed that docker respawns the correct node container but with different ip and mac address assignments. So i decided to fix this up first, i really don't want that docker decides to shuffle my virtual host network. This can be achieved by assigning static ips to the nodes at container creation time to give docker the chance to rebuild the correct network assignments.

I understand the conceptual impacts of coupling the host docker network infrastructure at cluster node creation time. This only makes sense if i have full control over the kind network (see above). By using the default docker network the assignment of static ips is conceptual not intended and presumably up to now not supported in kind because of possible network conflicts (correct?). But how can we get best of both worlds:

1. decoupled from host network and stateless (current core concept: with a kind net in the default docker network)

2. customizable network to get a persistent and more reliable virtual host environment for better integration in existing development and CI infrastructures.

In a first step i decided to extend the node creation by adding a new node type property "extraContainerArgs" to inject additional docker container args like --ip and --mac-address on the node level to check if this would solve at least my initial DNS problems after docker restarts.

And voila after docker restarts or pc reboots everything is fine, DNS resolution works as expected and the inspection of my $CLUSTER_NAME-kind docker network shows no alterations anymore.

Example cluster.yml:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
   - role: control-plane
     containerExtraArgs:
       "--ip": "172.118.1.10"
       "--mac-address": "02:42:ac:76:0a:0a"
     kubeadmConfigPatches:
     - |
       kind: InitConfiguration
       nodeRegistration:
         kubeletExtraArgs:
           node-labels: "ingress-ready=true"

   - role: worker
     containerExtraArgs:
       "--ip": "172.118.1.11"
       "--mac-address": "02:42:ac:76:01:01"
     extraMounts:
     - hostPath: /work/data
       containerPath: /data
     kubeadmConfigPatches:
     - |
       kind: JoinConfiguration
       nodeRegistration:
         kubeletExtraArgs:
           node-labels: "role=worker"

   - role: worker
     containerExtraArgs:
       "--ip": "172.118.1.12"
       "--mac-address": "02:42:ac:76:01:02"
     extraMounts:
     - hostPath: /work/data
       containerPath: /data
     kubeadmConfigPatches:
     - |
       kind: JoinConfiguration
       nodeRegistration:
         kubeletExtraArgs:
           node-labels: "role=worker"

networking:
   serviceSubnet: "10.96.0.0/12"
   podSubnet: "10.244.0.0/16"

```

This also works with the default docker network (without KIND_EXPERIMENTAL_DOCKER_NETWORK) Just create the cluster with the default network and let docker assign the initial ips and mac-addresses. After that inspect the kind net with "docker inspect network kind" and copy the ip/mac-addresses into your cluster.yml ... recreate the cluster.

The code:

https://github.com/eqsoft/kind/commit/474295ba1741ed21fecf8bb398085613994609ba

Please consider that i have no expertise in go coding and kind development. Nevertheless a PR could be created if this is appreciated.
Maybe i am totally on a wrong way but i am working with this new feature and it feels good :-)

Some Annotations to code decisions:

- I decided to omit the establishment of particular node properties like "NodeIP" or "MacAddress" in favour of a generic configuration of docker args.  Because there may be other candidates like "--security-opt" or extra "--env" parameter for better control and integration in CI and development infrastructures.
- all args are just appended to the internal args slice in the provision component. Validation, blacklisting for protected args or explicit whitelisting maybe conceivable.
- docker and podman client always grabs the last arg entry so it is possible to override internal args like --hostname. This also might be streamlined by first looking up extraContainerArgs to avoid doubling singlekey entries. Therefore a warning is displayed if extraContainerArgs are defined in any of the nodes.

best regards,
Stefan
