### ISSUE TITLE
A Pod becomes a memory hog in Kind (the issue seems Kind-specific)

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes-sigs/kind#2623]
**What happened**:
A very simple pod turns into a memory hog on a 3-node Kind cluster. This sample haproxy pod (see the manifest below) rapidly consumes as much memory as limits permit and starts consuming swap (and if there is no limit configured, it easily consumes gigabytes of memory).

**What you expected to happen**:
I expect this particular image to consume about 150Mi of RAM as it happens in Minikube and in a kOps/AWS cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Please apply the attached manifest and watch the pod's memory usage. 

**Anything else we need to know?**:
The problem is reproducible only in Kind that's why I'm filing the bug here as it may be specific to Kind. Minikube and kOps are not affected.

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.17.6 linux/amd64.
- Kubernetes version: (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`): containerd version: 1407cab509ff0d96baa4f0eb6ff9980270e6e620.m, runc version: v1.0.3-0-gf46b6ba2, init version: de40ad0
- OS (e.g. from `/etc/os-release`): Manjaro Linux Qonos 21.2.2
- 
[test.yaml.txt](https://github.com/kubernetes-sigs/kind/files/8020584/test.yaml.txt)

**Comment by BenTheElder** [comment]
i think you will find the same bug in `minikube --vm-driver=docker`, the problem is with nested containers we can't enforce resource limits. https://github.com/kubernetes-sigs/kind/issues/877

this is a known limitation, and is not trivial to fix. kind is not suitable for testing this sort of thing, unfortunately.

further, if you add additional notes, the host resouces will be over reported (duplicated for each node). see https://github.com/kubernetes-sigs/kind/issues/877 and linked issues from there.

**Comment by victor-sudakov** [comment]
@BenTheElder no, I'm running this same manifest  in Minikube v1.24.0 with the docker driver, and the container consumes just about 150Mi while the limit in the manifest is 512Mi. The problem is not in enforcing the limits, it's with the container going amok under Kind.

**Comment by BenTheElder** [comment]
this sounds like https://github.com/kubernetes-sigs/kind/issues/2597

I cannot just this moment. will revisit.

**Comment by victor-sudakov** [comment]
I thought my Kind config could be useful:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: office
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.88.63:5000"]
      endpoint = ["http://192.168.88.63:5000"]
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8081
        protocol: TCP
  - role: worker
  - role: worker
```
