### ISSUE TITLE
How to expose Public IP in cloud server

### ISSUE THREAD

**Issue by hxcGit** [kubernetes-sigs/kind#2641]
I use `kind` to create a kubernetes cluster in my cloud server and I want to connect this cluster in my local machine. Since the public IP cannot be seen inside the cloud server, I use `0.0.0.0` instead. However, the certificate is not valid for my public server IP. How can I expose my cloud server's Public IP?

Here is my kind-config yaml:
```shell
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "0.0.0.0"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
```

The error I met :
`Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 172.18.0.4, 0.0.0.0, not x.x.x.x`
`x.x.x.x` is the public IP.

**Comment by aojea** [comment]
you can use a kubeadm patch in your configuration to add a new hostname or IP to the apiserver certificate

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# add my-hostname to apiServer cert SANS
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
```

**Comment by hxcGit** [comment]
> you can use a kubeadm patch in your configuration to add a new hostname or IP to the apiserver certificate
> 
> ```
> kind: Cluster
> apiVersion: kind.x-k8s.io/v1alpha4
> # add my-hostname to apiServer cert SANS
> kubeadmConfigPatchesJSON6902:
> - group: kubeadm.k8s.io
>   version: v1beta2
>   kind: ClusterConfiguration
>   patch: |
>     - op: add
>       path: /apiServer/certSANs/-
>       value: my-hostname
> ```

Thank you very much. I didn't expect you to respond so quickly. Your reply solved my problem perfectly.

**Comment by crazygit** [comment]
above not work on kind version 0.20.0

here is the config method

```
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        certSANs:
          - my-hostname
```
