### ISSUE TITLE
Random syntax error when configuration file is provided

### ISSUE THREAD

**Issue by iblancasa** [kubernetes-sigs/kind#2642]
**What happened**:
I have this configuration YAML file:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.22.1@sha256:fae9a58f17f18f06aeac9772ca8b5ac680ebbed985e266f711d936e91d113bad
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```
Sometimes, kind fails while parsing it:
```sh
/usr/local/bin/kind create cluster --config kind-1.22.yaml
/usr/local/bin/kind: 3: Syntax error: newline unexpected
```
I provide exactly the same file other times, and everything works.

**Environment:**

- kind version: (use `kind version`): kind v0.11.1 go1.16.4 linux/amd64
- Running on GitHub actions using `ubuntu-20.04`

I'm trying to instrument `kind` to find where the problem is located but it is not easy since it happens randomly (and only in the GitHub Actions CI). It would be nice if the error provides more information about what is wrong with the syntax or something.
