### ISSUE TITLE
kind should return non-zero exit code when `kind create cluster --wait` times out

### ISSUE THREAD

**Issue by chrishiestand** [kubernetes-sigs/kind#2654]
**What happened**: 

 ```bash
kind create cluster --config=./cluster/kind-config.yaml --name delme --wait 5m
```

```
Creating cluster "environment-controller" ...
 • Ensuring node image (kindest/node:v1.19.11) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.19.11) 🖼
 • Preparing nodes 📦 📦   ...
 ✓ Preparing nodes 📦 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
 • Joining worker nodes 🚜  ...
 ✓ Joining worker nodes 🚜
 • Waiting ≤ 5m0s for control-plane = Ready ⏳  ...
 ✗ Waiting ≤ 5m0s for control-plane = Ready ⏳
 • WARNING: Timed out waiting for Ready ⚠️
```
And an exit code of 0 is returned. This means that our CI build fails in non-intuitive ways - it should fail earlier when the kind cluster fails to start correctly.

Here is the kind-config.yaml:
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729
  - role: worker
    image: kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729
```

This issue is caused by source code:
https://github.com/kubernetes-sigs/kind/blob/21d6d4d00c332fd90bc38632b32d84a9e13647e5/pkg/cluster/internal/create/actions/waitforready/waitforready.go#L91

**What you expected to happen**:

A non-zero exit code is returned

**How to reproduce it (as minimally and precisely as possible)**:

This is hopefully not necessary since it's plain from reading the source code that this is the current behavior of kind.

But if you want to reproduce I'm not entirely sure. I am having a problem in my env where kind clusters do not create successfully if a kind cluster has already been created within that VM, and then deleted. I believe something like non-namespaces sysctls are being set during the first cluster creation, which then prevents the second kind cluster from coming up later. But this is a topic for another issue, and I'm not sure how to reproduce it at will.

**Anything else we need to know?**:

Do you agree that a wait timeout should return a non-zero exit code? If you agree, I'd be happy to submit a PR as this looks like a fairly trivial fix. 

If you disagree, what's the rationale?

**Environment:**

- kind version: (use `kind version`): 0.10.0 (also a problem in main) 
- Kubernetes version: (use `kubectl version`): 1.19.11, 1.20.7
- Docker version: (use `docker info`): ??
- OS (e.g. from `/etc/os-release`): ??
