### ISSUE TITLE
Automatically inherit host's dcoker daemon registry mirrors configuration to the cluster

### ISSUE THREAD

**Issue by felipecrs** [kubernetes-sigs/kind#2664]
**What would you like to be added**:

Kind to inherit the registry mirror configuration for Docker Hub, which can be found from the `docker info`. Example:

```console
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.0)
  compose: Docker Compose (Docker Inc., v2.3.0)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 [...]
 Registry Mirrors:
  https://dockerhubmirror.internal.company.com/
 Live Restore Enabled: false
```

Then, kind could apply it automatically to containerd configuration. This is how it can be done manually:

```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

# Setup DockerHub mirror
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://dockerhubmirror.internal.company.com"]
```

**Why is this needed**:

Because kind is often used in CI, and in CI often we don't have control about the environment where it runs. If I run kind in network X I want the registry to be used (because of docker hub's rate limit), but in network Y I do not want it to use the registry mirror (because, for example, it does not have access to).

So, I can't hardcode this information in git. But my hosts are configured with the proper registry mirror. Inheriting it automatically would streamline the process.
