### ISSUE TITLE
Deploying onto a remote docker host

### ISSUE THREAD

**Issue by Danny-m08** [kubernetes-sigs/kind#2680]
Hi,

I am running docker on my local workstation and trying to get KIND running on a remote docker engine via DOCKER_HOST. I am able to provision the cluster but running into a few issues connecting to it. here is what I have tried:

1. Deploying with the default config. This exposes the cluster on 127.0.0.1 which is not accessible from my workstation
2. Deploying with custom config which sets the apiserver ip to "0.0.0.0". Once i overwrite my kubeconfig to have the IP or hostname of the server I am able to reach the cluster but then receive certificate error **Unable to connect to the server: x509: certificate is valid for [some list of IPs] and not [server IP]**
3. Deploying with custom config and setting apiserver ip to the server IP. This results in the following error: **failed to get random host port for port mapping: listen tcp [Some IP]:0: bind: cannot assign requested address**

Any suggestions on how I can deploy a cluster from my workstation onto the remote docker engine and be able to connect to it from my workstation?

**Comment by aojea** [comment]
https://kind.sigs.k8s.io/docs/user/configuration/#api-server

set apiServerAddress to 0.0.0.0

**Comment by Danny-m08** [comment]
Hi @aojea Thanks for the suggestion. As mentioned in the post I tried this option but was unable to connect successfully as I received x509 certificate error **Unable to connect to the server: x509: certificate is valid for [some list of IPs] and not [server IP]**

**Comment by aojea** [comment]
oohh, right, sorry, I just read too fast, you have to patch kubeadm with your server addresses

```
- role: control-plane
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
      certSANs:
        - "server_ip_here"  
```

**Comment by negz** [comment]
I happened to hit this today. I'm on MacOS, with my default Docker context being:

```console
$ docker context inspect mael
[
    {
        "Name": "mael",
        "Metadata": {
            "Description": "Virtual Machine via Tailscale"
        },
        "Endpoints": {
            "docker": {
                "Host": "ssh://negz@mael",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/negz/.docker/contexts/meta/b1d04b906a71131b1a2f17f029f7203b083ae8965cf7dd036fc9c4465c826a90",
            "TLSPath": "/Users/negz/.docker/contexts/tls/b1d04b906a71131b1a2f17f029f7203b083ae8965cf7dd036fc9c4465c826a90"
        }
    }
]
```

As mentioned in this issue, it's possible to get this working using the following config:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
nodes:
  - role: control-plane
    image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
      certSANs:
        - "mael"
```

This is great, and definitely livable, but I think two things would make it feel just as if Docker were exposing ports on localhost:

1. Let me make this config the default so I don't have to include `--config` every time. :) Probably a separate issue.
2. Let me specify a separate addr for the API server to expose itself on (`0.0.0.0`) from what is in my generated kubeconfig.

Without 2, `kind` either generates me a kubeconfig that doesn't work (as below) or I need to specify a specific IP to bind to.

```console
$ kind create cluster --config $HOME/.kube/kind.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.23.4) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
$ kubectl cluster-info --context kind-kind

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 0.0.0.0:60875 was refused - did you specify the right host or port?

$ sed -Ibak 's/0.0.0.0/mael/' ~/.kube/config
$ kubectl cluster-info --context kind-kind
Kubernetes control plane is running at https://mael:60875
CoreDNS is running at https://mael:60875/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
