### ISSUE TITLE
Make external load balancer config optional

### ISSUE THREAD

**Issue by pablochacin** [kubernetes-sigs/kind#269]
Presently, if multiple `control-plane` replicas are specified, it is mandatory to specify an `external-load-balancer` node in the configuration. However, this node configuration can have only one replica and the `image` parameter is optional, therefore, it would be trivial for the `create cluster` command to provide the necessary values for launching an external load-balancer if needed.

Forcing to have the `external-load-balancer` node specification seams more a convenience for maintaining a consistent configuration format (a developer convenience) than a user convenience. 

Therefore, it would be convenient for users to have the external load-balancer defined by default if multiple control plane are defined, making the node configuration necessary only if the defaults need to be overridden (e.g. change the `image`).

**Comment by neolit123** [comment]
i will have a stab at this today.
/assign
/kind design
/priority important-soon

**Comment by neolit123** [comment]
but the `image` field is valid if we want to support a custom LB, i guess?

**Comment by pablochacin** [comment]
Actually the only reason not to remove the node definition is to been able to specify the load balancer. However, this could be a cluster parameter lile `load-balancer-image`

**Comment by BenTheElder** [comment]
I think we should nest it at least like this so we can add other load balancer fields under a subsection if necessary later:
```yaml
kind: Config
nodes:
  - ...
# optional with defaulting, applies to the control plane LB if one will be provisioned
loadBalancer:
  image:  ...
```
But you could also imagine more generally setting some control plane details:
```yaml
kind: Config
nodes:
  - ...
# optional with defaulting, controls control plane details in general
controlPlane:
  # perhaps later we add a field like:
  # address: "127.0.0.1:6443"
 # optional with defaulting, applies to the control plane LB if one will be provisioned
  loadBalancer:
    image:  ...
```
