### ISSUE TITLE
etcdserver: read-only range request ... took too long (...) to execute

### ISSUE THREAD

**Issue by erichorwath** [kubernetes-sigs/kind#2692]
**What happened**:
Slow etcd in Kind control-plane slowing down complete helm instal / kubectl apply.
Etcd logs contain lots of errors of such type: 
```
2022-03-16 12:20:25.445202 W | etcdserver: read-only range request "key:\"/registry/helm.toolkit.fluxcd.io/helmreleases/istio-system/istio\" " with result "range_response_count:0 size:5" took too long (1.088797682s) to execute
```

**What you expected to happen**:
No etcd error

**How to reproduce it (as minimally and precisely as possible)**:
Startup Kind, check the etcd pod logs.

**Anything else we need to know?**:
We could reproduce this behavior in all our scenarios, which are mainly two:
- running on my 32GB laptop (in my case WSL2, see below)
- running inside a Kubernetes cluster, in a Docker-in-Docker-pod (see also https://github.com/kubernetes-sigs/kind/issues/303 ), even when using the fasted available VMs and biggest premiumSSDs the hyperscaler offers, we still see the same error. For me, it doesn't look like a DinD issue, but a problem related to Kind.

**Environment:**
- kind version: tested on v0.12.0 and v0.11.1 
- Kubernetes version:  node version:  kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6 and kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
- Docker version: (use `docker info`):  Docker 20.10.11 (WSL2) and docker:20.10.12-dind (DinD)
- OS (e.g. from `/etc/os-release`): tested on WSL2-Ubuntu20.04LTS and Alpine Linux v3.15 (DinD)

**Workaround:**
Run etcd in memory (tmpfs) resolves the etcd error messages and helm install timeouts: https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-1061353323 
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  etcd:
    local:
      dataDir: /tmp/etcd
```
See https://github.com/kubernetes-sigs/kind/issues/845#issuecomment-1061353323 or https://github.com/knative-sandbox/net-contour/pull/444/
