### ISSUE TITLE
etcd listen-metrics-urls with control plane IP address instead localhost

### ISSUE THREAD

**Issue by jverger** [kubernetes-sigs/kind#2695]
**What would you like to be added**:

Default value of **etcd** `listen-metrics-urls` is :
`--listen-metrics-urls=http://127.0.0.1:2381` in the file `/etc/kubernetes/manifests/etcd.yaml`

some other parameters in the same file are defined with the following format:
```
--advertise-client-urls=https://<kind control plane IP address>:2379
--initial-advertise-peer-urls=https://<kind control plane IP address>:2380
--initial-cluster=kind-control-plane=https://<kind control plane IP address>:2380
--listen-peer-urls=https://<kind control plane IP address>:2380
```

I'm able to set `--listen-metrics-urls=http://<kind control plane IP address>:2381`  in the file during cluster creation with `ClusterConfiguration`

```
  - |
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          listen-metrics-urls: http://<kind control plane IP address>:2381 
```
unfortunately it's not very confortable because kind control plane IP address is dependant of my docker bridge network.

is it possible to set directly `--listen-metrics-urls=http://<kind control plane IP address>:2381` in the file like some other parameters defined earlier ?

**Why is this needed**:
This configuration will help to setup `kube-prometheus-stack` helm chart out of the box for prometheus etcd target.

Regards
