### ISSUE TITLE
could not resolve host error (etcd)

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/kind#2698]
**What happened**:
I try to setuo `etcd` with the `kind`, but hit error in the pod of `etcd`,  like that:
```
2022-03-30 00:35:37.230475 I | etcdmain: etcd Version: 3.4.0
2022-03-30 00:35:37.230513 I | etcdmain: Git SHA: 898bd1351
2022-03-30 00:35:37.230523 I | etcdmain: Go Version: go1.12.9
2022-03-30 00:35:37.230527 I | etcdmain: Go OS/Arch: linux/amd64
2022-03-30 00:35:37.230532 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-03-30 00:35:37.230616 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/tls.crt, key = /etc/kubernetes/pki/etcd/tls.key, trusted-ca = /etc/kubernetes/pki/root/tls.crt, client-cert-auth = true, crl-file =
2022-03-30 00:35:37.231594 I | embed: name = etcd-0
2022-03-30 00:35:37.232186 I | embed: data dir = /var/lib/etcd/data
2022-03-30 00:35:37.232198 I | embed: member dir = /var/lib/etcd/data/member
2022-03-30 00:35:37.232202 I | embed: heartbeat = 100ms
2022-03-30 00:35:37.232206 I | embed: election = 1000ms
2022-03-30 00:35:37.232210 I | embed: snapshot count = 100000
2022-03-30 00:35:37.232220 I | embed: advertise client URLs = https://etcd-0.etcd:2379
{"level":"warn","ts":1648600537.2996814,"caller":"netutil/netutil.go:121","msg":"failed to resolve URL Host","url":"https://etcd-0.etcd:2380","host":"etcd-0.etcd:2380","retry-interval":1,"error":"lookup etcd-0.etcd on 10.96.0.10:53: no such host"}
{"level":"warn","ts":1648600538.4467804,"caller":"netutil/netutil.go:121","msg":"failed to resolve URL Host","url":"https://etcd-0.etcd:2380","host":"etcd-0.etcd:2380","retry-interval":1,"error":"lookup etcd-0.etcd on 10.96.0.10:53: no such host"}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
This is my yamls of `etcd`:
```
    statefulset:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: etcd
      spec:
        replicas: 1
        revisionHistoryLimit: 10
        serviceName: etcd
        selector:
          matchLabels:
            component-name: etcd
        # etcd will not be updated, unless it is deleted
        updateStrategy:
          type: OnDelete
        template:
          metadata:
            labels:
              component-name: etcd
          spec:
            subdomain: etcd
            containers:
            - name: etcd
              image: virtualcluster/etcd-v3.4.0
              imagePullPolicy: Always
              command: 
              - etcd
              # pass the pod name(hostname) to container for composing the advertise-urls args
              env:
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name 
              args:
              - --name=$(HOSTNAME)
              - --trusted-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --client-cert-auth 
              - --cert-file=/etc/kubernetes/pki/etcd/tls.crt
              - --key-file=/etc/kubernetes/pki/etcd/tls.key
              - --peer-client-cert-auth 
              - --peer-trusted-ca-file=/etc/kubernetes/pki/root/tls.crt
              - --peer-cert-file=/etc/kubernetes/pki/etcd/tls.crt
              - --peer-key-file=/etc/kubernetes/pki/etcd/tls.key
              - --listen-peer-urls=https://0.0.0.0:2380 
              - --listen-client-urls=https://0.0.0.0:2379
              - --initial-advertise-peer-urls=https://$(HOSTNAME).etcd:2380
              # we use a headless service to encapsulate each pod
              - --advertise-client-urls=https://$(HOSTNAME).etcd:2379
              - --initial-cluster-state=new
              - --initial-cluster-token=vc-etcd
              - --data-dir=/var/lib/etcd/data
              # --initial-cluster option will be set during runtime based on the number of replicas
              livenessProbe:
                exec:
                  command: 
                  - sh
                  - -c
                  - ETCDCTL_API=3 etcdctl --endpoints=https://etcd:2379 --cacert=/etc/kubernetes/pki/root/tls.crt --cert=/etc/kubernetes/pki/etcd/tls.crt --key=/etc/kubernetes/pki/etcd/tls.key endpoint health
                failureThreshold: 8
                initialDelaySeconds: 60
                timeoutSeconds: 15
              readinessProbe:
                exec:
                  command: 
                  - sh
                  - -c
                  - ETCDCTL_API=3 etcdctl --endpoints=https://etcd:2379 --cacert=/etc/kubernetes/pki/root/tls.crt --cert=/etc/kubernetes/pki/etcd/tls.crt --key=/etc/kubernetes/pki/etcd/tls.key endpoint health
                failureThreshold: 8
                initialDelaySeconds: 15
                periodSeconds: 2
                timeoutSeconds: 15
              volumeMounts:
              - mountPath: /etc/kubernetes/pki/etcd
                name: etcd-ca
                readOnly: true
              - mountPath: /etc/kubernetes/pki/root
                name: root-ca
                readOnly: true
            volumes: 
            - name: etcd-ca
              secret:
                defaultMode: 420
                secretName: etcd-ca
            - name: root-ca
              secret:
                defaultMode: 420
                secretName: root-ca
    # etcd will be accessed only by apiserver from inside the cluster, so we use a headless service to 
    # encapsulate it
    service:
      apiVersion: v1
      kind: Service
      metadata:
        name: etcd
        annotations:
          service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
      spec:
        type: ClusterIP
        clusterIP: None
        selector:
          component-name: etcd
```
and I create my cluster with this defination:
```
export CLUSTER_NAME="virtual-cluster" && \
kind create cluster --name ${CLUSTER_NAME} --config - <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
- role: worker
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
- role: worker
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
- role: worker
  image: kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c
EOF
```

**Anything else we need to know?**:
Seems the `coredns` not work or not work as expected.

I test with latest release version of `kind`: v0.12.0
after hit the error, I changed the version of `kindest/node`, that's my test result:
| Version | Is work |
| ------- | --------|
| kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9 | NOT |
| kindest/node:v1.22.7@sha256:1dfd72d193bf7da64765fd2f2898f78663b9ba366c2aa74be1fd7498a1873166  | NOT |
| kindest/node:v1.21.10@sha256:84709f09756ba4f863769bdcabe5edafc2ada72d3c8c44d6515fc581b66b029c  | WORKS |
| kindest/node:v1.16.15@sha256:64bac16b83b6adfd04ea3fbcf6c9b5b893277120f2b2cbf9f5fa3e5d4c2260cc | WORKS |

So, any idea?

**Environment:**

- kind version: (use `kind version`):
   kind v0.12.0 go1.18 linux/amd64
- Kubernetes version: (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}`

- Docker version: (use `docker info`):
  Docker version 20.10.14, build a224086

- OS (e.g. from `/etc/os-release`):
  NAME="Ubuntu"
  VERSION="20.04.3 LTS (Focal Fossa)"
