### ISSUE TITLE
[PODMAN] kind cluster creation fails on podman using Debian 11; identified a workaround to prevent clusterfail.

### ISSUE THREAD

**Issue by debuggerboy** [kubernetes-sigs/kind#2706]
Kind cluster creation failed on Podman (rootful) using Debian GNU/Linux 11 :

Kind to create multi-node cluster without errors on Podman using Debian:

Steps to Reproduce:

I am using kind 0.12.0 on Debian 11.

I have a kind config yaml file : 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "SetHostnameAsFQDN": true
networking:
  ipFamily: ipv4
  kubeProxyMode: "iptables"
nodes:
- role: control-plane
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
- role: worker
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
- role: worker
  image: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
```

I am trying to create a kind cluster on debian 11 using podman 3.0.1 using below command.

```
sudo kind create cluster --name ko2 --config /home/debuggerboy/labs/kubernetes/anish-kind/multi-node.yaml
```

The above command takes a lot of time and then fails with below error:

Full Error : https://gist.github.com/debuggerboy/e7ec918dd984cdbe9e8c1963393d2fe2#file-kind-sigs-cluster-creation-error-txt

Additional details with regards to this error:

After hours of debugging and mutiple attempts, I was able to prevent the kind cluster from failing.

I created an inject script : https://gist.github.com/debuggerboy/e7ec918dd984cdbe9e8c1963393d2fe2#file-podman-fix-for-cluster-fail-sh

I execute the above inject script a few seconds after the kind create cluster is invoked.

This will prevent the kind cluster on podman from failing.

**Environment:**

- kind version: `kind v0.12.0 go1.17.8 linux/amd64`
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 127.0.0.1:46667 was refused - did you specify the right host or port?
```
- Docker version: not applicable
- Podman version:
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 05:30:00 1970
OS/Arch:      linux/amd64
```
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Please see : https://gist.github.com/debuggerboy/e7ec918dd984cdbe9e8c1963393d2fe2

Note: I am not having much experience in kubernetes, please kindly ignore if this report does not qualify as a bug. My apologies

Thanks
debuggerboy

**Comment by aojea** [comment]
can you try using the node image that is published with that release?

https://github.com/kubernetes-sigs/kind/releases/tag/v0.12.0

**Comment by debuggerboy** [comment]
Hello @aojea 

Thank you for the reply, I have used the node image `1.23.4` from the [page](https://github.com/kubernetes-sigs/kind/releases/tag/v0.12.0) you suggested.

I am currently using: `kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9`

Please see my yaml file:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "SetHostnameAsFQDN": true
networking:
  ipFamily: ipv4
  kubeProxyMode: "iptables"
nodes:
- role: control-plane
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
- role: worker
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
- role: worker
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
```

but, I am still getting the same error : https://gist.github.com/debuggerboy/0bb774772921f8ee342ea82eb4a77ab7#file-kind-sigs-podman-debian-error-txt

I was able to confirm that the work-around "inject.sh" script is still capable of prevent the kind cluster from failing even with node image `"kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9"` image

See:

![Kind Cluster Creation with workaround Inject.sh](https://gist.githubusercontent.com/debuggerboy/0bb774772921f8ee342ea82eb4a77ab7/raw/3124f57b5be5b7b28aae4a99722e2556af10e9aa/workaround-inject-sh.png)

Thanks

**Comment by BenTheElder** [comment]
Can you please minimize the reproducer? For example does it fail without setting any feature gates?  Does it fail with only a single node?

Also I am confused by the screenshot where it appears to work.

You can remove the networking: section of config, ipv4 and iptables are default.

**Comment by debuggerboy** [comment]
@BenTheElder 

sorry for the confusion, let me explain.

The screenshot is to prove that the `kind create cluster` only works when the `"inject.sh"` is run along side the `kind create cluster` command.

If I am to leave the `kind create cluster` command run on its own (i.e. with out the `"inject.sh"` hack) the it fails with below error:
https://gist.github.com/debuggerboy/0bb774772921f8ee342ea82eb4a77ab7#file-kind-sigs-podman-debian-error-txt

let me know if my explanation was useful.

Let me try to run the cluster with a single node. I will share my findings here.

Thanks

**Comment by debuggerboy** [comment]
@BenTheElder 

As per your instruction. I modified my yaml file, as below:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "SetHostnameAsFQDN": true
networking:
  ipFamily: ipv4
  kubeProxyMode: "iptables"
nodes:
- role: control-plane
  image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
```

With a single node cluster the create cluster is working successfully.

```
debuggerboy@cassandra:~$ sudo kind create cluster --name ko2 --config /home/debuggerboy/labs/kubernetes/anish-kind/anish-multi-node.yaml
enabling experimental podman provider
Creating cluster "ko2" ...
 ✓ Ensuring node image (kindest/node:v1.23.4) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-ko2"
You can now use your cluster with:

kubectl cluster-info --context kind-ko2

Have a nice day! 👋
debuggerboy@cassandra:~$
```

So, the `kind create cluster` is only failing when we re trying to create a multi-node kind cluster with rootful podman.

@BenTheElder : when the multi-node kind cluster creation is in progress and we are to run the below `"inject.sh"` script:

https://gist.github.com/debuggerboy/e7ec918dd984cdbe9e8c1963393d2fe2#file-podman-fix-for-cluster-fail-sh

This workaround script can prevent the multi-node kind cluster from failing, I believe there seems to be an issue with kubedns
The workaround script is basically injecting the IPv6 and hostname to `"/etc/hosts"` file on all kind nodes.

Thanks,
