### ISSUE TITLE
K8s Service of type NodePort failed to open tcp port on kindest/node:v1.23.4

### ISSUE THREAD

**Issue by smalnote** [kubernetes-sigs/kind#2722]
**What happened**:
cannot assign port when create k8s service of type NodePort
service.yml
`
kind: Service
metadata:
  name: nginx-hello-service
  namespace: myspace
spec:
  type: NodePort
  # .... omit rest
`
k8s control-plane event report a kube-proxy warning:
kube-proxy  can't open port "nodePort for ... "

**What you expected to happen**:
expose service port to localhost

**How to reproduce it (as minimally and precisely as possible)**:
Follow the quickstart: https://kind.sigs.k8s.io/docs/user/quick-start/
Using node image of version kindest/node:v1.23.4, create a k8s service of type NodePort

**Anything else we need to know?**:
Switch to older version node image like kindest/node:v1.22.7 or kindest/node:v1.20.7 solve the problem.
So might be a bug introduce by version kindest/node:v1.23.4.

**Environment:**

- kind version: (use `kind version`):
  kind v0.12.0 go1.17.8 linux/amd64
- Kubernetes version: (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-03-06T21:07:35Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
- Docker version: (use `docker info`):
 Server Version: 20.10.11
- OS (e.g. from `/etc/os-release`):
CentOS Linux release 8.2.2.2004 (Core)

**Comment by BenTheElder** [comment]
Can you please include the full configurations you used? This is not reproducible as-is.

**Comment by BenTheElder** [comment]
this may be https://github.com/kubernetes/kubernetes/pull/107413

**Comment by smalnote** [comment]
ok, i delete my cluster and reproduce the senario  with node image kindest/node:v1.23.4.

```
# my-kind-cluster.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
```

kind create cluster --name=mycluster --config=my-kind-cluster.yml

```
# myspace.namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: myspace
```

kubectl apply -f myspace.namespace.yml

```
# nginx-hello.deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  namespace: myspace
  labels:
    app: nginx-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx-hello
        image: docker.io/nginxdemos/hello:plain-text
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
```

kubectl apply -f nginx-hello.deployment.yml

```
# nginx-hello.service.yml
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-service
  namespace: myspace
spec:
  type: NodePort
  selector:
    app: nginx-hello
  ports:
  - port: 80
    targetPort: 80
```

kubectl apply -f nginx-hello.service.yml

kubectl describe node mycluster-control-plane

Got a warning event: 
```
Type     Reason                                            Age    From        Message
  ----     ------                                            ----   ----        -------
  Warning  listen tcp4 :31625: bind: address already in use  6s     kube-proxy  can't open port "nodePort for myspace/nginx-hello-service" (:31625/tcp4), skipping it
```

I didn't specify a nodePort service spec, so it might not be the 'duplicate port' problem.

The waning gone after switch node image version to kindest/node:v1.22.7.
