### ISSUE TITLE
crictl images --digest does not display digests in the Kind node

### ISSUE THREAD

**Issue by deevroman** [kubernetes-sigs/kind#2734]
I upload the docker image using:

`kind load docker-image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0`

After that, I go to the Kind node:

`docker exec -it kind-control-plane bash`

And I execute:
```
root@kind-control-plane:/# crictl images --digests
IMAGE                                                 TAG                  DIGEST              IMAGE ID            SIZE
...
k8s.gcr.io/etcd                                       3.5.1-0              <none>              25f8c7f3da61c       98.9MB
k8s.gcr.io/ingress-nginx/kube-webhook-certgen         v1.0                 <none>              17e55ec30f203       48MB
k8s.gcr.io/kube-apiserver                             v1.23.4              <none>              0e16468a4aa36       79.6MB
....
```

And for all images, the DIGEST column contains only <none>

Why?

**Comment by BenTheElder** [comment]
`kind load` uses containerd's `ctr images import`. I guess it isn't producing a digest of the manifest when images aren't pulled. The docker-image command uses `docker save`.

**Comment by deevroman** [comment]
Do I understand correctly, if I create a sub in which the image is specified with a digest, then it will not be able to pull together only from outside?

<details>
<summary>pod.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pull-test
spec:
  containers:
  - name: net
    image: k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0@sha256:f3b6b39a6062328c095337b4cadcefd1612348fdd5190b1dcbcb9b9e90bd8068
    imagePullPolicy: IfNotPresent
```

</details>
