### ISSUE TITLE
Could not load image due to "Command Output: ctr: image might be filtered out"

### ISSUE THREAD

**Issue by alemis-pl** [kubernetes-sigs/kind#2772]
Hello, 

I've diagnosed a problem with loading images to my K8s cluster.  I'm using command `kind load docker-image my-image:local` and ouput of this command is: 

`Image: "my-image:local" with ID "sha256:b6933fd6aeb1d6531c4d26a37ca41884adef85dd09f900276d22bee827a194c9" not yet present on node "kind-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import --snapshotter overlayfs -" failed with error: exit status 1
Command Output: ctr: image might be filtered out`

Environment:

- MacOs Monterey 12.3.1, Apple M1 Pro
- kind version 0.13.0
- Docker version 20.10.14, build a224086 - installed as Docker Desktop

I'm creating cluster using kind and commands:

`kind create cluster --config "${BASE_DIR}"/kind-cluster-config.yml`
`kubectl config set-context kind-kind`
`kubectl cluster-info --context kind-kind`

kind-cluster-config.yml:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32101
        hostPort: 8081
```

What could be a problem?

Best
