### ISSUE TITLE
New way to change the cluster.local default domain deployed with kind

### ISSUE THREAD

**Issue by kluevandrew** [kubernetes-sigs/kind#2774]
I need to change "cluster.local" dns domain to something else, after some attempts i found #1466 issue, but seems it's not working now.

I've tried next config, but node stuck in NotReady state:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-a
networking:
  disableDefaultCNI: true
  podSubnet: 10.201.0.0/16
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        ---
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        networking:
          dnsDomain: "kind-a.cluster.local"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=4Gi,cpu=4
```

Any body knows how to fix it?
