### ISSUE TITLE
Cannot receive datas via UDP  

### ISSUE THREAD

**Issue by NilWil** [kubernetes-sigs/kind#2785]
**What I want to achieve:**
I want to deploy Chirpstack: https://github.com/JohnRoesler/chirpstack-kubernetes 

**What is the problem: **
The gateway component in a LoRaWAN network send datas via UDP to port 1700, so the gateway-bridge deployment have to listen to port 1700. But no data arrives to the corresponding pods. 

**What have I done: **
I created a multi node kind cluster with two worker and one control plane with: 

```
extraPortMappings:
- containerPort: 1700
    hostPort: 1700
    protocol: UDP
```

on the control plane. So I assume the control plane docker container will listen on port 1700 and forward the data to any pod which container listen to port 1700 via UDP. 

Follow the instructions from John Roesler to deploy Chirpstack. The logs of the gateway bridge are: 

time="2022-05-12T11:45:04Z" level=info msg="starting ChirpStack Gateway Bridge" docs="https://www.chirpstack.io/gateway-bridge/" version=3.9.2
time="2022-05-12T11:45:04Z" level=info msg="backend/semtechudp: starting gateway udp listener" addr="0.0.0.0:1700"
time="2022-05-12T11:45:04Z" level=info msg="integration/mqtt: connected to mqtt broker"

**What I use:**
My laptop is an MacBook Pro with macOS Monterey and an Apple M1 Pro Chip. 

I found beside a  UDP listener on Docker Hub: mendhak/udp-listener for testing and also test it on a Debian but with no success. For the sake of simplicity I list the K8s objects with which I think I should receive UDP messages with: nc -u localhost 5005 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-listener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udp-listener
  template:
    metadata:
      labels:
        app: udp-listener
    spec:
      containers:
      - image: mendhak/udp-listener
        name: listener
        ports:
        - containerPort: 5005
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-service
spec:
  type: NodePort
  ports:
    - name: udp-listener
      port: 5005
      targetPort: 5005
      protocol: UDP
  selector:
    app: udp-listener
```

and do the extra port mapping for port 5005 with protocol UDP as well. How can I receive UDP data in a kind multi node cluster? 

I'm new on K8s, Docker and especially kind and I hope this kind of issue is allowed to mention here. 

Any hints will be greatly appreciated.
