### ISSUE TITLE
Changing Kubernetes version documentation incomplete.

### ISSUE THREAD

**Issue by ScionOfDesign** [kubernetes-sigs/kind#2792]
The `kind` documentation uses the following as an example of changing the Kubernetes version:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: 
- role: control-plane 
- role: worker
  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
```

However, this configuration can lead to `kind` using a different version of Kubernetes for the control-plane. This causes an error when attempting to join the worker nodes.
The following configuration works instead:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: 
- role: control-plane
  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
- role: worker
  image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
```
