### ISSUE TITLE
Azuredisk Dynamic Provisioning from a Kind Cluster with the CSI disk.csi.azure.com driver.

### ISSUE THREAD

**Issue by syldej** [kubernetes-sigs/kind#2794]
Hi all,

With this kind configuration on a single VM :
```
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
    protocol: TCP
  extraMounts:
  - containerPath: /mnt/disks/localpv
    hostPath: /mnt/local-storage-provisioner/localk8sstorage
EOF
```

Trying to attach Azuredisk Dynamic Provisioning :  ref here https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md

The Persistent Volumes are well created on Azure in the correct ResourceGroup, but not possible to attach it to the POD.

* logs from the POD:
```  
Warning  FailedAttachVolume  4s (x5 over 13s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-56e6cb6f-c03e-421b-b0ed-462a1404e1aa" : rpc error: code = NotFound desc = failed to get azure instance id for node "kind-control-plane" (instance not found)
```
Somebody knowns how to make it work please ?

Thanks,
Kind regards,
