### ISSUE TITLE
Applying node-role labels causes crash

### ISSUE THREAD

**Issue by christianh814** [kubernetes-sigs/kind#2817]
**What happened**:

Trying to add the node label `node-role.kubernetes.io/worker=""` using `kubeadmConfigPatches` causes the kubelet in the node to crash. Using other key/values work however (e.g. `foo=bar` works)

**What you expected to happen**:

I expect the kubelet to apply the node label

**How to reproduce it (as minimally and precisely as possible)**:

run `kind create cluster --config=config.yaml` with the following 

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: True
  podSubnet: "10.254.0.0/16"
  serviceSubnet: "172.30.0.0/16"
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=''"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: 0.0.0.0
  - containerPort: 443
    hostPort: 443
    listenAddress: 0.0.0.0
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=''"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/worker=''"

```

**Anything else we need to know?**:

I've tested this on `kindest/node:v1.23` and `kindest/node:v1.24`

**Environment:**

- kind version: (use `kind version`):  `kind v0.14.0 go1.18.2 linux/amd64`
- Kubernetes version: (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}`
- Docker version: (use `docker info`): `20.10.17`
- OS (e.g. from `/etc/os-release`): `Fedora release 36 - Linux laptop 5.18.6-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 22 13:46:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
