### ISSUE TITLE
Can't use cluster ip in pod, but can use pod ip?

### ISSUE THREAD

**Issue by huanghantao** [kubernetes-sigs/kind#2834]
reproduction:

```bash
uname -a
Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:03:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba2c931
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```yaml
# config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.20.2
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 36443
```

```bash
kind create cluster --config=config.yaml
```

```yaml
# nfs-server.yaml
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: nfs-server
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        app: nfs-server
    spec:
      initContainers:
        - name: init-container
          image: busybox:1.28
          command: ["sh", "-c", "mkdir -p /exports"]
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
            - name: udp-111
              containerPort: 111
              protocol: UDP
      volumes:
        - name: nfs-vol
          emptyDir: {}
```

```bash
kubectl apply -f nfs-server.yaml

kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)            AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP            45m
nfs-server   ClusterIP   10.96.249.28    <none>        2049/TCP,111/UDP   41m
```

```bash
kubectl get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP            NODE                         NOMINATED NODE   READINESS GATES
nfs-server-7885c7c6b-vxkth          1/1     Running   0          42m   10.244.0.17   test-cluster-control-plane   <none>           <none>
```

```bash
# service's endpoints are correct
kubectl describe svc nfs-server
Name:              nfs-server
Namespace:         default
Labels:            app=nfs-server
Annotations:       <none>
Selector:          app=nfs-server
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.249.28
IPs:               10.96.249.28
Port:              tcp-2049  2049/TCP
TargetPort:        2049/TCP
Endpoints:         10.244.0.17:2049
Port:              udp-111  111/UDP
TargetPort:        111/UDP
Endpoints:         10.244.0.17:111
Session Affinity:  None
Events:            <none>
```

```bash
kubectl exec -it nfs-server-7885c7c6b-vxkth -- sh
/ # echo hello >> exports/test.txt
/ # mkdir test
# use cluster ip to mount, failed
/ # mount -t nfs 10.96.249.28:/ test
^C
# use pod ip to mount, success
/ # mount -t nfs 10.244.0.17:/ test
/ # cat test/test.txt
hello
```

Can you tell me why that is?
