### ISSUE TITLE
OOM 

### ISSUE THREAD

**Issue by mikelo** [kubernetes-sigs/kind#2848]
**What happened**:

I wanted to deliberately create a pod that would go "out of memory" but it seems to run fine.
**What you expected to happen**:
the pod should switch to status "OOMKilled" right after starting

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
kubectl patch deployment metrics-server -n kube-system -p '{"spec":{"template":{"spec":{"containers":[{"name":"metrics-server","args":["--cert-dir=/tmp", "--secure-port=4443", "--kubelet-insecure-tls","--kubelet-preferred-address-types=InternalIP"]}]}}}}'

```
apply the following deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkilled
  template:
    metadata:
      labels:
        app: oomkilled
    spec:
      containers:
      - image: gcr.io/google-containers/stress:v1
        name: stress
        command: [ "/stress"]
        args: 
          - "--mem-total"
          - "104858000"
          - "--logtostderr"
          - "--mem-alloc-size"
          - "10000000"
        resources:
          requests:
            memory: 1Mi
            cpu: 5m
          limits:
            memory: 20Mi
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
kind v0.14.0 go1.18.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.25.0-alpha.0.881+7c127b33dafc53
- Docker version: (use `docker info`):
$ docker version 
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:59 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:39 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- OS (e.g. from `/etc/os-release`):
cat /etc/redhat-release 
Fedora release 36 (Thirty Six)
