### ISSUE TITLE
If a cluster is defined with all nodes being control-planes, nothing can be scheduled

### ISSUE THREAD

**Issue by joejulian** [kubernetes-sigs/kind#2857]
With no qualifiers as to the type of node in [this check](https://github.com/kubernetes-sigs/kind/blob/b975bbb6590ded2e0c644b2d6e6132631e6b8598/pkg/cluster/internal/create/actions/kubeadminit/init.go#L112), a cluster built with this configuration has all nodes tainted:

```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
```

I would expect that if the nodes are all control planes, we would still remove the taints so workloads could be run on the control-plane nodes.
