### ISSUE TITLE
Add static manifests URL to config 

### ISSUE THREAD

**Issue by hikhvar** [kubernetes-sigs/kind#2862]
**What would you like to be added**:

For some demos, I have some KIND clusters with tools like metallb and and ingress controller preinstalled. I mostly use the manifests as in the [loadbalancer](https://kind.sigs.k8s.io/docs/user/loadbalancer/) documentation. It would be really cool, if I could create some kind config like this:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
manifests:
  - metallb.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```

**Why is this needed**:
This would allow me to drop some extra shelll scripts around the kind cluster creation
