### ISSUE TITLE
Issue certificate to `host.docker.internal`

### ISSUE THREAD

**Issue by skhaz** [kubernetes-sigs/kind#2878]
**What would you like to be added**:
I want the certificate issued on `kind-control-plane` to be issued to `host.docker.internal` too; with this, I can use it with docker-compose

**Why is this needed**:
In my docker-compose file, I have this line

```yaml
extra_hosts:
  - "host.docker.internal:host-gateway"
```

With this, I can connect to kind. However, the certificate is issued to `localhost`; with this change, other people will be able to use docker-compose along with Kind.

The error

```shell
app-1       | panic: Get "https://host.docker.internal:33345/apis/apps/v1/namespaces/argo/deployments": x509: certificate is valid for kind-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not host.docker.internal
```

**Comment by BenTheElder** [comment]
There’s past discussion of this in the tracker, will circle back to this later. in the meantime you can add additional host names yourself (sample config in past discussions)

**Comment by skhaz** [comment]
I could not find it. Could you please give an example @BenTheElder?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/issues/566#issue-448597863 (though drop the `version` field from the sample patch there, it's not necessary as the certSAN field is stable in kubeadm and v1beta1 is not used in current Kubernetes realases)

**Comment by skhaz** [comment]
Thank you

**Comment by skhaz** [comment]
For reference

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: host.docker.internal
```
