### ISSUE TITLE
Exposing kubernetes ingress to host machine running KinD on Windows and WSL2 using extraPortMappings doesn't work

### ISSUE THREAD

**Issue by Dunge** [kubernetes-sigs/kind#2889]
I'm using KinD on Windows via Docker Destop running on WSL2 and trying to set up the ingress to expose port on my host machine.

I followed the guide and installed the cluster with the config as shown here: https://kind.sigs.k8s.io/docs/user/ingress/, along with Ingress NGINX controller (from helm) and a custom Ingress ressource redirecting to my service with the proper classname.

```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 5180
    protocol: TCP
  - containerPort: 443
    hostPort: 51443
    protocol: TCP
```

If I kubectl port-forward to the ingress service, **it works fine** and I can access service website.

But I'm unable to access directly it via the `hostPort` setting set on the cluster config without port-forward (http://localhost:5180). KinD doesn't seem to attribute an external-ip to the ingress controller, it remains in `<Pending>` state.

Is this supposed to be functioning or am I missing something here?
Any idea why and how to diagnose further? Thanks!

```
pod/ingress-nginx-controller-6bf7bc7f94-2r74v                   1/1     Running     0             15h
service/ingress-nginx-controller                         LoadBalancer   10.96.1.208     <pending>     80:30674/TCP,443:30800/TCP              15h
service/ingress-nginx-controller-admission               ClusterIP      10.96.103.184   <none>        443/TCP                                 15h
my-ingress   nginx   *                 80      16h
```

**Comment by Aryan-Deshpande** [comment]
@Dunge I think specifying the type LoadBalancer for a service, they are used for external cloud provider LoaderBalancers like GCP/Azure/AWS that's why your 'IP' is still pending. You either have to set up service type NodePort or setup an Ingress resource. Please correct me if I am wrong. Can you share the yml file for further diagnosis?.

**Comment by Dunge** [comment]
@Aryan-Deshpande My own services are exposed as NodePort. The only one that shows up as LoadBalancer is the [ingress-nginx-controller](https://kubernetes.github.io/ingress-nginx) installed via [their own Helm chart](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx). I also have an ingress resource set up to with the goal to forward external requests to my services, but you need an ingress controller for that to work, hence the installation of nginx (as explained in the guide I linked above).

Anyway, since opening this ticket, I dropped KinD in favor of microk8s. This one have a "plugin" that  you enable that install it's own ingress controller. I find it strange that it needs a special custom ingress controller resource and not one solution that works on all infrastructure the same way (as I thought ingress-nginx would), but at least it's functional.

**Comment by BenTheElder** [comment]
Sorry, none of the maintainers use Windows and were a bit dependent on input from others for this platform.

I don't know enough about WSL2 networking quirks.

**Comment by aojea** [comment]
> But I'm unable to access directly it via the `hostPort` setting set on the cluster config without port-forward (http://localhost:5180). KinD doesn't seem to attribute an external-ip to the ingress controller, it remains in `<Pending>` state.

that is confusing but not relevant, you access the Service using the NodePort, that uses the container IP, most probably you don't have connectivity to the nodes/containers IPs

**Comment by aojea** [comment]
🤔 your config doesn't match the example we have in the documentation

```
  extraPortMappings:
  - containerPort: 80
    hostPort: 5180
    protocol: TCP
  - containerPort: 443
    hostPort: 51443
    protocol: TCP
```

are the ingress pods exposing the continer ports on 51443 and 5180?

**Comment by Dunge** [comment]
@aojea based on the names I would expect "containerPort" to be the port exposed inside the KinD docker, so inside the cluster, so the ones exposed by the ingress pods. While "hostPort" would be the one I want to open on the host machine, the one running the KinD container (my Windows host). Isn't that what that mean?Are they supposed to be the inverse? I just selected different ports because the host already have 80/443 mapped to another process (IIS). As per my first comment, I try to access the cluster from the extern using localhost:5180. But no, the ingress controller expose to the normal 80/443 internally.

**Comment by BenTheElder** [comment]
> @aojea based on the names I would expect "containerPort" to be the port exposed inside the KinD docker, so inside the cluster, so the ones exposed by the ingress pods. While "hostPort" would be the one I want to open on the host machine, the one running the KinD container (my Windows host). Isn't that what that mean?

Yes that's correct, containerPort is the port inside the node container and hostPort is on the host where the container is running.

**Comment by aojea** [comment]
oh, forgive me, I read it the other way around,

**Comment by icrdr** [comment]
I had the same issue. The ingress-nginx-controller installed via their official manifest (https://kubernetes.github.io/ingress-nginx/deploy/#quick-start). I fixed this issue by using the manifest provided in the kind doc https://kind.sigs.k8s.io/docs/user/ingress/#using-ingress. 
```shell
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```
As it said in the doc 
> The manifests contains kind specific patches to forward the hostPorts to the ingress controller, set taint tolerations and schedule it to the custom labelled node.
Hope it works for your situation.

**Comment by martijnvdp** [comment]
got it working with the normal helm chart and these values:
```
                controller:
                  extraArgs:
                    publish-status-address: localhost
                  hostPort:
                    enabled: true
                  publishService:
                    enabled: false
                  service:
                    type: NodePort
                  tolerations:
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/master
                      operator: Equal
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/control-plane
                      operator: Equal
                  watchIngressWithoutClass: true
                  nodeSelector:
                    ingress-ready: "true"
                    kubernetes.io/os: linux                 
```
