### ISSUE TITLE
Cannot use v1beta3 for patch within ClusterConfiguration for kind 0.14

### ISSUE THREAD

**Issue by andrejusc** [kubernetes-sigs/kind#2895]
**What happened**:
Following this example code:
https://github.com/kubernetes-sigs/kind/blob/v0.14.0/pkg/internal/apis/config/encoding/testdata/v1alpha4/valid-kind-patches.yaml#L16
I was trying to change version from `v1beta2` to already available `v1beta3` as I'm using kindest nodes of v1.23.6.

And so my snippet looks like such now:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane

kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta3
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: my-hostname
```
but after kind cluster (I've named it `test123`) is created - I'm checking presence of certSANs setting via such command:
```
kubectl --context kind-test123 get cm kubeadm-config -n kube-system -o yaml
```
and part of output is such (note such entry in output - `kubeadm.k8s.io/v1beta3`):
```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
      extraArgs:
        authorization-mode: Node,RBAC
        runtime-config: ""
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
...
```
If in my original snippet I change back version to `v1beta2` - then after creation of kind cluster - I could normally see my-hostname entry:
```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
      - my-hostname
      extraArgs:
        authorization-mode: Node,RBAC
        runtime-config: ""
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
...
```

**What you expected to happen**:
Expected to see presence of my-hostname in certSANs list

**How to reproduce it (as minimally and precisely as possible)**:
See yaml snippet above

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.14.0
- Kubernetes version: (use `kubectl version`): 1.23.6
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`): Linux amd64
