### ISSUE TITLE
Kind fails to startup when mounting /sys/fs/cgroup

### ISSUE THREAD

**Issue by NDStrahilevitz** [kubernetes-sigs/kind#2923]
**What happened**:
Tried to run kind with local cgroups mounted (/sys/fs/cgroup). Ran kind as following:
`kind create cluster --config kind-config.yaml`
with the following `kind-config.yaml` file:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /sys/fs/cgroup
      containerPath: /sys/fs/cgroup
      readOnly: true
```
I have received the following error log:
```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.24.0) 🖼
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

**What you expected to happen**:
That `kind` would start up as usual.

**How to reproduce it (as minimally and precisely as possible)**:
Described above.

**Anything else we need to know?**:
My environment is using full cgroupv2.

**Environment:**

- kind version: (use `kind version`): kind v0.14.0 go1.18.2 linux/amd64
- Kubernetes version: (use `kubectl version`): Client Version: v1.25.0
- Docker version: (use `docker info`): 20.10.18
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.1 LTS
