### ISSUE TITLE
Is there any way to add permissions to the Kind clusters and the pods that run within it

### ISSUE THREAD

**Issue by faizanbashir** [kubernetes-sigs/kind#2930]
My requirement is that I need to run a Pod with elevated permissions, specifically the `NET_ADMIN` permission. I have added it in the Kubernetes deployment file, but the functionality is failing nevertheless. The `securityContext` looks something like this:

```yaml
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            add: ["NET_ADMIN"]
```

The Kind cluster config is given below:

```yaml
kind create cluster --image kindest/node:v1.23.6 --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

Is there any way to make it work in Kind?
