### ISSUE TITLE
Cannot create kind cluster with --config flag

### ISSUE THREAD

**Issue by aliabbasjaffri** [kubernetes-sigs/kind#2959]
**What happened**:
I am trying to make my kind environment declarative and creating a kind config to create my cluster. Cluster creation with `--config` consistently fails, whereas without it succeeds.

**What you expected to happen**:
Kind cluster should be able to create with config provided to it.

**How to reproduce it (as minimally and precisely as possible)**:
The config that i am creating:

```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.25.14@sha256:6e0f9005eba4010e364aa1bb25c8d7c64f050f744258eb68c4eb40c284c3c0dd
- role: worker
  image: kindest/node:v1.25.14@sha256:6e0f9005eba4010e364aa1bb25c8d7c64f050f744258eb68c4eb40c284c3c0dd
- role: worker
  image: kindest/node:v1.25.14@sha256:6e0f9005eba4010e364aa1bb25c8d7c64f050f744258eb68c4eb40c284c3c0dd
```

the command that i'm using:

```bash
~ ❯❯❯ kind create cluster --config .kind/kind-v1.25.2.yml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.14) 🖼
 ✗ Preparing nodes 📦 📦 📦
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 
```bash
~ ❯❯❯ kind version
kind v0.16.0 go1.19.1 darwin/arm64
```
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
```bash
~ ❯❯❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.124-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 9.718GiB
 Name: docker-desktop
 ID: D3KZ:YKVP:6HJT:GUDW:DEVL:ZG44:RA7T:QRKA:YHN2:YHLK:GZZT:LPAT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`): macOS Monterey M1 macbook pro

https://github.com/kubernetes-sigs/kind/issues/2959#tasklist-block-5e9d2b70-5ebf-4f5b-b83b-5f91cb124c65
