### ISSUE TITLE
Trouble accessing ingress through the host browser

### ISSUE THREAD

**Issue by caniko** [kubernetes-sigs/kind#3005]
Using nginx-ingress, I created an Ingress for both K8ssandra and my API with 127.0.0.1.nip.io as host; however, http://127.0.0.1:30080/api fails to resolve my API. It works with port-forwarding, so it must be my ingress that is wrongly setup. I am using terraform.

One for my fastapi deployment:
```yaml
apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: service-http-ingress
    namespace: ${var.module_k8_namespace}
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
  spec:
    ingressClassName: nginx
    rules:
      - host: 127.0.0.1.nip.io
        http:
          paths:
            # Auth
            - path: /api/*
              pathType: Prefix
              backend:
                service:
                  name: ${var.fastapi_service_name}
                  port:
                    number: 8000
```

Along with another for k8ssandra:
```yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: service-http-ingress
    namespace: ${var.module_k8_namespace}
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
  spec:
    ingressClassName: nginx
    rules:
      - host: 127.0.0.1.nip.io
        http:
          paths:
            # Auth
            - path: /v1/auth.*
              pathType: Prefix
              backend:
                service:
                  name: k8ssandra-cluster-dc1-stargate-service
                  port:
                    number: 8081
            # GraphQL
            - path: /graphql-schema|/graphql/.+|/files/.+|/playground
              pathType: Prefix
              backend:
                service:
                  name: k8ssandra-cluster-dc1-stargate-service
                  port:
                    number: 8080
            # REST, Document
            - path: /v2.*
              pathType: Prefix
              backend:
                service:
                  name: k8ssandra-cluster-dc1-stargate-service
                  port:
                    number: 8082
```

I am using:
```yaml
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 3${cluster_id}080
    protocol: TCP
  - containerPort: 30443
    hostPort: 3${cluster_id}443
    protocol: TCP
  - containerPort: 30942
    hostPort: 3${cluster_id}942
    protocol: TCP
```
Where `cluster_id` is 0
