### ISSUE TITLE
Feature gate ValidationAdmissionPolicy on 1.26 doesn't work

### ISSUE THREAD

**Issue by samos123** [kubernetes-sigs/kind#3029]
**What happened**:
control plane failed to start

**What you expected to happen**:
k8s cluster up and running with validationadmissionpolicy working

**How to reproduce it (as minimally and precisely as possible)**:
1. Create cluster.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ValidatingAdmissionPolicy": true
nodes:
- role: control-plane
  image: kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352
- role: worker
  image: kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352
```

2. Create kind cluster `kind cluster create --config cluster.yaml`

**Anything else we need to know?**:

Note it works fine if I remove the featureGates

**Environment:**

- kind version: (use `kind version`):  kind v0.17.0 go1.19.4 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.25.5
- Docker version: (use `docker info`): 20.10.21
- OS (e.g. from `/etc/os-release`):  Archlinux

**Comment by samos123** [comment]
Closing the bug I had to also include `runtimeConfig: "admissionregistration.k8s.io/v1alpha1": true`  for this to work.

This was a working cluster yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ValidatingAdmissionPolicy": true
runtimeConfig:
  "admissionregistration.k8s.io/v1alpha1": true
nodes:
- role: control-plane
  image: kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352
- role: worker
  image: kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352
```

**Comment by BenTheElder** [comment]
So, also as a general rule, alpha features are not guaranteed to work on any given cluster. 

For example there's a snapshot feature that requires CRI functionality that is not in containerd yet at any released version ...

Usually it's something in Kubernetes, not KIND 🙃 

PS you are unlikely to need a dedicated worker node with two nodes like this, I would do:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ValidatingAdmissionPolicy": true
runtimeConfig:
  "admissionregistration.k8s.io/v1alpha1": true
nodes:
- role: control-plane
  image: kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352
```

With a single node, kind will ensure that node is schedulable. Nodes do not have fully isolated resources. Multi-node is useful for developing Kubernetes HA functionality or other multi-node behaviors.
