### ISSUE TITLE
Error in configuration: context was not found for specified context: kind-kind

### ISSUE THREAD

**Issue by bestofman** [kubernetes-sigs/kind#3034]
This is my `skaffold.yaml` file:

    apiVersion: skaffold/v2alpha3
    kind: Config
    deploy:
      kubeContext: kind-kind
      kubectl: 
        manifests:
          - ./infra/k8s/*
    build:
      local:
        push: false
      artifacts:
        - image: learnertester/auth
          context: auth
          docker:`
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: learnertester/ticketing-client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: '**/*.js'
                dest: .
        - image: learnertester/tickets
          context: tickets
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: learnertester/orders
          context: orders
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: learnertester/expiration
          context: expiration
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: learnertester/payments
          context: payments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .

When I try `kubectl config view` I get this result:

     
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: DATA+OMITTED
        server: https://192.168.1.2:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: DATA+OMITTED
        client-key-data: DATA+OMITTED

I have also installed `kind` and created a cluster with that. this is the result of `kubectl cluster-info --context kind-kind` :

```
Kubernetes control plane is running at https://127.0.0.1:41887
CoreDNS is running at https://127.0.0.1:41887/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

However when I run `skaffold dev` I get this error at the end:

     - Error in configuration: context was not found for specified context: kind-kind
    WARN[0480] deployer cleanup:kubectl delete: exit status 1  subtask=-1 task=DevLoop
    unable to connect to Kubernetes: getting client config for Kubernetes client: error creating REST client config for kubeContext "kind-kind": context "kind-kind" does not exist

I tried to remove `kubeContext: kind` from the `skaffold.yaml` file and add the context inside the `/.skaffold/config` file instead of that, as following:

    global:
      local-cluster: true
      survey:
        last-prompted: "2022-12-18T12:20:01-08:00"
      collect-metrics: true
      update:
        last-prompted: "2022-12-18T12:30:37-08:00"
    kubeContexts: [kind-kind]

But still I get:

    WARN[0000] Could not load global Skaffold defaults. Error encounter while unmarshalling the contents of file "/home/a/.skaffold/config"  subtask=-1 task=DevLoop
    WARN[0000] error retrieving insecure registries from global config: push/pull issues may exist...  subtask=-1 task=DevLoop
    getting run context: getting cluster: unmarshalling global skaffold config: yaml: unmarshal errors:
      line 8: cannot unmarshal !!str `kind-kind` into config.ContextConfig

**Comment by BenTheElder** [comment]
kind creates contexts named `kind-$name`, where the default name is `kind`. the `kind-` prefix is a common pattern that avoids collisions with other cluster tools.

I don't use skaffold, but you need to make sure the KUBECONFIG file it is reading is the one kind wrote to.

You can explicitly set that with the KUBECONFIG env or `--kubeconfig` flag the same as kubectl, or else it has the same default as kubectl, which is `$HOME/.kube/config`.

You can debug which contexts are available by using kubectl instead of skaffold.

**Comment by BenTheElder** [comment]
one way there would be different paths is executing under different users (e.g. root with `sudo` and some non-root user without `sudo`).

**Comment by bestofman** [comment]
> one way there would be different paths is executing under different users (e.g. root with `sudo` and some non-root user without `sudo`).

Thank you for your answer. At the moment I tried a lot of things that I found on the internet and don't know which of them added some kind settings to my `/.kube/config` file and it's like the following at the moment:
```

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhOVEF4TWpVeE4xb1hEVE15TVRJeE1qQXhNalV4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzhOCktaa2VpN1NCNXlybXJLQVNzL1UvMXpGZ0MraE1tQ3JPRTVTSnNjZDB2S3E1M3R4cjl6ZFczOEtVOGZXL0NLZjYKNGJOSG82NVhQS3NhQ3loeC92SGhFSm81ZGlRdVBuYjI3eDFtRlFjbjJ6NkhGb3UzWEwxb1JmRFF3QnR3bnpqawpLSnZzT2M3QzZuZEt2SkI3Y3Nzc20wVmp1VmJEVTBMeHBxL0pmUDNSL2Y0ZW5ONUJvS2ErVUpvWnZYU1VZYTEzCm1kcVg5YlBFYlJRWklJS2FmQmsyLzBOSk4zRHhwUGNyM0w5ZE44WVNpK1hmWDlxZGpGTGVVdTlsM0VETklGU2MKc0thUjVkY3VjdW4wVVB6em85MGh1VnJQb1UzbllTQ0JEVExWTmYwMlpYbFQ0R3dUVUdoVWlvWUNiLzB6SHNBcApHN2oxOSs4dHo5bUZ5Vk5ud2trQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNcHJpam92MkFaL3JzWjdnc3lBQjZ4cnpBcGxNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQWNBOUJaVk16ckZKN2cxRGJWYQpDOVhyMEV4RjFVQTVFbEN5eVkvV2puTlU2eUNyTHh1UVY3b1FFQU5JK1VlbEdyWjM1WFRhUnpBdm1FbzVjdmVkCmhZWkdnN2MvVWg2WTBjNFVWVUN4WWJDVUtNUG5tOHBiNkdIZUJPYVNzUVVxWE5WUW10NHFyMUxzY1JlTzlZTGUKb29ERzhVb042UVNwS2ovMU1LWEYyUjhvbEtmWjRlR09wMS9yWnRqamdwWkRkWFNEZGJHUWxrdFA0V04xR2p0dApmN0I1R2JGdDI1YlNsUGYzOGZvaEtKM2hpNDByS0ZPNGFidkI3MXdiL1ZzTnNCcStsenhPQVUxY2J3VXYwelF2CnlWZ3o4bml2d1VXd1JMZTNpTjJwd1FUMVBwLzJJMW8yd3NWZnU2alZ4M0NpOXc2RG5NbXJBRjhqTG1aSkFZMmEKb25JPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.2:6443
  name: kubernetes
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1USXhPVEF4TVRrd09Wb1hEVE15TVRJeE5qQXhNVGt3T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWJmCllrYTNOTlpMd1ZtS2h1NnhNaC9JZTFESnV2bGxmcVNGdU0xdGxyNXJ4MGRMWkFUaDhRWlBjVE9pL3BvYkhBU0sKOUR2V0E2RE5xOFBOYmdFN1B4USs1NjRieFlyQWxTLzZjNjZNL2d5b2dEc0syakEvSFczRUdROEp4Mk12aTZPQwpBUnFENEdaY2NWWVhxbzh2d0xsVWF1OHAraWR4UGo5QXlxS0c1RWlxSisyeHNzTU9EU21rczlnS1lOWGxVcDY5CkMvMVRvMHJzb1BoT2dtN2h6T0VLelE4SE1saTl5Wmo2ME9pZTlISjJ0dElNRUhsZjd5Q0VHQk10ekVIS3hIN1cKT0dHT2kwQlFFSVJmZTZ6b3BMZ0dVV3NNWVBxaVYwQzN2TlNtbDh3ODBSSFpIZHFaQUNleW11TWQ2QXUxVm14QQpzekNabUNRaS9lVVhQMHFLUVZrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJVm5Icjg3Y1BsUklvZ2w1NytXb1JwZ09UaDFNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXRDREhhYTVRUXV2S3Z4OW9oMwpOZUJOWTlCZTlYY3ZLTmUrc0dvUENxVVJLd0dOM1g3QUxLNG9FcG1OaWNKT0Q5VWsxL2pSVDRQRTlWbTlBMUx1CjlzbHZ5U2E5OG85ay8rWFJJdC9PVjNhdjd6bDYvYUJUbGRBbG96bHhOVnB5NmR6bWtVa1pIYlpibDlhZ3c3RkoKbld3U3RYejBIK3BOZDVqYVJEdlpyOWZEUFM4dHlUVjlldzI3aDFZYmhGZG5NRlk3dTRRNTNYSjU1Z2k0WkZRbApVaGRUTVFxMGE5Z2tyTFFYV1lheHFOZXh4QXMzdlNJUDJQMGg3bW1ldjJLbXFsN0pRcWRZajU3Q3J0Q1Ntc0FPCm9sK2RNem5sdjJDRXFDaFVqdHpCTU1TanY2WXVyM2lId3Btb01FWmpON3NScHRzclRVM2dLQkFOOGhCTnJyOGcKanMwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:41887
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJVkhtYWJrQ0RlRzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpFeU1UVXdNVEkxTVRkYUZ3MHlNekV5TVRVd01USTFNVGxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZZNWg5c05Lckx5OElOMmoKTEtDVnA1OUZsTitXV3diNjlTMG1wS0RxR3NaNXB2MnBsY3RxbkJNbVB6RUg2QmRtb2hMYWFBUnNyNWR1eHBsMQpCbVJHam1ZZWZlQXpEdEpzeEJNYWw4UXkyR1JaQThNMUMwZW5YSVJHVkJGZWJHSHk4cmZvZEhxeGdTUVJldHJhClczRE5rZDZFdkhuMWJwT1E2VlFhV0liQ3A5QzVWT0IveDFSZFhXWXBMM0tTVWdXTlV6ancvaUhTZWFqWG9KOUQKZmVRQzBoNWF5THpJY3N2YVo1UG9vTkhaYm80NUhVMnJrQ25TNjNMNmhNdkhIcE1ubS81NjJxdUhZc3ZsL1VOeQpWbVdZUE5VYmNiU3NuUHgyemdpa1ZaUjFtdTU5cHFPQWNncG5MWHY0M0dmYWYvT25YN08wcWN0R0g4ZUN0Tko0CkdCenh5d0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JUS2E0bzZMOWdHZjY3R2U0TE1nQWVzYTh3SwpaVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBakZaQmhMVzBMeHFDUCtIVFdDY3dRRVdFRE1xY0hkN09TOWlECkNCS2VVRHI5RDJ0YXNlSDlqRy9HN2lEYmRDT0J2bnhSNHRKUkJZckYrK0toSEVwZytkZ05ZSWdtSnVkcGYrcy8KL2lTN1V3NndrM2FsOWloTmJjMkh4UnNhSmo0NUNVWTBSMnpuaXdPcjRRS3BmZUpWSmc0Z3JyM1dkQTRnQW1XNApqeVROa3R0U0tHM08zUTNSL0VxUURUUzA3RmdIUiswaklUbWN0WWVsN2JETDJXT2k1cHowaUsyL0prWDdBdUpXCjlLUU4yY2tCcjdTcGRYbjlsZkNJOGlsMFkwWElaZ3lURllGaXBoc1dLRUxHWXpEVGJwZnRpV29EdERqQU9LWGsKa3ZVcUtJWDQ1RjdOY3FKNko5WmE1dng0MFo4MnFJYlo4c1Z0cG5UT2ZBMkFVakZQYWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdlk1aDlzTktyTHk4SU4yakxLQ1ZwNTlGbE4rV1d3YjY5UzBtcEtEcUdzWjVwdjJwCmxjdHFuQk1tUHpFSDZCZG1vaExhYUFSc3I1ZHV4cGwxQm1SR2ptWWVmZUF6RHRKc3hCTWFsOFF5MkdSWkE4TTEKQzBlblhJUkdWQkZlYkdIeThyZm9kSHF4Z1NRUmV0cmFXM0ROa2Q2RXZIbjFicE9RNlZRYVdJYkNwOUM1Vk9CLwp4MVJkWFdZcEwzS1NVZ1dOVXpqdy9pSFNlYWpYb0o5RGZlUUMwaDVheUx6SWNzdmFaNVBvb05IWmJvNDVIVTJyCmtDblM2M0w2aE12SEhwTW5tLzU2MnF1SFlzdmwvVU55Vm1XWVBOVWJjYlNzblB4MnpnaWtWWlIxbXU1OXBxT0EKY2dwbkxYdjQzR2ZhZi9Pblg3TzBxY3RHSDhlQ3ROSjRHQnp4eXdJREFRQUJBb0lCQUczdC8rUXl0OERicDZMTAp4cERnQkVwMHRNNjBxQ2JjTW5nem1pQ0piWnJmbGJlQmpuTGZ5RkVCVGdJQnRsc2tEeEpaS3E1K09tWE94YUNKCmFIT3ZmYmVoZzNkdXFVMmtQUTJ0SXBQM1phRlcrTVNVMWROWDE3aHd3YlNKYWlBaTRkbGZUSUVZa282WlUwWFQKWENVQmswWlFMTng5UWhmQm5wMmlkN0QxWGpnaGRKU2JnYnhreGpxWTFZc0RVWVhuS3VaR1UydUgvQ08wZDFxVgpVZ1JzSmFIR3kxRHp0b2YrQUdFWFA1ZUdGY1cvWlF6a0tsaGs2TUxRejljSEs1SFF4WlErSHAvSCtscXcxOHVHCklHUkh5Sms2TWF5dlBQUDRwNEdZby9jS2FDcWE4YW1HV016RFJyL0g2U0N4VlJLNmx3Q0ZjVGd1QS9Bc2M4bXAKUzFkM1Zia0NnWUVBOENESVNDSk1yR2hFQnJVdTN2THhORjNDaTlIME5GYmhkbUg2c0ZzV1IyNm9GdmxJSGdxZgpwcEhMczNlQjlUUGFIaktXSU9oQ3RmbmpGSlpSc0sxZ1NTd0FqaVpFUE9QVWU0eXNsQ1BqZnI2Qng5dmZXRDFvCmVGV3BVelY2MWdYaFRRUk8xUjVaU25GeE52QjUzYWRzclR2dUMxUFdIQlVPZFcvdkZFZHIzYzBDZ1lFQXloWGYKRWZrZEpZeGVEQUkzZmYyQ2VCdW0zZHl1a1BoSG80ZUg4QXExaytlcVhUZ0Jhby9vdkhkVXk1Yk81V0haaDQydQo4Z1g3NUM4K0xXeWZCWXlrM0F2VjVWWXMwemVwZlFPZFUvVzJJOEJ2MDFPb0dJR0R3OFpFd1RBUG15dWEzV1J6CllhT0NHZDFpc3JqV1JmQ3RPVUlnWU5mUmlEZkJKRHlhVjZBWXRmY0NnWUVBeEpheUlZd2pKWXIvRmxiREZyZmkKalRLdGtYYkQ3UTJyN0JWdS9XNjFJS29SWnkyU3d6V0RXd1ZGdFpvRGhWRjhJdmpiTy9tcWsvME8wYzMyOXlRYQpEZzIrTHFKWmYxZ3VueStlSW5IM1Q4NTd4Ym5XY2hGa05CQTlYZWdNdHFkOXVtWHFmRVFxYWUzUitGNk1CdEdKCkFaSnM0azB5bnk4RjlWTThjbWUrZ1lrQ2dZRUFta3BxbnpsWTFKTkFOdUQyWjE1SDM5WVU2QzJXcHA2NWE1U04KNkdyMHliRkY5SmhQRklJOWlxOTljVmQ2TGM0d25IdERpQXVqajB1MnFFM1hlQkF5eXNMS2s2ZmczMzhQQzZEWAozUU9zQmMzbVV5MzdHSUxDREpaelppQ0F1ZE5vRVFLaHlYbGlXc2NabFNUa2pFKytvZ25uMktqT2xMY2s0cnJXCmlISjJpMjhDZ1lFQXVTTGhreU1MbXNuSlgxZW1uc0NVeWZpUmxSdVVuYXhyLzkxRU5FdEY2ekFEbk9jaTZITS8KWDJTSVhxY1pwZmtMWkplU1JCaW42WWphamZ2MVk1Z1FXcVVlZHJsM2hLRHg0bkgrN2ExZ2U1MnBFTDRWcGRmTQo5S2Q1ekF2dHpObFJhcmJ6REhmSGg4bERuUzZQMzFWaWZoOHdnRmtUa0lFQnhETW5sbWpqSkVZPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
- name: kind-kind
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJUVF3UFNmYmJHa0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpFeU1Ua3dNVEU1TURsYUZ3MHlNekV5TVRrd01URTVNVEZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNVeFpReDluampuYnhOMjIKVmlZbHhoT1VIdVlzTjFSZU9wRFFzQ05OdnJwNG5uT1N2RUszcE1BQ2k3YzdKWFZTQjdFKytXM2xPbitXYzRWNgpwYTI0ZVFxVHNwT2l6Rmc4Zy96cUxGT1NrK09DU0NwU3crSWdWSXd2YTM4WituWEtlcHphWlZWY2ptUVVub2NIClk3SWU3UUxYUy90REorT1VQZGNJU01ES3liWjUzMHByRUpSUWFxcmc5aEtPQUlPbUhuWXVtSlIzZzZPb2RBVVUKRXQvYlJvWVhCWmgxejRxOE8vWjJ4YlFMbFB5RUs4RitGTTlENHVhSkFqNVVHRWJtNUVuZWlPMDdINWpKR1hEQgp6S3Fva3NCeUIyWExJZUVRcVZFbUQweUprSFZ4c3lsSVBkZnVqbjgzL1JRclBDMmVFM0w5L0dmZjQvU2wvYUt0CktvbWFGd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTRlp4Ni9PM0Q1VVNLSUplZS9scUVhWURrNApkVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUFF3VVFtYXJhN2p6cWxsYTlnSDBqR2tYdzJmRVdHWVRKTU5SCnh5NnpOb3NvNTNZVGxGZ1lnNjRJREJUVU9JMnJMSVU4eTFvTUVIUEdEUHBiU1M2dkY2eUEwQXRXRnRtdWJlaUMKVUU3bkRvb2N5Z3E4TmRvcFlMMmIvSXZVdUltdHVRdzlsNkJoV3dsZFZJVDBtd3BzVHJMZW9VVHlhODhzcVlDOAo3UjNFaTJ1TGFVbE4weGgxR3l1L3dqK1FHNUttTWhaZW5pUThseHlMSUtrVzkyRDB0b0k4emhVaVRSSjBvWG1ZCklNdHBVdDJkanp6M01CaG1xc3BGajdGV2hjOTRxbjBYb2NzMk9aS1FTSFd2eEV2SHdrY1lRcG9FSGtNZlBWQWcKMGhjKyt6S21ha0EzMHFxVWd1djUyczNUZS9qbExWbmk4N0xWc0pmbUhobW5nUGozRWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBc1V4WlF4OW5qam5ieE4yMlZpWWx4aE9VSHVZc04xUmVPcERRc0NOTnZycDRubk9TCnZFSzNwTUFDaTdjN0pYVlNCN0UrK1czbE9uK1djNFY2cGEyNGVRcVRzcE9pekZnOGcvenFMRk9TaytPQ1NDcFMKdytJZ1ZJd3ZhMzhaK25YS2VwemFaVlZjam1RVW5vY0hZN0llN1FMWFMvdERKK09VUGRjSVNNREt5Ylo1MzBwcgpFSlJRYXFyZzloS09BSU9tSG5ZdW1KUjNnNk9vZEFVVUV0L2JSb1lYQlpoMXo0cThPL1oyeGJRTGxQeUVLOEYrCkZNOUQ0dWFKQWo1VUdFYm01RW5laU8wN0g1akpHWERCektxb2tzQnlCMlhMSWVFUXFWRW1EMHlKa0hWeHN5bEkKUGRmdWpuODMvUlFyUEMyZUUzTDkvR2ZmNC9TbC9hS3RLb21hRndJREFRQUJBb0lCQVFDRExaTUpsNjI5ekU4dgpMRDloSkI1a25FM0dRdFRLSnpFRXNlckZ0NGtwS2J4ZXQvSUVPblMzZjUwaWxISTlkNzAybGN5YkxkVWhZQThICjcrVmJ1ZG00TEx3MHJ3a1BtZVZFWHBkQUxxRlByRS9UWndVUGl6b1NkQm9OdGQrWnNSY2JldndYWjMzd21GbXQKSlFpeG1iTko5d1VtWVlSQmVoOVBWYzc2VFRKODVMcXBCZkZpbEpLZzF6MVVYcWNhdW9JVy9VSUJzZ3A1Q1ViSApVVy82V252QVNJZThhYjRHVkJQdmRBeHpmWkpxOU5FNnJvaDhvY0poTnBwR25rR1JwbHRFTTBuY0NITjRmNGl6Clg1NDNrV1ZHVzgvWjVmR043bmtic3A0aDBCcWg5TWdJUXRFaTArazZ3dVIyaDRpU0NsUWtFSmc4NmhTeDRzY0sKanJkTFNNRlJBb0dCQU1Tc1RaMDZIRWN2bm1kWFlBaUp2RkY2dEtUQ04wbEpJNXdzNHU1TDV6TnlleTBycHNEcwpyMVpZK3dFc01NV1NYWk9VdzZBUFRuZWVSc2xVNkZCdkxNZy91b05yNHpzdFdDY0VMS1pGRDNpbmtCRlNvc2hICjYyTUwzZUFFNWJnMEFrSUdlZVpVdmlTZjdQbE1keWtSMjhqMjNTWHhSN2tINC91b0FhQ3h4ZHh2QW9HQkFPYkgKM0wvd2Njb01VZlZUdWxValpUK0dMWnNERU0rZnR6bTU4bExvYk9VVDJ1UC9JdFNabTZnWU8xdTJFSUI2ZXkrTAp1SmxGTmNxVUtSYWI1UlFZcGhJRmtabHloaHZXb3BnVzRVRmt4aGJ4UlVNMTlzVDV5NUxXRmQrL1F3azFOeWNOCmhmcG9LZEtPSGxvekMyaVhQaGRlTDJNdGovbUU0RXRtc3Z2dnFrRFpBb0dBV0pXL2M5VXJ6WWlPVWIvU1dxWW4KYzQvUWMvR2kwMWlsT0lBalN2QlhXQjMxaTFnQkNSN1NyeEx2SkEwU2ZyczVlUExsMWw5dW1ZUnFIOThsc0swUwp2N09zdit0RmMyOHVLSXpCeTdhSmpHLzAvVWg2VjduRk5WeXYrR3BjU2ticXlYQi9VWmJUK2swcWdQUEhMSEdGCnpKUWM4aTBtZ0Jva3YwSmlVVTRoYi9NQ2dZRUFqZGhBQlRVckswMmhQbEZsRUprOXpPcVNzMWtTQnhzYXlmOVIKUXNZYTBENEE1dXZWSTZqNk5Eb1ltY2p3b1pjbWlkV3Q4MzdIamlpOGpHbnJSZ3ZVWHZWUFJXcFBwV0twOHlMMAo5bldURDF6aC9tcDNyeC85a05YSEFnd1RqdUJIY3Roc0JibnFJc0U1UktWbEdMY0U4ZVh3NkZ1RHg1QjFMOE1DCnRiamNBeGtDZ1lFQXV3Y2l6YWUyN05SMG5oc085SERIZG1DMUxrbmxYZzJXUVVjZ2hvRi9FZGJaaWcvVEpZRjkKZDg1ZjJUdVJnSDhONTBIcmo3c2orQlJhNnhyQzUxQk1XWDk3aTA5ODR5UHlHbmdvYVoyaUgvcmNhQ1kzRzJ1dgpZYnNPeHVJNkNSaUU4NmNac3pCMTNONFd1RWJhcFRlcVFGR2ZZRXBlVG9yWGZDQ2w5c2Z0Y0FBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

I am not sure if is it a correctly configured file or not?
