### ISSUE TITLE
How do I access etcd container?

### ISSUE THREAD

**Issue by Detoxify92** [kubernetes-sigs/kind#3058]
Hi all,  
I have a simple cluster with the following configuration:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 22
    hostPort: 22
- role: worker
- role: worker
```
I successfully deploy it, and then try to access the ```etcd``` container by doing:
```
kubectl -n kube-system exec etcd-kind-control-plane -it -- sh
```
But I get the following error:
```
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "a22a7843cc56d0d4b6133e0eca2e1404bf80a683ac46aceff9a2f092de46e852": OCI runtime exec failed: exec failed: unable to start container process: open /dev/ptmx: operation not permitted: unknown
```
I get the same error if I try to do it within the control plane container. Any help is much appreciated. 
Kind version:
```
kind v0.17.0 go1.19.2 linux/amd64
```
Docker version:
```
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.4
 Git commit:        3a2c30b63a
 Built:             Tue Dec 20 20:43:40 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.4
  Git commit:       42c8b31499
  Built:            Tue Dec 20 20:42:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323.m
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by aojea** [comment]
is it possible to exec on the etcd containers?

**Comment by Detoxify92** [comment]
AFAIK no, as they are not accessible to docker, but I am not sure. Only the control plane and workers are visible:
```
docker container ls
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS       PORTS                                                               NAMES
493b9566acae   kindest/node:v1.25.3   "/usr/local/bin/entr…"   3 hours ago   Up 3 hours   0.0.0.0:22->22/tcp, 0.0.0.0:80->80/tcp, 127.0.0.1:45361->6443/tcp   kind-control-plane
48aa79b95c90   kindest/node:v1.25.3   "/usr/local/bin/entr…"   3 hours ago   Up 3 hours                                                                       kind-worker
7321dcb31b56   kindest/node:v1.25.3   "/usr/local/bin/entr…"   3 hours ago   Up 3 hours                                                                       kind-worker2
```
There have to be more containers running, but I don't know how to access them.

**Comment by aojea** [comment]
`docker ps` show the node images, the pods are running inside those containers, but IIRC the `etcd` pod image is distroless and you can not exec because of that

**Comment by Detoxify92** [comment]
I see. I just wanted a way to interact with `etcd` using `etcdctl`. Is it possible to do so using kind?

**Comment by aojea** [comment]
https://gist.github.com/aojea/6f17c07251cf9251f66a611d80c6a6f1

**Comment by BenTheElder** [comment]
https://mauilion.dev/posts/etcdclient/ is a post about this, antonio's gist above is based on this.

**Comment by aojea** [comment]
yeah, I've updated the gist with the right source now 😄

**Comment by aojea** [comment]
I think we can close it now

**Comment by rikatz** [comment]
updated version (because I was here)

* sleep is not part of the busybox container anymore, so looping on a "false" response
* updated image version

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: etcdclient
  name: etcdclient
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do false; done
    image: registry.k8s.io/etcd:3.5.21-0
    imagePullPolicy: IfNotPresent
    name: etcdclient
    volumeMounts:
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
      readOnly: true
    - mountPath: /var/lib/etcd
      name: etcd-data
      readOnly: false
    env:
    - name: ETCDCTL_API
      value: "3"
    - name: ETCDCTL_CACERT
      value: /etc/kubernetes/pki/etcd/ca.crt
    - name: ETCDCTL_CERT
      value: /etc/kubernetes/pki/etcd/healthcheck-client.crt
    - name: ETCDCTL_KEY
      value: /etc/kubernetes/pki/etcd/healthcheck-client.key
    - name: ETCDCTL_ENDPOINTS
      value: "https://127.0.0.1:2379"
    - name: ETCDCTL_CLUSTER
      value: "true"
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data

```
