### ISSUE TITLE
unable to attach EBS volume for a self-hosted kind cluster on EC2 instance

### ISSUE THREAD

**Issue by balusarakesh** [kubernetes-sigs/kind#3069]
**`TLDR: for some reason the kind cluster doesn't seem to have access to the block devices attached to the host EC2 instance where the kind cluster is running`**

**What happened**:
 - unable to attach  EBS volume for a self-hosted kind cluster on EC2 instance
 - I've deployed a kubernetes cluster (1.21.14) on an EC2 instance and deployed a pod with persistent volume
 - I can see the volume attached to the EC2 instance on the console, I can see the volume in `lsblk` and I can also see the volume on the kubernetes node 
 - for some reason the csi-driver is not able to find the block device attached to the host EC2 instance

**What you expected to happen**:
 - able to discover block devices attached to host node on a privileged pod

**How to reproduce it (as _minimally_ and precisely as possible)**:
 - run a kind cluster on an EC2 instance with aws-ebs-csi-driver deployed and try to add EBS persistent volume to a pod

**Anything else we need to know?**:
**ebs-csi-node logs**:
```
I0113 06:34:55.015055       1 node.go:510] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0113 06:34:55.016811       1 node.go:112] NodeStageVolume: called with args {VolumeId:vol-00e2c7143ba97550d PublishContext:map[devicePath:/dev/xvdbb] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-a58048ed-eaf2-4dde-b060-3afc4974b96a/globalmount VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Secrets:map[] VolumeContext:map[storage.kubernetes.io/csiProvisionerIdentity:1673589680047-8081-ebs.csi.aws.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0113 06:34:55.016890       1 node_linux.go:82] [Debug] Falling back to nvme volume ID lookup for: "/dev/xvdbb"
I0113 06:34:55.016901       1 node_linux.go:126] [Debug] nvme path "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d" not found
I0113 06:34:55.016909       1 node_linux.go:99] [Debug] error searching for nvme path "nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d": nvme path "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol00e2c7143ba97550d" not found
I0113 06:34:55.016916       1 node.go:164] NodeStageVolume: volume="vol-00e2c7143ba97550d" operation finished
I0113 06:34:55.016922       1 inflight.go:74] Node Service: volume="vol-00e2c7143ba97550d" operation finished
E0113 06:34:55.016926       1 driver.go:120] GRPC error: rpc error: code = Internal desc = Failed to find device path /dev/xvdbb. no device path for device "/dev/xvdbb" volume "vol-00e2c7143ba97550d" found
```

pvc config:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 4Gi
```

pod config:
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: ubuntu:22.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

**screenshots**:
As you can see from the screenshots the volume is clearly attached to the instance(first screenshot) but the privilege pod cannot find it (second screenshot, I re-built the above pod with `privileged: true`)

<img width="1259" alt="Screenshot 2023-01-12 at 10 38 50 PM" src="https://user-images.githubusercontent.com/17168699/212254280-4ee8a591-eb43-481f-a1c0-c009394fe2c2.png">
<img width="688" alt="Screenshot 2023-01-13 at 10 46 28 AM" src="https://user-images.githubusercontent.com/17168699/212395948-1fac8051-ddca-460d-b648-d8f43c0e17c8.png">

**Environment:**

- Kubernetes version
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- AWS EBS CSI Driver version:
helm chart version: `2.15.1`

- kind version: `v0.17.0`
- Runtime info: 
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-1026-aws
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 68.58GiB
 Name: ip-10-19-122-112
 ID: PC3E:BP5A:ZPGH:CC3D:GQDF:NHYX:HGMC:PUM7:NPVD:SDNO:ZW6P:GM5V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

kind command: `kind create cluster --config test-cluster.yaml --image=public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.21.14-eks-d-1-21-22-eks-a-25`

**Comment by aojea** [comment]
the kind cluster runs in a docker container, the pods runs inside the container ... there are several layers of virtualization in between

**Comment by balusarakesh** [comment]
figured it out, I had to mount the `/dev` directory onto control plane and worker nodes like this
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes: 
- role: control-plane
  extraPortMappings:
  - containerPort: 8081
    hostPort: 8081
  extraMounts:
  - containerPath: /dev
    hostPath: /dev
- role: worker
  extraMounts:
  - containerPath: /dev
    hostPath: /dev
```
