### ISSUE TITLE
Support Dynamic Volume Provisioning

### ISSUE THREAD

**Issue by squakez** [kubernetes-sigs/kind#3096]
I am trying to setup a dynamic volume leveraging the default `StorageClass`. I am using the approach proposed in https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/ - is this feature available?

I try to execute:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: camel-k-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
```
but this stick to phase `Pending`. It only works when a `PersistentVolume` was created ahead of time. Is it something we could expect any time soon if not yet available?
