### ISSUE TITLE
How to disable hairpinMode with Kind?

### ISSUE THREAD

**Issue by kevin85421** [kubernetes-sigs/kind#3118]
I am trying to disable `hairpinMode` with Kind. However, it does not work.

# Reproduce
<details>
<summary> kind-config.yaml </summary>

    # kind-config.yaml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
      kubeadmConfigPatches:
      - |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        hairpinMode: "none"

</details>

<details>
<summary> example.yaml </summary>

  ```
  apiVersion: v1
  kind: Service
  metadata:
    name: nginx
    labels:
      name: nginx
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      instance: nginx
  ---
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: nginx
  spec:
    replicas: 1
    selector:
      matchLabels:
        instance: nginx
    template:
      metadata:
        labels:
          name: nginx
          instance: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
            name: http
  ```

</details>

```sh
# Step 1: Create a cluster
kind create cluster --image=kindest/node:v1.23.0 --config kind-config.yaml

# Step 2: Log in to the control plane
docker exec -it kind-control-plane bash

# Step 3: Check the configuration
root@kind-control-plane:/# cat /var/lib/kubelet/config.yaml | grep hairpinMode
hairpinMode: none

# Step 4: Create a Nginx deployment and its service
kubectl apply -f example.yaml

# Step 5: The Nginx Pod can access itself via its ClusterIP service.
kubectl exec ${NGINX_POD} -- curl nginx:80 # succeed
kubectl exec ${NGINX_POD} -- curl nginx.default.svc.cluster.local:80 # succeed
```

In my expectation, both `curl` commands in Step 5 should fail because I disabled the `hairpinMode`. Thanks!
