### ISSUE TITLE
Contour ingress isn't working

### ISSUE THREAD

**Issue by brandonh-msft** [kubernetes-sigs/kind#3181]
I went thru the Ingress documentation to set up Contour. I got to the bottom and ran the two `curl` commands and am not met with any echo "foo-app" or "bar-app" as it says should happen. Instead, I get:

```
> curl localhost:8100/bar/hostname
curl: (52) Empty reply from server
```

Note I have to use `:8100` because my kind cluster is being setup w/ a different template than the default shown in the walkthrough

<details>
<summary>my cluster template</summary>

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8100
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
```

</details>

And so I modified the "Using ingress" template to replace all the 8080 with 80, then attempt to hit 8100.
If i try to just hit 80 I get
```
> curl localhost/bar/hostname
curl: (7) Failed to connect to localhost port 80 after 2242 ms: Couldn't connect to server
```

as I (believe) is correct given my cluster setup.

I am wondering if the images being used no longer echo back and, instead, just ACK as a way to signify e2e is working? If so, it seems this doc needs an update.
