### ISSUE TITLE
Add nodes to existing cluster

### ISSUE THREAD

**Issue by ricarhincapie** [kubernetes-sigs/kind#3205]
**What would you like to be added**:
I'd like to add a new node to my existing cluster named `k8-124` by creating a yaml file like this:

```
# extra-node.yaml
kind: Node
apiVersion: kind.x-k8s.io/v1alpha4
metadata:
  name: extra-node
  labels:
    node-role.kubernetes.io/worker: ""
spec:
  role: worker
  image: kindest/node:v1.24.12@sha256:0bdca26bd7fe65c823640b14253ea7bac4baad9336b332c94850f84d8102f873
```

And using a command similar to this:

```
kind create node --name k8-124 --config extra-node.yaml
```

**Why is this needed**:
This is needed because sometimes I get short on resources while working locally and not being able to add new nodes forces me to create bigger clusters than needed, being inefficient with my local machine's resources.
