### ISSUE TITLE
kubernetes master branch is broken

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#321]
https://testgrid.k8s.io/conformance-kind#kind,%20master%20(dev)%20%5Bnon-serial%5D&show-stale-tests=

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/9814

this commit range: https://github.com/kubernetes/kubernetes/compare/b8b143410...ee50d4784

most likely something with: https://github.com/kubernetes/kubernetes/pull/73452

/kind bug
/assign
cc @neolit123

**Comment by BenTheElder** [comment]
working on replicating locally ...

**Comment by BenTheElder** [comment]
Can replicate, `error execution phase control-plane-join/etcd: control-plane-join phase invoked with an invalid data struct`

**Comment by BenTheElder** [comment]
hmm also:

> [discovery] Failed to connect to API Server "172.17.0.2:6443": token id "abcdef" is invalid for this cluster or it has expired. Use "kubeadm token create" on the control-plane node to create a new valid token

**Comment by BenTheElder** [comment]
testing with: `kind create cluster --loglevel=debug --image=kindest/node:latest --config=$HOME/kind-basic.yaml --retain`

`kind-basic.yaml` is what we use in the kind e2e presubmits:
```yaml
# config for 1 control plane node and 2 workers
# necessary for conformance
kind: Config
apiVersion: kind.sigs.k8s.io/v1alpha2
nodes:
# the control plane node
- role: control-plane
- role: worker
  replicas: 2
```

the generated config for this looks like:
```yaml
apiServer:
  certSANs:
  - localhost
apiVersion: kubeadm.k8s.io/v1beta1
clusterName: kind
kind: ClusterConfiguration
kubernetesVersion: v1.15.0-alpha.0.63+3f9c29c5408f8b
metadata:
  name: config
---
apiVersion: kubeadm.k8s.io/v1beta1
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  bindPort: 6443
metadata:
  name: config
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
metadata:
  name: config
---
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: 0%
  nodefs.available: 0%
  nodefs.inodesFree: 0%
imageGCHighThresholdPercent: 100
kind: KubeletConfiguration
metadata:
  name: config
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metadata:
  name: config
```
