### ISSUE TITLE
Configuration file Description Image to be imported after cluster installation

### ISSUE THREAD

**Issue by nioshield** [kubernetes-sigs/kind#3259]
**What would you like to be added**:
Configuration file Description Image to be imported after cluster installation

**Why is this needed**:
In the internal environment, use a configuration file  to install the cluster on different nodes . The configuration file describes the docker image to be imported after the cluster is successfully installed. 
For example
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cls
networking:
  podSubnet: "10.241.0.0/16"
  serviceSubnet: "10.109.0.0/16"
nodes:
- role: control-plane
  loadImages:
  - nicolaka/netshoot:latest
- role: worker
  loadImages:
  - postgres:10.23
  - nginx:latest
```
