### ISSUE TITLE
How to pass configuration values to the config file when create cluster --config

### ISSUE THREAD

**Issue by Hinsteny** [kubernetes-sigs/kind#3266]
I want to setting the volume hostPath for {{hostPathFolder}}. But how to pass this value to kind?

create.sh
```
hostPathFolder=$(pwd)
echo ${hostPathFolder}
kind create cluster --config=cluster.conf
```

cluster.conf
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  extraMounts:
    - hostPath: {{hostPathFolder}}/plugins
      containerPath: /opt/plugins
```
