### ISSUE TITLE
Expose /metrics endpoint for kube-scheduler without setting bind address to 0.0.0.0?

### ISSUE THREAD

**Issue by tech1ndex** [kubernetes-sigs/kind#3271]
### Issue:

- Need to expose /metrics endpoint for Kube-Scheduler while keeping the `--bind-address=127.0.0.1`

### Steps to recreate:

1. Create new kind cluster with default parameters: `kind create cluster --name my-cluster`
2. Apply the following Service manifest:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  ports:
  - port: 10259
    protocol: TCP
    targetPort: 10259
    name: https-metrics
  selector:
    component: kube-scheduler
    tier: control-plane
  sessionAffinity: None
  type: ClusterIP
```
3. Check endpoints in kube-system:
![image](https://github.com/kubernetes-sigs/kind/assets/50547519/ab2d3454-e5cd-4971-a984-e65ef97fada3)

5. Run a simple curl pod to test metrics endpoint:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: monitoring
spec:
  containers:
  - image: curlimages/curl:8.1.1
    imagePullPolicy: IfNotPresent
    name: curl
    command: ["/bin/sh"]
    args: ["-c", "curl -ik https://172.18.0.3:10259/metrics"]
  restartPolicy: Always
```

6. Can't reach it:

![image](https://github.com/kubernetes-sigs/kind/assets/50547519/006cdc3a-a15b-4fa5-8085-47618e8b0fad)

So far I have only seen solutions involving setting the bind-address to 0.0.0.0 and while I understand that binding the kube-scheduler pod to 0.0.0.0 would make this endpoint reachable over the node IP, I am looking to keep this as secure as possible and don't want to expose the metrics outside of the cluster if possible.
