### ISSUE TITLE
A unique hostPort is not generated when using extraPortMappings without specifying hostPort.

### ISSUE THREAD

**Issue by prahaladramji** [kubernetes-sigs/kind#3301]
**What happened**:

Creating a kind cluster without any `hostPort` defined in the `extraPortMappings` should use random but unique `hostPort`. However it seems like it's using the same and so fails before cluster creation during validation. This was/is working as expected with kind v0.18.0

There is a workaround if creating only 1 cluster, which is to manually add `hostPort` and select a unique port. However this does not scale when we need to run multiple kind cluster. (eg for demonstrating or testing a multi cluster to replacate a multi region behaviour etc).

**What you expected to happen**:
The kind cluster to be created successfully

**How to reproduce it (as _minimally_ and precisely as possible)**:
Given the below config file and creating a cluster will fail with the folloing error.
```
ERROR: failed to create cluster: invalid configuration for node 1: invalid portMapping: port mapping with same listen address, port and protocol already configured: <nil>:0/
```

command run: `kind create cluster --config config.yaml`

```yaml
# config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 8080
      - containerPort: 8443
```

**Anything else we need to know?**:
This error only occurs after #3175 so all version from v0.19.0 on wards.
v0.18.0 continues to work as expected.

**Environment:**

- kind version: (use `kind version`): v0.20.0
- Runtime info: (use `docker info` or `podman info`): Docker engine 24.0.2
- OS (e.g. from `/etc/os-release`): OSX 13.4
- Kubernetes version: (use `kubectl version`): 1.24.15
- Any proxies or other special environment settings?: nil
