### ISSUE TITLE
Cannot use colon in private registry names

### ISSUE THREAD

**Issue by fjammes** [kubernetes-sigs/kind#3310]
**What happened**:

Failed to create a kind node which use private registry: "docker-registry.docker-registry:5000" because `docker``--volumes` option does not support 

**What you expected to happen**:

**How to reproduce it (as _minimally_ and precisely as possible)**:

Here is the configuration file `/tmp/kind-config.yaml`:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."docker-registry.docker-registry\:5000".tls]
      cert_file = "/etc/docker/certs.d/docker-registry.docker-registry\:5000/ca.crt"
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      enable-admission-plugins: NodeRestriction,ResourceQuota
nodes:
- role: control-plane
  extraMounts:
    # This option mounts the host docker registry folder into
    # the control-plane node, allowing containerd to access them.
  - containerPath: "/etc/docker/certs.d/docker-registry.docker-registry\:5000"
    hostPath: "/etc/docker/certs.d/docker-registry.docker-registry\:5000"
```
And the command which fails:
```
kind create cluster --config /tmp/kind-config.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.25.0) 🖼
 ✗ Preparing nodes 📦  
ERROR: failed to create cluster: command "docker run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --init=false '--volume=/etc/docker/certs.d/docker-registry.docker-registry\:5000:/etc/docker/certs.d/docker-registry.docker-registry\:5000' --publish=127.0.0.1:39711:6443/TCP -e KUBECONFIG=/etc/kubernetes/admin.conf kindest/node:v1.25.0@sha256:428aaa17ec82ccde0131cb2d1ca6547d13cf5fdabcc0bbecf749baa935387cbf" failed with error: exit status 125
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): kind v0.15.0 go1.19 linux/amd64
- Runtime info: (use `docker info` or `podman info`): Client: Docker Engine - Community, Version:    24.0.4
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.2 LTS
- Kubernetes version: (use `kubectl version`): v1.25.0
- Any proxies or other special environment settings?:
