### ISSUE TITLE
[Q] Using kindest/base in unit tests of a CRI API client application

### ISSUE THREAD

**Issue by thediveo** [kubernetes-sigs/kind#3314]
Disclaimer: I understand that (t)here be dragons.

I've created a `kindest/base:v20230525-4c49613f`-derived image by just adding a CNI configuration `10-kindnet.conflist`, taking the one that comes in kindest/node.

I then run this derived image using `docker run -it --rm --name kindisch --privileged $MYNAME`. Next, I take the container's PID that then will allow me to contact the containerd inside this container. For instance,

```bash
CRIAPI=unix:///proc/PID/root/run/containerd/containerd.sock
```

In the following `crictl` always implies `-i $CRIAPI -r $CRIAPI`.

Next, I create a simple `pod.json`:
```json
{
  "metadata": {
    "name": "busybox",
    "namespace": "test",
    "uid": "abcd"
  },
  "hostname": "test"
}
```

Now,
```bash
$ sudo crictl (...) pull busybox:stable
# OK
$ sudo crictl (...) runp pod.json
# FATA[0001]: run pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: failed to mount rootfs component: invalid argument: unknown
```

What am I missing (other than the dragons, that is)?

The host is a Kubuntu 23.04 (lunar) with Docker(-CE) engine 24.0.4.

**Comment by thediveo** [comment]
Found the solution: there are several more run options required. These can be glanced from the [Docker cluster provisioning provider](https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/provision.go). Basically:

```bash
docker run -it --rm --name kindisch --privileged --init=false --volume /dev/mapper:/dev/mapper --device /dev/fuse --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro $IMAGE
```

Also, the `/etc/containerd/config.toml` must set the `SystemCgroup` settings explicitly to `false`; this must be applied to:

```toml
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = false

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.options]
    SystemdCgroup = false

```
