### ISSUE TITLE
Add .metadata field to Cluster API for Kustomize support

### ISSUE THREAD

**Issue by elmazzun** [kubernetes-sigs/kind#3337]
**What would you like to be added**:
Hi!
I'd like to suggest the following enhancement: could you change from `Cluster.name`  to `Cluster.metadata.name` so that Kustomize can support patching Cluster kind.x-k8s.io/v1alpha4 resources?

To be clear, I'd like a Cluster to be defined from this:
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: mylab
nodes:
- role: control-plane
```

to this
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
metadata: 
  name: mylab # <--- .metadata.name
nodes:
- role: control-plane
```

**Why is this needed**:
I was about to add Cilium to my local KinD cluster: Cilium documentation suggested to [disable default KinD CNI](https://docs.cilium.io/en/stable/installation/kind/#configure-kind) and replace it with Cilium.

My KinD cluster is pretty generic and I didn't want to hard-code the configurations suggested by Cilium (no CNI, a certain pod subnet, a certain service subnet, ...) so I decided to use `kustomize` by putting my current generic Cluster configuration in a `base` folder and the patch disabling default CNI in `overlays/cilium` folder, like this:

```bash
├── manifests
│   ├── base
│   │   ├── cluster.yaml
│   │   └── kustomization.yaml
│   └── overlays
│       └── cilium
│           ├── disable-cluster-cni.yaml
│           └── kustomization.yaml
```

`manifests/overlays/cilium/disable-cluster-cni.yaml` is:
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: mylab
networking: 
  disableDefaultCNI: true
```

while `manifests/base/cluster.yaml` is the same YAML I posted at the top of this issue.

If I run `kustomize build overlays/cilium` in `manifests` folder, I get the following error:
```bash
# Added a newline to every colon
➜  manifests git:(main) ✗ kustomize build overlays/cilium
Error: accumulating resources: accumulation err='accumulating resources from '../../base':  
'/home/user/Desktop/repos/kind-cluster/manifests/base' must resolve to a file':  
recursed accumulation of path '/home/user/Desktop/repos/kind-cluster/manifests/base':  
accumulating resources:  
accumulation err='accumulating resources from 'cluster.yaml':  
missing metadata.name in object {{kind.x-k8s.io/v1alpha4 Cluster} {{ } map[] map[]}}':  # Guess this is problematic
must build at directory:  
'/home/user/Desktop/repos/kind-cluster/manifests/base/cluster.yaml': file is not directory
```

Do you have plans to make Kustomize compatible with KinD resources?
Or am I making a colossal blunder and I am missing something obvious?

Thanks for your work!
