### ISSUE TITLE
Coredns and local-path-provisioner pending if default cni disabled 

### ISSUE THREAD

**Issue by miguelacaro** [kubernetes-sigs/kind#3353]
If Default cni is disabled coredns pods and local-path storage remains in Pending state, also Nodes are not available.
I've tried several versions of kind  and diferents distributions and always having the same issue. 
If I don´t disable the default cni it works without issues. 
Any idea?

**What happened**:
Coredns pods pending 
**How to reproduce it (as _minimally_ and precisely as possible)**:
I´m using the following kind.yaml conf file to create the cluster.

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker
- role: worker
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): 0.12, 0.18, 0.19, 0.20
- Runtime info: (use `docker info` or `podman info`):
- OS (e.g. from `/etc/os-release`): Amazon Linux 2, Ubuntu 22.04, Mac Os Ventura 13.4
- Kubernetes version: (use `kubectl version`): Client v1.27.2  Server 1.26.3
- Any proxies or other special environment settings?:
