### ISSUE TITLE
kubeadm labelling failing using kubeletExtraArgs

### ISSUE THREAD

**Issue by doublethink13** [kubernetes-sigs/kind#3355]
**What happened**:

Tried to create a cluster with additional labels on the nodes using nodeRegistration.kubeletExtraArgs.node-labels but it didn't work.

I ran `kind create cluster --wait 5m --config config.yml` (config below).

**What you expected to happen**:

```yml
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
```

Should add labels as expected.

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

Following https://kind.sigs.k8s.io/docs/user/ingress/, I tried to create a cluster with this config file:

```yml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: control-plane
  - extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    labels:
      nginx-controller: true
    role: control-plane
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
```

The control-plane node does not have a label `ingress-ready=true`. However, it does have a label `nginx-controller=true`. If I create a cluster without the `labels` configuration, it stills doesn't add the expected label. It works, ie, `k get node --selector=ingress-ready=true` returns the expected node, if I use:

```yml
labels:
  nginx-controller: true
  ingress-ready: true
```

I've also tried the above methods in a worker node but `k get node --selector=ingress-ready=true` still returns no node.

**Environment:**

- kind version: (use `kind version`): `0.21.0-alpha.23+ac28d7fb19b4f3`
- Runtime info: (use `docker info` or `podman info`): 
 ```txt
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 29
  Running: 7
  Paused: 0
  Stopped: 22
 Images: 313
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-31-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.3GiB
 Name: eduardo-ThinkPad-E15-Gen-4
 ID: fce466fa-00bb-48e1-8ebf-0ee2b71af203
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false  
```
- OS (e.g. from `/etc/os-release`): 
```txt
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kubernetes version: (use `kubectl version`):
```txt
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
- Any proxies or other special environment settings?: Not to the best of my knowledge

**Comment by doublethink13** [comment]
I could have a look into this :slightly_smiling_face: (if really a bug and not a misstep on my part)

**Comment by wongcheechun** [comment]
Your config.yml is not correctly configured, the `-` on `extraPortMappings` is not needed. Here's what works for me 
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    labels:
      nginx-controller: true
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
```
Control plane should show `ingress-ready` label
```
$ kubectl get node test-control-plane -o json | jq '.metadata.labels'                                                                                                                                                                                            ⎈ kind-test
{
  "beta.kubernetes.io/arch": "amd64",
  "beta.kubernetes.io/os": "linux",
  "ingress-ready": "true",
  "kubernetes.io/arch": "amd64",
  "kubernetes.io/hostname": "test-control-plane",
  "kubernetes.io/os": "linux",
  "node-role.kubernetes.io/control-plane": "",
  "node.kubernetes.io/exclude-from-external-load-balancers": ""
}
```

**Comment by doublethink13** [comment]
>Your config.yml is not correctly configured, the - on extraPortMappings is not needed. Here's what works for me
What `-` do you mean?

Your config looks exactly the same as mine, you just ordered them differently.

Although your config seems to work.

Because of that, I tried switching the order of the control plane node.

Using:

```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    labels:
      nginx-controller: true
    role: control-plane
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: control-plane
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
  - image: kindest/node:v1.27.2@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    role: worker
```

Works. So apparently the control-plane order is important? Is there a good reason for it?
