### ISSUE TITLE
Ephemeral storage not available when using (docker/podman) rootless providers

### ISSUE THREAD

**Issue by josecastillolema** [kubernetes-sigs/kind#3359]
**What happened**:

When using kind with rootless docker/podman pods with ephemeral storage requests never get scheduled, i.e.:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: centos
    name: compute
    resources:
      requests:
        ephemeral-storage: 50M
```

**What you expected to happen**:
The pod gets properly scheduled, as it does with rootfull docker/podman

**How to reproduce it (as _minimally_ and precisely as possible)**:
1. Create a kind cluster with rootless docker/podman
2. Try to create the pod

**Anything else we need to know?**:
With rootfull docker/podman:
```
kubectl describe node ..
Capacity:
  cpu:                8
  ephemeral-storage:  71658616Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32629028Ki
  pods:               110
Allocatable:
  cpu:                8
  ephemeral-storage:  71658616Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32629028Ki
  pods:               110
```

With rootless docker/podman (no ephemeral storage):
```
Capacity:
  cpu:            8
  hugepages-1Gi:  0
  hugepages-2Mi:  0
  memory:         32629028Ki
  pods:           110
Allocatable:
  cpu:            8
  hugepages-1Gi:  0
  hugepages-2Mi:  0
  memory:         32629028Ki
  pods:           110
```

**Environment:**

- kind version: (use `kind version`): v0.20.0 go1.20.7 linux/amd64
- Runtime info: (use `docker info` or `podman info`): 
   - Docker: 24.0.1
   - Podman: 4.6.1
- OS (e.g. from `/etc/os-release`): Fedora Linux
