### ISSUE TITLE
How to add bandwidth cni plugin to Kind cluster?

### ISSUE THREAD

**Issue by chenweiyj** [kubernetes-sigs/kind#3371]
I want to control bandwidth of a certain pod, but I cannot find any documentation about using the bandwidth plugin in Kind. I put 
```yaml
metadata:
  annotations:
    kubernetes.io/ingress-bandwidth: 1M
    kubernetes.io/egress-bandwidth: 1M
```
in the deployment.yaml, however it not works.

So, how to add bandwidth cni plugin to Kind cluster?
