### ISSUE TITLE
Loadbalancer settings fail when using podman

### ISSUE THREAD

**Issue by tqq1994516** [kubernetes-sigs/kind#3388]
`OS:  Linux mustard-seed 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
`kind v0.20.0 go1.20.4 linux/amd64`
`podman version 3.4.4`
`node image: kindest/node:v1.26.6`
`kwasm-operator-0.2.3`
When I use podman to run the k8s cluster, I configure the metallb load balancer according to [LoadBalancer](https://kind.sigs.k8s.io/docs/user/loadbalancer/). The load balancer address is also assigned normally. Checking the node and pod status is normal. The address assigned using the load balancer cannot be accessed. , when accessing the service through curl, it prompts `No route to host`, and it is available normally when I use docker.
I also used kwasm to make the cluster support wasm. This should not be the problem. I still cannot access the load balancer without installing it.
![image](https://github.com/kubernetes-sigs/kind/assets/61398122/a308be3d-8c36-484e-9fb0-56e437d6290d)
Some configurations are as follows:
[Calico](https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml)
[Matallb](https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml)
**Metallb-ip-pool-config:**
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - 172.19.255.200-172.19.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
```
**cluster config:**
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "CSIMigration": true
name: myapp-cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "192.168.0.0/16"
  disableDefaultCNI: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
  extraMounts:
  - hostPath: /etc/docker/certs.d
    containerPath: /etc/containerd/certs.d
```
