### ISSUE TITLE
RFC: v1alpha3 config proposal

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/kind#340]
I've been thinking for a while now about how to improve the ergonomics of our config and extend it for more use cases. I intend to bring this up at the next meeting. Proposal is as follows:

----

# Proposed changes

### Rationale
This is more precise, it specifically configures a kind cluster, whereas some of the sub objects configure nodes etc. Additionally, `config.Cluster` is a better library type name than `config.Config`

### Cons
This is a bikeshed. They both work. Users will need to update (but the same is pretty much true for changing the API version).

## Allow specifying extra ports on nodes

Specifically allow config of the form:

```yaml
apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
nodes:
- role: worker
  nodePorts: [8080]
- role: worker
  nodePorts: [9090, 7070]
```

### Rationale

In single node mode this will be especially easy to use and allow serving traffic from workloads with Kubernetes `nodePort`s.

This should solve https://github.com/kubernetes-sigs/kind/issues/99, which is one of the earliest standing requests.

### Cons

For multi-node we will likely need to label the nodes with the ports or make the node names predictable or configurable. Suggestions are welcome.

This may also not be the most favorable solution long term versus say, implementing a form of `LoadBalancer` / `Ingress`, but should be much easier to solve and unblock usage.

## Add a `networking` struct to `Cluster`

Specifically:
```yaml
apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
networking:
  # 127.0.0.1 if unset, affects all nodes
  listenAddress: '0.0.0.0'
  apiServer:
    # random if unset, applies to the control plane node or load balancer
    listenPort: 6443
nodes:
 ....
```

### Rationale

There's increasing demand for configuring this. Additionally, we need to change the defaut listen address to 127.0.0.1 for security reasons ... users will need a way to configure this.

These fields are similar to kubeadm's config.

### Cons

I'm not aware of any. Minor complexity increase?

## Drop the `load-balancer` node role

... but keep the node type internally, and mark it as "control-plane-load-balancer" (or something similarly precise)

### Rationale

We only actually support the control plane load balancer, which is implicitly necessary for multiple control-plane clusters. Nothing about the control plane is currently configurable, and if it were it would actually be cluster-wide details (like the api server listen address).

We already intend to implicitly add these to `v1alpha2` https://github.com/kubernetes-sigs/kind/pull/274

### Cons

Users need to stop explicitly specifying `load-balancer` nodes when they upgrade to `v1alpha3`.

### Rationale

Having nodes internally copied is increasingly confusing as we add host mounts and other configuration knobs to nodes.

Writing one entry per node is more explicit and reduces some internal complexity.

### Cons

The config will be slightly more verbose, users need to copy + paste identical nodes.

## Make kubeadm config patches explicitly cluster-wide

Specifically move the `kubeadmConfigPatches` and `kubeadmConfigPatchesJson6902` fields off of the `nodes` in `Cluster` to the top level.

### Rationale

We already only generate one cluster-wide config, and it's unclear that it would ever make sense to have multiple configs in one cluster. If it does wind up making sense, we can add fields back to nodes later with higher precedence than the cluster-wide fields.

This should clarify the behavior.

### Cons

None? It will be straightforward to add per-node patches or other improvements if and when the use cases become apparent.

# Example Config:

This is an example of a config with several nodes and **every** knob set after the above changes.

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  # 127.0.0.1 if unset, affects all nodes
  listenAddress: '0.0.0.0'
  apiServer:
    # random if unset, applies to the control plane node or load balancer
    listenPort: 6443
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
  name: config
  networking:
    serviceSubnet: 10.0.0.0/16
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta1
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 3 control plane nodes and 3 workers
nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  # expose extra ports on this node
  nodePorts: [9090, 7070]
  # add extra bind mounts to this node
  extraMounts:
    # readonly bind mount the kind source code at /kind-source
    containerPath: /kind-source
    hostPath: /Users/bentheelder/go/src/sigs.k8s.io/kind
    readOnly: true
    # explicitly set some advanced values to their defaults
    selinuxRelabel: false
    propagation: None
- role: worker
  # add extra bind mounts to this node
  extraMounts:
    # readonly bind mount the kind source code at /kind-source
    containerPath: /kind-source
    hostPath: /Users/bentheelder/go/src/sigs.k8s.io/kind
    readOnly: true
- role: worker
  # add extra bind mounts to this node
  extraMounts:
    # readonly bind mount the kind source code at /kind-source
    containerPath: /kind-source
    hostPath: /Users/bentheelder/go/src/sigs.k8s.io/kind
    readOnly: true
```

**Comment by BenTheElder** [comment]
/priority important-soon
/assign
cc @neolit123 @fabriziopandini @munnerz @pablochacin

**Comment by neolit123** [comment]
> This is more precise, it specifically configures a kind cluster, whereas some of the sub objects configure nodes etc. Additionally, `config.Cluster` is a better library type name than `config.Config`

support for multi-cluster topology e.g. clusters sitting behind a load balancer a load balancer would have been fun, but out of scope so the change SGTM.

> Drop the `load-balancer` node role

SGMT, but this drops eventual load-balancer configurations if we want to support such even.
probably not anytime soon.

> Drop the `replicas` field from nodes

doesn't matter that much. slightly less friendly UX config wise.

> Make kubeadm config patches explicitly cluster-wide

someone might complain about this eventually and file the request to have them per node.

> Example Config:

SGTM.

> [BenTheElder](/BenTheElder) added this to the [0.2](/kubernetes-sigs/kind/milestone/4) milestone [19 minutes ago](#event-2159789542)

has the timeline of 0.2 shifted towards the 1.14 release and the 1.0 shifted for the future?
seems optimistic, but doable.

**Comment by BenTheElder** [comment]
Thanks for the comment @neolit123 

> support for multi-cluster topology e.g. clusters sitting behind a load balancer would have been fun, but out of scope so the change SGTM.

We could probably still do this by having cluster objects set the name metadata and having another object reference them by name?

This does seem out of scope for now though. Kubernetes has no concepts for this AFAIK.

> SGMT, but this drops eventual load-balancer configurations if we want to support such even.
probably not anytime soon.

Those settings can go under `networking` at the top level? (and we will be allowing setting eg the port)

> doesn't matter that much. slightly less friendly UX config wise.

_very_ slightly I think. it's less confusing in the config format and the code but more verbose. It shouldn't be too unbearable to repeat node specs in your config, most multi-node clusters will just look like:
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
```

> someone might complain about this eventually and file the request to have them per node.

If / when they do it will be useful to understand the use cases and why, and we can make per-node config override the cluster-global config at the node level. 

This should be less confusing and avoid people repeating it for every node when really they just wanted to change something cluster wide anyhow (like say the API server cert SANs).

> has the timeline of 0.2 shifted towards the 1.14 release and the 1.0 shifted for the future?
seems optimistic, but doable.

I shifted 0.2 to end of next week optimistically, most of these changes are quite trivial, and many of them like the ports can be added in a later edition of v1alpha3 without breaking change.

1.0 is definitely shifted to the future, this was always an aggressive and overly optimistic timeline to push for core feature design & iteration.

We should discuss these dates in another venue though (perhaps at the meeting)?

I'm also OK to not make this in 0.2, but I think we can at least get the breaking changes done quickly once we've reviewed the proposal.
