### ISSUE TITLE
Why are some ports on ExtraPortMapping available only on localhost?

### ISSUE THREAD

**Issue by ante-maric** [kubernetes-sigs/kind#3414]
In my kind configuration I have this:

```
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30017
        hostPort: 27017
        protocol: TCP
      - containerPort: 30018
        hostPort: 27018
        protocol: TCP
      - containerPort: 30019
        hostPort: 27019
        protocol: TCP
```
Port 80 and 443 are for nginx ingress and it is accessible from another machine. Ports 27017-27019 are for MongoDb, but I can access those only from localhost. That is unexpected for me considering that port 80/443 work and that listenAddress is by default 0.0.0.0 according to a documentation.

Should 27017-27019 be accessible from another machine or not? Are 80/443 ports a special case?

**Comment by BenTheElder** [comment]
No there's no special case in kind, they should all be on localhost only. possibly something else on the machine forwards those ports

**Comment by ante-maric** [comment]
What is the purpose of listenAddress then? In documentation we have this:

 ```
extraPortMappings:
  - containerPort: 80
    hostPort: 80
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "127.0.0.1"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
```
Comment is referring to a host in regards to listenAddress. If default is 0.0.0.0 I would guess that host listenes on hostPort on all interfaces.
