### ISSUE TITLE
Worker nodes roles not displayed

### ISSUE THREAD

**Issue by dancer1325** [kubernetes-sigs/kind#3421]
**This is a Bug Report**
* If you define your Cluster with >= 1 worker node, the roles of the worker are specified as `<none>`

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0
  - role: worker
    image: kindest/node:v1.28.0
  - role: worker
    image: kindest/node:v1.28.0
```

And after running `kubectl get nodes`

![image](https://github.com/kubernetes-sigs/kind/assets/39351487/cc5c1bb0-63ef-40ff-a389-697ca31b22cb)

**Proposed Solution:**

* Checking in the kind project code -- not familiarized with it .. 😢 

**Note:**
* My setUp is
  * kubectl Client Version: v1.28.2
  * kind v0.20.0
  * docker v24.0.5
* Following [thisDocumentationPart](https://kind.sigs.k8s.io/docs/user/configuration/#nodes)
