### ISSUE TITLE
Allow  kubeProxyMode: "nftables" in the networking configuration

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kind#3434]
**What would you like to be added**:

The [nftables proxier](https://github.com/kubernetes/kubernetes/pull/121046) is added in "alpha" with feature-gate `NFTablesProxyMode` in K8s v1.29. When it becomes more available, it should be possible to specify:

```
networking:
  kubeProxyMode: "nftables"
```
in the kind configuration.

**Why is this needed**:

For improved UE

### Background

To try the nftables proxier before this feature, please use:
```
featureGates:
  "NFTablesProxyMode": true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    mode: "nftables"
    nftables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 1s
      syncPeriod: 30s
```
and, use an image built on "master" or K8s v1.29 or later.

Please see also the [thread in slack](https://kubernetes.slack.com/archives/CEKK1KTN2/p1701084832395189).
