### ISSUE TITLE
how to change scheduler's log level in kind cluster

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes-sigs/kind#3446]
```
kube-scheduler --authentication-kubeconfig=/etc/kubernetes/scheduler.conf --authorization-kubeconfig=/etc/kubernetes/scheduler.conf --bind-address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true
```

**Comment by roman-kiselenko** [comment]
AFAIK you can leverage [`Kubeadm Config Patches`](https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches)
```yaml
kind: ClusterConfiguration
  metadata:
    name: config
  scheduler:
    extraArgs:
      # 
      
```

Or set the log level of scheduler component:

```shell
kubectl -n kube-system port-forward kube-scheduler-kind-control-plane 10259:10259
curl -s -X PUT -d '5' https://localhost:10259/debug/flags/v --header "Authorization: Bearer $TOKEN" -k
```
