### ISSUE TITLE
Is verbosity configuration working properly?

### ISSUE THREAD

**Issue by dancer1325** [kubernetes-sigs/kind#3464]
I want to see 'kube-scheduler' logs to track each time that a new pod is assigned to a node. I don't see any difference at all changing the verbosity -- maybe this info should not be logged independently of the verbosity .. 👁️  -- 

**Attempt1:** `kind create cluster --verbosity 6`

**Attempt2:** 
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        v: "6"
nodes:
  - role: control-plane
  - role: worker
```

And no difference at all in the logs, comparing with the default one --  `kubectl logs pod/kube-scheduler-verbosity-control-plane -n kube-system --v=6` --

**Note:**
* My setUp is
  * kubectl Client Version: v1.28.2
  * kind v0.20.0
  * docker v24.0.5

**Comment by neolit123** [comment]
to verify that the "v" extra arg was passed correctly check the command inside /etc/kubernetes/manifests/kube-scheduler.yaml
it should have the  "--v=6".

in terms of differences with default verbosity, AFAIK some k8s components print the CLI flags on --v>=5.
so that's one indication that the high verbosity was enabled.
for --v=10, you would start seeing API call response/request bodies.

if you are still not finding what you want best to ask in #sig-scheduling on k8s slack.
support tickets in kubernetes/kubernetes repo generally get closed:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

 or just log a kubernetes/kubernetes bug ticket - ALA "missing logs for scheduler action Foo"

**Comment by dancer1325** [comment]
Hi @neolit123 

* thanks for the fast reply 🚀 

> to verify that the "v" extra arg was passed correctly check the command inside /etc/kubernetes/manifests/kube-scheduler.yaml
it should have the "--v=6".

Maybe I am doing nonsenses, but going into the control plane component, and checking '/etc/kubernetes/manifests/kube-scheduler.yaml', I don't see any 'extra-arg' section in any part of the manifest

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: registry.k8s.io/kube-scheduler:v1.27.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```


> in terms of differences with default verbosity, AFAIK some k8s components print the CLI flags on --v>=5.
so that's one indication that the high verbosity was enabled.

 👍 

> for --v=10, you would start seeing API call response/request bodies.

 👍. I wasn't aware of those verbosity levels ... I think that Kubernetes Components would follow the [kubectl's verbosity](https://kubernetes.io/docs/reference/kubectl/quick-reference/#kubectl-output-verbosity-and-debugging)

>if you are still not finding what you want best to ask in #sig-scheduling on k8s slack.
support tickets in the kubernetes/kubernetes repo generally get closed:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
or just log a kubernetes/kubernetes bug ticket - ALA "missing logs for scheduler action Foo"

 👍 . Thanks for the recommendations 🎩 . My thought to ask here was that maybe some 'kind' related could be ...

**Comment by neolit123** [comment]
> My thought to ask here was that maybe some 'kind' related could be ...

yes, the problem is the version of the kubeadm API. try passing v1beta3 instead of v1beta2:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        v: "6"
nodes:
  - role: control-plane
  - role: worker
```

in 1.27 v1beta2 was already gone, only v1beta3 remained.
https://github.com/kubernetes/kubernetes/tree/release-1.27/cmd/kubeadm/app/apis/kubeadm

kind internally uses v1beta3, but if the patch is for v1beta2 it's not applied correctly.

the above config works:
```
docker exec -it kind-control-plane cat /etc/kubernetes/manifests/kube-scheduler.yaml | grep "\-\-v"
    - --v=6
```
