### ISSUE TITLE
v0.21.0: kind container makes changes to binfmt configutation

### ISSUE THREAD

**Issue by f84anton** [kubernetes-sigs/kind#3510]
**What happened**:
I'm using orbstack on macbook m1, upgraded to kind 0.21.0 and created a new cluster with k8s 1.23, image `kindest/node:v1.23.17@sha256:fbb92ac580fce498473762419df27fa8664dbaa1c5a361b5957e123b4035bdcf`
After that I've got problem with running amd64 images in docker or inside kind:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /service: exec format error
```

config file:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  TTLAfterFinished: true
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
    endpoint = ["http://kind-registry:5000"]
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "1%"
    imagefs.available: "1%"
    nodefs.inodesFree: "1%"
    memory.available: "50Mi"
  imageMinimumGCAge: "1h"
  imageGCHighThresholdPercent: 90
  imageGCLowThresholdPercent: 85
  allowedUnsafeSysctls:
  - "net.*"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 30443
    hostPort: 443
```

Here is how I created a cluster:
```
kind create cluster \
 --name kind \
 --image  "kindest/node:v1.23.17@sha256:fbb92ac580fce498473762419df27fa8664dbaa1c5a361b5957e123b4035bdcf"\
 --config /path/to/config \
 --wait 5m`
 ```

Here is binfmt info after kind container was created:
```
%  docker run --privileged --rm tonistiigi/binfmt
{
  "supported": [
    "linux/arm64"
  ],
  "emulators": [
    "python3.11"
  ]
}
```

After `kind cluster delete` and orbstack restart I see that the list goes back to normal:
```
%  docker run --privileged --rm tonistiigi/binfmt
{
  "supported": [
    "linux/arm64",
    "linux/amd64",
    "linux/riscv64",
    "linux/ppc64le",
    "linux/s390x",
    "linux/386",
    "linux/mips64le",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": [
    "mac-macho-arm64",
    "mac-macho-x86_64",
    "mac-universal-arm64",
    "mac-universal-x86_64",
    "qemu-arm",
    "qemu-i386",
    "qemu-mips64el",
    "qemu-ppc64le",
    "qemu-riscv64",
    "qemu-s390x",
    "qemu-x86_64",
    "rosetta",
    "rosetta",
    "rosetta"
  ]
}
```

I had to roll back to 0.20.0, there is no issue with this version and k8s image `kindest/node:v1.23.17@sha256:59c989ff8a517a93127d4a536e7014d28e235fb3529d9fba91b3951d461edfdb`

**What you expected to happen**:
I've expected that I will not loose ability to run amd64 images.

**How to reproduce it (as _minimally_ and precisely as possible)**:
Create kind cluster with v0.21.0 on macbook m1 with orbstack.

**Anything else we need to know?**:
there is a similar issue for minikube https://github.com/kubernetes/minikube/issues/17700

**Environment:**

- kind version: (use `kind version`): kind v0.21.0 go1.20.13 darwin/arm64
- Runtime info: (use `docker info` or `podman info`): 
```
% docker info
Client:
 Version:    25.0.2
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /Users/antonfaizrakhmanov/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     /Users/antonfaizrakhmanov/.docker/cli-plugins/docker-compose
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.17.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8c087663b0233f6e6e2f4515cee61d49f14746a8
 runc version: 82f18fe0e44a59034f3e1f45e475fa5636e539aa
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.13-orbstack-00122-g57b8027e2387
 Operating System: OrbStack
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 2.513GiB
 Name: orbstack
 ID: 70e419d6-93c9-4b9a-bb82-5507a43455ef
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 192.168.215.0/24, Size: 24
```
- OS (e.g. from `/etc/os-release`):  macos 14.2.1 (23C71) MacBook Air M1 2020
- Kubernetes version: (use `kubectl version`): 
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-06-15T02:24:51Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
```
