### ISSUE TITLE
Cannot use multiple extraPortMappings with default hostPort

### ISSUE THREAD

**Issue by wouterh-dev** [kubernetes-sigs/kind#3512]
**What happened**:

When creating a kind cluster using the config:

```
  extraPortMappings:
  - containerPort: 80
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 443
    listenAddress: 127.0.0.1
    protocol: TCP
```

kind errors with:

```
ERROR: failed to create cluster: invalid configuration for node 0: invalid portMapping: port mapping with same listen address, port and protocol already configured: 127.0.0.1:0/TCP
```

**What you expected to happen**:

Both hostPorts to be picked at random by kind, instead of an error about port 0 already being chosen.

**How to reproduce it (as _minimally_ and precisely as possible)**:

```bash
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 443
    listenAddress: 127.0.0.1
    protocol: TCP
EOF
```

**Anything else we need to know?**:

* The same happens when using hostPort -1
* It works fine when only specifying one port mapping, so the issue seems to be with the validation which should allow duplicate hostPorts of 0 and -1. For example, this works:

```bash
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    listenAddress: 127.0.0.1
    protocol: TCP
EOF

docker port kind-control-plane       
80/tcp -> 127.0.0.1:40705
6443/tcp -> 127.0.0.1:35909
```

**Environment:**

- kind version: (use `kind version`): 

```
kind v0.21.0 go1.21.6 linux/amd64
```

- Runtime info: (use `docker info` or `podman info`):

```
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.12.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.3
    Path:     /usr/lib/docker/cli-plugins/docker-compose
```

- OS (e.g. from `/etc/os-release`):

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
```

- Kubernetes version: (use `kubectl version`):

```
Client Version: v1.29.1
```

- Any proxies or other special environment settings?:

**Comment by BenTheElder** [comment]
Yes, this is as expected? You cannot forward the same host port to two container ports in docker.

/remove-kind bug
/kind support

**Comment by wouterh-dev** [comment]
I was expecting kind to pick two different random host ports, and forward one to containerPort 80 and the other to containerPort 443.

**Comment by ranjith-ka** [comment]
Yes my config looks like this,  
```
## This version is for kind v0.19.0  // https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
  - role: worker
    extraPortMappings:
      - containerPort: 32080
        hostPort: 80
        protocol: tcp
      - containerPort: 32443
        hostPort: 2443
      - containerPort: 31443
        hostPort: 443
      - containerPort: 31697
        hostPort: 27017
      - containerPort: 31699
        hostPort: 9092
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
    ```

```
## This version is for kind v0.19.0  // https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
  - role: worker
    extraPortMappings:
      - containerPort: 32081
        hostPort: 8080
        protocol: tcp
      - containerPort: 32444
        hostPort: 1443
      - containerPort: 31444
        hostPort: 143
      - containerPort: 31698
        hostPort: 57017
      - containerPort: 31698
        hostPort: 9093
    image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
```
    
  Error:
  
  ```
  ⢆⡱ Joining worker nodes 🚜
 ✗ Joining worker nodes 🚜
Deleted nodes: ["k8s-control-plane" "k8s-worker"]
ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged k8s-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
Command Output: I0209 04:51:45.490053     131 join.go:412] [preflight] found NodeName empty; using OS hostname as NodeName
I0209 04:51:45.490133     131 joinconfiguration.go:76] loading configuration from "/kind/kubeadm.conf"
I0209 04:51:45.490664     131 controlplaneprepare.go:225] [download-certs] Skipping certs download
```
