### ISSUE TITLE
Kind can't kind join node properly

### ISSUE THREAD

**Issue by ep4sh** [kubernetes-sigs/kind#3537]
**What happened**:

Creating a cluster in CI (private gitlab ci), using the following:
```
    export KIND_CLUSTER_NAME=kind
    export K8S_VERSION="v1.26.14"
    kind create cluster --image=kindest/node:${E2E_K8S_VERSION} --name=${KIND_CLUSTER_NAME} --config test/e2e/kind.yaml
```

test/e2e/kind.yaml:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  labels:
    topology.kubernetes.io/zone: zone-1
- role: worker
  labels:
    topology.kubernetes.io/zone: zone-1
- role: worker
  labels:
    topology.kubernetes.io/zone: zone-2
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  controllerManager:
    extraArgs:
      namespace-sync-period: 10s
      concurrent-deployment-syncs: "30"

```

Then I getting:
```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.26.14) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.26.14) 🖼
 • Preparing nodes 📦 📦 📦   ...
 ✓ Preparing nodes 📦 📦 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
 • Joining worker nodes 🚜  ...
 ✗ Joining worker nodes 🚜
Deleted nodes: ["kind-control-plane" "kind-worker" "kind-worker2"]
ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged kind-worker kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1
```

**What you expected to happen**:
Cluster is created

**How to reproduce it (as _minimally_ and precisely as possible)**:

**Anything else we need to know?**:

**Environment:**
- I've exported logs from kind cluster with --retain option  - please check the attachment
- kind version: (use `kind version`): 0.20.0
- Runtime info: (use `docker info` or `podman info`): please see attachment
- OS (e.g. from `/etc/os-release`): please see attachment
- Kubernetes version: (use `kubectl version`): please see attachment
- Any proxies or other special environment settings?: nope
[kind.zip](https://github.com/kubernetes-sigs/kind/files/14436139/kind.zip)
