### ISSUE TITLE
Add the ablity to specify extra labels in the config file

### ISSUE THREAD

**Issue by christianh814** [kubernetes-sigs/kind#3541]
**What would you like to be added**:

It would be nice to be able to add labels to running KIND instances. To do this, the config can be updated to include something like this...

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerRuntime:
  extraLabels:
    - name: myspecialkey
      value: myspecialvalue
    - name: foo
      value: bar
```

I know currently the labels `io.x-k8s.kind.cluster` and `io.x-k8s.kind.role` are automatically added, but it would be nice to be able to add additional labels.

**Why is this needed**:

When using KIND as a library, there's no way to distinguish which ones are created by KIND itself, or if it was created by another tool using KIND as a library. It would be nice to filter out these running containers based on other labels.

I looked into using Docker for this, but it looks like you can't add labels once the container is running:

- https://github.com/moby/moby/issues/15496#issuecomment-503549435
- https://github.com/moby/moby/issues/21721 

**Other Considerations**

Although I don't use it in my workflow (I just the config file mostly), it would be useful to add `--label` to the `kind create cluster` command to get the same effect.
