### ISSUE TITLE
PV-PVC binding remains stuck

### ISSUE THREAD

**Issue by thlr1** [kubernetes-sigs/kind#3615]
Hi, I can't seem to figure out PV / PVC binding. I have been trying to use a local volume in a pod but I can't get the volumes to consistently bind together. Here is a basic setup to try:

```yaml
# kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.11@sha256:681253009e68069b8e01aad36a1e0fa8cf18bb0ab3e5c4069b2e65cafdd70843
    extraMounts:
      - hostPath: ./local-volume
        containerPath: /data
```

```yaml
# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data
    type: Directory
```

```yaml
#pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

The volume shows `Available` but the pvc won't ever bind.

I have tried:

- Using labels with `matchLabels` selector - this is the method that I would like to use
- Setting `volumeName` in the pvc - not ideal to me
- Setting `claimRef` with the pvc name in the pv. That actually is the only way I have been able to bind the volume, but again, I would rather not write the exact object names

Does this have something to do with the `WaitForFirstConsumer` mode of the rancher storage class? I have tried to throw in a pod to use the pvc but it has not worked:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
  - name: test
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
      - mountPath: /var/lib/data
        name: data
```

What am I missing?

Thank you very much for your help
