### ISSUE TITLE
Invalid docs on mouting docker configs

### ISSUE THREAD

**Issue by th0ger** [kubernetes-sigs/kind#3642]
**What would you like to be documented**:

[Mount a Config File to Each Node ](https://kind.sigs.k8s.io/docs/user/private-registries/#mount-a-config-file-to-each-node) says:

> If you pre-create a docker config.json containing credential(s) on the host you can mount it to each kind node.
> 
> Assuming your file is at /path/to/my/secret.json, the kind config would be:
> ```yaml
> kind: Cluster
> apiVersion: kind.x-k8s.io/v1alpha4
> nodes:
> - role: control-plane
>   extraMounts:
>   - containerPath: /var/lib/kubelet/config.json
>     hostPath: /path/to/my/secret.json
> ```

But if I do this with my `hostPath: ~/.docker/config/secret.json`, it mounts an *empty directory* `/var/lib/kubelet/config.json/`.

The [extra mounts](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts) docs only states how to mount directories.
I assume that extra mount are not able to mount single files. But which directory should I mount the `.docker/config.json` to then?

**Why is this needed**:

It's not clear how/where to mount docker secrets.

**Comment by th0ger** [comment]
I found out that

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /var/lib/kubelet/.docker/config.json
    hostPath: ~/.docker/config.json
```

creates a local folder structure in the pwd where I call `kind create cluster --config=config.yaml`: `/home/USER_NAME/PWD_DIR/~/.docker/config.json/`. Yes, a literal `\~` dir structure, super trippy side effect.

**Comment by BenTheElder** [comment]
"~" is not a real path character. You should expand that value (your shell will expand it to the real path) or this is a feature request to specially handle that character.

**Comment by BenTheElder** [comment]
I think you have the wrong path?

https://kind.sigs.k8s.io/docs/user/private-registries/

**Comment by th0ger** [comment]
Thanks @BenTheElder it's working with:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /home/[USER]/.docker/config.json  # Full path, don't attempt ~ or $HOME !
```
So the documentation is okay 👍🏼 

I still find it odd that if you attempy to use `~/dir/` or `$HOME/dir/` it will *literally* create the folders `"~"` or `"$HOME"`  in the current workdir. It's totally fair if variable expansion are not supported. But trying to mount non-existing path A to B with the side effect of creating A (in addition to B) is really odd.
