### ISSUE TITLE
Allow setting the node image url in config file

### ISSUE THREAD

**Issue by alrz** [kubernetes-sigs/kind#3661]
So we don't need to specify it each time with --image

**Comment by stmcginnis** [comment]
This is already possible:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/custom-node:latest
```
