### ISSUE TITLE
extraMounts does not sync between host and kube node

### ISSUE THREAD

**Issue by vitalik** [kubernetes-sigs/kind#3674]
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mycluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/ubuntu/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
```

when I create this cluster - it works fine - my k8s can pull images from private repo

but over time (I guess once docker re-authenticates on host machine and `/home/ubuntu/.docker/config.json` changes) it no longer able to pull images

when I docker shell into node I see that /var/lib/kubelet/config.json does not match the host config...

so extraMounts does only one time sync ? how to make it work as usuakl docker volume mounts ?
