### ISSUE TITLE
hostPath Volume doesn't work in kind cluster

### ISSUE THREAD

**Issue by Philipp-Plotnikov** [kubernetes-sigs/kind#3686]
**What happened**:

I have created cluster using kind with the following config file
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    labels:
      argo-rollouts-controller: true
    extraMounts:
      - hostPath: /tmp
        containerPath: /Volumes
  - role: worker
  - role: worker
``` 
After I installed the Argo Rollouts chart (https://artifacthub.io/packages/helm/argo/argo-rollouts) with the following settings
```yaml
controller:
  nodeSelector:
    argo-rollouts-controller: "true"

  replicas: 1

  image:
    repository: argoproj/argo-rollouts

  logging:
    level: debug

  volumes:
    - name: gatewayapi-plugin
      hostPath:
        path: /Volumes/
        type: Directory

  volumeMounts:
    - mountPath: /argo-rollouts-gatewayapi-plugin
      name: gatewayapi-plugin

  trafficRouterPlugins:
    trafficRouterPlugins: |-
      - name: "argoproj-labs/gatewayAPI"
        location: "file:///argo-rollouts-gatewayapi-plugin/gatewayapi-plugin"

providerRBAC:
  providers:
    istio: false
    smi: false
    ambassador: false
    awsLoadBalancerController: false
    awsAppMesh: false
    apisix: false
    contour: false
    glooPlatform: false
```
I opened Docker Desktop to check that all volumes were executed and I see this
![image](https://github.com/user-attachments/assets/0ef78670-75e1-4652-b61e-2ffe4f26f01d)
![image](https://github.com/user-attachments/assets/c1af60cb-36f3-42d8-bcc7-2f3488ce7f20)
 

**What you expected to happen**:
I should see at the first picture above(folder argo-rollouts-gatewayapi-plugin) the content of Volumes folder but it is empty 

**How to reproduce it (as _minimally_ and precisely as possible)**:
Create cluster, that contains node the has the mount from host machine.
Install pod with corresponding HostPath Volume (the value of path is like container path from kind cluster config) 

**Anything else we need to know?**:

**Environment:**
MacOS(arm, m chip), Docker Desktop

- kind version: (use `kind version`): kind v0.23.0 go1.22.3 darwin/arm64
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`): 
```
Client:
 Version:    27.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1-desktop.1
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1-desktop.1
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.14
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.10.0
    Path:     /Users/philippplotnikov/.docker/cli-plugins/docker-scout

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.32-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 15.6GiB
 Name: docker-desktop
 ID: cb54be2c-c3e3-4721-9a32-cfb7c7d568ee
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/philippplotnikov/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.
```
- Any proxies or other special environment settings?:
