### ISSUE TITLE
Pod IP not removed from Service EndPoint when ReadinessProbe failed

### ISSUE THREAD

**Issue by bob2204** [kubernetes-sigs/kind#3725]
Hello

With Kind 0.24 and Node 1.31.0 the Pod IP is not removed from Service EndPoint when ReadinessProbe failed, although noticed NotReadyAddress in EndPoint !

This was fine wih kind 0.23 and Node 1.30.2

Is this normal ?

Best Regards

**Comment by aojea** [comment]
You have to add more details and a reproducer, is not easy to understand from the comments what can be failing there

**Comment by aojea** [comment]
Just to understand, this works in kubernetes versions 1.30 and 1.31, only fails with Node 1.31.0 ?

**Comment by bob2204** [comment]
After further investigations, I found that whatever kubernetes version is, the problem seems to be Virtualbox environnement.
I've to identical kind installations -- ***kind 0.24.0*** and ***kindest/node:1.31.0*** --, one on physical machine, one on Virtualbox VM :
* On physical machine, the behavior is fine with kubernetes 1.31, the Pod IP is removed from *endPoints* field on `kubectl describe svc nginx` when *readinessProbe* faill (as mentionned in doc "[If the readiness probe returns a failed state, Kubernetes removes the pod from all matching service endpoints."](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/) ).
* On VM, the Pod IP remains visible in *endPoints* field on `kubectl describe svc nginx` when *readinessProbe* faill.

An explanation ?

**Comment by aojea** [comment]
Is the kubectl the same version?

What difference make for kind running on top of virtual box or a VM, it just used docker container?

Are you doing something out of the ordinary? Adding custom nodes or different kind configuration?

**Comment by bob2204** [comment]
Kubectl is the same version
The two install are identical.
The both have the same Calico CNI version 3.28.
In both installs there is Docker.
The only difference is Physical Machine/Virtual Machine.

**Comment by bob2204** [comment]
With calico/cilium/kindnet i've the same behavior
With Virtualbox/VmWare/kvm the same.
With killercoda everything is fine ! For me it's like a witness.

I've tried this simple
```
kind create cluster --config=config.yml
``` 
with one Control-Plane and three Workers.

**Comment by aojea** [comment]
can you upload a tarball with the logs of the cluster that has the issue with `kind export logs` and indicate the name of the Service and the time (more or less) when the problem happens?

**Comment by bob2204** [comment]
[full-logs.tar.gz](https://github.com/user-attachments/files/16853476/full-logs.tar.gz)
Service name: nginx
UTC Time: 2024-09-03T18:43:56Z

**Comment by bob2204** [comment]
Manifest used
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 2
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx
```
Alternatively I create/destroy /usr/share/nginx/html/healthz to act on ReadinessProbe.

**Comment by aojea** [comment]
> [full-logs.tar.gz](https://github.com/user-attachments/files/16853476/full-logs.tar.gz) Service name: nginx UTC Time: 2024-09-03T18:43:56Z

that does not adds up, the ngninx container starts at 18:44 

> Sep 03 18:44:01 stage-worker2 containerd[185]: time="2024-09-03T18:44:01.642418279Z" level=info msg="StartContainer for \"0f8fa2821ddca5ce36b9ee686d36e60cf6ffa18b665585c663fe9f4baef699d0\" returns successfully"

and there is no more logs after that, you have period 2 and threshold 2, so it should start failing at 18:44:05 but there are no logs there

I noticed that your environment has only 2 GB of ram in the VM, it would not be surprising that the problem is that your VMs are constrained and everything is slower on that environment

**Comment by bob2204** [comment]
I'm so sorry to waste your time, but the problem remains the same with 8GB !
This is the new dump.
[full-log-2.tar.gz](https://github.com/user-attachments/files/16893050/full-log-2.tar.gz)

**Comment by aojea** [comment]
@bob2204 is like the kubelet is continuously restarting ... if you have the cluster running can you verify that?

**Comment by bob2204** [comment]
None of the three kubelets is continuously restarting.
This the log of `systemctl status kubelet` of one node. The others are the same :
```
root@stage-worker2:/# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf, 11-kind.conf
     Active: active (running) since Thu 2024-09-05 11:44:26 UTC; 14h ago
       Docs: http://kubernetes.io/docs/
    Process: 197 ExecStartPre=/bin/sh -euc if [ -f /sys/fs/cgroup/cgroup.controllers ]; then /kind/bin/create-kubelet-cgroup-v2.sh; fi (code=exited, status=0/SUCCESS)
    Process: 198 ExecStartPre=/bin/sh -euc if [ ! -f /sys/fs/cgroup/cgroup.controllers ] && [ ! -d /sys/fs/cgroup/systemd/kubelet ]; then mkdir -p /sys/fs/cgroup/systemd/kubelet; fi (code=exited, status=0/SUCCESS)
   Main PID: 199 (kubelet)
      Tasks: 12 (limit: 9425)
     Memory: 43.2M
        CPU: 7min 5.993s
     CGroup: /kubelet.slice/kubelet.service
             └─199 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///run/containerd/containerd.sock --node-ip=172.18.0.3 --node-labels= --pod-infra-container-image=registry.k8s.io/pause:3.10 --provider-id=kind://docker/stage/stage-worker2 --runtime-cgroups=/system.slice/containerd.service
```

**Comment by faisalkamilansari** [comment]
@bob2204 

I am also having same problem , is your problem solved ??

kubernetes version : v1.31.2

**Comment by chsakell** [comment]
I have the same problem, even if the pod is not ready, its IP address is being added to the service endpoints.
The files for the probes don't even exit in the pod.

__Client Version__: v1.31.5
__Kustomize Version__: v5.4.2
__Server Version__: v1.32.0
__kind__ v0.26.0 go1.23.4 linux/amd64

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: probe-demo
    image: nginx
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 1
      failureThreshold: 30
    livenessProbe:
      httpGet:
        path: /live.html
        port: 80
      periodSeconds: 10
      failureThreshold: 30   
    readinessProbe:
      httpGet:
        path: /ready.html
        port: 80
      periodSeconds: 10
      failureThreshold: 20       
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80      
```

![Image](https://github.com/user-attachments/assets/c0a1482b-0b59-4624-8eb3-4e956fb99443)
