### ISSUE TITLE
etcd do not encrypt secrets

### ISSUE THREAD

**Issue by network-charles** [kubernetes-sigs/kind#3726]
**What happened**:

In etcd, I am trying to encrypt `secrets` at rest but its not working. I can still view the unencrypted data when I query the secret using `etcdctl`.

**What you expected to happen**:

I expected the value from the secrets to be encrypted.

**How to reproduce it (as _minimally_ and precisely as possible)**:
```bash
# Create cluster 
kind create cluster --config cluster.yaml

# Create secret 1 and 2
kubectl create secret generic secret1 --from-literal user=admin
kubectl create secret generic secret2 --from-literal pass=12345678

# Access ETCD and try to view the secrets
kubectl apply -f https://gist.githubusercontent.com/aojea/6f17c07251cf9251f66a611d80c6a6f1/raw/c00a517341528862fe16b2fb8c40126d5dfd17b3/etcdclient.yml
kubectl exec -it etcdclient -- sh
etcdctl get /registry/secrets/default/secret1
etcdctl get /registry/secrets/default/secret2

# Encrypt etcd at rest
# Get the base64 encoding of any random value
head -c 32 /dev/urandom | base64
# Exec into the master node and specify the encryption argument and its corresponding configuration
docker exec -it kind-control-plane bash
cd /etc/kubernetes/pki
vi etcd-encryption.yaml
```
**etcd-encryption.yaml**
```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - identity: {}
      - aescbc:
          keys:
            - name: key1
              secret: cGFzc3dvcmRwYXNzd29yZA==
```
```bash
# add argument at the last row of {.spec.containers.command}
vi /etc/kubernetes/manifests/kube-apiserver.yaml
--encryption-provider-config=/etc/kubernetes/pki/etcd-encryption.yaml

# Create a new secret and view the value in etcd
kubectl create secret generic secret3 --from-literal user=charles
kubectl exec -it etcdclient -- sh
etcdctl get /registry/secrets/default/secret3
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.24.0 go1.22.6 linux/amd64`
- Runtime info: (use `docker info`):
```bash
Client:
 Version:    25.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.0.0+unknown
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: 4bccb38cc9cf198d52bebf2b3a90cd14e7af8c06
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.102-111.182.amzn2023.x86_64
 Operating System: Amazon Linux 2023.5.20240819
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.738GiB
 Name: ip-172-31-43-37.eu-west-2.compute.internal
 ID: 770b5019-995f-4ed1-996c-105cf795a820
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
- Kubernetes version: (use `kubectl version`):
```bash
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0
```

**Comment by network-charles** [comment]
For some weird reason, arranging the encryption manifest this way worked by putting `identity` at index 1 of the `providers` array.
```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: cGFzc3dvcmRwYXNzd29yZA==
      - identity: {}
```

Also, I used `nano` to edit the file and paste the above rather than `vim` for better formatting. But the main issue was due to the index position from the above. I used `nano` and placed `identity` at index 0 and it still didn't encrypt.

> This is not a Kind issue alone, I also tried Killercoda and the index position issue persisted.
