### ISSUE TITLE
Unable to pull local imagen in Kind with Podman in Windows 11

### ISSUE THREAD

**Issue by carrulop** [kubernetes-sigs/kind#3732]
I have installed latest version from Podman and podman desktop (podman 5.2.2) on Windows 11.
I have installed kind extension (v0.24.0 gol.22.6).
I have created an image using podman build -t mi-microservice .    using Containerfile, and image is successfully created. Indeed, I saw it in podman desktop: localhost/mi-microservice.  This image consists on a microservice created by spring boot that enables a java server listening on 8080 port.

If I create a container using this image, for example, with podman run, it is successfully created, and I can reach to my microservice with a browser, at localhost://8080, and it works fine.

The issue comes when I want to deploy my image like a pod with kubernetes, using kind.

I created the following manifest for my microservice:

**app.yml**
```
kind: Service
apiVersion: v1
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  type: NodePort
  selector:
    app: demo-service
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo-service
spec:
  containers:
    - name: microservice-app
      image: localhost/mi-microservicio:latest
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
          hostPort: 8080
```
This manifest contains a pod that uses my local image, and a service.
When I execute:
**kubectl apply -f app.yml**

This tell me the service and pod was created. But if I execute: kubectl get pod, it tells that image could not be pulled, and status is ErrImagePull.

If I create the pod using podman desktop, it works.

How can I make my manifest works with Kind? Why Kind does not load my local image? What am I doing bad?

Thanks a lot!

Best regards

**Environment:**

- kind version: (v0.24.0):
- Podman version: (5.2.2):
- OS (Windows 11):
- Kubernetes version: (1.31.0):
