### ISSUE TITLE
serviceSubnet in kind cluster config not respected during cluster creation

### ISSUE THREAD

**Issue by vpatov** [kubernetes-sigs/kind#3792]
**What happened**:

I create a kind cluster using the following config:
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: my-cluster
networking:
  serviceSubnet: 172.29.0.0/16
nodes:
  - role: control-plane
    image: kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570
  - role: worker
    image: kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570
    labels:
      node.ourapp.cloud/rack: "1"
      node.ourapp.cloud/class: "cpu"
  - role: worker
    image: kindest/node:v1.29.0@sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570
    labels:
      node.ourapp.cloud/rack: "2"
      node.ourapp.cloud/class: "cpu"

```

The resultant docker network `kind` had the following subnet:
```
[
    {
        "Name": "kind",
        "Id": "de3952523dd53a93423ee18a4d8b3866d3bf17927d52df496697dea4ec8434b8",
        "Created": "2024-11-13T13:23:21.750947292-05:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "fc00:f853:ccd:e793::/64"
                },
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "43ff4ce30957e5ba6d842979ebb729b7ca949690a59301c40a707f01bc371659": {
                "Name": " my-cluster-control-plane",
                "EndpointID": "3a94e41fa3bd8708b942a03ef352a93ad21d5738182b4c323263306a7e9e5e8e",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": "fc00:f853:ccd:e793::2/64"
            },
            "67a9f42b9d2d8bb56dbe1fabd438b85f7ad5803fbbb88a558d0a1cd530aaf4e9": {
                "Name": " my-cluster-worker2",
                "EndpointID": "e7ff4d29c336c2612d97d49b2292dfd09e83dc39024d862861f71141ddd3befc",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": "fc00:f853:ccd:e793::4/64"
            },
            "c830ed939fab0c017640a48a82fb891138dd96c98418232ed86f9af255485533": {
                "Name": " my-cluster-worker",
                "EndpointID": "846386325a1fc6988305b0c77a4de5f83dbb585540ed0bbed70cbe79f72e03ac",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": "fc00:f853:ccd:e793::3/64"
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**What you expected to happen**:

I expect the docker network's serviceSubnet to reflect what I specify in the networking.serviceSubnet field:
```
                {
                    "Subnet": "172.29.0.0/16",
                    "Gateway": "172.29.0.1"
                }
```

It should be `29`, not `17`

**How to reproduce it (as _minimally_ and precisely as possible)**:

Remove all kind docker networks you may have using `docker network rm kind`.
Create the cluster `kind create cluster --config ./kind.yaml`
Inspect the network and see the incorrect subnet `docker network inspect kind`

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
`kind v0.23.0 go1.21.6 linux/amd64`
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 535
  Running: 6
  Paused: 0
  Stopped: 529
 Images: 1478
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 nvidia
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-39-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.79GiB
 Name: vpatov-3
 ID: 41a8e96f-1933-46c1-a3ae-70e588d22896
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```
- Any proxies or other special environment settings?:
Nope
