### ISSUE TITLE
Broken Kubeadm Config Patches for kubeadmConfigPatches

### ISSUE THREAD

**Issue by rooty0** [kubernetes-sigs/kind#3849]
**What happened**:

Start the KIND cluster like this
```bash
kind create cluster --config kind.yaml
```
My `kind.yaml` is 
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        registerWithTaints:
          - effect: NoSchedule
            key: mri-agent
            value: presence
```

**What you expected to happen**:
The worker node should have the taint assigned 

**How to reproduce it (as _minimally_ and precisely as possible)**:
Take the config and run it, It is **easy** to reproduce 

**Anything else we need to know?**:
When I run an alternative following configuration everything works ok: 
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "mri-agent=presence:NoSchedule"
``` 
Thought I'm getting the following: `Jan 18 00:28:49 test-worker2 kubelet[188]: Flag --register-with-taints has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.`

**Environment:**
- kind version: kind v0.26.0 go1.23.4 darwin/arm64
