### ISSUE TITLE
Can't Pull Image From Local Registry

### ISSUE THREAD

**Issue by enchant3dmango** [kubernetes-sigs/kind#3857]
Hi guys, I just deployed a Kind cluster in my local (M1 Pro 2021). I followed the guide at https://kind.sigs.k8s.io/docs/user/local-registry/, but somehow, I can't pull any local image to my Kind registry (I can't connect to `localhost:5001`). Kindly help me, I'm stuck.

Here is the log when I try to pull image from my local registry:
```log
# cat /etc/containerd/certs.d/localhost:5001/hosts.toml
[host."http://kind-registry:5000"]

# ctr --namespace=k8s.io images pull localhost:5001/airflow:2.9.3-python-3.11
INFO[0000] host will try HTTPS first since it is configured for HTTP with a TLS configuration, consider changing host to HTTPS or removing unused TLS configuration  host="localhost:5001"
INFO[0000] trying next host                              error="failed to do request: Head \"https://localhost:5001/v2/airflow/manifests/2.9.3-python-3.11\": dial tcp [::1]:5001: connect: connection refused" host="localhost:5001"
ctr: failed to resolve reference "localhost:5001/airflow:2.9.3-python-3.11": failed to do request: Head "https://localhost:5001/v2/airflow/manifests/2.9.3-python-3.11": dial tcp [::1]:5001: connect: connection refused
```

This is my provision script and my kind cluster config:

- k8s/provision.sh
```sh
#!/bin/sh
set -o errexit

# 1. Create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
cluster_name=$1

if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run \
    -d --restart=always -p "127.0.0.1:${reg_port}:5000" --network bridge --name "${reg_name}" \
    registry:2
fi

# 2. Create kind cluster with containerd registry config dir enabled
# TODO: kind will eventually enable this by default and this patch will
# be unnecessary.
#
# See:
# https://github.com/kubernetes-sigs/kind/issues/2875
# https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration
# See: https://github.com/containerd/containerd/blob/main/docs/hosts.md
kind create cluster --name ${cluster_name} --config k8s/kind-cluster.yaml

# 3. Add the registry config to the nodes
#
# This is necessary because localhost resolves to loopback addresses that are
# network-namespace local.
# In other words: localhost in the container is not localhost on the host.
#
# We want a consistent name that works from both ends, so we tell containerd to
# alias localhost:${reg_port} to the registry container when pulling images
REGISTRY_DIR="/etc/containerd/certs.d/localhost:${reg_port}"
for node in $(kind get nodes --name ${cluster_name}); do
  docker exec "${node}" mkdir -p "${REGISTRY_DIR}"
  cat <<EOF | docker exec -i "${node}" cp /dev/stdin "${REGISTRY_DIR}/hosts.toml"
[host."http://${reg_name}:5000"]
EOF
done

# 4. Connect the registry to the cluster network if not already connected
# This allows kind to bootstrap the network but ensures they're on the same network
if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' "${reg_name}")" = 'null' ]; then
  docker network connect "kind" "${reg_name}"
fi

# 5. Document the local registry
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:${reg_port}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
EOF

# 6. Create GCP service account
# Create a file named serviceaccount.json inside files/ containing your GCP service account json
sa_file_path='files/serviceaccount.json'
kubectl create ns airflow
kubectl create secret generic airflow-gcp-sa --from-file=${sa_file_path} -n airflow

# Extra step: uncomment this step and create a file named gitSshKey inside ./files/ containing the git ssh key
# https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#mounting-dags-from-a-private-github-repo-using-git-sync-sidecar
# 7. Create Git SSH key
# ssh_key_file_path=./files/gitSshKey
# kubectl create secret generic airflow-ssh-secret --from-file=${ssh_key_file_path} -n airflow
```

- k8s/kind-cluster.yaml
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "has-cpu=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "has-gpu=true"
```

Thanks in advance, guys!
