### ISSUE TITLE
Deploy kubernetes resources at cluster start

### ISSUE THREAD

**Issue by ebuildy** [kubernetes-sigs/kind#3892]
**What would you like to be added**:

Define kubernetes resources in Cluster YAML that will be deploy at cluster start. Or better, define a host volume to store Kubernetes resources.

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
resources:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: coredns-custom
    namespace: kube-system
  data:
    opsrel.server: |-
      # Include specific server zone
      opsrel.io. {
        errors
        forward . /etc/resolv.conf
        hosts {
          74.220.17.133 myapp.opsrel.io.
          fallthrough
        }
      }
```

**Why is this needed**:

To have a ready cluster in a single command.
