### ISSUE TITLE
Fails to Bind PVC When Pod Spec Includes nodeName in Kind Cluster

### ISSUE THREAD

**Issue by anisurrahman75** [kubernetes-sigs/kind#3897]
In a Kind cluster, the `rancher.io/local-path` provisioner (used by the default standard StorageClass) fails to bind a PV to a PVC when the Pod spec includes a `nodeName` field. However, removing the `nodeName` field allows the `PVC` to bind successfully and the Pod to run.

Question:
Is this a bug in the `local-path-provisioner` or Kind’s default setup? Or am I missing a configuration step to support nodeName? 

```YAML
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-target-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo
spec:
  nodeName: kind-control-plane
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args: 
    - |
      echo "sample_data" > /target/mountpath/data.txt
      sleep infinity
    securityContext:
      readOnlyRootFilesystem: false
    volumeMounts:
    - name: my-volume
      mountPath: /target/mountpath
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: backup-target-pvc
```
