### ISSUE TITLE
The kubeadmConfigPatches (KubeletConfiguration) configuration cannot take effect separately on different nodes and appears to share the first configuration.

### ISSUE THREAD

**Issue by monshunter** [kubernetes-sigs/kind#3923]
**What happened**:

When I was configuring different KubeletConfigurations for different nodes, all the nodes seemed to only use the configuration of the first KubeletConfiguration.
The KubeletConfiguration for the first node (role: control-plane) is as follows:

```
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        readOnlyPort: 10255
        systemReserved:
          memory: 40Gi
          cpu: 100m
          ephemeral-storage: 96Gi
        kubeReserved:
          memory: 100Mi
          cpu: 100m
          ephemeral-storage: 1Gi
        evictionHard:
          memory.available: "5%"
        # Set control-plane node to 8GB
        maxPods: 60
        # 8GB in Ki
        kubeletCgroups: "/system.slice/kubelet.service"
        systemCgroups: "/system.slice"
        cgroupRoot: "/"
        cgroupsPerQOS: true
        cgroupDriver: "systemd"
        enforceNodeAllocatable:
        - "pods"
```

The KubeletConfiguration for other nodes (role: worker) is as follows:

```
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        readOnlyPort: 10255
        systemReserved:
          memory: 42Gi
          cpu: 100m
          ephemeral-storage: 96Gi
        kubeReserved:
          memory: 100Mi
          cpu: 100m
          ephemeral-storage: 1Gi
        evictionHard:
          memory.available: "5%"
        # Set worker node to 4GB
        maxPods: 60
        # 4GB in Ki
        kubeletCgroups: "/system.slice/kubelet.service"
        systemCgroups: "/system.slice"
        cgroupRoot: "/"
        cgroupsPerQOS: true
        cgroupDriver: "systemd"
        enforceNodeAllocatable:
        - "pods"
```

The difference in the configuration is that in the first configuration, systemReserved.memory: 40Gi, and in other configurations, it is systemReserved.memory: 42Gi.
However, after creating the cluster, when viewing through kubectl describe nodes xxxx, the Allocatable section for kind-control-plane and kind-worker is as follows (they are the same):

```
Allocatable:
  cpu:                3800m
  ephemeral-storage:  20035248Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             4844565467
  pods:               60
```

**What you expected to happen**:
Control plane node:

```
Allocatable:
  cpu:                3800m
  ephemeral-storage:  20035248Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             4844565467
  pods:               60
```

Other nodes:

```
Allocatable:
  cpu:                3800m
  ephemeral-storage:  20035248Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  hugepages-32Mi:     0
  hugepages-64Ki:     0
  memory:             2744565467 (~2.5Gi)
  pods:               60
```

**How to reproduce it (as _minimally_ and precisely as possible)**:
Make different kubeadmConfigPatches to the different nodes in the config.yaml
**Anything else we need to know?**:

**Environment:**
- OS: Linux k8s-kind-dev 5.15.0-136-generic #`147`-Ubuntu SMP Sat Mar 15 15:51:36 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
- Kind version: kind v0.27.0 go1.23.6 linux/arm64
- image:  kindest/node:v1.33.0
- K8S version: 

```
Client Version: v1.32.4
Kustomize Version: v5.5.0
Server Version: v1.33.0
```

- Runtime info: 
```
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 16
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-136-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 46.96GiB
 Name: k8s-kind-dev
 ID: 37a0f6db-fb3c-418c-a21e-6afa34ce69e3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
