### ISSUE TITLE
Using Feature Gates

### ISSUE THREAD

**Issue by matthyx** [kubernetes-sigs/kind#563]
**What would you like to be documented**:
How to specify [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) in the cluster created by kind.

**Why is this needed**:
Sometimes I would like to use and test Alpha features with kind, and I don't quite see how to set this up.

**Comment by aojea** [comment]
@neolit123 do you know if is possible to patch the kubeadm config to enable feature gates? if affirmative, can you add an example?

**Comment by neolit123** [comment]
it's different per component and you may have to enable a gate for all of them (i.e. it depends what gate you want and component it should affect).

example kind config with patch:
```
# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feture-gates": "FeatureGateName=true"
  scheduler:
    extraArgs:
      "feture-gates": "FeatureGateName=true"
  controllerManager:
    extraArgs:
      "feture-gates": "FeatureGateName=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feture-gates": "FeatureGateName=true"
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
- role: worker
- role: worker
```

more info on customizing kubeadm control plane components:
https://kubernetes.io/docs/setup/independent/control-plane-flags/
