### ISSUE TITLE
Add host.docker.internal to certSAN list

### ISSUE THREAD

**Issue by Ilyes512** [kubernetes-sigs/kind#566]
**What would you like to be added**:
I would like to add `host.docker.internal` to the kubeadm certSAN list.

This is both usefull for [Macos](https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) and [Windows](https://docs.docker.com/docker-for-windows/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host).

I think I found the place that would need to be changed: 
See [SourceGraph](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes-sigs/kind%24+file:pkg/cluster/internal/kubeadm/config.go+certSANs)

**Why is this needed**:
So I can connect to the Kind cluster from within another [container](https://hub.docker.com/r/ilyes512/ansiblek8s) (same host, but not inside the cluster).

At this point you get a warning if you change `https://localhost:<port>` to `https://host.docker.internal:<port>`:

```
Unable to connect to the server: x509: certificate is valid for traefik-control-plane, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, not host.docker.internal
```

There are at this point two ways to get around the above error:
1. Use the global kubectl flag `--insecure-skip-tls-verify`.
2. Use a kind config with a jsonpatch that adds the host to the list of certSANs:
```yaml
# kind-config.yml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatchesJson6902:
  - group: kubeadm.k8s.io
    version: v1beta1
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: host.docker.internal
```

@BenTheElder asked my to create an issue for the above, see our Slack chat: https://kubernetes.slack.com/archives/CEKK1KTN2/p1558816949030500
