### ISSUE TITLE
Failed to create cluster from the kind-example-config.yaml

### ISSUE THREAD

**Issue by LiliC** [kubernetes-sigs/kind#666]
**What happened**:
```
kind create cluster --config multinode.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.0) 🖼
 ✓ Preparing nodes 📦📦📦📦
 ✗ Creating kubeadm config 📜
Error: failed to create cluster: failed to generate kubeadm config content: failed to find an object with kubeadm.k8s.io_v1beta1_ClusterConfiguration|config to apply the patch
```

```
cat multinode.yaml
# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta1
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
- role: worker
- role: worker
```

**What you expected to happen**:

Have a multi node cluster up and running created with kind. 

**How to reproduce it (as minimally and precisely as possible)**:

Use the above example which is suggested in the [docs](https://kind.sigs.k8s.io/docs/user/quick-start#configuring-your-kind-cluster).

**Anything else we need to know?**:

I noticed this issue came up before, not sure if tests already exist for this, but if not maybe there could be a test for the examples?

I removed the extra config patches and the cluster was created correctly.

**Environment:**

- kind version: (use `kind version`):
`v0.4.0`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version: (use `docker info`):
`Version:           18.06.1-ce`
- OS (e.g. from `/etc/os-release`):
`darwin OSX`
