### ISSUE TITLE
Failed to interact with cluster in wsl2

### ISSUE THREAD

**Issue by anjiawei1991** [kubernetes-sigs/kind#707]
I setup the cluster in wsl2, but can't interact with it.

**How to reproduce it (as minimally and precisely as possible)**:
* install kind、docker、kubectl
* using `kind create cluster` to create default cluster. and  using `export KUBECONFIG="$(kind get kubeconfig-path --name="kind")" ` to set KUBECONFIG env for kubectl
* using `kubectl  cluster-info`  to lookup cluster

Then after a lot of time, I see `Error from server (InternalError): an error on the server ("") has prevented the request from succeeding`

**Anything else we need to know?**:

the output of `cat $KUBECONFIG` is:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EY3hOVEE1TlRFMU5sb1hEVEk1TURjeE1qQTVOVEUxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDNQCjBhV2srZlFXTFFGOXZmbDdhNW40cm4vSXhZamNqdXRWUHhaNjF5MjFpRElrb3h1dnhsT3NRLzZhZTBzRlFIeS8KeU9rSW9DaHowdHJwR0MvV0JMQWlWME5YMzQrQWFZdFhpZEtad0lyMVZZVG9iVWxCSHp3bXpSSlRPMkNaU3ZmWQpYemVTSVZwV1pnRmhnZVJUaWFWN0pTdHVxWG9hOGJrcW5NdE1MdXhhakU3Tk5Xc0psOEdWY01MdnNoWXhUNkR1CkRaZ0xBVmhiWktNSDdmOGREemRGNGVTZVdBV3BsY0ZmNEErR3ZHRVp2YUJMdWxjU2Z1VDZDcWRLV2czeDloYkIKWkdxMjN6MTl3Tzk4SnJ2TWozemE1SGZvOGk1QTdmbTBTa1dLMWJoL2h6SWNLcTRzSmRvRlUvcTgvQVZTZDdpMwpUYVdXQUo0aGN3QUxKNUlWSHJVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCeFZmTlpEVnZHTjJwNzRRVHoyblU4NUI0Qk8KS3owSFRxT3ZJUnJGRUFHWUJsdW50clZscFlNOUhZZWZxaGplam5DWEZhS1Q1cXhtTlJUaEdKeE5CblBIc2lrUQpObythNGZsUmc3c3JjQ08vOHY0SGZMcEZ3WXFIZ1JuVlUzT3l5cmdyU2VmeW5WdlB1SUovM2V0UnZZYjZudjB3Cmt3bktWUGpiaTBVN1ZCRFo5U2NPQXFDQ2xXaDJvRUtDemYvOG54ckdHeW8xMnZZQWh3WGVhbXc0cDl0RWtrZ3QKM3JRL0FUOHRLOEdIZXhwVEY4RldZZHR4OEZWdTZOVHoxQThGWktTc0RQcmM1KzNwOWZNbXZCK0VlaFJKdkZycAp2S1VkblE5aUZjaDFBUGVMNy9kTlRKVHhTajJLOFdKZkFxMWpjVlRJKzhvcWFEc0dDanJuYWpBUWJoYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:45991
  name: kind
contexts:
- context:
    cluster: kind
    user: kubernetes-admin
  name: kubernetes-admin@kind
current-context: kubernetes-admin@kind
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJWENWRnlZUU5XMDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RBM01UVXdPVFV4TlRaYUZ3MHlNREEzTVRRd09UVXhOVGRhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRjMHNnVEk4MHZ5anBmUHMKWTdZN1Byb094SlNGT0ZmK1E0VE5OcWZNNE93cS9UWGlaNFVxQWtadjBUZDltSUNibnRJb0N4a2RINjBVZzg1Ygo1WG5YZEw3WFVydlNBWTRJOFRVZDkxUEF3aGJnL2hkQjFHZkwzVkljcWlwOERPV3dkZFdxYjZIb3RZRkVIanlpCnd5MlZvT0RwWGUyNmtWY3RuSmlQbGgvRFgxMVM3eFN1S1ZGNitMajF3cFE1NEpMZTNHNHBISWxpdy9YQnBVL2MKdVF6amk4QlM0MS82RTg2WGk3c1Z6ZnRYL2tKUm41SlNzUXgzMjQ3aWpwcWxnRVM0Zy9pSVZhNUU0N0cvWGl2NwpoVTFpeDVHYThEWm9FVi9HUXhOWjVyWDhYOFAvditMOEFKSkx3ZmphV3l2dHl0ZVFNUnVzWE04dEsxcmJtTHVIClBybGk4UUlEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDMEZWMzlZVGpGT3k5cGdjSDlMVGpjN3BkdnU5RFNQVHNJbApud3lUMzR2S3FVTWNJWnRXRVBrUEw2MXRsOFJrK3RENGNvbXUyQUtETUJreEo1M252Yy9HOG9nQTdDL1V3TWRKCi9kVU9zZkVzRTFOQWgrU2pGazZWMmFlcWRNNHJUOFRlaWhvYldGMWpzb1lON3NNRS9FeHV2NVBGZndtSm92d1AKcnJNOTlIaG13MXZmUlkyVzJNNHp1SURONlNoWEViNWVPcitQWnh5dWxZQWIvajZvZ0hOeEdqQm1yYXVhWjZxdApPUHNjREpmMkdkL08zMnVYWE82bEdPTE5wY0VOOUR0emxteHZZN2krS3dEbEZkZmlMNUN6SW5mRGlxb1p2ZFZRClZVa0tSOUdlRXRSRkxpd3FBSlZvcXoya2U5NlV2bWM0Uk1BbkFVVDlYbVR2TzhwdG50cz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdGMwc2dUSTgwdnlqcGZQc1k3WTdQcm9PeEpTRk9GZitRNFROTnFmTTRPd3EvVFhpClo0VXFBa1p2MFRkOW1JQ2JudElvQ3hrZEg2MFVnODViNVhuWGRMN1hVcnZTQVk0SThUVWQ5MVBBd2hiZy9oZEIKMUdmTDNWSWNxaXA4RE9Xd2RkV3FiNkhvdFlGRUhqeWl3eTJWb09EcFhlMjZrVmN0bkppUGxoL0RYMTFTN3hTdQpLVkY2K0xqMXdwUTU0SkxlM0c0cEhJbGl3L1hCcFUvY3VRemppOEJTNDEvNkU4NlhpN3NWemZ0WC9rSlJuNUpTCnNReDMyNDdpanBxbGdFUzRnL2lJVmE1RTQ3Ry9YaXY3aFUxaXg1R2E4RFpvRVYvR1F4Tlo1clg4WDhQL3YrTDgKQUpKTHdmamFXeXZ0eXRlUU1SdXNYTTh0SzFyYm1MdUhQcmxpOFFJREFRQUJBb0lCQUNsOXV2TjljSzVDWkdMaQppWWUwTms4NWpWZEdBaVY2eDVmSFBrS0VCMWtwN1NHKzQzMzJ3VUNscksxVitiOE5VdmJyUmFKS3gvL0xzNHZsClU4bktoZWFxQzJCaFp5dGRyQ0xJbVo4eHFTTmlyMVN1SUNNRzBWc2dlMVJHdityOW5NazN5MThRMTVoYytSdmgKZ05BRW5rcUtLaGg2d2dLYm45aEdaVGJBNXdqalUzOUFKTFJPWElTWDVhdHhkQ3hxUlZpOElRNExSNVJ1Tmd6VgpFVDNET3FKSExkejN3M1ZibjRKa0RlMVQ2UnNGU0NwUUsrbjBxUDNZanlDTmU4aW1lK1FMREtjcm1WS0crNmtrCmQ3TldIUC9pTUpUbmZQUEFCOTBFMTlTWHF6dVA2V1JDbXpGNklMSXdNQ3Bpd0o4UHVWYVRnWnFNTFg3a0xIWGUKNUZaQXBkVUNnWUVBd0FZMEFLTE12cGVPaDl0elpNTENOajJsQ2Vjc3ZjejdkaEtIbmNnT3lIRjRaSzVxNzZwSQpMcE5lbnM5U2JoRmljaFpLcG9ST083cjhQUjZCZjc0RW1hUjY1cEVXSFZtWmxYU2pzNWdEUFR4MTUzZGVpcFhNCjVMTGcxbzlnd2VyNmRJOFFUNjlVN0JTWndUR3pRSDlGYkJJTHhlZ1NOOG5kUVkxR3FSSytJbGNDZ1lFQThsOFIKWTlXa3RnZkh3S3N2MVJvQi9ZT2h4c1M4RWk5cGI4RmFJNXhIWHh5bGFnbGpEYVVlNFJhUGtTUWNvRFdCelV3OQpVRXVjTE90NGJPY1g3VEJpdUNjSkdKbEZKdDZvY2pUNTdwN1JNMzRsK3Nxc0hxd21BN20xUHQ3cVN0Q2NWNFB2CjNXTUFHTEZnNkJCekdOcUlYSFlRWkx3bUVNUEt2SDk2WUNWdEovY0NnWUJpd0Ezb01kREhSeHVHWkdYUWNKUDkKM3UvTHl2WG9XYzBMcUhYVHYzbFN2WC9qandyeFc0bXBZaUlyMjRTUmxDRWplTEZGTnc4Z2lvV0RUUGZkNExOdQo2L1pFTW1MRUR6cjdjRE5yZllaVTdJM1p6anB4WEo0MUVvU3I4cW9ZcjZYRFlYdEs3MmpseTZaU2d5T2l6SkRBCkJmdkYrQlcrV1BLTzduOWpIWDlvR3dLQmdBdmZFREQ5bytXdWwrQWVBbWZEc0ZsRWUwWUxHTk1qTTF6ZjhaUlEKOFVYOVZ6VE1aT2VrTU5FQmsrS2VERERrcmdqcU5RNmJ4WGlGeUE0OWUzU0lyQzBzN0VzaUpycnlxUGwvRXNiWApUSlBqRitVaXpDOXNheWcvamxzWC9BM1NEZlpUWmdwSDhSZEVpT1NVK2E0NzlmWGhhb2drbHhDM0psVDVRWHM0CkdoS2RBb0dBVUpIdDRWRHZTeGNJb0NJaW8vRTVLc0R1RUU4Ty9kekZDRGhZRUJ0QUl0c0JuVHdXNWJtM05hcjAKdzhFME91TWwyZnp0MXg1TVB2bUNsUVk4K2FpQjR1eVZyeFpVYUZhMER5NVdVT3VadzYrcGpyMmdoUnJrRis2dwpveVlNaktJNitVaU5PVktBY3I2aTczUkJIbkJCTG9Pb2M5emJ5TmY1a0VldGx4cGdvQmc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

the output of `netstat -ano | grep 45991` is:
```
tcp        0      0 127.0.0.1:45991         0.0.0.0:*               LISTEN      off (0.00/0/0)`
```

the output of `docker exec kind-control-plane ps aux` is:

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  17656  9320 ?        Ss   09:51   0:00 /sbin/init
root        28  0.1  0.0  22672 10996 ?        S<s  09:51   0:00 /lib/systemd/systemd-journald
root        39  2.2  0.3 2203172 52276 ?       Ssl  09:51   0:17 /usr/bin/containerd
root       193  2.4  0.5 1550088 86272 ?       Ssl  09:51   0:18 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --fail-swap-on=false --node-ip=172.18.0.2 --fail-swap-on=false
root       223  0.0  0.0  10744  4316 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/9ac4b869efb1aeb0f1ecb9e355ab98694ea5fcd8bc85f241da3f9e611be49833 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       235  0.0  0.0   9336  4964 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/b8ecacb545e4e5494d0f9f9091559351c37ac623be77979876983e623599b5a0 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       254  0.0  0.0   1024     4 ?        Ss   09:52   0:00 /pause
root       257  0.0  0.0   1024     4 ?        Ss   09:52   0:00 /pause
root       273  0.0  0.0   9336  4856 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/16ff3c7ea1eb204351dfd6965c21e0a3dcebe61f6a51643fb18b02a5a49e0fc4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       286  0.0  0.0  10744  4900 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/9f72767303cf43748717f43bc0b5c3179185eeba66aaef22298000ac26cf34e2 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       325  0.0  0.0   1024     4 ?        Ss   09:52   0:00 /pause
root       345  0.0  0.0   1024     4 ?        Ss   09:52   0:00 /pause
root       451  0.2  0.0  11800  5840 ?        Sl   09:52   0:01 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/886f4a122b83039bf4be05f5c51190bb594bffb9ed5434df815abf278a9255e4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       459  0.0  0.0  10744  5016 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/331e944e695051e09ebcbd12b0bee78543ee79946fe5b6bf1a4a5f32154d1c6c -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       483  0.0  0.0   9336  3976 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/a0d18fd3bdc8fd3c64f754d631b14cd219eebda1fe03167992e9dc84427ddc7c -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       485  2.3  0.2 10536552 43808 ?      Ssl  09:52   0:17 etcd --advertise-client-urls=https://172.18.0.2:2379 --cert-file=/etc/kubernetes/pki/etcd/server.crt --client-cert-auth=true --data-dir=/var/lib/etcd --initial-advertise-peer-urls=https://172.18.0.2:2380 --initial-cluster=kind-control-plane=https://172.18.0.2:2380 --key-file=/etc/kubernetes/pki/etcd/server.key --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.2:2379 --listen-peer-urls=https://172.18.0.2:2380 --name=kind-control-plane --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --snapshot-count=10000 --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
root       490  4.1  1.8 403296 278432 ?       Ssl  09:52   0:30 kube-apiserver --advertise-address=172.18.0.2 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
root       494  0.0  0.0   9336  5016 ?        Sl   09:52   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/3a3269e0a50fc0318fb17bdb8695b0f8c6e2bc80f7af11658506caecc6c5ac7c -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       530  0.3  0.2 141492 38792 ?        Ssl  09:52   0:02 kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true
root       551  1.9  0.6 217304 105244 ?       Ssl  09:52   0:14 kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=10.244.0.0/16 --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --enable-hostpath-provisioner=true --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size=24 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --use-service-account-credentials=true
root       834  0.0  0.0  10744  4988 ?        Sl   09:53   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/f72eb97e6cf183a96c59bed33893957c25f4b510b94e2a7f3a091f83d781ee1d -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       846  0.0  0.0   9336  4900 ?        Sl   09:53   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/7bed5b9f1b5f0b56c1511821fc1ff47807aa6ae809215610b61f55d30eaaae7f -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       857  0.0  0.0   1024     4 ?        Ss   09:53   0:00 /pause
root       871  0.0  0.0   1024     4 ?        Ss   09:53   0:00 /pause
root       936  0.0  0.0  10744  4892 ?        Sl   09:53   0:00 containerd-shim -namespace k8s.io -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io/2b426d366b0fdeefa7e90600b40de834303c065544cd38f0275b829724861f55 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd
root       959  0.0  0.2 139736 32216 ?        Ssl  09:53   0:00 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=kind-control-plane
root      7272  0.0  0.0   5836  2856 ?        Rs   10:04   0:00 ps aux

```

- kind version: (use `kind version`): v0.4.0
- Kubernetes version: (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

- Docker version: (use `docker info`):

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- OS (e.g. from `/etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
