### ISSUE TITLE
Potential resource leak

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kind#759]
**What happened**:
On July 10th, we started using kind in our prow cluster for Istio (see https://github.com/istio/test-infra/pull/1455). We have about 6 tests or so that use kind, and maybe run 40 tests a day, so I'd estimate we are creating roughly 250 kind clusters a day across 60 nodes.

Ever since July 10th, we have run into problems on our cluster. Almost immediately, we ran out of inotify watches, which we fixed by just increasing the limit -- see https://github.com/kubernetes-sigs/kind/issues/717.

Since then, the CPU of our nodes has slowly increased, like a memory leak but CPU. This can be attributed to the Kubelet process, which a profile indicates most of the time spent by cAdvisor.

Here is a graph of the minimum CPU of our nodes for a 4 hour interval. During a 4 hour time, it is almost certain we will have no test pods scheduled on the node, so this essentially shows the base overhead CPU of the nodes.

![2019-07-08_08-23-40](https://user-images.githubusercontent.com/623453/62636342-37d5da80-b8ee-11e9-88b3-769a00896ed3.png)

The big drops are times when we got rid of nodes. You can see the problems seem to start right around when we started using kind (note - it is possible it is a coincidence. My only evidence it is related to kind is the timing).

Within two weeks we see some nodes using 90% of CPU just idling.

**What you expected to happen**:
kind does not cause cluster-wide degradation.

**How to reproduce it (as minimally and precisely as possible)**:
I am not sure, but we consistently run into this problem so I can run some diagnostics on the node.

**Environment:**

- kind version: (use `kind version`): v0.3, v0.4
- Kubernetes version: (use `kubectl version`): GKE versions 1.11, 1.12, 1.13 (tried upgrading twice to attempt to resolve this)
- OS (e.g. from `/etc/os-release`): COS

**Comment by aojea** [comment]
this issue remembers this other one https://github.com/kubernetes-sigs/kind/issues/421

**Comment by howardjohn** [comment]
I did run into that while investigating, but it seems the conclusion was

> I can confirm that repeated cluster creation / deletion does NOT leak cgroups. The output of lscgroup | grep -c memory is the same after each creation / deletion cycle.

By the way, if it is relevant, we never do `kind cluster delete`, we just do `kind create cluster` then run some test and exit.

**Comment by aojea** [comment]
> By the way, if it is relevant, we never do `kind cluster delete`, we just do `kind create cluster` then run some test and exit.

but ... then the old cluster containers keep running forever ... is it possible to add the `kind cluster delete` to your workflow once the tests finish and check if this solves the problem?

**Comment by howardjohn** [comment]
But we run it in a pod, once the pod is removed shouldn't everything be cleaned up? Or maybe because we have

```
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
```

in our pod spec, so it never gets properly cleaned up.

I'll try adding the delete cluster to the end. 

Does Kubernetes prow do this in their tests using kind? I am worried if the test crashes part way through we won't properly clean up
