### ISSUE TITLE
Issue while creating kind cluster with workers

### ISSUE THREAD

**Issue by harshavardhanc** [kubernetes-sigs/kind#821]
I'm trying to create cluster in local(Arch linux) with single master node it is working fine, but if I try to create a cluster with workers getting the below error.

```
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.0) 🖼 
ERRO[19:19:20] 40e341e7e12ebf6301f6ad6eab0927d16689032987a6cb796af209c28df1c12b 
ERRO[19:19:20] docker: Error response from daemon: driver failed programming external connectivity on endpoint kind-worker (b3ad65eb44b2852397f568c3f074129f65c8039e4bc66a298f69d6dfae03970e):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32787 -j DNAT --to-destination 172.17.0.4:0 ! -i docker0: iptables v1.8.3 (nf_tables): Port `0' not valid 
ERRO[19:19:20]                                              
ERRO[19:19:20] Try `iptables -h' or 'iptables --help' for more information. 
ERRO[19:19:20]  (exit status 2)).                           
 ✗ Preparing nodes 📦📦
ERRO[19:19:20] docker run error: exit status 125            
Error: failed to create cluster: docker run error: exit status 125
```
Below is my config file to create a cluster.
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000
  - containerPort: 3443
    hostPort: 3443
  - role: worker
```

Please help me in fixing this issue.

**Comment by BenTheElder** [comment]
see https://github.com/kubernetes-sigs/kind/issues/821 for improvements to catching this error.

the corrected config would be:
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000
  - containerPort: 3443
    hostPort: 3443
- role: worker
```
