### ISSUE TITLE
Cluster fail because of wrong extraPortMappings configuration

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kind#822]
**What happened**:

The cluster creation fails with the following error

```

ERRO[19:46:55] 8e06d28793e7b6dfd16f89fffc1f6b551b9de9d4025c387aad54d8a225155177 
ERRO[19:46:55] docker: Error response from daemon: driver failed programming external connectivity on endpoint kind-worker (771b19a2d315e78e8eb8a43af9a977d28b2685ecc875e8a844736fa1671e7d6b):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32797 -j DNAT --to-destination 172.17.0.4:0 ! -i docker0: iptables v1.8.3 (nf_tables): Port `0' not valid 
ERRO[19:46:55]                                              
ERRO[19:46:55] Try `iptables -h' or 'iptables --help' for more information. 
ERRO[19:46:55]  (exit status 2)).                           
 ✗ Preparing nodes 📦📦
ERRO[19:46:55] docker run error: exit status 125            
Error: failed to create cluster: docker run error: exit status 125
```

**What you expected to happen**:

Kind should validate the configuration and throw an error

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with the following configuration

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000
  - containerPort: 3443
    hostPort: 3443
  - role: worker
```

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`):
- Kubernetes version: (use `kubectl version`):
- Docker version: (use `docker info`):
- OS (e.g. from `/etc/os-release`):
