### ISSUE TITLE
Mount Points from Dynamically Created PVC's Are Not Writeable by Non-Root Users

### ISSUE THREAD

**Issue by Xtigyro** [kubernetes-sigs/kind#830]
**What happened**:

1. A `PVC` is provisioned.
2. It is dynamically bound to a `hostPath` volume by the KiND's provisioner.
3. A pod is created that mounts the `PVC`.
4. The process in the pod is running as `runAsUser` 65533 ("git-sync" user), with `fsGroup` 65533 too.
5. The process can not write to the `PVC` mount, since it is only writeable by `root` user.

Trying `mode` or `defaultMode` 0777 has no effect to the permissions of the mount folder.

Since we don't want to allow escalating privileges in the pod, we can't use the PVC mount at all.

**What you expected to happen**:
Some way of specifying in the PVC what UID / GID the `hostPath` should be owned by, so we can write to it. 

**How to reproduce it (as minimally and precisely as possible)**:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
...
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    svc: test-pvc-permissions
spec:
  volumes:
    - name: test-volume-1
      persistentVolumeClaim:
        claimName: test-pvc-1
  containers:
  - image: k8s.gcr.io/git-sync:v3.1.2
    name: notebook
    volumeMounts:
     - mountPath: /home/test
       name: test-volume-1
    command: ["/bin/sh", "-c", "touch /home/test/hi"]
  securityContext:
    fsGroup: 65533
    runAsUser: 65533
...
```

Works fine with `root`:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
...
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    svc: test-pvc-permissions
spec:
  volumes:
    - name: test-volume-1
      persistentVolumeClaim:
        claimName: test-pvc-1
  containers:
  - image: k8s.gcr.io/git-sync:v3.1.2
    name: notebook
    volumeMounts:
     - mountPath: /home/test
       name: test-volume-1
    command: ["/bin/sh", "-c", "touch /home/test/hi"]
  securityContext:
    fsGroup: 0
    runAsUser: 0
...
```
