### ISSUE TITLE
Connect to KIND created cluster from Java Kubernetes-API 

### ISSUE THREAD

**Issue by palade** [kubernetes-sigs/kind#873]
I would like to connect to a Kubernetes cluster created using KIND. I can connect to a Kubernetes cluster using kubeadm. The problem is the IP of the API Server, but I don't know how to change it. How can I remotely connect into a cluster created using KIND on a physical machine in the network, from a different physical machine in the same LAN?

**Comment by BenTheElder** [comment]
We _really_ highly recommend you not expose kind clusters to the internet, they're intended for **local, ephemeral, test** clusters and as such are not designed to be long lived or have a particular mind for security.

If you _really_ want to do this you can set this in the config
```yaml
networking:
  apiServerAddress: "..."
  apiServerPort: ...
```
However I really don't reccomend it. To create a production usage cluster shared across many machines there are many more suitable options available (EG using kubeadm without kind)

**Comment by palade** [comment]
@BenTheElder I'm using this setup only in a local cluster for development of a Proof of Concept prototype. I added the rquired fields to the .yaml file, however it still has the same localhost ip address.
```

# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    apiServerAddress: 192.168.1.25
    apiServerPort: 9090
    serviceSubnet: 10.0.0.0/16
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta1
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
- role: worker
- role: worker
```

**Comment by BenTheElder** [comment]
those fields are for kind, not for kubeadm

**Comment by BenTheElder** [comment]
kind.sigs.k8s.io/v1alpha3
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  apiServerAddress: 192.168.1.25
  apiServerPort: 9090
  serviceSubnet: 10.0.0.0/16
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
- role: worker
- role: worker
```
